### ISSUE TITLE
iCubErzelli02: Left hand ring finger becomes loose

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1003]
## Brief description of the request/failure
After a few hours of usage the ring finger (left hand) loosens.

**Comment by julijenv** [comment]
Hi @ddetommaso ,
a video (wcs foto) of the situation would be much more appreciated to understand the meaning of "loose".
thx

**Comment by ddetommaso** [comment]
Hi @julijenv 
I am not able to record a video cause I don't have access to the robot anymore. Basically the finger tends to close little by little from its original position after every session of usage.

**Comment by vtikha** [comment]
All is well after @julijenv 's intervention
