### ISSUE TITLE
[iCubGenova04] Shoulder Cable Broken

### ISSUE THREAD

**Issue by CarlottaSartore** [robotology/icub-tech-support#1009]
## Brief description of the request/failure
Today during the experiments with the robot we broke the left shoulder cable. 
We succeed in fixing the right shoulder cable but it is a little bit loose, maybe it is good to check also this one.  
C.C.  @gabrielenava

**Comment by violadelbono** [comment]
Cable 8 of left shoulder was replaced.
The following item was taken from warehouse:

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| 4765 | 1 |  SHOULDER ROTATION CABLE 8|  |
