### ISSUE TITLE
[iCubGenova04] Left elbow broken

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1012]
## Brief description of the request/failure

While doing some experiments of robot-robot collaboration the left elbow cable broke.

## Accompanying material

cc @julijenv @violadelbono @kouroshD @Yeshasvitvs

**Comment by violadelbono** [comment]
Cable 9 was replaced:

|  IITCODE | ALIAS  | QUANTITY  |  DESCRIPTION |  
|---|---|---|---|
|4551.1   | RC_TLR_005_P_103  | 1  |   ELBOW CABLE 9|

**Comment by lrapetti** [comment]
Thanks a lot for fixing it!
