### ISSUE TITLE
[iCubGenova04] Backpack piece detached 

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1013]
## Brief description of the request/failure
During today experiments the backpack piece that was glued to the backpack got detached.
![photo5798407039209288955](https://user-images.githubusercontent.com/35487806/96613740-9c1c6880-12ff-11eb-8737-111c7454a417.jpg)

I left it in the `iCubGenova04` toolbox
![photo5798407039209288954](https://user-images.githubusercontent.com/35487806/96613782-a6d6fd80-12ff-11eb-9c9e-b14cf5804000.jpg)

**Comment by violadelbono** [comment]
Done, it had been re-glued.
