### ISSUE TITLE
iCubErzelli01: Leftarm wrist cable broken

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1016]
## Brief description of the request/failure
During a grasping operation one of the cable of the left arm broke.

## Accompanying material
![DSC_1046_](https://user-images.githubusercontent.com/3440640/97193611-7b458e80-17a9-11eb-91f5-ac8971c39800.JPG)

[log_icub-head_yarprobotinterface_6263.txt](https://github.com/robotology/icub-tech-support/files/5439754/log_icub-head_yarprobotinterface_6263.txt)

**Comment by ddetommaso** [comment]
The cable has been replaced and the robot is working fine.

**Comment by julijenv** [comment]
it has been used the cable n8 forearm V2

IITCODE|Qta|description
---|---|---
356|1|ribbon flat cable
