### ISSUE TITLE
iCubErzelli01: left camera cable damanged

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1018]
## Brief description of the request/failure
The image from the left camera is not streaming correctly. Most probably the flat cable has to be replaced.

**Comment by ddetommaso** [comment]
The cable has been replaced and the camera is streaming correclty

**Comment by julijenv** [comment]
Hi @reafrancesco ,
we took one of your spare flat cable, and we will give it back to you when I will be passing by Erzelli next time.

IITCODE|Qta|Description
---|---|---
6417|1|WRIST V2 TENDON #8 - 107mm
