### ISSUE TITLE
Problem with the hand motor feedbacks

### ISSUE THREAD

**Issue by kouroshD** [robotology/icub-tech-support#1019]
## Brief description of the request/failure
I have logged the encoder values and velocities of the robot hand, however it seems there is a sign mismatch between [encoder values](https://robotology.github.io/yarp-documentation/git-master/classyarp_1_1dev_1_1IEncoders.html#a8c5adefdc8c0627a7ecfe7f6d972deaa) and [encoder speeds](https://robotology.github.io/yarp-documentation/git-master/classyarp_1_1dev_1_1IEncoders.html#ac84ae2f65f4a93b66827a3a424d1f743).

## Detailed context
Apparently there is a problem with retrieved encoder velocity or encoder values.
It seems that there is a `-1` missing somewhere (sign mismatch) between the motor values and velocities. Looking at the patterns of motor value (`motor val fb`) and velocity feedbacks `motor vel fb`, when the motor values are decreasing the velocity is positive and vice versa.
Instead, when I compute the motor values (`motor val comp`) from the motor velocity feedbacks or when I compute the velocities (`motor vel comp`) from the motor value feedback the computed ones seems to be coherent with the encoder feedback that I have used.

## Accompanying material
This figure are plotted for the thumb motor associated with the distal joint (`r_thumb_distal`).
![velocityProblem2](https://user-images.githubusercontent.com/17707730/97585677-b50cd400-19f9-11eb-85fa-c011b91543a5.png)

![velocityProblem3](https://user-images.githubusercontent.com/17707730/97585682-b63e0100-19f9-11eb-863c-67e0629779ac.png)

The link to my committed implementation robotology/walking-teleoperation@3a3dc78

cc @pattacini  @traversaro

**Comment by pattacini** [comment]
Thanks for reporting @kouroshD 👍🏻 
We'll be giving a look at it in the next days.

**Comment by Nicogene** [comment]
Hi @kouroshD!

is it possible to have a dump of the `stateExt:o` of both arms?
And which fw is used for the board of the hands?

**Comment by kouroshD** [comment]
I have not dumped the data related to `stateExt:o`, I have the two following datasets if you want to use them and the matlab scripts to read those data and in order to plot the data. Only make unzip and copy them in the same directory, and make a folder with the datasets name (since, it save the plots!)

[HapticGloveModule_2020-10-29_11-03-37_log.mat.zip](https://github.com/robotology/icub-tech-support/files/5476529/HapticGloveModule_2020-10-29_11-03-37_log.mat.zip)

[HapticGloveModule_2020-10-29_11-20-58_log.mat.zip](https://github.com/robotology/icub-tech-support/files/5476532/HapticGloveModule_2020-10-29_11-20-58_log.mat.zip)

[PlotData.m.zip](https://github.com/robotology/icub-tech-support/files/5476535/PlotData.m.zip)

Regarding the fw version, I am not sure about it, probably the last version! But this is sth to check.

**Comment by kouroshD** [comment]
Plotting the data of the first motor of the thumb, I have noticed that its velocity feedback value are zero.
![motor1](https://user-images.githubusercontent.com/17707730/97907418-8c604380-1d45-11eb-9ec2-91b8e5d84b69.png)

**Comment by kouroshD** [comment]
Thanks to @gabrielenava , we have the following dataset and info regarding the fw versions.

![Screenshot from 2020-11-03 19-38-58](https://user-images.githubusercontent.com/17707730/98030352-2ccf6a00-1e11-11eb-8af4-3a7d7a146272.png)

[stateExt_00003.zip](https://github.com/robotology/icub-tech-support/files/5483548/stateExt_00003.zip)

cc @Nicogene

**Comment by Nicogene** [comment]
Thanks @kouroshD and @gabrielenava !

**Comment by Nicogene** [comment]
I analyzed the data using a modified version of this [script](https://github.com/dic-iit/MAPest/blob/master/src/readStateExt.m)
<details>
  <summary>Click to expand!</summary>
  
~~~matlab
% Copyright (C) 2017 Istituto Italiano di Tecnologia (IIT)
% All rights reserved.
%
% This software may be modified and distributed under the terms of the
% GNU Lesser General Public License v2.1 or any later version.

function [q, dq, d2q, m, dm, d2m, time] = readStateExt(n, filename)
% READSTATEEXT reads data from robot acqisizion. 
%
% Inputs 
% - n       : is the number of degrees of freedom of the part of the robot;
% - filename: is the name of the file containing the data from stateEXT:o 
%             port.

format = '%d %f ';
fid    = fopen(filename);

data   = textscan(fid,'%s','delimiter','\n');
text=data{1};

nlines = length(text);
q=[];
dq=[];
d2q=[];
m=[];
dm=[];
d2m=[];
for j = 1 : 10
   format = [format, '('];
   for i = 1 : n
      if j < 9
         format = [format, '%f '];
      else
         format = [format, '%d '];
      end
   end
   format = [format, ') [ok] '];
end
for i=1:nlines
    line = text{i};
    C    = textscan(line, format);
    %size(C)
    time = C{1, 2};
    %size(cell2mat(C(1, 3    :3+  n-1)))
    %size(q')
    q    = [q; cell2mat(C(1, 3    :3+  n-1))]; % n columns of "q" value
    dq   = [dq; cell2mat(C(1, 3+  n:3+2*n-1))]; % n columns of "dq" value
    d2q  = [d2q; cell2mat(C(1, 3+2*n:3+3*n-1))]; % n columns of "d2q" value

    m    = [m; cell2mat(C(1, 3+3*n:3+4*n-1))]; % n columns of "m" value
    dm   = [dm; cell2mat(C(1, 3+4*n:3+5*n-1))]; % n columns of "dm" value
    d2m  = [d2m; cell2mat(C(1, 3+5*n:3+6*n-1))]; % n columns of "d2m" value

end


if fclose(fid) == -1
   error('[ERROR] there was a problem in closing the file')
end
end
~~~
</details>


The original script seemed to read only one line and read only q, dq, and d2q(a.k.a encoder position, velocity, and acceleration)

My modified version read the whole file and reads also m, dm, and d2m, that should be motor position, velocity, and acceleration(according to (https://github.com/robotology/yarp/blob/master/src/libYARP_dev/src/idl_generated_code/yarp/dev/impl/jointData.cpp#L180L216)

(Is it the case to open a PR for adding this version? Can be useful? cc @traversaro)

I found the same strange behavior of fingers that @kouroshD  found also on the motor side.

|   | `thumb_oppose` | `thumb_distal`  | 
|---|---|---|
| pos_encoder  | ![thumb_oppose_pos_enc](https://user-images.githubusercontent.com/19152494/98274630-f0784700-1f93-11eb-92b2-b701ce73be0b.png)  |  ![thumb_distal_pos_enc](https://user-images.githubusercontent.com/19152494/98273851-09342d00-1f93-11eb-8dee-ecbd80d5b7c7.png)  |  
|  pos_motor |  ![thumb_oppose_pos_motor](https://user-images.githubusercontent.com/19152494/98274668-fcfc9f80-1f93-11eb-932b-57ba7def8cca.png) |  ![thumb_distal_pos_motor](https://user-images.githubusercontent.com/19152494/98274014-37b20800-1f93-11eb-866c-2e267f03cfac.png) |
| vel_encoder  |  ![thumb_oppose_vel_enc](https://user-images.githubusercontent.com/19152494/98274713-0b4abb80-1f94-11eb-9437-1312d9a0c840.png)  | ![thumb_distal_vel_enc](https://user-images.githubusercontent.com/19152494/98274100-4f898c00-1f93-11eb-8b52-70d4d7ddb3ae.png)  |
| vel_motor  |  ![thumb_oppose_vel_motor](https://user-images.githubusercontent.com/19152494/98274743-1867aa80-1f94-11eb-810a-52fb5d7e8eb1.png)  |  ![thumb_distal_vel_motor](https://user-images.githubusercontent.com/19152494/98274118-544e4000-1f93-11eb-881f-4b0c1ff4c101.png)  | 
 

I hope that this analysis can give hints to @ale-git in order to see the source of the problem

Here is the resulting workspace
[testFingersProblem.zip](https://github.com/icub-tech-iit/fix/files/5495978/testFingersProblem.zip)

**Comment by traversaro** [comment]
> (Is it the case to open a PR for adding this version? Can be useful? cc @traversaro)

Yes sure, feel free to propose a PR, I suspect it will not be used in MAPEst itself, but that script is frequently copied around, so it is good to have a single point where to report improvements.

**Comment by pattacini** [comment]
@ale-git @kouroshD @Nicogene 
Essentially:
- Thumb distal: although the motor and the encoder positions do have opposite signs, their velocities do have the same sign.
- Thumb opposition: velocities are somehow not computed.

**Comment by kouroshD** [comment]
@pattacini  If I am not wrong, this is the behavior for all the hand motors.

**Comment by Nicogene** [comment]
Hi @kouroshD !

@ale-git says:

>About the thumb distal, my best guess is that the Gearbox_M2J parameter has the wrong sign.
The parameter is in https://github.com/robotology/robots-configuration/blob/devel/iCubGenova04/hardware/mechanicals/right_arm-eb28-j8_11-mec.xml
About the thumb opposition I think that the motor quadrature encoder could be simply broken.
I suggest a quick test by changing the thumb distal Gearbox_M2J sign in the configuration file linked above.

Could you please try to change the Gearbox_M2J parameter and try again?

**Comment by kouroshD** [comment]
Thank you @Nicogene  for the updates.

> About the thumb opposition I think that the motor quadrature encoder could be simply broken.

I will try with the left hand.

> I suggest a quick test by changing the thumb distal Gearbox_M2J sign in the configuration file linked above.

So, you are suggesting to reverse the sign of the `Gearbox_M2J` values written here https://github.com/robotology/robots-configuration/blob/d415b08661e9491b0193ecdcb38a460bf6744177/iCubGenova04/hardware/mechanicals/right_arm-eb28-j8_11-mec.xml#L16, from `256` to `-256`?!

**Comment by kouroshD** [comment]
> About the thumb opposition I think that the motor quadrature encoder could be simply broken.

 @Nicogene  Just to understand better, the velocity feedback is computed by time differentiation of the encoder values, right? Since we have values for `thumb_oppose`, then is the broken motor quadrature encoder a valid assumption?!

**Comment by pattacini** [comment]
>@Nicogene Just to understand better, the velocity feedback is computed by time differentiation of the encoder values, right? Since we have values for thumb_oppose, then is the broken motor quadrature encoder a valid assumption?!

@kouroshD made a good point indeed. Any idea @ale-git @Nicogene ?

Changing the sign of `Gearbox_M2J` doesn't sound unusual as there are other cases where the gear ratio is inverted to take into account opposite rotations of the two pulleys. See for example https://github.com/robotology/robots-configuration/search?q=Gearbox_M2J.

**Comment by Nicogene** [comment]
>So, you are suggesting to reverse the sign of the Gearbox_M2J values written here https://github.com/robotology/robots-configuration/blob/d415b08661e9491b0193ecdcb38a460bf6744177/iCubGenova04/hardware/mechanicals/right_arm-eb28-j8_11-mec.xml#L16, from 256 to -256?!

Yes if you search this param in `robots-configuration` sometimes it is set with the - probably for compensating issues like this.
A test on the other arm will be exahaustive in this sense, I expect that Gearbox_M2J has to have the same sign between arms

> @Nicogene Just to understand better, the velocity feedback is computed by time differentiation of the encoder values, right? Since we have values for thumb_oppose, then is the broken motor quadrature encoder a valid assumption?!

The encoder velocity is computed as follows https://github.com/robotology/icub-firmware/blob/master/emBODY/eBcode/arch-arm/embobj/plus/mc/AbsEncoder.c#L480-L508, actually yes it seems that it is computed by time differentiation but maybe @ale-git can correct me.

**Comment by kouroshD** [comment]
Yesterday, I have collected two datasets, one is related to logging the data of both arms left and right, without changing any parameter. I moved hand motors plus wrist and elbow motors. The data is in the following:
[loggedfileWithoutChanges.zip](https://github.com/robotology/icub-tech-support/files/5529207/loggedfileWithoutChanges.zip)

Following your suggestion, I have changed the sign of Gearbox_M2J of the right hand (the ones in [this link](https://github.com/robotology/robots-configuration/blob/d415b08661e9491b0193ecdcb38a460bf6744177/iCubGenova04/hardware/mechanicals/right_arm-eb28-j8_11-mec.xml#L16) to `-256`), and here is the logged data:
[loggedAfterChanging Gearbox_M2J.zip](https://github.com/robotology/icub-tech-support/files/5529223/loggedAfterChanging.Gearbox_M2J.zip)

**Comment by ale-git** [comment]
@xEnVrE has found this comment:

```
        /*
        NOTE: (VALE)
            In this board, thumb oppose and thumb proximal joints are coupled.
            I get decoupled matrix from mc4(CAN) firmware version 0x228 function "decouple_dutycycle".
            In this function, the fw uses a different decoupled matrix if it runs on left arm or right arm.
            Currently I tested only left arm, so we need to check if the same matrix can be use also on twin board on right arm.
        */
```

This part is not used any more because the coupling matrices have been moved to the configuration files, but if there was an error in the right hand it has been moved to the configuration file as well, since the values are the same for right and left hands.

https://github.com/robotology/icub-firmware/blob/f5850b0d935e814eab5f1a448a6471b141dfcc5f/emBODY/eBcode/arch-arm/embobj/plus/mc/Controller.c#L1135

**Comment by ale-git** [comment]
I didn't know that there is a coupling in the thumb. I'll check the mc4 firmware in order to see if the values are different for the two hands.

**Comment by Nicogene** [comment]
I analyzed the data, as before on the right are reported the plots of `thumb_distal`, on the left the `thumb_oppose`.

Here is the plot regarding the right arm **with the M2J fix**.

![r_thumb_oppose_thumb_distal_after_change](https://user-images.githubusercontent.com/19152494/98957603-a34f2480-2501-11eb-8904-d482d33387ba.png)

As expected now motor velocity and encoder velocity now has opposite signs, and now the encoder velocity is coherent with the encoder values.

Here is the data **before the changes** for left arm and right arm respectively

![l_thumb_oppose_thumb_distal_after_change](https://user-images.githubusercontent.com/19152494/98958283-6c2d4300-2502-11eb-9c88-461932897ac2.png)
![r_thumb_oppose_thumb_distal_after_change](https://user-images.githubusercontent.com/19152494/98958311-73545100-2502-11eb-95ce-a723489e86ef.png)

**Comment by pattacini** [comment]
So we managed to solve the problem related to the sign of the velocity, cool 👍🏻 
The velocity of the thumb opposition is still zero though.

**Comment by pattacini** [comment]
Hi @kouroshD 

Do you mind opening up a PR to fix the sign problem?
Meanwhile, we'll be reasoning on the thumb opposition problem.

**Comment by kouroshD** [comment]
> Hi @kouroshD
> 
> Do you mind opening up a PR to fix the sign problem?
> Meanwhile, we'll be reasoning on the thumb opposition problem.

Sure, I will do it. @pattacini  @Nicogene Thank you for the investigation that and spotting the problem.

**Comment by pattacini** [comment]
Concerning the velocity of the thumb opposition, @ale-git is investigating whether the following explanation may be plausible.

The coupling matrices (direct and inverse) contain the correct signs that give the direction of motion but wrong absolute values. This hypothesis may explain why the position control is behaving as expected (we just need the correct signs) and why, by contrast, the computed velocities end up being very small (practically equal to zero).

Investigating... ⚙

**Comment by ale-git** [comment]
The source of the hand coupling model is the CAN robot, in particular:

https://github.com/robotology/icub-firmware/blob/60c6b0485d178a08f124e000212239fc32ddd51b/motorControllerDsp56f807/common_source_code/pwm_decoupling.c#L126

```
    if (_kp[0] > 0)
    {
        //right hand
        pwm_out[0] = pwm[0];
        pwm_out[1] = pwm[1] + pwm[0];
        pwm_out[2] = pwm[2];
        pd_out[0] = _pd[0];
        pd_out[1] = _pd[1] + _pd[0];
        pd_out[2] = _pd[2];
    }
    else
    {
        //left hand
        pwm_out[0] = pwm[0];
        pwm_out[1] = pwm[1] - pwm[0];
        pwm_out[2] = pwm[2];
        pd_out[0] = _pd[0];
        pd_out[1] = _pd[1] - _pd[0];
        pd_out[2] = _pd[2];
    }
```

In the .xml configuration file hardware/mechanicals/right_arm-eb28-j8_11-mec.xml we have:

```
    <group name="COUPLINGS"> 
                            
        <param name ="matrixJ2M"> 
            1.000   0.000   0.000   0.000
           -1.000  +1.000   0.000   0.000
            0.000   0.000   1.000   0.000
            0.000   0.000   0.000   1.000   
        </param>

         <param name ="matrixM2J"> 
            1.000   0.000   0.000   0.000
           +1.000  +1.000   0.000   0.000
            0.000   0.000   1.000   0.000
            0.000   0.000   0.000   1.000   
        </param>
```

It seems wrong to me since it is identical to the left hand. My guess is that the right configuration file has been copied from the left one but the coupling numbers haven't been updated. Accordingly to the CAN robot originals, the coupling in the right hand should be:

```
    <group name="COUPLINGS"> 
                            
        <param name ="matrixJ2M"> 
            1.000   0.000   0.000   0.000
           +1.000  +1.000   0.000   0.000
            0.000   0.000   1.000   0.000
            0.000   0.000   0.000   1.000   
        </param>

         <param name ="matrixM2J"> 
            1.000   0.000   0.000   0.000
           -1.000  +1.000   0.000   0.000
            0.000   0.000   1.000   0.000
            0.000   0.000   0.000   1.000   
        </param>
```

**Comment by pattacini** [comment]
Thanks heaps @ale-git 👍🏻 

I believe this is only part of the investigation yet, which should allow us to sort out a bug anyway, as it's unlikely that this can explain why we don't get velocities from both hands.

**Comment by pattacini** [comment]
@kouroshD I would ask you to integrate into the upcoming PR also the [modifications][1] highlighted by @ale-git above in order to fix the control of the right thumb, at least.

Once done, could you please report here the outcome of any ongoing test?

We talked to @ale-git today and he also agrees that there must be still something else on the velocity side.

Still investigating... ⚙

[1]: https://github.com/robotology/icub-tech-support/issues/1019#issuecomment-730148256

**Comment by kouroshD** [comment]
@pattacini I should open the PR on `devel`, right?!

**Comment by pattacini** [comment]
I'd say so yes, thanks! 👍🏻 

@Nicogene let's keep an eye wide open on this because of the upcoming distro 2020.11 👀

**Comment by kouroshD** [comment]
I've opened the PR in https://github.com/robotology/robots-configuration/pull/206

I've added the fixes for all the  motors of the left and right hands. Moreover, I've added the fix suggested in https://github.com/robotology/icub-tech-support/issues/1019#issuecomment-730148256

**Comment by pattacini** [comment]
Thanks a lot @kouroshD 👍🏻 
PR merged ✔️ 

I would keep still open anyway to address https://github.com/robotology/icub-tech-support/issues/1019#issuecomment-730253787.

**Comment by kouroshD** [comment]
Thanks a lot @pattacini

**Comment by pattacini** [comment]
@kouroshD did you have already the chance to test these modifications?

**Comment by kouroshD** [comment]
> @kouroshD did you have already the chance to test these modifications?

No, not yet. Others were using the robot, and there is a problem with robot configuration installation to be investigated.
cc @traversaro

**Comment by pattacini** [comment]
Hi @kouroshD 

Regarding the null velocity, I had the chance to talk to @ale-git today, who told me that velocities seem to be computed by differentiating the motor encoders. Look at https://github.com/robotology/robots-configuration/blob/master/iCubGenova04/hardware/mechanicals/left_arm-eb26-j12_15-mec.xml#L18.

This is conceptually wrong. Therefore, you could proceed by trying to change those parameters to all zeros. This way, the differentiation will be applied to the joint encoders, as it should be.

Once done, you could open up another convenient PR.

The fact that the velocity of the thumb opposition is zero stems then from the motor encoder that remains unvaried as well (probably it's broken).

Awaiting your feedback on this.

**Comment by kouroshD** [comment]
OK, thanks to @traversaro,  we fixed the problem mentioned here. But then, the right hand of iCub is sort of broken so, I cannot yet confirm for that. However, I did the check for the left hand. It seems like not all the values should become `-`. So, here is the result for all the left-hand motors.













|  Left hand values before the fix | Left hand values after the  fix  |
|---|---|
| ![Motor_angles_velocities1](https://user-images.githubusercontent.com/17707730/100373606-52fcba00-300b-11eb-8644-46bb1943f666.png) |  ![Motor_angles_velocities1](https://user-images.githubusercontent.com/17707730/100374087-0b2a6280-300c-11eb-8aa7-bbf4774533dc.png) |
|  ![Motor_angles_velocities2](https://user-images.githubusercontent.com/17707730/100373610-54c67d80-300b-11eb-9412-a50172fd8727.png) |  ![Motor_angles_velocities2](https://user-images.githubusercontent.com/17707730/100374094-0cf42600-300c-11eb-945d-1a4d800732b3.png) |
| ![Motor_angles_velocities3](https://user-images.githubusercontent.com/17707730/100373612-555f1400-300b-11eb-90e9-691b92a84b72.png)   |  ![Motor_angles_velocities3](https://user-images.githubusercontent.com/17707730/100374100-0e255300-300c-11eb-8ac7-8de6897e67be.png) |
|  ![Motor_angles_velocities4](https://user-images.githubusercontent.com/17707730/100373615-55f7aa80-300b-11eb-8406-66fb26c4198a.png) |  ![Motor_angles_velocities4](https://user-images.githubusercontent.com/17707730/100374103-0ebde980-300c-11eb-8e10-25b27ebadeee.png) |
| ![Motor_angles_velocities5](https://user-images.githubusercontent.com/17707730/100373617-56904100-300b-11eb-9d8b-d0d420ba5353.png) |  ![Motor_angles_velocities5](https://user-images.githubusercontent.com/17707730/100374104-0f568000-300c-11eb-931f-96fecee83c1e.png) |
| ![Motor_angles_velocities6](https://user-images.githubusercontent.com/17707730/100373619-56904100-300b-11eb-9853-326f922cfed9.png)  | ![Motor_angles_velocities6](https://user-images.githubusercontent.com/17707730/100374109-0fef1680-300c-11eb-8cc3-4c2f9f602f97.png)  |
| ![Motor_angles_velocities7](https://user-images.githubusercontent.com/17707730/100373620-5728d780-300b-11eb-9c17-1afb4c18eb65.png)  |  ![Motor_angles_velocities7](https://user-images.githubusercontent.com/17707730/100374112-1087ad00-300c-11eb-9a88-35a6a3f2f2bc.png) |
|  ![Motor_angles_velocities8](https://user-images.githubusercontent.com/17707730/100373621-57c16e00-300b-11eb-9ac2-fa476a22715c.png)  |  ![Motor_angles_velocities8](https://user-images.githubusercontent.com/17707730/100374114-1087ad00-300c-11eb-9c24-d2842815669e.png)  |

The dashed lines are computed not feedbacks. 
- Blue line: motor angle feedback
- Blue dashed line: motor angle computed from integration of velocities
- Orange line: motor velocity feedback
- Orange dashed line: motor velocities computed from derivation of motor angles

###
So, the values should for the left hand int configuration files should be:
```
Motor 1:  X         Motor 5:  -256
Motor 2:  256    Motor 6:    256
Motor 3:  256    Motor 7:    256
Motor 4:  256    Motor 8:    -256
```
Data for before changing the configuration values:
[Archive.zip](https://github.com/robotology/icub-tech-support/files/5604064/Archive.zip)

Data for before after changing the configuration values:
[Archive 2.zip](https://github.com/robotology/icub-tech-support/files/5604068/Archive.2.zip)

I will fix this for the next PR.

**Comment by pattacini** [comment]
Great debugging @kouroshD 👍🏻 

>It seems like not all the values should become `-`

You know why? To fix a wrong winding of the cables around the pulley in the past it was common to change the sign of those parameters. This shouldn't be happening any longer (hopefully).

**Comment by kouroshD** [comment]
> Hi @kouroshD
Regarding the null velocity, I had the chance to talk to @ale-git today, who told me that velocities seem to be computed by differentiating the motor encoders. Look at https://github.com/robotology/robots-configuration/blob/master/iCubGenova04/hardware/mechanicals/left_arm-eb26-j12_15-mec.xml#L18.
This is conceptually wrong. Therefore, you could proceed by trying to change all the values of useMotorSpeedFbk to zero. This way, the differentiation will be applied to the joint encoders, as it should be.

So, this means, if `useMotorSpeedFbk` is to true, then for force feedback we are using the motor encoders, otherwise we are using the joint encoders to compute the velocity feedback.

>  Once done, you could open up another convenient PR.
The fact that the velocity of the thumb opposition is zero stems then from the motor encoder that remains unvaried as well (probably it's broken).
Awaiting your feedback on this.

Yes, I will do the requested changes. As you said it can be because of broken motor encoders in that case. However, the two thumbs together have the same problem has low probability. I will do it tonight and let you know.

**Comment by pattacini** [comment]
> Do you think the problem of wrong winding can be addressed in that issue as well. If not, I will keep the values we found. If this can be addressed as well, we can keep all the values equal to 256.

Rewinding cables can be quite time-consuming, I'm afraid. Check that with @julijenv, but I believe we can survive for the time being with the current situation.

Essentially, software-wise we had to:
- update the calibration matrices
- fiddle with `Gearbox_M2J`
- put `useMotorSpeedFbk` equal to 0

You applied/are going to apply those changes to `iCubGenova04`. Can you double-check that?

Then, we'll be dealing with extending the mods to all remaining robots.

**Comment by kouroshD** [comment]
> Rewinding cables can be quite time-consuming, I'm afraid. Check that with @julijenv, but I believe we can survive for the time being with the current situation.

OK, I'll check with him, otherwise I'll find the signs for `Gearbox_M2J` of the right hand after it is fixed.

> update the calibration matrices

Which calibration matrix? you mean coupling `matrixJ2M ` matrix? If yes, I've done that before!

> put useMotorSpeedFbk equal to 0

I should double-check this for the right arm, but currently is broken. 


@pattacini  @traversaro  As a matter of curiosity, I've checked all the values of `useMotorSpeedFbk`for all the robot parts and they are equal to `1`. Then, how we control the robot at higher levels if somebody needs the velocity feedback?!  I mean for some motor/joints part may not change if there is no coupling there, but for the coupled motor/joints it should change a lot? Shoudn't we put `useMotorSpeedFbk` for all the robot by default to `0`?

**Comment by pattacini** [comment]
>Which calibration matrix? you mean coupling matrixJ2M matrix? If yes, I've done that before!

Yep, sorry, coupling matrix. I've amended my comment above.

>@pattacini @traversaro As a matter of curiosity, I've checked all the values of useMotorSpeedFbkfor all the robot parts and they are equal to 1. Then, how we control the robot at higher levels if somebody needs the velocity feedback?! I mean for some motor/joints part may not change if there is no coupling there, but for the coupled motor/joints it should change a lot? Shoudn't we put useMotorSpeedFbk for all the robot by default to 0?

We are going to update all the robots for what concerns the finger control, where actually the velocity feedback is never used, or at least the velocities are usually computed at the high level.

The fact that the motor joints are always chosen for doing differentiation I think stems from the high-speed (optical) encoders that provide much more ticks per round in the hope that this gives in turn more stable estimates for the speed. I've never been convinced about that, honestly. As you can see from your plots, differentiating high-speed encoders does not guarantee clean velocity signals.

**Comment by traversaro** [comment]
fyi @isorrentino (in particular the last comment by @pattacini)

**Comment by kouroshD** [comment]
@pattacini  But then, in this case the coupling between the motors and joints should be taken into account for the higher level control, no?! Because at the end what is important for higher level controllers are the joint velocities? For example consider the shoulder joints that the motors and joints are coupled.

cc @DanielePucci

**Comment by pattacini** [comment]
>@pattacini But then, in this case the coupling between the motors and joints should be taken into account for the higher level control, no?! Because at the end what is important for higher level controllers are the joint velocities? For example consider the shoulder joints that the motors and joints are coupled.

Sure, but the velocities computed at the motor side are then of course processed through the coupling and/or simply the gear ratio and reported to the joint side. By doing this, we're assuming that the map remains constant, which is actually a good approximation of a tendon-driven actuation, but you know, not really for the hands where we have slack and a lot of felixibility.

**Comment by kouroshD** [comment]
As soon as we have the right hand again, I will check that, and open a PR.

**Comment by Uboldi80** [comment]
Following a thorough check on the hands that are currently on my desk for maintenance, we found that some proximal tendons were wrapped incorrectly, moreover almost certainly, as indicated by @gsisinna , following the profound experience made on the joints of the inches and on the coupling of the same, I imagine that most likely the coupling matrix is to be verified.
