### ISSUE TITLE
Bumpy head motor

### ISSUE THREAD

**Issue by Iaxama** [robotology/icub-tech-support#1022]
## Brief description of the request/failure
The neck pitch joint of the head keeps going in hardware fault.

## Detailed context
Motor needed to be disassembled, lubricated, and put back in place in order to run smoothly. Doctor @julijenv took care of it.

**Comment by julijenv** [comment]
As mentioned by @laxama i had to tear apart some piece of the motor, the grease was very old and rusty, i clean everything (the rotor part of the motor) and make some little adjustments.
