### ISSUE TITLE
iCubGenova08: Left thumb cable broken

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1026]
## Brief description of the request/failure
We'd need @julijenv intervention for fixing the cable of the left thumb, 
We are currently using the left hand without the 3 joints of the broken part.

As suggested we modified the file:

`iCubGenova08/calibrators/left_arm-calib.xml`

with the following change in the calib order:

`<param name="CALIB_ORDER">(0 1 2 3) (4) (5 6 7) ( 11 13) ( 12 14 15) </param>`

## Accompanying material
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/3440640/99054137-7b130480-2599-11eb-99d3-951050f87417.png)

**Comment by julijenv** [comment]
has been repaired , it was the proximal thumb broken.

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| 1815|1m|carlsthal 0.63mm||
