### ISSUE TITLE
icubGenova04 wrist stays in hardware fault

### ISSUE THREAD

**Issue by kouroshD** [robotology/icub-tech-support#1028]
## Brief description of the request/failure

icubGenova04 wrist stays in hardware fault and does not calibrate.

## Detailed context
The error shown in the logger is:
```
21084	4700.530971	ERROR		 from BOARD 10.0.1.27 (right_arm-eb27-j4_7), src LOCAL, adr 0, time 178s 893m 63u: (code 0x02000008, par16 0x0002 par64 0x000000000000000b) -> MC: AEA encoder invalid data. Hardware problem in the magnetic position sensor of the joint caused invalid position readings. par16 = AEA port (msb) and ID of joint (lsb). + .
```
It seems that the cables are fine. 
## Accompanying material

[log_icub-head_yarprobotinterface_9608.zip](https://github.com/robotology/icub-tech-support/files/5554727/log_icub-head_yarprobotinterface_9608.zip)

**Comment by julijenv** [comment]
it seems like the AEA encoder grounding was flaky. Now it worls (I recrimp the ground of the AEA)
