### ISSUE TITLE
icubGenova04 left shoulder cable is broken

### ISSUE THREAD

**Issue by kouroshD** [robotology/icub-tech-support#1029]
## Brief description of the request/failure

We were doing some teleoperation experiments, and after some time the robot went to strange configuration, and as a result the left shoulder cable is broken.

## Detailed context

![photo_2020-11-17_19-44-30](https://user-images.githubusercontent.com/17707730/99433502-e0565500-290d-11eb-9af7-809986c7d942.jpg)

## Accompanying material

[log_icub30_HapticGloveModule_31540.txt](https://github.com/robotology/icub-tech-support/files/5555542/log_icub30_HapticGloveModule_31540.txt)

**Comment by julijenv** [comment]
it has been reapired

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| 4764.1 | 1 | shoulder cable 7 |  |
