### ISSUE TITLE
Connection errors to the torso

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1034]
## Brief description of the request/failure
After restarting the ``yarprobotinterface`` it often happens that the robot is not able to communicate with the torso. I attach here the log.

## Detailed context
There seems to be problems in communicating with the torso.

## Accompanying material

[log_icub-head_yarprobotinterface_26057_torso_not_Starting.txt](https://github.com/robotology/icub-tech-support/files/5575415/log_icub-head_yarprobotinterface_26057_torso_not_Starting.txt)

cc @GiulioRomualdi

**Comment by S-Dafarra** [comment]
The robot is not starting anymore 
[log_icub-head_yarprobotinterface_2960_notStarting.txt](https://github.com/robotology/icub-tech-support/files/5664842/log_icub-head_yarprobotinterface_2960_notStarting.txt)

**Comment by S-Dafarra** [comment]
By looking at the ``FirmwareUpdater`` it seems that the problem may be on the right arm. Indeed, we had to mount a new cover recently cc @salvi-mattia 

![image](https://user-images.githubusercontent.com/18591940/101612227-b541bb80-3a0a-11eb-99f0-91402f0440d7.png)

**Comment by julijenv** [comment]
the cable from EB29 (right forearm - C shape MC4+) and the torso had the green cable broken from the root of the connection inside the upper arm - probably due to continuous open and close cover to check hardware pblm
