### ISSUE TITLE
Right thumb distal does not reach the lower limit

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1036]
## Brief description of the request/failure

When commanded to 0, the joint `r_thumb_distal` cannot go beyond ~23 degrees.

## Accompanying material

![Screenshot from 2020-11-21 14-53-52](https://user-images.githubusercontent.com/6014499/99879016-c1a3d700-2c09-11eb-91a9-632d4ff885d3.png)

**Comment by julijenv** [comment]
Hi @xEnVrE ,
I think we mae kthis ok this morning recalibrating hte thumb, so I close it
