### ISSUE TITLE
iCubGenova04 cable of the right shoulder is broken 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1038]
One of the cables of the right shoulder got broken while testing the torque control with the new velocity estimation filter.

![2020-11-24-174248](https://user-images.githubusercontent.com/16744101/100124915-81985a80-2e7c-11eb-8c5f-d43430ac9c5d.jpg)

cc @isorrentino @kouroshD and @S-Dafarra

**Comment by julijenv** [comment]
Hi @GiulioRomualdi , a part from the fact that the picture was mirrored (it iwas the left choulder which was broken, but on the picure it looks like it is the right one)
It has been repaired and tested.
everything okrs well now.
you can proceed.

It has been taken from warehouse:

IITCODE|ALIAS|Qta|rev.|Description
-- | -- | -- | -- | --
4759 | RC_IIT_019_G_002 | 1 |  1| SHOULDER ROTATION CABLE 2
