### ISSUE TITLE
iCubGenova04 right thumb oppose and proximal does not work

### ISSUE THREAD

**Issue by kouroshD** [robotology/icub-tech-support#1039]
## Brief description of the request/failure

The  right thumb oppose and proximal of iCubGenova04 does not work.
## Detailed context
One of the two coupled motors of right thumb works, but the other one does not work. So we can control well the robot right thumb finger.

**Comment by kouroshD** [comment]
This morning, when I started the robot it was working the right hand. However, after some time all the fingers starts shaking and went to hardware fault again.

**Comment by julijenv** [comment]
It has been restored the nentire wiring on the last finger.
it has been done the recalibration of all the joints of the forrearm
THe robot start nicely, I suppose everthing is alright now, let me know

**Comment by kouroshD** [comment]
Thanks a lot @julijenv  for the great work you have done. 
I'll confirm that right thumb oppose and proximal are working correctly now.
