### ISSUE TITLE
The wheels of the iCubGenova09 pole are very bent

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1042]
## Brief description of the request/failure
Several of the wheels of the iCubGenova09 pole seem to be about to fall (see picture below). As a consequence, it also became hard to move since the chassis closes the brakes.

## Detailed context
By looking at the back of the robot, I have noticed the two wheels on the right to be particularly bent.

## Accompanying material

![image](https://user-images.githubusercontent.com/18591940/100982135-fc7e0700-3547-11eb-9500-4173226f9d8b.png)
![image](https://user-images.githubusercontent.com/18591940/100982150-01db5180-3548-11eb-949b-d0677d066503.png)
![image](https://user-images.githubusercontent.com/18591940/100982191-09025f80-3548-11eb-899e-12ab3503d1cc.png)

cc @pattacini @GiulioRomualdi @prashanthr05 @DanielePucci

**Comment by julijenv** [comment]
Hi @S-Dafarra ,
unfirtunately I cant do anything as long as the robot is on the stand, Plus my first question, will be: wwas the stand created to bear the weigh of iCub3? maybe iCub3 is way heavier than each wheel can stand.
Anyhow, net time you have the robot away form the stand letme know and I will check

**Comment by DanielePucci** [comment]
@julijenv 
> unfortunately, I can't do anything as long as the robot is on the stand,

I believe you can use a crane to lift the robot

**Comment by S-Dafarra** [comment]
The robot is held on the pole by three screws (hexagonal, dimension 5), accessible from the bottom of the root link. In case, I can help you tomorrow in taking it off the pole

**Comment by S-Dafarra** [comment]
The screws holding the wheels were almost completely unscrewed. I tighten them up and the problem is fixed. Closing
