### ISSUE TITLE
Right_Arm Calibration (Joint 15) (r_little_finger) iCubGenova07 

### ISSUE THREAD

**Issue by omareldardear** [robotology/icub-tech-support#1043]
## Brief description of the request/failure
Joint 15 of the right arm fail to calibrate. 

## Detailed context
we firstly noticed a little noise from on of the motors in the right arm (the calibration was going right at that time) 
Now.. This noise became much louder and during the trials of calibrating joint 15 of the right arm. 
The calibration fail for this arm and cause some other joints in the wrist to be in Idle mode. 
The state of joint 15 is Not configured in yarpmotorgui (Can't be controlled)

Note: This Issue happened before, and was fixed by changing the cable as far as I know
The old closed issue is here https://github.com/robotology/icub-tech-support/issues/958 

## Accompanying material

Errors from the log of yarprobotinterface 

[ERROR]Right_Arm_Calibrator : Timeout while calibrating  15 
[ERROR]Right_Arm_Calibrator : set 5 : Calibration went wrong! Disabling axes and keeping safe pid limit

[ERROR]A 0.250000 sec timeout occured in embObjMotionControl::checkRemoteControlModeStatus(), BOARD right_arm-eb29-j12_15 IP 10.0.1.29, joint 3, current mode: cal, requested: idl
[ERROR]failure of embObjMotionControl::checkRemoteControlModeStatus(j=3, targetmode=idl) for BOARD right_arm-eb29-j12_15 IP 10.0.1.29 after 17 attempts and 0.261028 seconds
[ERROR]In embObjMotionControl::setControlModeRaw(j= 3 , mode= idl ) for  BOARD right_arm-eb29-j12_15 (IP 10.0.1.29)   has failed checkRemoteControlModeStatus()

**Comment by julijenv** [comment]
Hi @omareldardear ,
eveything should be alright now.
it will remain to rwire the ring finger of he left arm which close a bit later than the pinkie finger.
next time
