### ISSUE TITLE
Left thumb cable broken and right hand not calibrating on iCubGenova04

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1045]
## Brief description of the request/failure

The left thumb cable on iCubGenova04 is broken due to the failure occurred in https://github.com/robotology/icub-tech-support/issues/1044.

## Detailed context

see https://github.com/robotology/icub-tech-support/issues/1044

**Comment by julijenv** [comment]
Has been repaired.
After checking there were also both pinky and ring fingers broken
