### ISSUE TITLE
Sometimes the left arm goes in hardware fault at startup

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1046]
## Brief description of the request/failure

on iCubGenova04, we noted that sometimes the left shoulder roll goes in hardware fault at startup.

## Detailed context

I will add more details as soon as it happens again.
cc @isorrentino @CarlottaSartore

**Comment by julijenv** [comment]
Hi @gabrielenava ,
Please add a log file whenever it repeats
cc @isorrentino , @CarlottaSartore
