### ISSUE TITLE
iCubOS image request

### ISSUE THREAD

**Issue by Iaxama** [robotology/icub-tech-support#1052]
## Brief description of the request/failure
Given the necessity to reinstall the OS on the laptops of the iCub Purple robot, we would need the iCubOS images for either laptops, CUDA workstation, head and server.

**Comment by Iaxama** [comment]
@traversaro

**Comment by traversaro** [comment]
cc @mbrunettini 

Note that this request has been done following the documentation in https://icub-tech-iit.github.io/documentation/icub_operating_systems/other-machines/icub-server-from-image/#where-to-get-the-latest-icubos-image .

**Comment by julijenv** [comment]
Hi @mbrunettini 
in proto we have one head already cabled (ex-TUC) that can be taken to try to mount the new OS if i can be of any help..
@Fabrizio69 , @violadelbono

**Comment by Iaxama** [comment]
In the end we have managed to set up the OS starting from a clean Ubuntu 20.04 installation. The server and the head are unchanged, and the network set up was pretty smooth. First tests show that the regular workflow to start up the robot is working as usual.

**Comment by traversaro** [comment]
> 
> 
> Hi @mbrunettini
> in proto we have one head already cabled (ex-TUC) that can be taken to try to mount the new OS if i can be of any help..
> @Fabrizio69 , @violadelbono

To clarify, the request from @Iaxama was about the latest image with Ubuntu 18.04, not the new one (that I guess is still not ready) with Ubuntu 20.04 .

**Comment by violadelbono** [comment]
@Iaxama can we close this issue?

**Comment by traversaro** [comment]
For everyone from the community still interested on this: the uploading of the iCubOS image somewhere from which anyone can download them is still a work in progress, but it is tracked in an IIT internal repo.
