### ISSUE TITLE
The robot power supply makes a lot of noise when the boards are running

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1054]
## Brief description of the request/failure
After the new power cable has been mounted on iCubGenova09, we noticed that the power supply makes an annoying whistle when starting the motors. It was not happening before.

**Comment by julijenv** [comment]
Hi @S-Dafarra ,
unfortunately the sound is coming from the reaction from the Power supply to the plug of the current sensing that has been added. It regulates the voltage and current and the frequencies of the pwm can be inside the hearing bandwidth, the only thing that can be done is removing it to get rid off the noise.
let me know what you prefer.

**Comment by S-Dafarra** [comment]
> Hi @S-Dafarra ,
> unfortunately the sound is coming from the reaction from the Power supply to the plug of the current sensing that has been added. It regulates the voltage and current and the frequencies of the pwm can be inside the hearing bandwidth, the only thing that can be done is removing it to get rid off the noise.
> let me know what you prefer.

What do we gain in having the current sensing wrt not having it?

**Comment by S-Dafarra** [comment]
We got used to it :grin: Closing
