### ISSUE TITLE
Right ankle roll encoder is dirty 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1055]
## Brief description of the request/failure
Whenever we try the walking-controller on iCubGenova09 the right ankle roll joint went in hardware fault because of `2FOC quadrature encoder dirty`

Here the complete error:
```
	8686,378997	ERROR		 from BOARD 10.0.1.12 (right_leg-eb12-j4_5), src LOCAL, adr 0, time 1467s 625m 336u: (code 0x0200000b, par16 0x0001 par64 0x0000000000000000) -> MC: 2FOC quadrature encoder dirty. The number of thicks in a complete revolution of the motor was lower than expected, the optical disks need to be cleaned. In par64 0xFF is the mask of raw encoder value. par16 = ID of joint. + .
``` 

## Accompanying material
Here the log: [log_icub-head_yarprobotinterface_6457_right_ankle.txt](https://github.com/robotology/icub-tech-support/files/5810157/log_icub-head_yarprobotinterface_6457_right_ankle.txt)

cc @S-dafarra

**Comment by julijenv** [comment]
Hi @GiulioRomualdi ,
it has been cleanded yeserday the optical disk,hopefully it will resolve the issue.I close it , ut feel free to reopend it if it rehappen
