### ISSUE TITLE
Left elbow does not move

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1056]
## Brief description of the request/failure
The left elbow does not start. As soon as we run the ``yarprobotinterface`` the left elbow goes into hardware fault because of I2T error, and it does not move. From the ``motorgui`` it is possible to run it again, but it just makes some very small movement and it goes in hardware fault immediately. We also noticed that the measured current reaches high values (around 9A) even if it does not move at all.

**Comment by julijenv** [comment]
Unfortunately, the iCubGenova09 firmware on evryboard had been twicked to get rid of the message error :

> MC: 2FOC quadrature encoder phase broken. The motor encoder is not counting even if the motor is moving, please check motor encoder cables

and as a result we were not advised to chech the AEA, which was broken.
rewiring the AEA cable broekn save the day
