### ISSUE TITLE
iCubErzelli01: Right thumb cable broken

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1059]
## Brief description of the request/failure
During experiment the right thumb cable broke.

## Accompanying material
![image](https://user-images.githubusercontent.com/3440640/104898594-1fd70700-597a-11eb-8861-b26f73a16d93.jpeg)

**Comment by julijenv** [comment]
It has been repaired both the thumb proximal and distal cable.
It has beentaken from the toolbox the following itemns:
IITCODE Qta DEsciption
1895x1m: carlstahl cable 0.63mm uncoated
2391x1m:cakstahl cable 0.61 uncoated
