### ISSUE TITLE
Left shoulder roll AEA problem

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1063]
## Brief description of the request/failure
While moving the robot, the left should roll encoder outputs invalid data.
Here the error:
```
 from BOARD 10.0.1.1 (left_arm-eb1-j0_1), src LOCAL, adr 0, time 464s 680m 680u: (code 0x02000008, par16 0x0001 par64 0x0000000000000002) -> MC: AEA encoder invalid data. Hardware problem in the magnetic position sensor of the joint caused invalid position readings. par16 = AEA port (msb) and ID of joint (lsb). + .
```
## Detailed context
This does not happen at startup, but when moving the joint

## Accompanying material

[log_icub-head_yarprobotinterface_9294_left_shoulder_roll_issue.txt](https://github.com/robotology/icub-tech-support/files/5849489/log_icub-head_yarprobotinterface_9294_left_shoulder_roll_issue.txt)

**Comment by julijenv** [comment]
it has been recrimped to 2 calbes and done
