### ISSUE TITLE
Left shoulder cables broken

### ISSUE THREAD

**Issue by FabioBergonti** [robotology/icub-tech-support#1064]
## Brief description of the request/failure
During an experiment with iCubGenova04, the left shoulder cables got broken (cable 1 and 8).

## Detailed context
The failure occurred during a balancing experiment.

## Accompanying material

![20210121_142622](https://user-images.githubusercontent.com/38210073/105359545-dd226280-5bf7-11eb-8f37-ed6eef2cb35f.jpg)

**Comment by julijenv** [comment]
it has been taken from the warehouse
IITCODE|Qta|Description
---|---|---
