### ISSUE TITLE
iCubGenova01 - Right hand thumb proximal cable broken

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1071]
## Brief description of the request/failure

During the calibration phase, the cable got broken.

![IMG_20210206_113643504](https://user-images.githubusercontent.com/6014499/107116018-e9055a00-6870-11eb-964f-3b2892c8a254.jpg)

**Comment by julijenv** [comment]
Hi @xEnVrE ,
as for the request the proximal joint has been restored
it has been taken from the warhouse the foolowing item

IITCODE| Qta |Description
---|---|---
1815 | 1m | Carlstahl 0.63mm

**Comment by xEnVrE** [comment]
Thank you @julijenv
