### ISSUE TITLE
Left shoulder tendon broken

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1080]
## Brief description of the request/failure
During an experiment, something went wrong with the references on the left shoulder and some cables broke.

## Accompanying material

![image](https://user-images.githubusercontent.com/18591940/107801055-dd79cd80-6d5f-11eb-8533-fa5d973d87f0.png)

**Comment by S-Dafarra** [comment]
cc @violadelbono @kouroshD @Yeshasvitvs

**Comment by violadelbono** [comment]
Cable 7 of left shoulder was repaired:

|IITCODE   |  ALIAS  | REV  |  QUANTITY |  DESCRIPTION |
|---|---|---|---|---|
| 4764 | RC_IIT_019_G_007 | 1 | 1  | SHOULDER ROTATION CABLE 7 |
