### ISSUE TITLE
Thumb proximal cable tendon broke at startup

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1082]
## Brief description of the request/failure
During the initial calibration phase, the right thumb got broken on its own. In any case, it was not moving well before either. See https://github.com/robotology/icub-tech-support/issues/1075#issuecomment-778328711

**Comment by julijenv** [comment]
it has been repaired by @giacomovassallo

list of material taken from warehouse for the repair
| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| 1815 | 1m | stainless steel microcable |  |
| 13900 | 2 | set screw |  |
