### ISSUE TITLE
iCubGenova01 - right r_pinky misbehaves

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1086]
## Brief description of the request/failure

After calibration, while the right ring stays at zero degrees, the right little finger goes to ~ 90 degrees and the encoder in the `yarpmotorgui` reads ~ 125 degrees for the joint `r_pinky`.

If I try to command zero degrees, nothing happens.

If I try to command the maximum value, first the little goes to zero (unexpected) and then both ring and little closes (expected). After that If I try to command zero degrees, both fingers open but then, after some seconds, the little closes again, ~ 90 degrees, and the encoder reads 125.0 for the joint `r_pinky`.

## Detailed context

The issue has appeared today but the right hand was not used for weeks.

**Comment by julijenv** [comment]
it looks like we need to recalibrate the last fingers

**Comment by xEnVrE** [comment]
Meanwuile, as discussed together, I disabled calibration on `r_pinky` to avoid braking the cable during robot startup.

**Comment by violadelbono** [comment]
Hi @xEnVrE, I was thinking to look at this tomorrow, is it fine for you?

**Comment by xEnVrE** [comment]
Hi @violadelbono, yes it is fine with me!

**Comment by xEnVrE** [comment]
It is working as expected after @violadelbono intervention.

Thank you!
