### ISSUE TITLE
Left arm wrist not calibrating correctly

### ISSUE THREAD

**Issue by lunagava** [robotology/icub-tech-support#1088]
## Brief description of the request/failure
The wrist yaw of the left arm (iCubGenova02) seems not calibrating correctly with the fingers pointing slightly upwards (not pointing straight).

**Comment by lrapetti** [comment]
Adding here a picture a reference picture I took today.
I think also the right one might not be perfectly calibrated (pointing a bit downwards?)

![photo5911310377822565989 (1)](https://user-images.githubusercontent.com/35487806/109998279-5c37aa00-7d11-11eb-9e68-23e1d526921b.jpg)

**Comment by violadelbono** [comment]
Wrist pitch and yaw recalibrated (here the [commit](https://github.com/robotology/robots-configuration/commit/3c71e095a7c1c6b5463518dcbe96746430e588b6)).
