### ISSUE TITLE
The right thumb proximal (?) bearing is worn out

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1089]
## Brief description of the request/failure
After fixing the right thumb many times, it turned out that one of the bearings may need to be replaced.

**Comment by kouroshD** [comment]
Is there any plan to fix this issue @violadelbono ?

**Comment by violadelbono** [comment]
@kouroshD I have been busy, I can try to plan that for next week

**Comment by GiacomoVassallo13** [comment]
@violadelbono the bearing has been replaced.
cc: @S-Dafarra

**Comment by violadelbono** [comment]
See ticket https://github.com/icub-tech-iit/tickets/issues/1147
Closing.
