### ISSUE TITLE
Cameras did not start after unpacking the robot

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1090]
## Brief description of the request/failure
During a demo, as soon as we unpacked the robot, the cameras did not start. Here a screenshot of the error when launching the camera device:
![a7471601-e36e-4e06-a16a-7592fb9b5ced](https://user-images.githubusercontent.com/18591940/109855312-66e23880-7c58-11eb-9097-7d95f9386ec2.jpg)

In particular, the device exited with the error ``no active cameras``.
After rebooting the head, the issue did not appear anymore. So this issue is mainly for reporting the problem and discussing about possible causes.

**Comment by S-Dafarra** [comment]
This is the line of code that throws the error: https://github.com/robotology/icub-main/blob/6a27bc28c9570db7f96a3e033a563f1ec6291ce3/src/libraries/icubmod/dragonfly2/linux/FirewireCameraDC1394-DR2_2.cpp#L335

**Comment by violadelbono** [comment]
Hello @S-Dafarra, I put this issue in the Feedback pipeline, please write here if it happens again.
It could be an isolated event.
