### ISSUE TITLE
iCubErzelli01: Neck issues

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1099]
## Brief description of the request/failure
After around two weeks running the same experiment without any problem, in the past few hours the neck sometime get stuck requesting to look at looking at requests (towards left/right). Attached you can find the logs

## Accompanying material
[log.txt](https://github.com/robotology/icub-tech-support/files/6146824/log.txt)

**Comment by maggia80** [comment]
`5384	848.943519	INFO	 from BOARD 10.0.1.5 (torso-eb5-j0_2), src LOCAL, adr 0, time 900s 93m 218u: (code 0x06000005, par16 0x0007 par64 0x3000000000000000) -> eoerror_INTERNALERROR__valueisempty + .`

@marcoaccame  could you help us on interpreting this INFO?

**Comment by violadelbono** [comment]
The connector of the motor of the roll joint was not totally inserted inside its board. It has been also re-crimped to ensure a correct contact.

![image](https://user-images.githubusercontent.com/61685519/111473347-3c4db080-872b-11eb-9112-5f8bd047aa95.png)

Hopefully this solved the problem.

**Comment by ddetommaso** [comment]
Everything works great again!
