### ISSUE TITLE
Waist cable broken

### ISSUE THREAD

**Issue by lunagava** [robotology/icub-tech-support#1100]
## Brief description of the request/failure
Hello, I'm sorry but one cable belonging to the waist of iCubGenova02 is broken, therefore it has to be substituted with a new one. It seems broken in several points, since the pulley kept rotating after the first break. 
@violadelbono 

## Detailed context
I do not know the reason of the break, since I was controlling the left arm to move within a limited range -0.15m < y < 0.15m with the DoF related to the torso yaw enabled. 

## Accompanying material

![IMG_7330](https://user-images.githubusercontent.com/45895918/111348607-a52c1e80-8680-11eb-88aa-425cedab3884.jpg)

**Comment by violadelbono** [comment]
The cable of the yaw joint has been replaced (cable # 13).
List of items and quantity:

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| 4770.1 | 1   | WAIST TOP CABLE 13 |  |
