### ISSUE TITLE
Left wrist cables loose

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1101]
## Brief description of the request/failure
The left wrist seems very loose. I guess that some cable need to be tighten

https://user-images.githubusercontent.com/18591940/111440455-a7d15700-8706-11eb-8619-27c72a83becc.mp4

I can also help in tightening them up if you point me to the correct screw.

**Comment by violadelbono** [comment]
@S-Dafarra I believe [these ]( https://icub-tech-iit.github.io/documentation/icub_tendons/wrist_hand_cabling_V2/#13-wrist-passive-tendons)are the tendons which need to be tensed. 
You can try to tight them. You should only need a cross screwdriver but be careful, they are tiny and delicate!

Let me know

![image](https://user-images.githubusercontent.com/61685519/111477086-0a3e4d80-872f-11eb-8d7f-b86dbae7d207.png)
![image](https://user-images.githubusercontent.com/61685519/111477308-44a7ea80-872f-11eb-9137-891576b0fd43.png)

**Comment by S-Dafarra** [comment]
Thanks @violadelbono, I tried to tighten them a bit, but not a lot. I think it improved a bit, at least it is comparable to the other hand. I think that the tendon might be a little long, if that is possible. In any case, I think it is not a big problem and we can close this. If this turns out to be a problem, I will open a new issue.
