### ISSUE TITLE
l_hand_finger encoder miscalibrated or broken

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1102]
## Brief description of the request/failure
It is currently displaying 170deg, but the value seems to be changing when moved manually.

## Detailed context

https://user-images.githubusercontent.com/18591940/111441226-6beac180-8707-11eb-9cf9-cac9997df686.mp4

**Comment by violadelbono** [comment]
This has been (hopefully) solved after rotating the joint magnet and performed a calibration.
