### ISSUE TITLE
R1 sn001 left arm and right hand malfunction - Luca Nobile

### ISSUE THREAD

**Issue by lnobile** [robotology/icub-tech-support#1107]
## R1 sn001 left arm and right hand malfunction

The left arm (roll joint) and right hand on R1-sn001 have a malfunction.

The roll joint of the left arm doesn't properly calibrate and the yarprobotinterface returns the error:
`2FOC hall sensor fault. Invalid sequence in motor Hall sensors, please check motor hall cable connections. par16 = ID of joint. +.`

The right hand wrist pronosupination joint seems mechanically broken (you can ear the motor spinning but there are no visible joint movements).

**Comment by fbiggi** [comment]
right wrist repaired

**Comment by emilianob80** [comment]
After the covers were removed, the AEA support of the shoulder was found broken. The helicoil was ripped from the shoulder

![supporto AEA](https://user-images.githubusercontent.com/53729815/112383746-d0041b80-8ced-11eb-9ec2-e8490d8963f9.png)


The 5N2 cable that connects the EMS electronic board (EB5) to the crushed and damaged F / T sensor of the left shoulder was also found. The cable has been totally replaced.

![Cavo danneggiato](https://user-images.githubusercontent.com/53729815/112383769-d7c3c000-8ced-11eb-8c3e-92829dc5a018.png)
![Cavo schiacciato](https://user-images.githubusercontent.com/53729815/112383773-d85c5680-8ced-11eb-8af1-733e979d3d4b.png)


Regarding the hall sensor, a visual check was carried out and nothing abnormal or damaged was found. We recommend a functional check when it will be possible (given the short notice it was not possible to deepen the debug)


cc: @Fabrizio69 @lnobile @fbiggi @violadelbono
