### ISSUE TITLE
R1 sn003 neck_pitch_joint malfunction

### ISSUE THREAD

**Issue by lnobile** [robotology/icub-tech-support#1110]
## Description

The R1 sn003 neck_pitch_joint doesn't move: when I try to give a position command the joint doesn't actuate.

## Detailed context

yarprobotinterface doesn't return any error.
Encoder readings seem to be fine.
From yarpmotorgui, when a command is given, the encoder reading box gets coloured in red and the head doesn't move.

**Comment by pattacini** [comment]
@lnobile please don't assign people yourself 😃 
We'll take care of doing triaging.

**Comment by emilianob80** [comment]
@lnobile all motors of the head are working properly. I have not found any hardware anomalies. The only problem that can be there is the burnt channel of the electronic board. I ask you to please check the operation of the motors again before eventually replacing it

cc: @violadelbono @Fabrizio69

**Comment by emilianob80** [comment]
> @emilianob80
> I checked again and from the yarp motor gui I'm not able to move the joint, I'm able to control the other joint of the head so I don't think it's a configuration issue. I also checked the yarprobotinterface configuration files and everything seems ok.

@lnobile at this point I suspect the channel of the electronic board. I can try to program one and replace it in order to remove the doubt. I have not found other hardware problems

**Comment by emilianob80** [comment]
![IMG_20210331_152130](https://user-images.githubusercontent.com/53729815/113150957-eaca1900-9234-11eb-860c-ab2d2642ed93.jpg)
@lnobile I replaced the electronic board and put it in a temporary way in order to do a test run. If the problem is solved la.momto permanently

Cc: @Fabrizio69

**Comment by lnobile** [comment]
Thanks, we tested the board and updated the firmware to the latest version. Everything seems to work correctly.

**Comment by emilianob80** [comment]
@lnobile Tuesday 06/04/2021 I will definitively fix the electronic board and apply a ceramic heatsink on it

cc: @Fabrizio69 @maggia80

**Comment by emilianob80** [comment]
https://github.com/icub-tech-iit/tickets/issues/1158#event-4544986603
