### ISSUE TITLE
Spikes in left arm encoders

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1112]
## Brief description of the request/failure
While trying the yoga, the robot fell once because of spikes in the encoders of the left arm.

## Accompanying material

[log_icub-head_yarprobotinterface_3349_external_fault_false_positive.txt](https://github.com/robotology/icub-tech-support/files/6242369/log_icub-head_yarprobotinterface_3349_external_fault_false_positive.txt)

**Comment by S-Dafarra** [comment]
Note that the log is the same of #1111

**Comment by violadelbono** [comment]
The encoder with spikes is the AEA of joint 6 - left wrist. Probably some cable loose.
I will check board EB24 connector P11.

![image](https://user-images.githubusercontent.com/61685519/114165079-59416200-992c-11eb-9960-b549c546ea35.png)

**Comment by kouroshD** [comment]
As I mentioned to @violadelbono , we have the following problems:
- the left hand wrist encoder does not change values,
- Moreover, we face a couple of times right elbow was not configuring 

![Screenshot from 2021-05-27 11-16-02](https://user-images.githubusercontent.com/17707730/119834630-6cba8380-bf00-11eb-9d48-53ddbd6e48f2.png)
![Screenshot from 2021-05-27 15-04-18](https://user-images.githubusercontent.com/17707730/119834638-6d531a00-bf00-11eb-99e4-3e1c09b1e323.png)
This is the image for the right prosup, however, later we fault the robot and unfault the robot, and restrarted the robot and it started working. However, for the sake of reporting, I am mentioning it here:

![Screenshot from 2021-05-27 11-16-07](https://user-images.githubusercontent.com/17707730/119835605-447f5480-bf01-11eb-8c26-4bda8ac44094.png)

**Comment by kouroshD** [comment]
I can say also the right wrist prosup is not working as expected:
In this case, we were moving the right prosup to the whole possible range of motion using yarp motor gui, while in reality it was not moving more than 20-30 degrees. You can see the robot behavior in the video attached here.

![Screenshot from 2021-05-27 17-29-21](https://user-images.githubusercontent.com/17707730/119854108-16097580-bf11-11eb-82ae-cbdc82f410eb.png)


Here is a video showing when we try to reach all the range of the robot right wrist prosup motion using motorgui while in reality the robot range of motion was much less:


https://user-images.githubusercontent.com/17707730/119855063-e444de80-bf11-11eb-9b2c-999f331c5d19.mp4

cc @DanielePucci  @violadelbono

**Comment by maggia80** [comment]
![image](https://user-images.githubusercontent.com/6987330/119960429-3d118700-bfa5-11eb-81b3-afa1c6666342.png)

the AEA sensors for the wrist are LA-AE5 and LA-AE6

we should check the connectors P10 and P11 of the board EB24

![image](https://user-images.githubusercontent.com/6987330/119960684-819d2280-bfa5-11eb-8257-920f5df164e8.png)

**Comment by violadelbono** [comment]
Both the connectors of the 2 encoders were loose and  have been re-crimped. The encoder cable of the left arm was also replaced.
