### ISSUE TITLE
R1 sn003 neck_pitch_joint mechanical malfunction

### ISSUE THREAD

**Issue by lnobile** [robotology/icub-tech-support#1114]
## Description

The R1 sn003 neck_pitch_joint doesn't move even if the motor seems to spin.

## Detailed context
With @fbiggi  we discovered that this could be a mechanical issue with the motor shaft that spins freely without effectively moving the head joint.

**Comment by fbiggi** [comment]
the surgery we will do next week as it is necessary to untwist and disassemble the whole head

cc @emilianob80 @maggia80 @Fabrizio69

**Comment by fbiggi** [comment]
repositioned the head on the motor seat
fixing the screw with threadlocker glue
testing performed ok

cc @ emilianob80 @ maggia80 @ Fabrizio69 @violadelbono
