### ISSUE TITLE
R1 microphones not working

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-tech-support#1115]
Only 2 of the 6 microphones seems to properly work. The other 4 microphones are only recording silence.
The problem seems to be an electrical issue since the same software has been test on R1-01 (in Erzelli) and it works.

**Comment by violadelbono** [comment]
We will check this together with https://github.com/robotology/icub-tech-support/issues/1114

**Comment by randaz81** [comment]
![microfoni_cer04](https://user-images.githubusercontent.com/2869969/113844446-c3270380-9794-11eb-89a8-e1176ac16994.png)
4 of 6 microphones are now visible on audacity. The internal mics seems to be still missing.
A comparison of the picture with CER02 (currently at Erzelli) will be done to confirm this hypothesis

**Comment by violadelbono** [comment]
> 4 of 6 microphones are now visible on audacity.

The left microphone cable was found damaged and fixed
