### ISSUE TITLE
Shoulder cable of the left arm needs to be replaced. 

### ISSUE THREAD

**Issue by lunagava** [robotology/icub-tech-support#1119]
### Request/Failure description

One of the shoulder cables of the left arm (iCubGenova02) is worn and it is likely to break soon.  

@violadelbono 

### Detailed context

As you can see in the following pictures, the tendon is a little frayed. 

### Additional context

![shoulder_cable](https://user-images.githubusercontent.com/45895918/114691470-02ff6500-9d18-11eb-8602-f2f106bf0c67.JPG)
![shoulder_cable_zoom](https://user-images.githubusercontent.com/45895918/114691526-10b4ea80-9d18-11eb-8b79-01915c9ffd3f.JPG)

**Comment by violadelbono** [comment]
Hi @lunagava 

It seems that only the Teflon cover of the cable is breaking (correct me if I am wrong), so you can go on for a while before the actual cable breaks.

**Comment by lunagava** [comment]
Hi @violadelbono, I heard a strange sound coming from the left shoulder, while the robot is moving. I tried to see if the cable was damaged partially or not. If you have verified that is only the covered plastic broken, I agree to wait until the cable will break definitely.

**Comment by violadelbono** [comment]
@lunagava maybe you can show me next time you use it :)

**Comment by violadelbono** [comment]
Closing for now, you can open a new one when the cable will actually break
