### ISSUE TITLE
Eyes vergence is reversed

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1121]
### Request/Failure description

The motors of the eyes are probably swapped, causing the vergence to make the eyes diverge instead of converging.

### Detailed context

I have tested it using the motorgui. The eyes start straight. By increasing the vergence, I get the status of the picture

### Additional context

![image](https://user-images.githubusercontent.com/18591940/115048523-f0cd2480-9ed9-11eb-9351-75a675c9ed8f.png)

**Comment by violadelbono** [comment]
Hi @S-Dafarra,

As you anticipated, the motors of left eye (M2) and right eye (M3) were inverted on the board. I switched them back

![image](https://user-images.githubusercontent.com/61685519/115514425-5deb0c00-a284-11eb-8c16-6eb174c3b66a.png)
