### ISSUE TITLE
Pinky joint of right arm not working 

### ISSUE THREAD

**Issue by lunagava** [robotology/icub-tech-support#1122]
### Robot name 🤖

iCubGenova02

### Request/Failure description

The 15th joint (pinky) of the right hand does not move, probably caused by a broken cable. 

### Detailed context

I noticed this problem because I heard a strange noise coming from the motor of the right arm. 
To solve it temporally, we disabled the 15th joint from the yarprobotinterface launching file.

@violadelbono

**Comment by Uboldi80** [comment]
Tendon of joint 15 right hand replaced.
