### ISSUE TITLE
R1SN003 - power supply not working

### ISSUE THREAD

**Issue by lnobile** [robotology/icub-tech-support#1123]
### Robot name 🤖

R1SN003

### Request/Failure description

The power supply of the robot has stopped working and outputs the following error message: "fail 4".

### Detailed context

Please look at the attached photo:
![IMG_8369](https://user-images.githubusercontent.com/56638910/115534843-7c5b0280-a298-11eb-9c99-0c1944a30878.jpg)

**Comment by maggia80** [comment]
```
R1 SN003 (cer04)
```

@lnobile cer04 is deprecated. R1 SN003 is now R1SN003

**Comment by lnobile** [comment]
> ```
> R1 SN003 (cer04)
> ```
> 
> @lnobile cer04 is deprecated. R1 SN003 is now R1SN003

Edited ;)

**Comment by violadelbono** [comment]
IITCODE is 1596

I didn't find anything useful in the [manual](http://www.av.it.pt/Medidas/Data/Manuais%20&%20Tutoriais/33%20-%20Power%20Supply%20CPX400DP/CPX400D%20&%20DP%20Instruction%20Manual.pdf) 

Here similar problem and someone repaired it https://www.eevblog.com/forum/repair/sorensen-xpf-60-20dp/

cc @emilianob80 @maggia80

**Comment by lnobile** [comment]
Do you think that is possible to temporarily use the SN000 power supply? SN000 is actually not used and they share the same power supply. However, the connector cable is different and we should also switch the cables to make it work. (I can do this also on my own, just need permission)

**Comment by randaz81** [comment]
Since this is an emergency, I also agree that the quick solution is to switch the cables with SN000 power supply. 
Please ask to @emilianob80 or @MrAndrea for help on the power supply settings.

**Comment by MrAndrea** [comment]
I didn't find anything useful information to understand FAIL4 error message like @violadelbono, probably there is a worrying hardware problem inside and now another power supply is needed.

**Comment by emilianob80** [comment]
> I didn't find anything useful information to understand FAIL4 error message like @violadelbono, probably there is a worrying hardware problem inside and now another power supply is needed.
> 
> Here a video of a similar [FAIL4](https://arshow.info/watch/1aBJ_t9QagI/sorensen-xpf-60-20dp-failed.html)

https://www.eevblog.com/forum/repair/sorensen-xpf-60-20dp/

**Comment by lnobile** [comment]
I swapped the power supply with the one of the old SN000 so that now we can work for now

**Comment by Andreamenini68** [comment]
@violadelbono  Allego richiesta info per Assistenza Riparazione
[Mail RS per richiesta Assistenza.pdf](https://github.com/robotology/icub-tech-support/files/6356862/Mail.RS.per.richiesta.Assistenza.pdf)

pc @maggia80  @Fabrizio69

**Comment by Andreamenini68** [comment]
@violadelbono  Ti allego risposta da parte del Fornitore RS
[Risposta RS per Alimentatore.pdf](https://github.com/robotology/icub-tech-support/files/6383234/Risposta.RS.per.Alimentatore.pdf)

pc @maggia80  @Fabrizio69

**Comment by maggia80** [comment]
@Andreamenini68 puoi provare a sentire il produttore? Se fanno riparazioni fuori dalla garanzia

**Comment by Andreamenini68** [comment]
@maggia80  certo ho sentito Gardella in quanto se passiamo dalla casa madre le tempistiche sono lunghissime

**Comment by violadelbono** [comment]
Ciao @Andreamenini68, ci sono aggiornamenti su questa issue?

**Comment by Andreamenini68** [comment]
@violadelbono  Gardella non riesce a fare nulla , abbiamo contattato la casa madre stiamo attendendo risposta, sollecitiamo.

**Comment by Fabrizio69** [comment]
@Andreamenini68 ci sono novità in merito a questa issue? Hai ricevuto info?

**Comment by Andreamenini68** [comment]
@Fabrizio69  ho sollecitato la Silvia in quanto aveva scritto lei alla casa madre. Ti aggiorno quanto prima

**Comment by Fabrizio69** [comment]
@Andreamenini68 ci sono stati aggiornamenti in merito?

cc: @maggia80

**Comment by Andreamenini68** [comment]
@Fabrizio69  Ciao Fabrizio, nessun aggiornamento in merito , per sicurezza faccio un passaggio sulla Silvia in quanto ha scritto lei.

**Comment by silviacriscenzo** [comment]
Ciao @Fabrizio69 sono riuscita ad ottenere un riscontro dalla casa madre. Dovrebbero riuscire ad occuparsi della riparazione, ma vorrebbero sapere il seriale dell'alimentatore. Io ho verificato sul DDT di RS e non c'è scritto. Potete gentilmente fornirmelo? Grz mille @Andreamenini68

**Comment by LaMelis** [comment]
Ciao @Fabrizio69 riusciresti per caso a fornirmi il num di serie dell'alimentatore? Così posso rispondere alla casa madre. Grazie!

cc @maggia80 @Andreamenini68

**Comment by Andreamenini68** [comment]
@LaMelis  eccolo Serial number: 504849

**Comment by Andreamenini68** [comment]
@LaMelis  se ti manca qualcosa a disposizione

**Comment by LaMelis** [comment]
Grazie @Andreamenini68 ho risposto alla casa madre. Vi aggiorno non appena avrò riscontro.

**Comment by Fabrizio69** [comment]
Ciao @LaMelis , scusa se non ho risposto alla [tua richiesta](https://github.com/robotology/icub-tech-support/issues/1123#issuecomment-1003315671), ma in dipartimento, non sono riuscito a trovare l'alimentatore. Forse in questo è riuscito @Andreamenini68 che ti ha fornito [la risposta](https://github.com/robotology/icub-tech-support/issues/1123#issuecomment-1003391520).
Scusami ancora....
Grazie a tutti

cc: @maggia80

**Comment by Andreamenini68** [comment]
@Fabrizio69 io dell'alimentatore non so nulla !!!!

cc: @maggia80 @LaMelis

**Comment by emilianob80** [comment]
@Fabrizio69 @Andreamenini68 l' alimentatore è in laboratorio con relativa scatola. Il numero seriale è 504849

cc: @maggia80 @LaMelis

**Comment by Fabrizio69** [comment]
Ciao @emilianob80 potresti per favore consegnarlo a @Miche19 in modo che lo metta tra il materiale da spedire e possa qui indicare peso e dimensione del collo contenente:

1 pezzo cod.1596 - Power supply with digital BUS interfaces, 2x 420W, 0-60V, 0-20A, 210x130x375mm, Portable, Input 110V to 240V 

@Andreamenini68 penso che valga la pena riparare questo alimentatore, quindi se @maggia80  è d'accordo procederei con la riparazione. In caso contrario procederei con lo smaltimento.
Grazie mille a tutti

cc: @LaMelis

**Comment by emilianob80** [comment]
> Ciao @emilianob80 potresti per favore consegnarlo a @Miche19 in modo che lo metta tra il materiale da spedire e possa qui indicare peso e dimensione del collo contenente:
> 
> 1 pezzo cod.1596 - Power supply with digital BUS interfaces, 2x 420W, 0-60V, 0-20A, 210x130x375mm, Portable, Input 110V to 240V
> 
> @Andreamenini68 penso che valga la pena riparare questo alimentatore, quindi se @maggia80 è d'accordo procederei con la riparazione. In caso contrario procederei con lo smaltimento. Grazie mille a tutti
> 
> cc: @LaMelis

ok

**Comment by LaMelis** [comment]
Ciao a tutti. 
Volevo solo informarvi che la casa madre (Thurlby Thandar Instruments Ltd), l'unica che può procedere con la riparazione dell'alimentatore, non è iscritta al nostro albo fornitori. Pertanto, nel caso in cui si decidesse di continuare, vi chiedo di tenere in considerazione la loro volontà o meno di iscriversi e le tempistiche dell'iscrizione. Grazie! 

@maggia80  @Fabrizio69 @emilianob80 @Andreamenini68 @zapp

**Comment by Andreamenini68** [comment]
@Fabrizio69  Ho già avvertito Salvatore per preparare la documentazione e predisporre la spedizione. Il tutto procederà dopo l'apertura della parte aministrativa.
cc: @maggia80 @LaMelis

**Comment by Miche19** [comment]
> Ciao @emilianob80 potresti per favore consegnarlo a @Miche19 in modo che lo metta tra il materiale da spedire e possa qui indicare peso e dimensione del collo contenente:
> 
> 1 pezzo cod.1596 - Power supply with digital BUS interfaces, 2x 420W, 0-60V, 0-20A, 210x130x375mm, Portable, Input 110V to 240V
> 
> @Andreamenini68 penso che valga la pena riparare questo alimentatore, quindi se @maggia80 è d'accordo procederei con la riparazione. In caso contrario procederei con lo smaltimento. Grazie mille a tutti
> 
> cc: @LaMelis

Ciao @Andreamenini68 il materiale è pronto per essere ritirato

Si tratta di una scatola di cartone.
Dimensioni: 30x35x50 cm Peso: 8,5 kg

cc: @Fabrizio69 @emilianob80 @LaMelis
