### ISSUE TITLE
iCubGenova09 fault broken

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1125]
### Robot name 🤖

iCubGenova09

### Request/Failure description

The fault on iCubGenova09 broke when the robot started. 

<img src="https://user-images.githubusercontent.com/43743081/116087687-676bde00-a6a1-11eb-9843-1b0e88143091.jpg" width=400>
<img src="https://user-images.githubusercontent.com/43743081/116087700-6a66ce80-a6a1-11eb-99a2-3876f915cb0c.jpg" width=400>
<img src="https://user-images.githubusercontent.com/43743081/116087708-6c309200-a6a1-11eb-81f3-88ee3a905829.jpg" width=400>

### Detailed context

The fault cable was blocked under the cart wheel and as soon as I started the robot through `yarprobotinterface` the fault jack broke and the connector into the robot torso as well.

**Comment by MrAndrea** [comment]
I removed the back cover and I saw that the `FED` board was damaged because the jack stereo of the Fault torn the pcb nets.
The white part was broken and I put some drop of Pattex glue to join the two pieces.

![image](https://user-images.githubusercontent.com/20459541/116102193-c84de300-a6ae-11eb-8d19-f0f4ea2f49c6.png)

![image](https://user-images.githubusercontent.com/20459541/116102083-ab191480-a6ae-11eb-9f11-368d5632050b.png)

I prepared a new `FED`  board and tomorrow Davide Gandini will repair the fault cable.

cc @Fabrizio69 @maggia80

**Comment by isorrentino** [comment]
Thanks @MrAndrea!

**Comment by Gandoo** [comment]
![20210427_072818](https://user-images.githubusercontent.com/53341641/116197951-a8adcd80-a735-11eb-98b3-5a1b271aa880.jpg)

![20210427_072826](https://user-images.githubusercontent.com/53341641/116197966-aba8be00-a735-11eb-94fa-0c6fc6327667.jpg)

![20210427_073534](https://user-images.githubusercontent.com/53341641/116197975-aea3ae80-a735-11eb-829d-3d03ce35ebef.jpg)

ciao @MrAndrea la patex non ha risolto la rottura, ho messo attak con dello scotch come rinforzo momentaneo, Mattia lo fa costruire e appena possibile si sostituisce. 

![20210427_070043](https://user-images.githubusercontent.com/53341641/116198526-54571d80-a736-11eb-8145-e87863a1c861.jpg)

Risaldato jack al cavo di Fault

cc @Fabrizio69 @maggia80 @isorrentino

**Comment by MrAndrea** [comment]
Grazie @Gandoo, avevo provato la Pattex ma forse era meglio darci subito l'Attack, comunque il pezzo ristampato andrà sicuramente meglio.

**Comment by MrAndrea** [comment]
@salvi-mattia possiamo ristampare il supporto bianco con un diametro maggiore per il foro cerchiato in rosso? può avere il diametro del foro che c'è nella cover nera. Il motivo é che il jack tocca sui bordi del foro e non arriva in fondo al connettore sulla scheda.

![image](https://user-images.githubusercontent.com/20459541/116202563-02fd5d00-a73b-11eb-83bd-c937581cd541.png)

**Comment by Gandoo** [comment]
![20210427_102751](https://user-images.githubusercontent.com/53341641/116212575-3fce5180-a745-11eb-99fe-3103273e6cef.jpg)

![20210427_101210](https://user-images.githubusercontent.com/53341641/116212592-43fa6f00-a745-11eb-9911-7e4fd3c1e591.jpg)

ciao, @MrAndrea  come scritto prima il problema del Fault era dovuto al fatto che il jack del pulsante non andava in battuta e relativa sede del connettore femmina sulla scheda. (FORSE DOVUTO AL FATTO CHE IL SUPPORTO SI è SPEZZATO PROPRIO NELLA ZONA DI FISSAGGIO )

@salvi-mattia ho allargato sia il foro sel supporto bianco che il foro della cover nera sulla parte bassa.

@davidetome  ha fatto il test di verifica del funzionamento del Fault, risulta funzionante.

cc @Fabrizio69 @maggia80 @isorrentino

**Comment by salvi-mattia** [comment]
avendo recepito le richieste soprastanti

![immagine](https://user-images.githubusercontent.com/43994292/116219841-604dda00-a74c-11eb-984e-28fb7a9aed9d.png)

**Comment by salvi-mattia** [comment]
![immagine](https://user-images.githubusercontent.com/43994292/116225279-f0dae900-a751-11eb-8df8-1b2d7fb62b64.png)

**Comment by violadelbono** [comment]
Ciao @salvi-mattia,

Hai novitá su questa issue? E' arrivato il pezzo?

**Comment by salvi-mattia** [comment]
si, e' arrivato da tempo
@Fabrizio69 aveva detto di tenerlo a magazzino come spare, al momento lo ho io.
se lo vogliamo montare ve lo porto

cc @violadelbono

**Comment by salvi-mattia** [comment]
here It Is on your desk @violadelbono 

![IMG_20210513_145926.jpg](https://user-images.githubusercontent.com/43994292/118132525-14638c00-b400-11eb-80f1-ecc2aa170868.jpg)

**Comment by violadelbono** [comment]
We decided to store the new piece in the warehouse and to eventually replace it when it will break totally.
Closing
