### ISSUE TITLE
iCubGenova09 torso joint 1 AMO not working

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1127]
### Robot name 🤖

iCubGenova09

### Request/Failure description

After https://github.com/robotology/icub-tech-support/issues/1125 the torso pitch motor is not starting properly. 

### Detailed context

Maybe, the joint 1 reading is not working due to a broken cable.

Here the saved log.

[log_icub-head_yarprobotinterface_3779.txt](https://github.com/robotology/icub-tech-support/files/6384542/log_icub-head_yarprobotinterface_3779.txt)

cc @davidetome

**Comment by isorrentino** [comment]
cc @S-Dafarra

**Comment by davidetome** [comment]
The sensor is connected to the `EMS` board `EB5` connector `P8`

cc @pattacini @simeonedussoni

**Comment by pattacini** [comment]
We will check it out!

**Comment by pattacini** [comment]
@davidetome and @simeonedussoni fixed it up.
We will finalize the work on this today.

**Comment by davidetome** [comment]
@gandoo 🏅  repaired the fault by crimping the 2 Molex connectors of the sensor cable

cc @pattacini @simeonedussoni @S-Dafarra @isorrentino

**Comment by isorrentino** [comment]
Thank you all!
