### ISSUE TITLE
Wrists not calibrating correctly

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1128]
### Robot name 🤖

iCubGenova02

### Request/Failure description

The calibration of the robot wrists seem not to be symmetric (similarly issue https://github.com/robotology/icub-tech-support/issues/1088)

### Detailed context

At the startup, the robot wrists configuration is not symmetric

### Additional context

![photo5787318206745130943](https://user-images.githubusercontent.com/35487806/116667189-30951100-a99c-11eb-99a0-bec9fd23844e.jpg)
![photo5787318206745130942](https://user-images.githubusercontent.com/35487806/116667194-31c63e00-a99c-11eb-80e3-a3616ae006db.jpg)

**Comment by violadelbono** [comment]
Hi @lrapetti 

I fixed the calibration and installed `robots-configuration`. Here the [commit](https://github.com/robotology/robots-configuration/pull/258/files).
