### ISSUE TITLE
R1 SN003 new back cover hides fault button inside the robot

### ISSUE THREAD

**Issue by lnobile** [robotology/icub-tech-support#1132]
### Robot name 🤖

R1 SN003

### Request/Failure description

R1 SN003 new back cover hides fault button inside the robot

### Detailed context

As you can see from the photo the falt button is inside the robot once the cover is closed.
Is it possible to connect an external fault button or make the existing one accessible?
![IMG_8523](https://user-images.githubusercontent.com/56638910/117001894-3152dd80-ace3-11eb-86c0-50224697a54b.jpg)

**Comment by maggia80** [comment]
@lnobile yes we added the possibility to use an external fault. We can do a remote fault. Currently the connector is closed with a jumper inside the robot.

![](https://user-images.githubusercontent.com/6987330/117012612-6ebd6800-acef-11eb-84a3-a2670c1d9041.jpeg)

**Comment by maggia80** [comment]
cc @emilianob80 @Fabrizio69

**Comment by emilianob80** [comment]
@lnobile  tomorrow morning I'll wire an iCub-style remote fault button. The length will be 3 meters

cc: @maggia80 @Fabrizio69

**Comment by lnobile** [comment]
> @lnobile tomorrow morning I'll wire an iCub-style remote fault button. The length will be 3 meters
> 
> cc: @maggia80 @Fabrizio69 @violadelbono

Great! But given the fact that we will need the robot to navigate autonomously around the museum maybe it's better a shorter cable so that it can be easily stuffed inside the cover and the external fault button attacched/hanged on the robot

**Comment by maggia80** [comment]
@lnobile you can plug the jumper when you don't want to use the fault button.

**Comment by emilianob80** [comment]
wired external fault
 
![IMG_20210505_074227](https://user-images.githubusercontent.com/53729815/117101122-cacacf80-ad75-11eb-858f-c89860b12191.jpg)

cc: @maggia80 @lnobile @randaz81 @violadelbono

**Comment by lnobile** [comment]
great! thank you!

**Comment by violadelbono** [comment]
Robot launched and faulted multiple times ✔️ everything works

**Comment by emilianob80** [comment]
@lnobile When you want to connect the external fault, disconnect the jumper in the photo. The connector has a retainer, so first press the tab and then carefully pull

![IMG_20210505_120640](https://user-images.githubusercontent.com/53729815/117126144-a46b5b00-ad9a-11eb-9338-141257715a45.jpg)

![IMG_20210505_120632](https://user-images.githubusercontent.com/53729815/117126124-a1706a80-ad9a-11eb-9f86-b7289484016f.jpg)

cc: @violadelbono
