### ISSUE TITLE
Shoulder tendon is broken 

### ISSUE THREAD

**Issue by gabrielegiudici93** [robotology/icub-tech-support#1133]
### Robot name 🤖

iCub[Pisa][01]

### Request/Failure description

- Shoulder tendon is broken
- Nose Belt is broken

### Detailed context

Hi, 
I've two problems:
1 - during a common position control using motorgui the tendon of the Left Shoulder has broken [ referring to this manual : https://icub-tech-iit.github.io/documentation/icub_tendons/shoulder_elbow/ we identified that the broken one is the **SHOULDER ROTATION CABLE 2 ** ]
Where can we buy the cable or the set of cable for the whole arm( is not the first time that we have this kind of problem)?
2- We also need to replace the belt in the face( I can't identify the precise part) but is the belt "in the nose" ?

**Comment by gabrielegiudici93** [comment]
![20210511_160929](https://user-images.githubusercontent.com/62802841/117830523-01bc4c00-b274-11eb-922f-75ea84f10573.jpg)
![20210511_160958](https://user-images.githubusercontent.com/62802841/117830526-02ed7900-b274-11eb-9c8d-a48df2a92fd0.jpg)

**Comment by maggia80** [comment]
@[**gabrielegiudici93**](https://github.com/gabrielegiudici93) **which robot you are referring to?**

**Comment by gabrielegiudici93** [comment]
Of course, forgive me I am referring to iCubPisa01(SSSA)

**Comment by gabrielegiudici93** [comment]
The problem remains unsolved, could someone help me?

**Comment by violadelbono** [comment]
Ciao @gabrielegiudici93,

If you want to purchase a kit of cables I can put you in contact with @andreaderito who is responsible for it.

**Comment by gabrielegiudici93** [comment]
Yes please, I tried to contact him from the appropriate form on the IIT website

**Comment by andreaderito** [comment]
Ciao @gabrielegiudici93,

I'm going to send an email to your email address I found on the internet gabriele.giudici@santannapisa.it to follow up this topic.

**Comment by andreaderito** [comment]
Ciao @gabrielegiudici93,

I've spoken with Egidio, and internally asked for the BOM of iCubPisa01, the availability of the belt and of shoulder rotation cable 2 so as to estimate lead time. The rest will follow by email.
cc @Fabrizio69 cc @violadelbono cc @Uboldi80 cc @maggia80

**Comment by gabrielegiudici93** [comment]
I am very grateful to you, we await news

Il Ven 21 Mag 2021, 11:19 Andrea Derito ***@***.***> ha
scritto:

**Comment by maggia80** [comment]
@gabrielegiudici93 could you confirm that the belt you need is the one for the TILT of the eyes?

**Comment by gabrielegiudici93** [comment]
Yes

**Comment by andreaderito** [comment]
Ciao @gabrielegiudici93 we checked and found availability of both items (shoulder rotation cable 2 and belt), soon we'll ship them to your premises (presumably this week), for the other information (costs etc.) I follow up by email.

**Comment by gabrielegiudici93** [comment]
Thank you very much, you can contact Egidio Falotico directly
***@***.***

Il Lun 24 Mag 2021, 10:52 Andrea Derito ***@***.***> ha
scritto:
