### ISSUE TITLE
Right upperarm skin patches not working on iCubGenova09

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/icub-tech-support#1134]
### Robot name 🤖

iCubGenova09

### Request/Failure description

Right upperarm skin patches not working on iCubGenova09

### Detailed context

During some recent tests I noticed that two of the traingular patches from the right upperarm skin are not working

![117036337-9a4b4d00-ad05-11eb-870b-29c07e30e41d](https://user-images.githubusercontent.com/6505998/117843887-83fe3d80-b27f-11eb-8aed-b3f54f963b34.jpg)

Sorry, at the moment I do not have SkinGui visualization to show

**Comment by maggia80** [comment]
cc @simeonedussoni

**Comment by simeonedussoni** [comment]
I took the cover and already asked the warehouse  a replacement fior the patch.

**Comment by simeonedussoni** [comment]
a new patch is mounted on the cover and checked.

**Comment by Yeshasvitvs** [comment]
Thanks @simeonedussoni
