### ISSUE TITLE
assembly both arms icubGenova SN.031

### ISSUE THREAD

**Issue by Uboldi80** [robotology/icub-tech-support#1136]
change the hardware configuration of the robot to reassembly both arms after experimental fly.

**Comment by Uboldi80** [comment]
right arm is assembled and tested
some problem in the joint 8-9

**Comment by Uboldi80** [comment]
left arm is assembled but we have few problems hardware:
 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/80786976/119170687-e7e4eb00-ba63-11eb-9ae2-bb1b1092f7a7.png)

some parts are missing, like a  upper arm cover and a finger tip

**Comment by kouroshD** [comment]
After the assembly has been performed, we have the following problem with the right arm and hand:

the right thumb oppose encoder feedback is high, so it is stays in HW fault

![Screenshot from 2021-05-27 15-04-18](https://user-images.githubusercontent.com/17707730/119834638-6d531a00-bf00-11eb-99e4-3e1c09b1e323.png)

We face a couple of times right elbow was not configuring.
This is the image for the right prosup, however, later we fault the robot and unfault the robot, and restrarted the robot and it started working. However, for the sake of reporting, I am mentioning it here:

![Screenshot from 2021-05-27 11-16-07](https://user-images.githubusercontent.com/17707730/119835605-447f5480-bf01-11eb-8c26-4bda8ac44094.png)

An issue was closed about this recently, in https://github.com/robotology/icub-tech-support/issues/1111


I can say also the right wrist prosup is not working as expected:
In this case, we were moving the right prosup to the whole possible range of motion using yarp motor gui, while in reality it was not moving more than 20-30 degrees. You can see the robot behavior in the video attached here.

![Screenshot from 2021-05-27 17-29-21](https://user-images.githubusercontent.com/17707730/119854108-16097580-bf11-11eb-82ae-cbdc82f410eb.png)


Here is a video showing when we try to reach all the range of the robot right wrist prosup motion using motorgui while in reality the robot range of motion was much less:


https://user-images.githubusercontent.com/17707730/119855063-e444de80-bf11-11eb-9b2c-999f331c5d19.mp4

cc @DanielePucci  @violadelbono

**Comment by kouroshD** [comment]
@violadelbono let me know if I should open an issue for the right thumb oppose and reopen the issue https://github.com/robotology/icub-tech-support/issues/1111

**Comment by violadelbono** [comment]
Solved in https://github.com/robotology/icub-tech-support/issues/1111.
I saw you opened another 2 issues for the middle proximal and the thumb oppose, so I close this one.
