### ISSUE TITLE
Left middle proximal does not work

### ISSUE THREAD

**Issue by kouroshD** [robotology/icub-tech-support#1140]
### Robot name 🤖

icubGenova04

### Request/Failure description

The left middle proximal joint of robot icubGenova04 does not move.

### Detailed context

Here is a photo of the behavior from yarpmotorgui.

![photo_2021-05-28_11-17-47](https://user-images.githubusercontent.com/17707730/119962542-70551580-bfa7-11eb-9266-e8c89d059b1b.jpg)

**Comment by kouroshD** [comment]
> @kouroshD the joint doesn't move but in the motorgui it's green, right?

Yes, that's correct.

**Comment by violadelbono** [comment]
> tests to be performed:
> 
> - check the connector
> - use the jogger for moving the motor

Checks performed and it moves smoothly. However, it requires about 4-5V to start moving. The other proximal joints move at around 1V so the motor is probably damaged.

**Comment by violadelbono** [comment]
After inspection, the gearbox was damaged and often getting stuck.
It has been replaced and the joint has been cabled again. Now it works smoothly.
