### ISSUE TITLE
Encoder cable of the right hip pitch motor broke while the leg was moving

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1144]
### Device name 🤖

iCubGenova09

### Request/Failure description

The cable of the encoder of the right hip pitch motor needs to be repaired.

### Detailed context

While using the robot and moving the right hip pitch joint, the cable of the encoder detached and broke.

cc @S-Dafarra @GiulioRomualdi

**Comment by Uboldi80** [comment]
encoder connector of the pitch right cable fixed
