### ISSUE TITLE
Right Ankle AEA encoders stream invalid data 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1145]
### Device name 🤖

iCubGenova04

### Request/Failure description

While testing the walking the ankle encoders read invalid data. 

### Detailed context

yarprobotinterface streams the following error

```
2348.149160	ERROR		 from BOARD 10.0.1.9 (right_leg-eb9-j4_5), src LOCAL, adr 0, time 2524s 287m 954u: (code 0x02000008, par16 0x0001 par64 0x000000000000000b) -> MC: AEA encoder invalid data. Hardware problem in the magnetic position sensor of the joint caused invalid position readings. par16 = AEA port (msb) and ID of joint (lsb). + .
```

we also noticed timeout of the right strain2.
```
2213.163043	ERROR		 from BOARD 10.0.1.9 (right_leg-eb9-j4_5), src LOCAL, adr 0, time 2389s 305m 786u: (code 0x04000003, par16 0x0000 par64 0x0000000000000000) -> DEBUG: tag03 + strain timeout
```

### Additional context

Here the log
[log_icub-head_yarprobotinterface_3166.txt](https://github.com/robotology/icub-tech-support/files/6663635/log_icub-head_yarprobotinterface_3166.txt)

cc @paolo-viceconte

**Comment by violadelbono** [comment]
The cables of the AEA sensor were broken and they have been restored.
It probably happened when hitting the leg cover.
