### ISSUE TITLE
Unable to record audio with USB Sweex DAC board

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-tech-support#1147]
### Device name 🤖

iCubGenova09

### Request/Failure description

After installing the USB Sweex DAC board, the microphone was not able to record audio.

### Detailed context

This issue is to track the problem we spotted w/ the USB Sweex DAC board on `iCubGenova09`.

@davidetome checked the device off of the robot and @emilianob80 installed it as it was required to improve the sound quality.

Nevertheless, we came across a couple of problems:
- P1: The iCub microphone was not able to record audio
- P2: The iCub speaker was not able to reproduce sound (via YARP, while regular portaudio commands were working correctly)

We found out that P2 is most likely due to a regression in YARP (see https://github.com/robotology/yarp/issues/2620), whereas P1 is still to be investigated.

It might be still possible that the problem is caused by  faulty cables.

At the time being, we went back to the previous HW configuration.

### Additional context

cc @S-Dafarra @maggia80 @traversaro

**Comment by Fabrizio69** [comment]
XPrize done, hence closing.
Feel free to open it up again if required.
