### ISSUE TITLE
Left knee continuously goes in hardware fault 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1148]
### Device name 🤖

iCubGenova09

### Request/Failure description

The left knee of the robot goes in hardware fault continuously. 

### Detailed context

While switching in HF the board streams the following error
```
 586,915393 <ERROR>  from BOARD 10.0.1.7 (left_leg-eb7-j2_3), src LOCAL, adr 0, time 814s 144m 727u: (code 0x02000008, par16 0x0001 par64 0x0000000000000002) -> MC: AEA encoder invalid data. Hardware problem in the magnetic position sensor of the joint caused invalid position readings. par16 = AEA port (msb) and ID of joint (lsb). + . 
```

### Additional context

[knee_hf.txt](https://github.com/robotology/icub-tech-support/files/6692561/knee_hf.txt)

@S-Dafarra @isorrentino @pattacini @maggia80 @DanielePucci @emilianob80

**Comment by violadelbono** [comment]
AEA LS3 connector was loose and it has been fixed.
