### ISSUE TITLE
iCubGenova01 - skin not responding as expected

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1149]
### Device name 🤖

iCubGenova01

### Request/Failure description

The skin is not responding as expected (not activating on all the surface or not responding at all).

### Detailed context

The following parts have some patches that are not activating as expected:
- torso
- right forearm

The following parts are not activating at all:
- right hand palm
- right hand fingertips

**Comment by violadelbono** [comment]
> - right forearm
> - right hand palm
> - right hand fingertips

Some skin connectors were faulty and have been restored. Moreover, the wiring of the thumb fingertip R0 was soldered incorrectly on the board. It has been also replaced.

**Comment by Uboldi80** [comment]
the chest skin was damaged in several places
some cables were torn and a portion of skin w0mash0.
thanks to @emilianob80 to replace the mash.
