### ISSUE TITLE
iCubGenova01 - right eye camera not working in some configurations

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1150]
### Device name 🤖

iCubGenova01

### Request/Failure description

The right eye camera does not work in some configurations of the eye bulb.

### Detailed context

The right eye camera does not work in some configurations of the eye bulb. In such cases, the image goes almost black with weird blue stripes. See the image attached in the `Additional Context` section.

### Additional context

![Screenshot from 2021-06-23 16-25-36](https://user-images.githubusercontent.com/6014499/123116509-4295ac00-d441-11eb-8108-fa4578e77644.png)

**Comment by violadelbono** [comment]
The flat cable of right camera was damaged and has been replaced.

**Comment by xEnVrE** [comment]
Thank you @violadelbono @Uboldi80
