### ISSUE TITLE
iCubErzelli01 - neck tendons loosening

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1155]
### Device name 🤖

iCubErzelli01

### Request/Failure description

We would ask you to schedule a maintenance to tighten the cables of the neck.

### Detailed context

The robot works fine except sometime during calibration and stopping yarprobotinterface.

**Comment by violadelbono** [comment]
Hi @ddetommaso,

The neck tendons have been tensioned. 
Moreover, the screws holding the neck were also loose and have been tightened, causing relative motion between the neck driven pulley and the neck pan motor holder. See pictures:

![image](https://user-images.githubusercontent.com/61685519/124606139-e1240300-de6c-11eb-875d-66f22e6dc36c.png)

![image](https://user-images.githubusercontent.com/61685519/124606288-087ad000-de6d-11eb-9de9-4350ea518d8e.png)
