### ISSUE TITLE
iCubGenova01 - Left thumb opposition encoder misbehaves

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1156]
### Device name 🤖

iCubGenova01

### Request/Failure description

The encoder of the joint left thumb opposition does not work.

### Detailed context

The encoder of the joint left thumb opposition does not work. Specifically, it provides a sort of fixed value (~ -120.0 degrees) independently from the actual position of the joint.

**Comment by Uboldi80** [comment]
Hal'senor of thumb oppose appears to have broken.
probably need to change.
We tried to test the sensor with the jogger but doesn't work

**Comment by violadelbono** [comment]
Hi @xEnVrE,

We found ot that the problem was actually the connector P8 on the board 1B3 (Hall sensor of thumb) which was not working anymore:

![image](https://user-images.githubusercontent.com/61685519/124758052-805cff00-df2e-11eb-9b5f-2ad9a37badfa.png)



Changing that board solved the problem.

**Comment by xEnVrE** [comment]
Thank you @violadelbono @Uboldi80
