### ISSUE TITLE
Unmount the arms of iCubGenova04

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1157]
### Device name 🤖

iCubGenova04

### Request/Failure description

On Monday next week we would like to convert iCubGenova04 to iRonCub, and we would need support for unmounting the forearms.

### Detailed context

We would need it in view of the iRonCub experiments

**Comment by Uboldi80** [comment]
![image](https://user-images.githubusercontent.com/80786976/125262705-ae618b00-e302-11eb-8a6b-feffd9d7f5a9.png)

Done!
