### ISSUE TITLE
Icub robot does not want to turn on 

### ISSUE THREAD

**Issue by ivan9a** [robotology/icub-tech-support#1158]
### Device name 🤖

iCubZagreb01

### Request/Failure description

Icub robot does not want to turn on 

### Detailed context

Icub robot does not want to turn on, when I press the power button and motor driver button nothing happens. In normal conditions, these buttons should be in green light.
Please see pictures down below:

![IMG_20210709_085222](https://user-images.githubusercontent.com/83449933/125039095-6b02e480-e096-11eb-9550-39e415329436.jpg)

![IMG_20210709_085215](https://user-images.githubusercontent.com/83449933/125039110-6dfdd500-e096-11eb-9326-0b081890f6fe.jpg)

Thank you,
Best regards,
Ivan Župančić

**Comment by Uboldi80** [comment]
Hi Ivan
from what i see, the leds do not even turn red, therefore, no power arrives to the robot.
please check the following:
- verify the cables of power supply, from the power supply to the robot (maybe are loose something to the connection?) and take a photo please.
- Verify the connector cable under the backback and check if is thightened 
- if the previous checks failed, check the fake battery in the back pack and try to press lightly on it


let me kno

**Comment by ivan9a** [comment]
Hi Uboldi,

The LEDs do not turn red but LEDs inside the robot turn on, I have checked every connection as you described. Please see the pictures down below:

![IMG_20210709_112214](https://user-images.githubusercontent.com/83449933/125057202-42d0b100-e0a9-11eb-8b3b-fe7941143113.jpg)
![IMG_20210709_112247](https://user-images.githubusercontent.com/83449933/125057204-4401de00-e0a9-11eb-85a0-8f560605aa9f.jpg)
![IMG_20210709_112340](https://user-images.githubusercontent.com/83449933/125057206-449a7480-e0a9-11eb-9453-d436c7b69565.jpg)
![IMG_20210709_112353](https://user-images.githubusercontent.com/83449933/125057208-449a7480-e0a9-11eb-834c-a87f19c74d76.jpg)
![thumbnail_IMG_20210709_112236](https://user-images.githubusercontent.com/83449933/125057209-449a7480-e0a9-11eb-9ca8-eda493b00d53.jpg)

The connector under the backpack is tightened, everything looks ok with cables.

Thank you,
Best regards,
Ivan Župančić

**Comment by Uboldi80** [comment]
OK, as far as I can see the voltage reaches the board and in fact the LED are on.
you should check on the BCB (the board that houses the power keys that do not light up) below the image that indicates the point to check.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/80786976/125073390-268a3f80-e0bc-11eb-9fa4-6b6fa52afcd9.png)

**Comment by Uboldi80** [comment]
you should check that the pins are not bent and consequently NOT TOUCH each other, otherwise this could reset the board and give this problem.

**Comment by Uboldi80** [comment]
hello Ivan

to perform this check I suggest you:

turn off the setup, and disconnect the power cable and the ethernet cable

**Comment by Uboldi80** [comment]
if due to the backpack you cannot see that point on the card then I will show you the steps to remove the battery and the backpack.
Unfortunately, those pins are very close to the plastics, and may have bent due to a bump or pressure at that point.

**Comment by ivan9a** [comment]
Hello Uboldi,

The problem is fixed !, I have removed the plastic and checked all pins on that PCB. The first two pins were connected, now everything is as it should be.

Thank you,
Best regards,
Ivan Župančić

**Comment by Uboldi80** [comment]
Great!!!! 

thankyou @MrAndrea, master stroke!

**Comment by Uboldi80** [comment]
ok Ivan 

i'm very happy for you, and now i will close this issue.
