### ISSUE TITLE
Fix the mounting of iCubGenova09 left hand cover 

### ISSUE THREAD

**Issue by kouroshD** [robotology/icub-tech-support#1162]
### Device name 🤖

iCubGenova09 

### Request/Failure description

At the moment, the left-hand cover of the robot is not fixed well in place, and some screws are not  in place. As you can see in the photo, it moves cover moves easily.

cc @S-Dafarra  @DanielePucci  @evalli-iit 

### Detailed context

![image](https://user-images.githubusercontent.com/17707730/126199922-37100394-20ea-44b3-b66e-855947060782.png)

**Comment by Uboldi80** [comment]
![icub 3](https://user-images.githubusercontent.com/80786976/126337090-f7bc0c89-f167-4351-9bf6-d1b5ea60b6f5.jpg)

I have finded a solution for the palm.
note: tha palm was broken to the countersink positioned to the lower side, where the palm (plastic part) is fixed on to the metal part.
and then, to fix the broken part to the hand, i added the glue to the 3 spacer and i have inserted 3 washer with the screws.
the hand calibration has done well

![icub](https://user-images.githubusercontent.com/80786976/126336851-876c0535-e15e-45f9-8074-73ae82a13cb8.jpg)
