### ISSUE TITLE
Right hip pitch cable broken

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1168]
### Device name 🤖

iCubGenova04

### Request/Failure description

the right leg hip pitch joint metal cable got broken during an experiment.

### Detailed context

while performing experiments, the robot landed violently on the ground and the hip pitch cable broke.

**Comment by maggia80** [comment]
@Uboldi80 the documentation related to that tendon is here: https://icub-tech-iit.github.io/documentation/icub_tendons/waist_legs/#31-hip-flexion-cable-14

@fbiggi knows how to fix it, once the electronics cards have been removed.

**Comment by Uboldi80** [comment]
Today @fbiggi replace the tendon broken.

**Comment by fbiggi** [comment]
riconsegno il robot in dara 03/08/2021 tempo di intervento 3 h 1/2


![20210803_100601](https://user-images.githubusercontent.com/20420331/127981515-1f21aaff-f189-4a96-8a2a-a980341dcf59.jpg)
![20210803_100609](https://user-images.githubusercontent.com/20420331/127981521-0d583f58-c157-447c-bdae-2641c6f6c196.jpg)
