### ISSUE TITLE
iCubGenova01 - Left camera images contains artifacts

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1169]
### Device name 🤖

iCubGenova01

### Request/Failure description

When running the **left** camera for a while, strange artifacts start appearing in the top part of the image.

https://user-images.githubusercontent.com/6014499/127656318-a449c419-2df7-4a45-9197-bd333e2276fa.mp4

### Detailed context

When running the **left** camera for a while, strange artifacts start appearing in the top part of the image.

The cameras were running at 640 x 480.

**Comment by traversaro** [comment]
We had some similar problems related to the `libdc1394` library on other setups,  evein if in that case the problem was highly non-deterministic, and was disappearing if the `yarprobotinterface` was launched before hand. Just to understand, in this case the `yarprobotinterface` was running or not?

**Comment by xEnVrE** [comment]
In this case the `yarprobotinterface` was running.

**Comment by Uboldi80** [comment]
@traversaro, do you think that problem could be related an hardware problem? ccd of left camera?

**Comment by traversaro** [comment]
> 
> 
> @traversaro, do you think that problem could be related an hardware problem? ccd of left camera?

I don't have a clear idea, but @maggia80 indeed suggested that that could be the case.

**Comment by maggia80** [comment]
yes! I think so since the corrupted image does not have rows with issues but it's a more weird behavior. We could try to replace just the CCD.

**Comment by Uboldi80** [comment]
ok @maggia80  i can try to replace that.

Thks!

**Comment by Uboldi80** [comment]
Today I replaced the CCD of the left camera.
for now seem to work well.

**Comment by xEnVrE** [comment]
The CCD has been replaced but the problem still persists at 640 x 480.

Nevertheless, since it is not happening at 320 x 240, that is the usual target when using this robot, I think we can close this for now. 

This also means that the problem might be:
- hardware related, as it presents only when running at higher resolution, maybe related to the firewire bandwidth, etc?
- software related, maybe one of the modules inside the chain from the camera to the output is broken (maybe a memory leak?)
