### ISSUE TITLE
Robot Motors do not start anymore

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1175]
### Device name 🤖

iCubGenova04

### Request/Failure description

While testing the current controller on the pole the robot went in over-current.

After this event, the robot motors do not start anymore and the motor button led blinks.

cc @Uboldi80 @Giulero  

### Detailed context

The head starts as usual.

Here the log
[log_icub-head_yarprobotinterface_1669.txt](https://github.com/robotology/icub-tech-support/files/6938592/log_icub-head_yarprobotinterface_1669.txt)

**Comment by S-Dafarra** [comment]
cc @DanielePucci @maggia80

**Comment by maggia80** [comment]
@GiulioRomualdi could you run the current controller for each part of the robot separately, to better understand if there is a particular part that causes the over-current of the whole robot.

**Comment by S-Dafarra** [comment]
> @GiulioRomualdi could you run the current controller for each part of the robot separately, to better understand if there is a particular part that causes the over-current of the whole robot.

I think that the problem is that the motors do not turn on at all anymore

**Comment by maggia80** [comment]
ah ok! so we need to figure out which board is causing the short-circuit.

**Comment by GiulioRomualdi** [comment]
When we tried to switch on the motors none of the boards blinks

**Comment by maggia80** [comment]
board 3B6 was in short circuit:
![image](https://user-images.githubusercontent.com/6987330/129032195-18e571bb-9569-4cbc-bf2a-3e7427029fff.png)

we replaced ( thanks @emilianob80 ) the 3B6 with a new one.
The problem was caused by a screw:

![image](https://user-images.githubusercontent.com/6987330/129032764-c3f0391d-9cc5-48ec-80f3-1a5408916e5a.png)

![image](https://user-images.githubusercontent.com/6987330/129032791-d8369ffe-81d0-4408-b556-882079acf88f.png)

you can now use the robot even if the covers of the left upper leg are not mounted.

**Comment by S-Dafarra** [comment]
Oh wow, a screw! Super, thanks a lot!

**Comment by DanielePucci** [comment]
Big thanks @maggia80 and @emilianob80 for the support, having the robot functional this week was an important milestone for performing tests of a looming outdoor demo in September. Grazie ragazzi

**Comment by DanielePucci** [comment]
Big thanks @maggia80 and @emilianob80 for the support, having the robot functional this week was an important milestone for performing tests of a looming outdoor demo in September. Grazie ragazzi!

P.s. I belive that this is indeed another lesson learnt. We may think of designing the next generation of the robot electronics so as to avoid this kind of occurrence (e.g. encapsulate the electronics, or having the robot simply fully covered by covers)

**Comment by GiulioRomualdi** [comment]
@maggia80  and @emilianob80, thank you so much!

**Comment by S-Dafarra** [comment]
Thanks a lot to @maggia80 which connected the leg back. I have tested it and the robot seems ok. Is it possible to put the covers back on?

**Comment by DanielePucci** [comment]
CC @Fabrizio69

**Comment by emilianob80** [comment]
> Thanks a lot to @maggia80 which connected the leg back. I have tested it and the robot seems ok. Is it possible to put the covers back on?

@S-Dafarra Of course, if the robot is working the covers can be reassembled

**Comment by S-Dafarra** [comment]
> > Thanks a lot to @maggia80 which connected the leg back. I have tested it and the robot seems ok. Is it possible to put the covers back on?
> 
> @S-Dafarra Of course, if the robot is working the covers can be reassembled

Yes, please!
