### ISSUE TITLE
Left hip pitch encoder cable disconnected

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1176]
### Device name 🤖

iCubGenova09

### Request/Failure description

While testing the robot on the pole the left hip pitch encoder cable went  out.

@Giulero and I tried to reconnect the cable but we were not able to do it

### Detailed context

The connector is not damaged

![20210805_195520](https://user-images.githubusercontent.com/16744101/128428219-3a698d3c-f2bf-462f-9abc-7a6216b56f8a.jpg)

**Comment by Uboldi80** [comment]
i fixed the hip pitch connector and tha face mask.

**Comment by GiulioRomualdi** [comment]
Thank you @Uboldi80
