### ISSUE TITLE
Right hand often fails to calibrate and right thumb oscillate

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1179]
### Device name 🤖

iCubGenova04

### Request/Failure description

The right hand often fails to calibrate, and the thumb, the index and the middle fingers remain closed.

### Detailed context

The right hand fails to calibrate quite often. Even when it calibrates, the right thumb keeps oscillating. We also noticed several MAIS timeouts when starting it up. I guess that the main reason might be the thumb itself, which does not move properly at startup.

**Comment by S-Dafarra** [comment]
cc @DanielePucci

**Comment by Uboldi80** [comment]
Hy @S-Dafarra 

Maybe is better to remind this problem in the issue 1139.
Can  you close this issue please? 
perhaps it would be better to describe this problem in the issue which already describes the swing of the right thumb and the attempts to repair it.

**Comment by S-Dafarra** [comment]
Hi @Uboldi80. Yes, you are right, this is a duplicate. Closing this then
