### ISSUE TITLE
Broken motor for the left arm ring and little finger slider

### ISSUE THREAD

**Issue by cedricgoubard** [robotology/icub-tech-support#1181]
### Device name 🤖

iCubLondon01

### Request/Failure description

Hello, 
The motor responsible for moving the slider that closes the ring/little fingers on the left arm is broken. How can we get a new one?

### Detailed context

Here a picture of the motor:
![PXL_20210825_145222098 MP](https://user-images.githubusercontent.com/40461909/130944044-329f19c3-ff01-4bc9-92b8-a7b4262e1fc4.jpg)

It does not turn anymore.

**Comment by Uboldi80** [comment]
Hy Cedric
I give you in advance the photo for the motor replacement:
of course, before disassembly the gearmotor you must remove the wiring welds on the motor.
![IMG_20210914_111909](https://user-images.githubusercontent.com/80786976/133232893-a1ede8e5-93d1-467f-9624-08a76b928164.jpg)

![IMG_20210914_111929](https://user-images.githubusercontent.com/80786976/133232924-ee0ba875-22a3-4562-ac49-319f2bf23033.jpg)

![IMG_20210914_111723](https://user-images.githubusercontent.com/80786976/133232961-ce7ded81-1a64-4961-b36e-e7085fc6c688.jpg)

![IMG_20210914_111959](https://user-images.githubusercontent.com/80786976/133232996-8c5acfd0-71b1-4e80-b032-57b0b060bf3d.jpg)

As you can see the motor and the gear box are screwed and basically, to remove the motor you must unscrew the motor from the gearbox.
you have to very carefull during the assembly of the new motor in the older gear box, cause, the risk is to damage itself.
to avoid this, i suggest to you to screw the two parts very gently.
if you feel a resistance during this operation you must unscrew and retry the action.

let me know

**Comment by cedricgoubard** [comment]
Hi @Uboldi80,
Thank you for the instructions; I'll let you know as soon as I receive it.

**Comment by andreaderito** [comment]
Hi @cedricgoubard goods should leave end of this week (dragonfly, flat cable and motor+encoder) - expected delivery within mid of next week

**Comment by andreaderito** [comment]
Hi Cédric,
the parcel will leave this afternoon or tomorrow afternoon at the latest, tracking available on www.dhl.com  using AWB no.: 1496572803. See related email to you, best
