### ISSUE TITLE
iCubGenova04 - Both upper arm skin covers torn along near the corner screws

### ISSUE THREAD

**Issue by prashanthr05** [robotology/icub-tech-support#1183]
### Device name 🤖

iCubGenova04

### Request/Failure description

The skin covers on both the upper arms of the robot are torn and remain slightly unattached from its link. This might sometimes expose the taxel sensors beneath in the open.

### Detailed context

While performing some walking experiments, we had to force the robot to stop with  the emergency fault. Consequently, the robot fell which unduly resulted in the covers getting torn at the corners (we did not exactly catch how it had happened). 

|Right arm| Left arm|
|:--:|:--:|
|![image](https://user-images.githubusercontent.com/6506093/131040432-55889a28-08af-4e33-85db-14a8a709f425.png)|![image](https://user-images.githubusercontent.com/6506093/131040486-b9534738-a6aa-4abc-9939-053474b5990a.png)|

cc @Yeshasvitvs @DanielePucci

**Comment by Uboldi80** [comment]
I arranged a temporary solution to fix the skin on to the shoulders.
i have utilized 2 washer with 2 M2x8 screws to fix the lower sid of skin, and i fix with hot glue the upper side of the skin.
the hot glue should come off smoothly in case of disassembly.

**Comment by prashanthr05** [comment]
Thank you @Uboldi80 !!
