### ISSUE TITLE
iCubErzelli032 - Left wrist detached

### ISSUE THREAD

**Issue by Nicolasr3** [robotology/icub-tech-support#1184]
### Device name 🤖

iCubErzelli032

### Request/Failure description

Left wrist cannot reach the desired position. When iCub is calibrating the left wrist is not moving correctly. 

### Detailed context

On the wrist is missing 2 screws.
Yarplogger and yarpmotorgui don't show any error.

![icub1](https://user-images.githubusercontent.com/44875110/131313843-01410b89-ad7c-407f-b44d-958b65e11283.jpeg)
![icub2](https://user-images.githubusercontent.com/44875110/131313848-5a1be2f7-0d78-4b88-a8a1-febb1a213bd3.jpeg)
![icub3](https://user-images.githubusercontent.com/44875110/131313852-39253767-a09d-43e4-a612-0ce5f582a883.jpeg)
![icub4](https://user-images.githubusercontent.com/44875110/131313855-fc88d814-1f31-488a-9510-e978bad9b8f7.jpeg)

**Comment by Uboldi80** [comment]
@Nicolasr3 fixed hitself the problem with the wrist.
the 2 screw of on the wrist went loose.
