### ISSUE TITLE
iCubGenova04 - replace the power connector

### ISSUE THREAD

**Issue by vpunithreddy** [robotology/icub-tech-support#1185]
### Device name 🤖

iCubGenova04

### Request/Failure description

@gabrielenava  noted that the power connector of iCubGenova04 is very damaged:

![](https://user-images.githubusercontent.com/12396934/129195334-79d7bee9-fe88-456d-b61f-d2e657874785.jpeg)

It would be nice to replace it.

### Detailed context

The knurling for the connector is damaged and is difficult to assemble and dismantle the connector for the power cable.
The connection is not secure since the robot is flying. It would be better to have a more secure connection by replacing the connector.

**Comment by Gandoo** [comment]
![20210901_100307](https://user-images.githubusercontent.com/53341641/131643081-5b1c8724-1038-4eb9-87a2-e735dfe92300.jpg)

![20210901_100341](https://user-images.githubusercontent.com/53341641/131643093-0f038e17-a0b2-4e5c-872d-584d77d74b73.jpg)

un pin dove e saldato il filo è spezzato, la causa sicuramente dovuta alla rotazione della curva durante l'inserimento del connettore. **Non bisogna usale una pinza ma usare solo la mano per avvitare la ghiera**

cc  @DanielePucci @FabioBergonti @maggia80 @Uboldi80 @Fabrizio69 @gabrielenava

**Comment by Uboldi80** [comment]
replacement of power connector done.

Thankyou @Gandoo

**Comment by FabioBergonti** [comment]
Thank you @Gandoo 

>un pin dove e saldato il filo è spezzato, la causa sicuramente dovuta alla rotazione della curva durante l'inserimento del connettore. 
**Non bisogna usale una pinza ma usare solo la mano per avvitare la ghiera**

@robotology/iit-dynamic-interaction-control probably most of you already know, but I remind you that the black nut must be tightened (by hand), while the grey one must not be touched/rotated

![image](https://user-images.githubusercontent.com/38210073/131653792-a802240e-477e-4d97-b53d-f0b6b7cab5dc.png)

**Comment by DanielePucci** [comment]
@robotology/iit-artificial-mechanical-intelligence indeed an important comment by @FabioBergonti , i.e.
> probably most of you already know, but I remind you that the black nut must be tightened (by hand), while the grey one must not be touched/rotated
