### ISSUE TITLE
R1SN003 - left arm broken

### ISSUE THREAD

**Issue by lnobile** [robotology/icub-tech-support#1186]
### Device name 🤖

R1SN003

### Request/Failure description

Left arm JOINT 4 (l_wrist_pronosupination_joint) doesn't work properly.

### Detailed context

The motor and encoder are working correctly but even if I can hear the motor spinning the joint doesn't move. Probably a loosen/broken belt.

**Comment by maggia80** [comment]
@fbiggi @emilianob80 could you check it?

**Comment by emilianob80** [comment]
@maggia80 Ok I do a first cechk myself because @fbiggi is in the mechanical workshop these days. If you are unable to solve it independently, we schedule an intervention with @fbiggi 

cc: @Uboldi80

**Comment by emilianob80** [comment]
@lnobile The screw indicated in the red circle in the following image was loose. The problem was solved and the rotation with the jogger tested

![wrist](https://user-images.githubusercontent.com/53729815/132462421-9a770be9-d900-4bb5-b453-0c3b87163d3d.JPG)

cc: @maggia80 @fbiggi
