### ISSUE TITLE
iCubGenova01  - Left thumb opposition cable needs to be replaced

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1187]
### Device name 🤖

iCubGenova01

### Request/Failure description

After talking with @GiacomoVassallo13, that is working in order to fix #1166, it seems that it is required to substitute the cable of the left thumb opposition. Hence I am opening this issue.

### Detailed context

Ditto.

**Comment by Uboldi80** [comment]
tendon replaced and tested
