### ISSUE TITLE
Left elbow cable broken 

### ISSUE THREAD

**Issue by lunagava** [robotology/icub-tech-support#1188]
### Device name 🤖

iCub[Genova][02]

### Request/Failure description

The tendon responsible for the elbow joint is broken and it needs to be substituted with a new one. The replacement is not particularly urgent.

### Detailed context

The arm is not able to stay in the home configuration. 

### Additional context

![IMG_0807](https://user-images.githubusercontent.com/45895918/132723747-45720f6a-0ff9-4bbd-ab00-8d6613a705fb.jpg)

**Comment by GiacomoVassallo13** [comment]
The cable has been replaced.
