### ISSUE TITLE
iCubGenova04 left camera not working

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1191]
### Device name 🤖

iCubGenova04

### Request/Failure description

We tried to run the `yarpdev` for the cameras. The right camera is working fine while the left one not. Everything remains black.

### Detailed context

cc @S-Dafarra @isorrentino and @paolo-viceconte

**Comment by Uboldi80** [comment]
I replaced 2 flats (left and right) and tested the cameras.
