### ISSUE TITLE
Battery charger connector broken - iCubGenova09 (icub3)

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1194]
### Device name 🤖

iCubGenova09

### Request/Failure description

The connector to recharge the battery on the iCub3 power cable got broken

### Detailed context

![image](https://user-images.githubusercontent.com/18591940/134052314-4261ac86-c378-478d-a467-ffea8c168047.png)

cc @pattacini @emilianob80

**Comment by emilianob80** [comment]
@S-Dafarra connector restored

![IMG_20210924_104429](https://user-images.githubusercontent.com/53729815/134645991-ca841c8e-e6f9-43fa-bff9-5dbe9de48b4b.jpg)

cc: @Fabrizio69 @pattacini
