### ISSUE TITLE
Right thumb oppose  tendon broken - iCubGenova09

### ISSUE THREAD

**Issue by davidetome** [robotology/icub-tech-support#1198]
### Device name 🤖

iCubGenova09

### Request/Failure description

the right thumb oppose is loose, probably due to a broken tendon

cc @pattacini 

### Detailed context

/

**Comment by davidetome** [comment]
@GiacomoVassallo13 is going to fix this 🛠️

**Comment by GiacomoVassallo13** [comment]
@davidetome the thump oppose was been replaced.
Ticket:
cc: @Fabrizio69 @Uboldi80

**Comment by isorrentino** [comment]
I just turned on the robot and the thumb of the right hand moves without any input and continuously. Reopening.
cc @pattacini

**Comment by pattacini** [comment]
cc @GiacomoVassallo13 @davidetome

**Comment by pattacini** [comment]
Moved the writeup of @Uboldi80 from https://github.com/robotology/icub-tech-support/issues/1058 here, as this is the originating issue:

> for some reason that I still do not fully understand, despite the pulling of the hand tendons being performed at least 2 more times, the tendon retaining grains were again slack. this obviously contributes to making the joint difficult to control as well as making it oscillate. This morning I re-tensioned the thumb cables but this time I added a special low-resistance bellow to prevent damage by irreparably blocking the grain. it is loctite 222 pink. probably part of the problem is due to the size of the fixing screws: I believe that M 1.6 is really too little to offer adequate resistance, also considering that the threaded piece I believe is in aluminum, so I assume that following some uses of this joint in particular (thumb) subjected to greater stress than the other joints tends to release the retaining grain in a short time. it would probably help if the grains of the fingers were at least M2 in order to guarantee a better seal against the tendon. please let me know.

**Comment by pattacini** [comment]
Nice report @Uboldi80 🚀

**Comment by Uboldi80** [comment]
THKS @pattacini !!
