### ISSUE TITLE
Hardware error for left shoulder roll encoder

### ISSUE THREAD

**Issue by cedricgoubard** [robotology/icub-tech-support#1201]
### Device name 🤖

iCubLondon01

### Request/Failure description

Hello,
I get an `[ERROR] sharedcan [1] board 1 ABS ENCODER ERROR AXIS 1` when running `yarprobotinterface` in calibration mode. If I ignore it and run `yarpmotorgui`, I can see that the left shoulder roll has a hardware fault.

### Detailed context

This happened just after I rewired the whole shoulder, so I guess the cause is obvious :-)
However, I have a few questions:
 - Where is the encoder in question? is it the one on the front of the shoulder (see picture below)? If so, I opened it and it does not appear broken... Is there any other way to check?
 - I noticed that there seem to be a missing "screw" on this side of the shoulder compared to the other. Could this have anything to do with the issue?

### Additional context

The `yarpmotorgui` interface:
![motorfault](https://user-images.githubusercontent.com/40461909/134780269-81314e0d-598d-456b-b694-7dc3b99a8fdf.png)

The encoder I am mentioning in my question (is it the roll encoder?):
![PXL_20210925_171026356 MP](https://user-images.githubusercontent.com/40461909/134780287-6f309d06-31b8-4306-a072-fa2744deaee5.jpg)

The missing "screw" on the left side, compared to the right (in the middle of the shoulder):

![PXL_20210925_171032871 MP](https://user-images.githubusercontent.com/40461909/134780298-2b6afcac-2a3c-4585-95d8-ded498e781b0.jpg)
![PXL_20210925_171400686 MP](https://user-images.githubusercontent.com/40461909/134780330-e43d8b78-f278-4c52-986a-8935dfdc09c1.jpg)

**Comment by Uboldi80** [comment]
Hy Cedric 
Yes, the encoder that you mentioned is the ROLL.
Now, probably the problem is caused by a torn thread.
1 point. you must check the AEA encoder :
![image](https://user-images.githubusercontent.com/80786976/134883983-777f28d0-8c38-44c5-a6e2-6dc15dc3f3ac.png)

2 point: you need to check the chain of encoder:
as you can see, trough the AEA roll and the EMS4 1B0 you have a sectioning. The sectioning is delicated and you should find that in the shoulder. The position of the connector in the BLL is P14.
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/80786976/134885301-1a90d053-3fbb-498c-b627-ea4379bb3889.png)

let me know

**Comment by cedricgoubard** [comment]
Hi @Uboldi80,
Thank you for your answer. I checked the AEA encoder, and I don't see anything wrong:

![PXL_20210927_094907527 MP](https://user-images.githubusercontent.com/40461909/134891078-ed6f946a-0d4a-4ff9-b656-039d5a030ebe.jpg)

I then looked at the EMS4 1B0, but I cannot find the P14 connector. Am I missing something?
I noticed that P8 is supposed to be empty, but is not on our board. Maybe that is where the P14 is connected?
![PXL_20210927_101211346 MP](https://user-images.githubusercontent.com/40461909/134891089-8d0f00a2-a8c8-48a7-877d-cf91a4b20f7c.jpg)
![PXL_20210927_102110895 MP](https://user-images.githubusercontent.com/40461909/134891095-ff43efe5-3f4e-48df-b9d4-0628cae50183.jpg)

**Comment by Uboldi80** [comment]
hy

under the P9 connector you should find the P14 (to the other side of the same board)

**Comment by cedricgoubard** [comment]
Hi @Uboldi80,
I did not find anything under the board:
![PXL_20210927_120746554 MP](https://user-images.githubusercontent.com/40461909/134909951-952be3a0-308c-483c-a344-9e597c847d9a.jpg)

**Comment by cedricgoubard** [comment]
I just checked, and the encoder cable is actually connected to P9. One of the wires seems broken; I'll try to fix it and see if that solves the issue.

**Comment by Uboldi80** [comment]
ok, great!
Sorry, i thinked your setup was a little bit different in thath board, but aniway, we find the torn wire.

**Comment by cedricgoubard** [comment]
No problem, even though the connector was wrong, we still found the issue!
I fixed the wire and it's working again, thank you for your help.
