### ISSUE TITLE
The board measuring the battery charge on one of the iCubGenova04 batteries is dead

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1204]
### Device name 🤖

iCubGenova04

### Request/Failure description

While inserting the battery into the robot, we saw the LEDs turning on in a weird way. After that, the button for checking the battery charge stopped working, and we were no more able to detect the battery charge from the robot either.

cc @maggia80 @MrAndrea 

### Detailed context

This is the battery:
![image](https://user-images.githubusercontent.com/18591940/134876482-dbf41a4b-5674-4d8a-836a-597d533b68cf.png)

**Comment by Uboldi80** [comment]
the problem has fixed.

Replaced BMON 6123.b by @Gandoo
