### ISSUE TITLE
iCubGenova04 - Right shoulder cable broken

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1209]
### Device name 🤖

iCubGenova04

### Request/Failure description

The cable of the robot shoulder came out of the pulley

### Detailed context

It happened during human-robot collaborative lifting experiments

**Comment by Uboldi80** [comment]
Replaced tendon N.3 with @GiacomoVassallo13

**Comment by lrapetti** [comment]
Thanks a lot! I have restarted the robot and the shoulder was working fine!
