### ISSUE TITLE
iCubSingapore01: Both hands do not complete properly the calibration

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1214]
### Device name 🤖

iCubSingapore01

### Request/Failure description

The calibration of both hands fails.

### Detailed context

The calibration sequence is shown in the video attached.

RIGHT ARM: Middle finger seems not reaching the desired position (the motor continues acting)
LEFT ARM: At a certain point the wrist joint stop working

### Additional context

https://user-images.githubusercontent.com/3440640/136350163-4178aa13-8d9b-463b-8d7d-2ae86b716323.mp4

[log_pc104_yarprobotinterface_1771_calibration_2.txt](https://github.com/robotology/icub-tech-support/files/7300585/log_pc104_yarprobotinterface_1771_calibration_2.txt)

**Comment by Serehal** [comment]
Hi @Uboldi80,

thank you for your help. 
As soon as I can enter the lab (we have some restrictions here in Singapore) I will get back to you with more info!

**Comment by sgiraz** [comment]
Hi @ddetommaso,

We have finally received the robot! We can now proceed with the maintenance activities, stay tuned! 📢

cc @AntonioConsilvio @GiacomoVassallo13

**Comment by AntonioConsilvio** [comment]
Hi @ddetommaso,

## ⚙️ Maintenance 
We finalized all the activities on `iCubSingapore01`. Watch the videos below for some tests:

| Startup  | YogaDemo |
| ------------- | ------------- |
| <video src="https://github.com/robotology/icub-tech-support/assets/114915464/1724481e-1dbc-4b19-8831-e2dcfb25dc7d">| <video src="https://github.com/robotology/icub-tech-support/assets/114915464/0bc0f5e1-ea3c-4363-9415-8313bf4ca546"> |


| Face expressions |
| ------------- |
| <video src="https://github.com/robotology/icub-tech-support/assets/114915464/478a3fb8-30ca-4e91-acd9-a778bfb65225">  |

--- 

## 📦 Shipment 
The shipping process should start in early September.

As soon as it is shipped, you will receive the following package:
 
| Full package |
| ------------- |
| ![Package](https://github.com/robotology/icub-tech-support/assets/114915464/edee34eb-03d8-4ac8-a7fb-f59d15cd5550) |


## ℹ️ Info

We updated the Ubuntu version of the robot head and laptop to the latest versions.
We updated the robotology-superbuild version of the robot head and laptop to the latest versions.

We updated the robots-configuration files with this two PR:

- https://github.com/robotology/robots-configuration/pull/552
- https://github.com/robotology/robots-configuration/pull/556 (latest)





cc @maggia80 @sgiraz @Fabrizio69 @andreaderito

**Comment by sgiraz** [comment]
Yesterday, the robot was shipped successfully.
I close the issue as all the tasks have been completed.
