### ISSUE TITLE
iCubSingapore01: Facial expressions do not activate properly

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1215]
### Device name 🤖

iCubSingapore01

### Request/Failure description

Sometimes facial expressions do not activate properly.

### Detailed context

Even if yarp processes are running and connected properly the facial expression do not activate as usual. The issue occurs randomly on a recurring basis. 

### Additional context

[log_pc104_yarprobotinterface_1771_emotions_2.txt](https://github.com/robotology/icub-tech-support/files/7300854/log_pc104_yarprobotinterface_1771_emotions_2.txt)

**Comment by sgiraz** [comment]
Hi @ddetommaso, see
- https://github.com/robotology/icub-tech-support/issues/1214#issuecomment-1545548149

**Comment by AntonioConsilvio** [comment]
Hi @ddetommaso, see the following comment for update:

- https://github.com/robotology/icub-tech-support/issues/1214#issuecomment-1692945803

**Comment by sgiraz** [comment]
@AntonioConsilvio, the comment you pointed out shows that the issue related to the facial expression has been resolved. As a result, I am closing this issue and leaving #1214 open until it has been delivered.

cc @ddetommaso
