### ISSUE TITLE
Convert iCubGenova04 into iRoncub

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1216]
### Device name 🤖

iCubGenova04

### Request/Failure description

We would need help to convert iCubGenova04 into iRonCub for the next experimental campaign. More specifically:

 - we need to detach the arms from the robot;
 - if possible, can we replace the new covers with the old ones? This is because during the campaign the covers can be damaged / get dirty, and this is a pity since they are brand new. Alternatively, we could also:
   * replace just the legs covers with the old ones;
   * remove the cloth from the covers and put something on the skin to protect it from dirt and heat.

However I anticipate that the robot will also be used for wind tunnel experiments in November / December, and by that time we would need to mount on the robot the old covers because they are going to be endowed with sensors for collecting data in the wind tunnel.

### Detailed context

**Tentative experiment start date: 18th October**. The campaign will last ~2 weeks, as usual it depends on the weather conditions.

cc @Fabrizio69 @DanielePucci @maggia80

**Comment by Uboldi80** [comment]
thanks @emilianob80

**Comment by DanielePucci** [comment]
Great guys, thanks a lto
