### ISSUE TITLE
BMS board not working

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1220]
### Device name 🤖

iCubGenova09

### Request/Failure description

The board controlling the battery of the robot is probably fried.

### Detailed context

Before the Maker Faire demo, the robot produced some smoke. @maggia80 @Gandoo @MrAndrea and @Fabrizio69 checked the robot and found some broken components on the BAT board. There was also a broken fuse on the BMS board. While replacing it, some sparks occurred and the BMS stopped working.

**Comment by Fabrizio69** [comment]
Hi @S-Dafarra we are working to replace the BMS (ordered a new board)

cc: @MrAndrea

**Comment by S-Dafarra** [comment]
> Hi @S-Dafarra we are working to replace the BMS (ordered a new board)
> 
> cc: @MrAndrea @Uboldi80

Do you have any indication about the possible time of arrival? We are going to shoot a video with the robot on the first week of November, and we would need to use the battery

**Comment by maggia80** [comment]
BMSs have been delivered to ELTEC for repairing them. As soon they check them they can tell us when the boards will be ready.

**Comment by S-Dafarra** [comment]
We received the BMS https://github.com/icub-tech-iit/purchases/issues/1402 https://github.com/icub-tech-iit/purchases/issues/1431, but it still needs to be installed. We have yet another demo the 25 with a TV crew and it is important to have it

**Comment by Uboldi80** [comment]
The BMS was replaced and tested.
