### ISSUE TITLE
Some of the neck boards can get stuck

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1223]
### Device name 🤖

iCubGenova09

### Request/Failure description

During the Maker Faire, we realized that one of the boards of the neck (if I remember correctly the one controlling the yaw) got stuck. The board was still pingable, and we managed to reset it using the FirmwareUpdater.

### Detailed context

Initially, we thought it was related to #673, but since the board did not reset, it is a different problem.

cc @pattacini @marcoaccame @maggia80

**Comment by S-Dafarra** [comment]
So far, we did not have that error anymore, but we can keep it open for the time being

**Comment by pattacini** [comment]
It was agreed that we can close this.
