### ISSUE TITLE
Failure of MAIS of left hand on iCub3

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1230]
### Device name 🤖

iCubGenova09

### Request/Failure description

After few minutes on, the MAIS of the left hand turned off. The behavior is very similar to the one experienced during the Maker Faire in Rome.

### Detailed context

Here the log 
[log_icub-head_yarprobotinterface_2491_mais_left_hand_failure.txt](https://github.com/robotology/icub-tech-support/files/7433049/log_icub-head_yarprobotinterface_2491_mais_left_hand_failure.txt)

cc @emilianob80 @GiacomoVassallo13 @S-Dafarra

**Comment by Uboldi80** [comment]
![IMG_20211102_090409](https://user-images.githubusercontent.com/80786976/139808854-19bb5d09-e7e0-4ce2-922f-097872522aaa.jpg)

The problem with the MAIS error was caused by a problem with wiring in the pinky.
after 1 day of test the MAIS seems to work well.
cc. @emilianob80 @gandoo

**Comment by Gandoo** [comment]
ciao @Uboldi80 qundi conviene sostituire i fili che vanno a massa in quella posizione??

**Comment by Uboldi80** [comment]
Ciao @gandoo, per non togliere tempo ai ragazzi che devono settare il robot per Venezia eviterei di farlo fino al rientro.
Quindi lo farei dal 10/11 in poi.

Grazie
