### ISSUE TITLE
iCub 3 neck loosing mechanics 

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1233]
### Device name 🤖

iCubGenova09 

### Request/Failure description

The neck moves when it should not when blocked. The issue is similar to https://github.com/robotology/icub-tech-support/issues/932

### Detailed context

https://user-images.githubusercontent.com/5045846/140335679-c640a89c-b9be-4618-8e15-6361acbd29f4.MOV

**Comment by DanielePucci** [comment]
As agreed with @S-Dafarra, tomorrow early morning, November 5th, would be great to get the attempt to fix the issue

**Comment by S-Dafarra** [comment]
@Uboldi80 @gsisinna @GiacomoVassallo13 I think you already did some fixes, but it is still necessary to unmount the mechanism. Am I correct?

**Comment by GiacomoVassallo13** [comment]
Buongiorno, la testa di iCub 3 è stata staccata e il collo sottoposto a manutenzione.
Per quanto riguarda il gioco sul giunto dello yau, si è risolto aggiungedo un rasamento trovato  magazzino, per tenere fermo nella sede il cuscinetto.
![drutff](https://user-images.githubusercontent.com/70649516/142027623-1c862a07-126f-484a-891d-8f3da63cd06e.jpeg)

Ticket materiale: https://github.com/icub-tech-iit/tickets/issues/1829

**Comment by GiacomoVassallo13** [comment]
Purtroppo è stata riscontrata un anomalia grave tra l assieme RC_IIT_010_A_004. 
Il componente RC_IIT_010_P_024 (giallo) risulta storto una volta montato sul pezzo RC_IIT_010_P_008 (grigio).
Immagini della posizione corretta presa a CAD.

![het5aj45d6u7kfyglihm](https://user-images.githubusercontent.com/70649516/142031514-14261097-92d9-4344-a752-cdf3fa2bdc45.PNG)
![n mnkjwefsrgf](https://user-images.githubusercontent.com/70649516/142031547-b184acfc-54e8-4942-a7ec-0fbf85347489.PNG)

Immagini dell assieme fisico.
![sgnd](https://user-images.githubusercontent.com/70649516/142031715-bcd5491e-bf60-44be-9231-f53ed2150dc4.jpeg)

![awrestwdrtyib](https://user-images.githubusercontent.com/70649516/142031747-d2136334-539d-47c8-90fd-b08941ee644d.jpeg)

cc: @maggia80 @fbiggi @Fabrizio69 @Uboldi80

**Comment by Uboldi80** [comment]
the bearings of the neck was replaced and the harmonic inside was blocked trough loctite.
now the neck work well.
