### ISSUE TITLE
Right shoulder roll optical encoder connector is broken

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1234]
### Device name 🤖

iCubGenova09

### Request/Failure description

The motor encoder of the right shoulder roll is not working well. The joint goes in HF because of i2t error and we are not able to move it from the motorgui. I guess that the connector is broken

### Detailed context

We were doing some wide movements with the arm during the Venice video and probably some of the cables of the connector got damaged.

**Comment by S-Dafarra** [comment]
@gsisinna @GiacomoVassallo13

**Comment by Gandoo** [comment]
The problem would seem to be the black wire disconnected on the left shoulder connector, I re-crimped the wires and replaced the connector.
Checked if the RE1 cable was intact by disconnecting it to the 2Foc board to check the operation and reading of the encoder.
With the jogger reads.

**Comment by Uboldi80** [comment]
The right shoulder connector of encoder was fixed by @emilianob80.
now is ok.
