### ISSUE TITLE
Torso cable exited from the guide

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1237]
### Device name 🤖

iRonCub (iCubGenova04)

### Request/Failure description

Torso cable on the left side exited from the guide. They do not seem broken, they just slip out the guide.

### Detailed context

The robot was trying to take off, then it fell pitching in the front. To react to this fall, the robot put both arms horizontal and  increased the arm's thrust, but it over reacted and the robot was blown away backward. When it landed back, the cable exited the guide.

**Comment by Fabrizio69** [comment]
Hi @gabrielenava the solution of this issue is planned for next Monday 22 with estimated duration: 1 day

cc: @fbiggi @emilianob80 @Uboldi80 @gsisinna

**Comment by gabrielenava** [comment]
Perfect, thanks!!

**Comment by emilianob80** [comment]
@gabrielenava Fortunately, the repair of the mechanical cable of the torso (cable n ° 11) was faster than expected. The robot is ready to be tested. I close the issue

cc: @Fabrizio69 @gsisinna @Uboldi80

**Comment by gabrielenava** [comment]
thank you!!
