### ISSUE TITLE
Right MAIS intermittent issue

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1238]
### Device name 🤖

iCubGenova09

### Request/Failure description

The right MAIS sometimes starts with delay and some of the fingers do not calibrate or do not move properly. 

### Detailed context

Often, after a couple of reboots, everything starts correctly

### Additional context

cc @Fabrizio69 @gsisinna @emilianob80

**Comment by emilianob80** [comment]
After a check, the damaged black wire was found on the CAN cable connector connected to the MAIS electronic board. The wire was repaired and the problem solved

**Comment by Uboldi80** [comment]
the can line of the right hand was fixed by @emilianob80  and @gsisinna 

the robot was tested and work well.
