### ISSUE TITLE
Issues with iCubGenova01 PC104 boot

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1239]
### Device name 🤖

iCubGenova01

### Request/Failure description

This evening we had issues while trying to boot up the iCubGenova01 PC104 machine. As discussed with @Uboldi80 I am opening an issue to report the outcome.

At the beginning, we could not reach the PC104. Then, together with @Uboldi80 @gsisinna and @Arya07 we decided to
1. first check the Ethernet connectivity by testing a different Ethernet cable attached directly to the PC104 to no avail;
2. attach a VGA display to the PC104, using the adapter, in order to verify whether the iCub OS was completing the boot  or not. We found that the bootup process was struck due to I/O errors on the USB drive device.

As suggested by @mbrunettini we then downloaded the [iCub OS image](https://storage.cloud.google.com/icub_os_images/iCubLive_7.10-rt-amd64.img.gz) and dumped it over a new USB drive and finally we were able to make the robot start again.

After that, the only additional steps we did were updating the `.bashrc_iCub` using the [one](https://raw.githubusercontent.com/icub-tech-iit/icub-os-files/master/user-environment/bashrc_iCub_superbuild) required for a `robotology-superbuild`-based setup, setting up the yarp namespace with `yarp namespace /icub01` and finally `yarp detect --write`.

**Comment by maggia80** [comment]
do you think we can suggest following this step to https://github.com/robotology/icub-tech-support/issues/1205 ?

**Comment by Uboldi80** [comment]
Hy @maggia80 , we tried to connect the pc 104 of London01 to the vga monito but the pc 104 didn't started

**Comment by Uboldi80** [comment]
> Hy @maggia80 , we tried to connect the pc 104 of London01 to the vga monito but the pc 104 didn't started

https://github.com/robotology/icub-tech-support/issues/1205#issuecomment-930296168

**Comment by gsisinna** [comment]
After replacing the tendon as reported in https://github.com/robotology/icub-tech-support/issues/1236 , the system had the problem as described in detail by @xEnVrE . The USB flash drive seems to have become corrupted and it was necessary to create a new one using USB 2.0 version. The robot has been brought back to an optimal working condition but it is necessary to replace the USB flash drive in the near future with one provided by the warehouse and of a suitable size, as the current one has a capacity of about 16GB.

After heavy weekend use, the robot seems stable.

cc @Uboldi80
