### ISSUE TITLE
Right hand fingers cable broken

### ISSUE THREAD

**Issue by lunagava** [robotology/icub-tech-support#1240]
### Device name 🤖

iCub[Genova][02]

### Request/Failure description

The ring and pimkie fingers of right hand do not move. The motor just spins empty without moving them. I suppose it is a broken cable.

### Detailed context

As you can see from the figure below, the two fingers remain straight. 

If possible, it would helpful solving this issue before Wednesday 24th November, because we will have to show a demo for an interview with Rai Gulp on Thursday 25th November . The robot during the movement could hurt the table. Thanks in advance!

### Additional context

![IMG_2234](https://user-images.githubusercontent.com/45895918/142715013-d9cbf1ca-19a3-4ce9-8bc4-222d9b721313.jpg)

**Comment by Uboldi80** [comment]
we had replaced the little finger tendon.

we tested them by yarpmotorgui and the hand work well
