### ISSUE TITLE
Neck yaw joint hardware fault - R1

### ISSUE THREAD

**Issue by DatSpace** [robotology/icub-tech-support#1242]
### Device name 🤖

R1SN003

### Request/Failure description

When the robot yaw joint of the neck moves from left to right we get HW fault.

### Detailed context

It can be easily replicated with yarpmotogui. The neck yaw joint can freely move from right to left, but when told to move from left to right it always goes to hw fault. We tried several degrees and it keeps failing. Moving the head while in fault manually back from right to left, and pressing idle on the gui seems to get the joint out of fault. But only from right to left.

**Comment by emilianob80** [comment]
Two neck AEA2 sensor wires were broken. They have been restored. Now the neck works regularly
