### ISSUE TITLE
100th support request

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1246]
### Device name 🤖

iCubGenova09, iCubGenova04, iCubGenova02, iCubGenova05

### Request/Failure description

Well, I guess I just need to say thank you for all the support though-out all the years!

cc  @Fabrizio69 @maggia80  @Uboldi80 @gsisinna @GiacomoVassallo13 @emilianob80 @gandoo @davidetome @MrAndrea @julijenv @violadelbono, @DanielePucci , and all the others!

### Detailed context

At least, for this time, I did not break anything

**Comment by Uboldi80** [comment]
Thanks a lot @S-Dafarra !

**Comment by DanielePucci** [comment]
Top!
