### ISSUE TITLE
iCubGenova01 - Left thumb proximal is very loose

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1247]
### Device name 🤖

iCubGenova01

### Request/Failure description

The left thumb proximal is very loose and it is thereby difficult to perform grasp actions as the thumb cannot counteract the force exerted by the index and middle fingers.

We verified together with @Uboldi80 that we might need to tighten it a bit.

**Comment by Uboldi80** [comment]
me and @gsisinna fixed the tendon and we tested the robot.

**Comment by xEnVrE** [comment]
Thank you so much @Uboldi80 @gsisinna
