### ISSUE TITLE
iCubGenova01 - right hand does not calibrate

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1249]
### Device name 🤖

iCubGenova01

### Request/Failure description

The right hand does not calibrate, i.e. the robot calibrates all the joints of the right arm except from the 7-th onwards. After the startup these joints are in hardware fault.

Together with @Uboldi80 we have noticed that during the calibration the LED showing the CAN comm. activity of the board of the right hand switches off indicating that this might depend on the cable connecting the associated board with the robot.

**Comment by Uboldi80** [comment]
I have restored the connector of the CAN line directed to the MAI.
we tested the setup and it works.
to be safe I put some glue on the connector itself.

**Comment by xEnVrE** [comment]
Thank you @Uboldi80
