### ISSUE TITLE
iCubGenova01 - Right pinky broken

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1253]
### Device name 🤖

iCubGenova01

### Request/Failure description

The ring and little fingers broke up during the calibration procedure.

### Detailed context

The ring and little fingers broke up during the calibration procedure. Specifically, I heard the typical noise of the cable while it breaks. However I could not verify visually where the damage occured. At the moment, the right pinky joint cannot be actuated from the `yarpmotorgui`.

**Comment by gsisinna** [comment]
The repair was carried out by @GiacomoVassallo13 and I recalibrated the joint in question.
