### ISSUE TITLE
iCubLyon/Dijon power connection and startup

### ISSUE THREAD

**Issue by pfdominey** [robotology/icub-tech-support#1254]
### Device name 🤖

iCubLyon01

### Request/Failure description

iCub has just returned from getting fixed up in Genoa.  We no longer use the iKart, and so the power/internet/redbutton/greenswitches connections are different.  Just want to find out the correct connection procedure before startup.

### Detailed context

I attach a photo of the iCub external power connector, and the two power supplies in the rack.
Will I need to take the power supplies out of the rack and connect the power cables?
Please let me know, and send an photos, guides, videos etc.
This will be like the original connection in 2009 before the iKart?
Thanks!  :)
cheers
Peter
![20211207_172900](https://user-images.githubusercontent.com/32130758/145069028-9281afec-3359-4045-8087-5d2541ff23db.jpg)
![20211207_173055](https://user-images.githubusercontent.com/32130758/145069036-fbaed5c9-adc6-45d9-997a-ddcfac36f26d.jpg)

**Comment by pfdominey** [comment]
I also sent an email to Paolo.Uboldi@iit.it related to this.  Thanks.

**Comment by pfdominey** [comment]
Woops!  Sorry - I did not look closely enough in the rack box!  I see the additional red switch, green switches etc.  So then do I just connect the fat cable labeled iCubLione directly to the robot and the power supply
![20211207_174048](https://user-images.githubusercontent.com/32130758/145070586-24a20523-bdc9-4279-85be-2f6af7072e65.jpg)
?

**Comment by gsisinna** [comment]
We did a videocall this morning to provide the necessary support and get iCubDijon01 up and running at his lab.

cc @Uboldi80
