### ISSUE TITLE
iCubGenova04 - hardware checkup, in particular for tendons

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1256]
### Device name 🤖

iCubGenova04

### Request/Failure description

I would like to perform a very quick hardware checkup of `iCubGenova04`  (aka, iRonCub) after the long experimental campaign, and before stopping for the Christmas holiday.

### Detailed context

In particular I would like to verify the status of the tendons and other parts to spot possible damages due to the high temperature and stress on the robot.

### Additional context

The robot is already prepared for the checkup (jetpack removed)

**Comment by GiacomoVassallo13** [comment]
Ciao @gabrielenava l intervento è stato eseguito. Attuamlente i giochi sono stati ridotti. per azzerarli serve richiedere un intervento apposta. Procedo con la chiusura della issue.
cc: @Uboldi80 @gsisinna @Fabrizio69
