### ISSUE TITLE
Left wrist yaw tendon broken

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1257]
### Device name 🤖

iCubGenova09

### Request/Failure description

The tendon of the left wrist yaw is broken

### Detailed context

During an intensive test session with the robot manipulating on the table, we broke the right yaw tendon

**Comment by GiacomoVassallo13** [comment]
@S-Dafarra il polso di del robot è stato ripristinato. Procedo con la chiusura della issue
cc: @Uboldi80 @Fabrizio69
