### ISSUE TITLE
iCubGenova09 Hand middle_proximal joint does not work 

### ISSUE THREAD

**Issue by kouroshD** [robotology/icub-tech-support#1259]
### Device name 🤖

iCubGenova09

### Request/Failure description

- The robot right hand `r_middle_proximal` axis does not follow the given command. More precisely the tracking is poor and it cannot reach more than `45 deg` while it should have range of motion with uper-bound of `90 degs`.  
The control has been done in this through `yarp-motor-gui` and with position control.

- Instead, the `l_middle_proximal` does not reach its whole range of motion.
 
### Detailed context

The following video shows the robot behavior:

https://user-images.githubusercontent.com/17707730/146176186-6081ae8e-ed29-440a-bfaf-7332a09d9ece.mp4

cc @DanielePucci  @S-Dafarra

**Comment by Uboldi80** [comment]
i have calibrate I calibrated both proximal mids
the situation seems to me to have definitely improved.
now the range of motion has increased a lot.
