### ISSUE TITLE
[iCubGenova04] A cable is damaged inside the robot head

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1263]
### Device name 🤖

iCubGenova04

### Request/Failure description

We noticed that there is a damaged cable inside the robot head. Would it be possible to fix/replace it?

### Detailed context

![](https://i.imgur.com/gf3d16r.jpg)

### Additional context

It is not urgent (the robot works fine for now) and the robot is still on the roof, I opened the issue to notify this problem but working on it on January is fine to me.

cc
@Uboldi80 @Fabrizio69

**Comment by gabrielenava** [comment]
hello, would it be possible to schedule this fix in the next days of the week? The robot is currently not connected to the crane and we can bring it down, I think this will simplify a lot the fixing procedures

**Comment by Uboldi80** [comment]
could you bring me the setup for Wednesday?

**Comment by gabrielenava** [comment]
>could you bring me the setup for Wednesday?

sure!

**Comment by emilianob80** [comment]
@gabrielenava The cable was shortened and repaired using self-agglomerating tape and braiding

![IMG_20220121_120609](https://user-images.githubusercontent.com/53729815/150517103-2d122951-4968-459f-84ef-530d794a77cd.jpg)
![IMG_20220121_120606](https://user-images.githubusercontent.com/53729815/150517111-6d87282a-2296-4fa9-bd53-e79afe66edf3.jpg)


CC: @Uboldi80 @Fabrizio69
