### ISSUE TITLE
The `l_hand_finger` and `r_hand_finger` axis of iCubGenova09 are almost always in HW fault 

### ISSUE THREAD

**Issue by kouroshD** [robotology/icub-tech-support#1265]
### Device name 🤖

iCubGenova09 

### Request/Failure description

We are interested to use the `l_hand_finger` and `r_hand_finger` axes of the iCubGenova09, but they are in HW fault. 

### Detailed context

In order to enhance the manipulation capabilities of the robot, in order to perform in-hand manipulation, we are interested to use the `l_hand_finger` and `r_hand_finger` axes of the robot. Those are specially important when we want to rotate an object in hand using the thumb and index or middle fingers, which humans tend to do it naturally as well.
However, those axes are almost always in HW fault. 

cc @DanielePucci @S-Dafarra

**Comment by Uboldi80** [comment]
Both the joint 7 are calibrated and the value committed.

![1640337701329](https://user-images.githubusercontent.com/80786976/147339887-02b13bba-a5ce-4d96-9f76-75d7db11add7.jpg)
![1640337701340](https://user-images.githubusercontent.com/80786976/147339897-a31ad1db-ba39-4470-9c4d-87faaa047446.jpg)
