### ISSUE TITLE
[iCubErzelli01] Issue with the board torso-eb5-j0_2

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1266]
### Device name 🤖

iCubErzelli01

### Request/Failure description

The robot does not even start calibrating. 

### Detailed context

The issue seems related to broken connections with the board of the torso.

### Additional context

[log_icub-head_yarprobotinterface_1528.txt](https://github.com/robotology/icub-tech-support/files/7779595/log_icub-head_yarprobotinterface_1528.txt)

**Comment by maggia80** [comment]
@ddetommaso I added Gabriele Sisinna. I think it could an issue related to some disconnection. If you are in the lab could you run the _FirmwareUpdater_ to see which boards are not visible in the ETH network?

**Comment by ddetommaso** [comment]
@maggia80 I can confirm that from FirmwareUpdater the board torso-eb5 (10.0.1.5) is not visible.

**Comment by maggia80** [comment]
@ddetommaso is the only one that is not visible?
Or also the 10.0.1.6 ... are not visible?

https://icub-tech-iit.github.io/documentation/icub_wiring/icub2_x/#ethernet-backbone

**Comment by ddetommaso** [comment]
@maggia80 this is the current situation
![ethloader](https://user-images.githubusercontent.com/3440640/147692285-9dbb6312-85f4-4b4d-95c1-d29759916a3c.jpg)

**Comment by maggia80** [comment]
![Screenshot_20211230_052448.jpg](https://user-images.githubusercontent.com/6987330/147721634-7cb20ec5-f4cb-47a8-962a-d796aaaaba6b.jpg)

Ok so the issue is in the right arm. None of the cards of the right arm are visible

**Comment by Uboldi80** [comment]
We solved the problem with the right arm:

the power connectors were fused
probably the connections between the crimp and the cables had gone loose causing an arc and overheating the connector part.
we therefore replaced the 3 connectors on the MC4 PLUS and redone the power supply wiring.

**Comment by gsisinna** [comment]
> We solved the problem with the right arm:
> 
> the power connectors were fused probably the connections between the crimp and the cables had gone loose causing an arc and overheating the connector part. we therefore replaced the 3 connectors on the MC4 PLUS and redone the power supply wiring.

Some pics of the broken connector:
![photo1641396613](https://user-images.githubusercontent.com/36999962/148243912-d74b6c6f-eec5-4a24-a075-b3ff60648604.jpeg)
![photo1641396613 (1)](https://user-images.githubusercontent.com/36999962/148243918-9c4d2e89-67e6-4aca-987e-80f9a54a9611.jpeg)
![photo1641396613 (2)](https://user-images.githubusercontent.com/36999962/148243920-c5815037-92b2-4a83-adc2-37a902eb6ae1.jpeg)
