### ISSUE TITLE
iCubErzelli01 - EB11 (MS4) right leg overheating

### ISSUE THREAD

**Issue by gsisinna** [robotology/icub-tech-support#1271]
### Device name 🤖 ###
iCubErzelli01

### Request/Failure description
We noticed that some right leg MTB boards are not working. The problem is the MS4 (EB11) that goes into overheating.

### Detailed context
It is necessary to replace the board in question with a new one

**Comment by gsisinna** [comment]
cc @ddetommaso

**Comment by Uboldi80** [comment]
we have to change an EMS4 board from the right but we standing @ddetommaso to schedule the intervention after the the experiment.

**Comment by Uboldi80** [comment]
as legs are not used at the moment we will not proceed with the replacement of the EB11 on the right leg.
