### ISSUE TITLE
Some fingertip skins of left and right hands of the iCubGenova09 are broken

### ISSUE THREAD

**Issue by kouroshD** [robotology/icub-tech-support#1272]
### Device name 🤖

iCubGenova09 

### Request/Failure description

Some of the fingertip skins of the robot, both on the left and right hand are broken.

### Detailed context

Following the issue in https://github.com/robotology/icub-tech-support/issues/1261, on the 23rd of December all the skins were working.

After that day, we tried the skins on this Tuesday (5th of Jan), some of them were broken again.

### Additional context
The application to check the visual fingertip skin status can be found in https://github.com/robotology/walking-teleoperation/blob/semifinals_testing/app/scripts/XprizeSemifinal2022.xml.
@S-Dafarra @DanielePucci

**Comment by Uboldi80** [comment]
today with @S-Dafarra checked the fingertip broken:

left hand:  pinkie and index
right hand: thumb

**Comment by Uboldi80** [comment]
right thumb fingertip replaced

**Comment by Uboldi80** [comment]
i fixed the L0 and L3 fingertips in the left hand.
