### ISSUE TITLE
Right thumb oppose tendon broken

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1273]
### Device name 🤖

iCubGenova09

### Request/Failure description

During a normal calibration, the tendon snapped on its own.

### Detailed context

The right thumb oppose was moving to the classical position during calibration, and the cable snapped on its own.

cc @pattacini @kouroshD @DanielePucci

**Comment by gsisinna** [comment]
The broken cable was the right thumb proximal. This has been replaced and it will be checked again for calibration once the robot is running.

**Comment by emilianob80** [comment]
After the tendon was replaced by @gsisinna , the arm was reassembled on the robot and rewired in the missing parts.

@S-Dafarra  can you carry out a functional test when you can?

cc @pattacini @kouroshD @DanielePucci @Uboldi80

**Comment by Uboldi80** [comment]
Thanks @emilianob80

**Comment by S-Dafarra** [comment]
> @S-Dafarra can you carry out a functional test when you can?

Yes, sure!

**Comment by Uboldi80** [comment]
the thumb oppose is ok and seems to work well
