### ISSUE TITLE
iCubGenova01 - Wrist pitch AEA cover to be replaced

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1275]
### Device name 🤖

iCubGenova01

### Request/Failure description

As per the title, the cover of the AEA board of the pitch of the right wrist needs to be replaced.

See the picture below:

![image](https://user-images.githubusercontent.com/6014499/148751427-f48fc22f-e227-48ae-a785-b97a1b1fde97.png)

### Detailed context

As per the title, the cover of the AEA board of the pitch of the right wrist needs to be replaced.

See the picture below:

![image](https://user-images.githubusercontent.com/6014499/148751427-f48fc22f-e227-48ae-a785-b97a1b1fde97.png)

**Comment by Uboldi80** [comment]
the cover has been replaced
