### ISSUE TITLE
[iCubErzelli01] General maintenance, robot update and other issues

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1278]
### Device name 🤖

iCubErzelli01

### Request/Failure description

We would need to update the entire robot (head and boards) and ask for support with the other open issues by the end of February.

### Detailed context

- Complete update of the robot head and boards
- Overall tightening of cables, electrical connections and other generic check up
- upgrade os and yarp version

### Additional context

The robot would be available for maintenance between the 14th to the 28th of February.

**Comment by ddetommaso** [comment]
cc @Nicolasr3

**Comment by gsisinna** [comment]
Today, together with @Uboldi80 and @Nicogene, the software (icub-head) of iCubErzelli01 has been completely rebuilt with an installation of the latest version of iCubOS and robotology superbuild. It has been made a configuration of the local network for the icub-head and updated the firmware of the boards that were left in previous versions. The yarprobotinterface is now working with the new installation.

It remains to make the calibration and update the files in robots-configuration.
