### ISSUE TITLE
iCubGenova01 - Calibration of thumb left distal

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1284]
### Device name 🤖

iCubGenova01

### Request/Failure description

As requested by @Uboldi80 in #1255, this issue is for calibrating the thumb left distal.

### Detailed context

As requested by @Uboldi80 in #1255, this issue is for calibrating the thumb left distal.

**Comment by gsisinna** [comment]
The joint has been calibrated and tested today.

cc @Uboldi80 @xEnVrE
