### ISSUE TITLE
iCub3 right eye mechanical issue

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1292]
### Device name 🤖

iCubGenova09

### Request/Failure description

The right eye of iCub3 moves by simply touching it.

### Detailed context

https://user-images.githubusercontent.com/18591940/152164253-389e5076-4720-4516-9a87-6bbc79390683.mp4

cc @gandoo @fbiggi

**Comment by Gandoo** [comment]
![20220202_143543](https://user-images.githubusercontent.com/53341641/152168923-4fcf4586-1b9f-412a-901a-474f7b18d83f.jpg)

![20220202_144048](https://user-images.githubusercontent.com/53341641/152168938-9b7c7696-e14a-4a17-82ee-0469e27d0097.jpg)

eseguito l'intervento, trovato la vite che è caduta, recuperata e fissato il motore all'asta dell'occhio


cc @fbiggi @GiacomoVassallo13 @Uboldi80 @gsisinna @Fabrizio69 @DanielePucci
