### ISSUE TITLE
iCubErzelli02: embedded boards switch on when we switch on the power supply

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-tech-support#1296]
### Device name 🤖

iCubErzelli02

### Request/Failure description

When we switch on the power supply, the boards of both legs switch on also even if the button on the battery pack is red.

### Detailed context

When we press the motor button on the battery pack, then all boards switch on.

**Comment by gsisinna** [comment]
Today we replaced the BDC board and this solved the problem with the legs and the power supply.

cc @Uboldi80 

![photo1644841535](https://user-images.githubusercontent.com/36999962/153864340-2755d47e-8628-46da-8aec-b1441bd7c267.jpeg)
