### ISSUE TITLE
iCubGenova09 torso pitch not calibrating

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1297]
### Device name 🤖

iCubGenova09

### Request/Failure description

The torso pitch joint reamins in not configured status at startup.

### Detailed context

Afer installing the FT58 on the right leg, the torso pitch joint does not start and remains in "Not configured" status.

Here the log 
[log_icub-head_yarprobotinterface_1648_torso_pitch_broken.txt](https://github.com/robotology/icub-tech-support/files/8043510/log_icub-head_yarprobotinterface_1648_torso_pitch_broken.txt)

cc @davidetome @Gandoo @pattacini

**Comment by emilianob80** [comment]
@S-Dafarra tomorrow morning as soon as I arrive I do a check of the electrical wiring

cc: @davidetome @pattacini @Fabrizio69

**Comment by S-Dafarra** [comment]
Awesome, thanks!

**Comment by emilianob80** [comment]
After checking the wiring, I didn't encounter any problems. @S-Dafarra  when you arrive can we do a test together please?

**Comment by S-Dafarra** [comment]
Yes sure!

**Comment by emilianob80** [comment]
@S-Dafarra The robot has been tested with @gsisinna  and works correctly

cc: @davidetome @Fabrizio69  @Gandoo @pattacini

**Comment by S-Dafarra** [comment]
Thanks! Just for future reference, what was the problem? The log didn't seem to be very informative

**Comment by gsisinna** [comment]
@S-Dafarra probably just a badly inserted connector. All the joints are calibrated (green) in the yarpmotorgui.

**Comment by S-Dafarra** [comment]
> @S-Dafarra probably just a badly inserted connector. All the joints are calibrated (green) in the yarpmotorgui.

Talking also with @emilianob80, we assume that the problem was in the CAN connector of the corresponding 2FOC
