### ISSUE TITLE
iCubGenova09 Strain timeouts

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1299]
### Device name 🤖

iCubGenova09

### Request/Failure description

We often notice that since startup we have a lot of errors regarding strain timeout. But lately we noticed that the ankles may go in HF when in compliant because of timeout in the feedback. I wonder if this could be related.

### Detailed context

Here the log 
[log_icub-head_yarprobotinterface_1452_strain_timeout.txt](https://github.com/robotology/icub-tech-support/files/8049989/log_icub-head_yarprobotinterface_1452_strain_timeout.txt)

Often, it is enough to reboot the motors (maybe a couple of times), but still it would be interesting to understand why this is happening.

cc @GiulioRomualdi @isorrentino @pattacini @DanielePucci @traversaro

**Comment by marcoaccame** [comment]
Following the examination of the log [log_icub-head_yarprobotinterface_1452_strain_timeout.txt](https://github.com/robotology/icub-tech-support/files/8049989/log_icub-head_yarprobotinterface_1452_strain_timeout.txt) in https://github.com/robotology/icub-tech-support/issues/1299, I have spotted a failure in reading encoders of type `absnalog` used for joints 7 and 8 in both arms.

```
11,439618 <ERROR>  from BOARD 10.0.1.24 (left_arm-eb24-j4_7), src LOCAL, adr 0, time 150s 851m 386u:
(code 0x05000016, par16 0x4008 par64 0xfffffffff000500f) -> CFG: EOtheEncodeerReader cannot be configured:
verification fails. p16&0xf000: number of joint; primary encs: 
failure mask in p16&0x000f and errorcodes in p64&0x0000ffff; secondary encs: 
failure mask in p16&0x00f0 and errorcodes in p64&0xffff0000 + .

```

 **Listing**. One of the four error logs related to failure of reading the `absanalog` encoder. 

The boards managing the encoder are of type `mc4plus` w/ binary ver 3.47 released in [here](https://github.com/robotology/icub-firmware-build/pull/47). 

I believe that the previously used version 103.45 (see PR in [here](https://github.com/robotology/icub-firmware-build/pull/45)) did not have the problem.

I would check if both version 103.45 and 3.45 really work correctly and then look for possible regression bugs.

**Comment by marcoaccame** [comment]
> Following the examination of the log [log_icub-head_yarprobotinterface_1452_strain_timeout.txt](https://github.com/robotology/icub-tech-support/files/8049989/log_icub-head_yarprobotinterface_1452_strain_timeout.txt) in #1299, I have spotted a failure in reading encoders of type `absnalog` used for joints 7 and 8 in both arms.
> 
> ```
> 11,439618 <ERROR>  from BOARD 10.0.1.24 (left_arm-eb24-j4_7), src LOCAL, adr 0, time 150s 851m 386u:
> (code 0x05000016, par16 0x4008 par64 0xfffffffff000500f) -> CFG: EOtheEncodeerReader cannot be configured:
> verification fails. p16&0xf000: number of joint; primary encs: 
> failure mask in p16&0x000f and errorcodes in p64&0x0000ffff; secondary encs: 
> failure mask in p16&0x00f0 and errorcodes in p64&0xffff0000 + .
> ```
> 
> **Listing**. One of the four error logs related to failure of reading the `absanalog` encoder.
> 
> The boards managing the encoder are of type `mc4plus` w/ binary ver 3.47 released in [here](https://github.com/robotology/icub-firmware-build/pull/47).
> 
> I believe that the previously used version 103.45 (see PR in [here](https://github.com/robotology/icub-firmware-build/pull/45)) did not have the problem.
> 
> I would check if both versions 103.45 and 3.45 really work correctly and then look for possible regression bugs.

Thanks to @isorrentino we have a fresh [log_icub-head_yarprobotinterface_4475.txt](https://github.com/robotology/icub-tech-support/files/8072182/log_icub-head_yarprobotinterface_4475.txt)  from `iCubGenova09`.

According to this log **there is no failure in reading the encoders**, so it cannot be a regression bugs. 
.

**Comment by Uboldi80** [comment]
About 2 weeks ago the FTs on the arms were replaced: from strain 1 to strain 2
Following this replacement, has the existing problem been solved or does it persist?
https://github.com/icub-tech-iit/proto/issues/1535

**Comment by pattacini** [comment]
Hi @Uboldi80 

The idea here is to wait for a SW development underway, which will help us collect more information.

**Comment by pattacini** [comment]
Hi @S-Dafarra 

Currently, @davidetome is upgrading the iCub 3 system with you for using multiple FT sensors connected to a single EMS board. The idea is to start off by enabling the new service for the pair of sensors in the soles.

After the preliminary tests, we will extend the use of the latest multiple FT service to all the FT sensors equipping the robot. This way, we will benefit from augmented diagnostics helping us narrow down the timeout problem.

cc @marcoaccame

**Comment by pattacini** [comment]
All the FT of iCub 3 are now working with the latest diagnostics.

**Comment by S-Dafarra** [comment]
Just FYI, initially the ``rate`` inside the ``CANMONITOR`` group was set to ``20*1000``. This was causing the diagnostic to be printed at a very high rate, saturating the logger. In https://github.com/ami-iit/robots-configuration/commit/374cfc607411bb39990d7132c115028f1f00e547 we changed that value to ``20000`` and fixed the issue. I am not sure if that ``20*1000`` was a typo.

**Comment by pattacini** [comment]
Thanks @S-Dafarra for reporting 👍🏻 

>I am not sure if that 20*1000 was a typo.

cc @davidetome @triccyx @marcoaccame

**Comment by triccyx** [comment]
Yes, you are right @S-Dafarra .

**Comment by pattacini** [comment]
Fixed the main doc via https://github.com/robotology/icub-main/commit/acec2b6af4298203e2616891bd4ff87b6d5dcb0a.

**Comment by pattacini** [comment]
FYI

`20000` does represent an update time of 20 seconds (thus the value is given in `ms`).

**Comment by pattacini** [comment]
Units made more explicit via https://github.com/robotology/icub-main/pull/807.

**Comment by gsisinna** [comment]
@pattacini if the issue has been solved can we close it?

**Comment by pattacini** [comment]
Strictly speaking, we just made available some more info to debug the timeout problem.
Don't know the status though or if they had the chance to inspect it further.

At any rate, if @S-Dafarra agrees, we can close this issue anyway as we can always open it up again if something related needs to be reported.

**Comment by S-Dafarra** [comment]
Judging from the log in https://github.com/robotology/icub-tech-support/issues/1195#issuecomment-1238243755 it seems that no error appeared!

**Comment by pattacini** [comment]
> Judging from the log in [#1195 (comment)](https://github.com/robotology/icub-tech-support/issues/1195#issuecomment-1238243755) it seems that no error appeared!

Cool 👍🏻 
I'd close the issue then.
Feel free to open it up again if needed.
