### ISSUE TITLE
iCub neck joint broken 

### ISSUE THREAD

**Issue by lunagava** [robotology/icub-tech-support#1302]
### Device name 🤖

iCub[Genova][02]

### Request/Failure description

A tendon near neck joints is broken, probably due to the weight exerted by the camera on icub head fixed with the helmet.  

### Detailed context

I ask you to fix it as soon as possible because I need for doing experiments for a deadline in few days. Thanks in advance for the help.  

### Additional context

![Uploading IMG_4473.jpg…]()

**Comment by Uboldi80** [comment]
Today me and @GiacomoVassallo13 replaced the B tendon in the neck.
should be ok.
@lunagava  please can you give me a feedback?

**Comment by Uboldi80** [comment]
After some tests the neck seems to work fine!
