### ISSUE TITLE
iCubGenova09 left hip pitch AMO connector broken

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1303]
### Device name 🤖

iCubGenova09

### Request/Failure description

The connector of the left hip pitch AMO sensor is broken

### Detailed context

We noticed that the left hip pitch is often miscalibrated. By checking the connector @Uboldi80 and @emilianob80 noticed that the connector is broken

**Comment by Uboldi80** [comment]
The cables blue and green in LS0 was demaged.
I have shortened the cable and replaced the connector.

![1645105339061](https://user-images.githubusercontent.com/80786976/154494200-e9c325f4-fcd1-4e04-8799-677ce33416e2.jpg)
