### ISSUE TITLE
The right thumb proximal has delays while moving

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1304]
### Device name 🤖

iCubGenova09

### Request/Failure description

When trying to move the right thumb proximal we can hear the motor moving, but the joint does not move for a while.

### Detailed context

Discussing with @Uboldi80 and @gsisinna, it seems that the problem is the cable that might be a bit loose.

**Comment by Uboldi80** [comment]
after a first analysis I noticed that the proximal thumb cable had been completely rewound on the pulley of the motor itself.
I untangled the cable and put it back in place.
this problem occurs after a certain use on demanding holds, as the 1.6mm grains on the phalanx tend to relax and leave the tendon free.
After resetting the routing, I replaced the hall sensor cover on the wrist code: 4682.A1
