### ISSUE TITLE
Right index and right middle fingertip not working

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1305]
### Device name 🤖

iCubGenova09

### Request/Failure description

The right index and right middle fingertip skin is not working.

### Detailed context

The right index skin is blinking, while the right middle finger seems not working at all.

**Comment by gsisinna** [comment]
I replaced an R0 fingertip, soldered two cables, and now they work. Try them out and give feedback please.

I have noticed that during the calibration procedure, based on the starting position, the thumb may conflict with the leg cover. This should be avoided for the safeguard of the fingertips which are very delicate.

cc @Uboldi80

**Comment by S-Dafarra** [comment]
Today we tried them. The middle is working fine, but the index is very sensitive. The slightest touch seems enough to make it saturate. Then, it takes a while for it to "discharge"

**Comment by Uboldi80** [comment]
i close this one in favour of: 
 https://github.com/robotology/icub-tech-support/issues/1318
