### ISSUE TITLE
IMU sensors in iCub head

### ISSUE THREAD

**Issue by GiuliaScorzaAzzara** [robotology/icub-tech-support#1306]
### Device name 🤖

iCubGenova03 SN.020

### Request/Failure description

The MTX inertial box (http://wiki.icub.org/wiki/Inertial_sensing) in iCub head is not working. 

### Detailed context

We opened the head to verify the wire connections and everything seemed to be connected in the proper way, but when starting the robot the inertial sensors in the head did not respond.

**Comment by Uboldi80** [comment]
Hy @GiuliaScorzaAzzara 
Tomorrow I will be in Erzelli for an intervention on another robot.
I should still have time to take a look at yours.

**Comment by Uboldi80** [comment]
Hy @GiuliaScorzaAzzara, I have the spare part.
I think next Wednesday 2/03/22 i can try to change it to fix the problem.

**Comment by gsisinna** [comment]
Today we replaced the MTx intertial box and we fixed also a wrong pinout on the PC104:
![immagine](https://user-images.githubusercontent.com/36999962/155703607-e02895cb-1467-45ef-902c-2d982474fd02.png)

After this intervention it is possible to read the values with yarp from the /icub/interial port:
![immagine](https://user-images.githubusercontent.com/36999962/155703840-96fc559f-13ac-4af3-b51f-85259f93780b.png)

Here some test plots for the Euler angles:
![plot](https://user-images.githubusercontent.com/36999962/155703903-0236b89a-7bd7-4f7c-8f2f-7f76546aeb1b.png)

As requested by team members we also fixed a skin patch:
![WhatsApp Image 2022-02-25 at 11 49 25](https://user-images.githubusercontent.com/36999962/155704244-7d9b0432-799a-4e3d-a406-e907a77705b9.jpeg)

I would like to thank the team of the laboratory for the collaboration that was essential to identify the problem immediately, and lead to its resolution.

Closing this issue.

cc @Uboldi80 @Fabrizio69 @GiuliaScorzaAzzara
