### ISSUE TITLE
[iCubGenova08] General maintenance 

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1309]
### Device name 🤖

iCubGenova08

### Request/Failure description

We would need to schedule an intervention for maintenance of the robot.

### Detailed context

Overall tightening of cables, electrical connections and other generic check up

**Comment by gsisinna** [comment]
Today we tested the setup and with @Uboldi80 we checked the following parts/modules:

- Finger movements, properly closing and opening verified
- General grasping performance related to customized cube test
- Torso (calibration)
- Cameras opened correctly with yarpdev and yarpview
- Head inertial values correctly read
- Face expressions (cycle of all expressions and colors)
- All neck tendons are tightened

The startup calibration speed was increased for the torso, as requested by @Nicolasr3, and the neck was moved in a loop to verify correct functioning.

The robot appears to be in an optimal state, and no severe problems or malfunctions were found during preventive maintenance. 

Pull request sent to update calibration files.

cc @ddetommaso @Fabrizio69
