### ISSUE TITLE
iCubGenova04 preparation for wind tunnel experiments

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1310]
### Device name 🤖

iCubGenova04

## Description

We would need support from icub-tech for the iRonCub wind tunnel experiments that will occur on **March 21st** at **Politecnico di Milano**.

### Description of the activity

- the robot will be placed on a pole inside the wind tunnel;
- with some sensors installed on the robot covers and with a scale, we will measure the  pressure distribution and aerodynamic forces on the robot at different wind speed;
- the robot will move the joints in different configurations in position control.

### Support request 

1) **Week 7 March - 11 March**:  we would need to schedule 1 day of maintenance for the iRonCub robot. We didn't notice specific issues on the robot so far, besides the usual shoulder and elbow wires a bit loose. If possible, it would be better to schedule the maintenance in the first days of the week (e.g. 7th March would be perfect). We also need to change the robot covers from the green ones to a 3d printed version we prepared for the wind tunnel.

2)  **Week 14 March - 18 March**:  we will be at Polimi and work with two technicians from wind tunnel to add the necessary sensors to the covers. Here, I think that the minimum support we need would be to that someone from icub-tech support remains available to  travel 1 day to Milan in case of emergency, for example if a tendon breaks or if there is a faulty cable. Best solution would be that someone from icub-tech can come to Milan with us for the full week / half week.

3) **21st March - 22nd March:** the robot will perfrom the experiment. It would be better if someone from icub-tech can travel to Milan in these days in case of issues during the experiments.

### Additional context

cc @Fabrizio69 @maggia80

**Comment by pattacini** [comment]
Hi @gabrielenava 

This is not the right place for such a request.
Could you open up instead a ticket into our internal workflow?

Thanks!
