### ISSUE TITLE
Frequent MAIS timeout on left arm cause the index finger to go to hardware fault

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1311]
### Device name 🤖

iCubGenova09

### Request/Failure description

During a recent experiment we noticed that there are frequent timeouts on one of the left arm MAIS.

### Detailed context

Unfortunately, I lost the log of it and I am not sure if it was the proximal or the distal, but it was surely the left index.

**Comment by Uboldi80** [comment]
I have checked the CAN line of the left arm up to the CORN but unfortunately I have not found the problem that has been encountered.
I still leave the issue open to verify that it does not happen again.
