### ISSUE TITLE
[iCubErzelli01] Right hand finger not working properly

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1314]
### Device name 🤖

iCubErzelli01

### Request/Failure description

From yarpmotorgui the joint 7 of the right arm does not change position on demand.

### Detailed context

The initial calibration goes well and from yarpmotorgui the motor of joint 7 looks fine, not in hardware faul
[log_icub-head_yarprobotinterface_2511.txt](https://github.com/robotology/icub-tech-support/files/8154522/log_icub-head_yarprobotinterface_2511.txt)
t

**Comment by gsisinna** [comment]
The joint 7 has been calibrated and now it's working properly.

Yarpmotorgui for the right arm (all green):
![Screenshot from 2022-03-03 12-09-31](https://user-images.githubusercontent.com/36999962/156554168-63311a09-b907-4ae5-897d-0dadbe2f4e9f.png)

cc @ddetommaso @Uboldi80
