### ISSUE TITLE
iCubErzelli02: Shutting down of the robot after a small electrical shock

### ISSUE THREAD

**Issue by lauracavaliere** [robotology/icub-tech-support#1315]
### Device name 🤖

iCubErzelli02

### Request/Failure description

The robot shut down by itself after a small electrical shock.

### Detailed context

 While I was going to press the motor button to shut down the robot, I got a small electric shock and the robot turned off (both motor and CPU buttons turned red), without really pushing the button.

**Comment by Uboldi80** [comment]
Both yesterday and today I verified that the robot worked regularly.
at this moment it is switched on and working regularly.
In all probability it was an electrostatic discharge.
