### ISSUE TITLE
[iCubGenova03] - left thumb distal tendon and fingertip

### ISSUE THREAD

**Issue by lindalastrico** [robotology/icub-tech-support#1319]
### **Device name 🤖**
iCubGenova03

### **Request/Failure description**
The left thumb tendon broke and the fingertip is not working

cc: @GiuliaScorzaAzzara 

### **Additional context**

**Comment by Uboldi80** [comment]
As we discuss today, we cannot operate to fix this problems in the 16 March.
We need to replace a L0 fingertip and thumb distal 2391 cable.

**Comment by Uboldi80** [comment]
Wednesday, March 30th we will be with you for the resolution of the problems described above.

cc. @GiuliaScorzaAzzara

**Comment by gsisinna** [comment]
Today we restored the distal thumb tendon and the fingertip.

We found another problem with the skin of the right palm and therefore it will be necessary to schedule the next session with the researchers and prepare the necessary components.

cc @Uboldi @reafrancesco @GiuliaScorzaAzzara
