### ISSUE TITLE
Several CRC errors from the torso board and CAN issue on left arm

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1321]
### Device name 🤖

iCubGenova09

### Request/Failure description

Today we noticed a very high number of CRC errors coming from the robot torso. In addition, at a certain point we lost the left arm and we were not able to recover it. The motorgui did not show any error code

### Detailed context

It happened three times today that a certain point the robot stops being responsive and after a while we loose the left shoulder. By checking the logs we noticed a high number of CRC errors and some issues with the CAN of the left arm.

Here a log with both CRC and CAN errors
[log_icub-head_yarprobotinterface_6967_ehsan_left_arm_failure.txt](https://github.com/robotology/icub-tech-support/files/8234397/log_icub-head_yarprobotinterface_6967_ehsan_left_arm_failure.txt)

This happened kind of in a bad moment as on Monday we will have a demo

cc @Uboldi80 @gsisinna @pattacini @emilianob80 @Fabrizio69 @DanielePucci @prashanthr05 @kouroshD  @lrapetti @EhsanRanjbari

### Additional context

Here some previous logs where we also had major issues, but they were also saturated
[log_icub-head_yarprobotinterface_1456_ehsan_failure2.txt](https://github.com/robotology/icub-tech-support/files/8234404/log_icub-head_yarprobotinterface_1456_ehsan_failure2.txt)
[log_icub-head_yarprobotinterface_6649_Ehsan_failure.txt](https://github.com/robotology/icub-tech-support/files/8234406/log_icub-head_yarprobotinterface_6649_Ehsan_failure.txt)

**Comment by emilianob80** [comment]
@S-Dafarra This morning the electrical wiring of the torso and left shoulder were checked. In the torso the junction on the eth E5 line has been removed and the cable re-crimped. On the left shoulder the entire CAN cable that connects the EMS4 (EB1) electronic board with the 2FOC (1B0) electronic board has been replaced.
At the end, the function test was carried out and everything is ok. Thanks @gsisinna  and @Uboldi80 for the support


cc: @Fabrizio69
