### ISSUE TITLE
Left wrist loose

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1323]
### Device name 🤖

iCubGenova09

### Request/Failure description

The tendons of the left wrist seem loose

### Detailed context

https://user-images.githubusercontent.com/18591940/158247373-477e514c-6606-44f9-8eee-06fc3029b1f2.mp4

https://user-images.githubusercontent.com/18591940/158247371-6a7d5bfb-c31b-4862-a2e4-fc5d30ed5a10.mp4

**Comment by Uboldi80** [comment]
Me and @gsisinna have tightened the left wrist and we tested with @kouroshD
