### ISSUE TITLE
Right thumb oppose cable is tearing

### ISSUE THREAD

**Issue by kouroshD** [robotology/icub-tech-support#1324]
### Device name 🤖

iCubGenova09 

### Request/Failure description

There are a number of problems, however important, with the iCubGenova09 hands: 
### Detailed context

The right thumb oppose cable of the robot `iCubGenova09` is going to tear.
- Right thumb oppose cable is tearing: right thumb oppose cable of the robot `iCubGenova09` is going to tear. This has been confirmed by @Uboldi80.As a result, the performance of tracking is degraded as well.
-  The r_hand_finger axis is too close, as a result when calibrating at the startup of the yarprobotinterface, the fingers touch each other. This is partially a result of the added glove cover as well. However, this can be avoided if the fingers are opened, similarly to the left hand finger.
- l_middle_proximal and l_middle_distal axes cables are probably are not tight enough, such that the combined error on on those axes are high.
- 
cc @DanielePucci  @S-Dafarra 

### Additional context
![Screenshot from 2022-03-15 11-31-36](https://user-images.githubusercontent.com/17707730/158359386-ecf21eed-e4ee-44a7-983d-9feda3cfc6a9.png)
![Screenshot from 2022-03-15 11-31-41](https://user-images.githubusercontent.com/17707730/158359391-4fb02007-fd64-4de8-a654-47db2e11a0ea.png)
![Screenshot from 2022-03-15 11-32-00](https://user-images.githubusercontent.com/17707730/158359392-fd9732a7-cf26-42db-852b-5136ddefe419.png)

_No response_

**Comment by gsisinna** [comment]
Tomorrow is the robot available? We can replace the thumb oppose tendon and do a general check.

@kouroshD 

cc @Fabrizio69 @GiacomoVassallo13 @Uboldi80

**Comment by kouroshD** [comment]
> Tomorrow is the robot available? We can replace the thumb oppose tendon and do a general check.
We discussed this with @S-Dafarra , Thursday is a better choice for us.

**Comment by kouroshD** [comment]
> We discussed this with @S-Dafarra , Thursday is a better choice for us.

please coordinate this with @S-Dafarra .

**Comment by Uboldi80** [comment]
@GiacomoVassallo13  **replaced the thumb oppose tendon and tight all the others proximal tendons in both hands**.
