### ISSUE TITLE
Right thumb distal broken 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1325]
### Device name 🤖

iCubGenova09

### Request/Failure description

While teleoperating the right thumb distal cable got broken. 

We also noticed that the left thumb cable is loose 

### Detailed context

cc @S-Dafarra @Uboldi80 @DanielePucci

**Comment by Uboldi80** [comment]
after replacing the distal cable we proceeded to recalibrate the joint.
The thumb now calibrates correctly.
