### ISSUE TITLE
Left shoulder roll and pitch goes in Hardware fault

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1327]
### Device name 🤖

iCubGenova09

### Request/Failure description

While teleoperating, the Left shoulder roll and pitch went in HF. We were not able to put the joints in idle but they went directly in HF.

We had to reboot the motors to restore a working configuration

cc @DanielePucci @S-Dafarra @Uboldi80 

### Detailed context

[log_icub-head_yarprobotinterface_6769_crc.txt](https://github.com/robotology/icub-tech-support/files/8254447/log_icub-head_yarprobotinterface_6769_crc.txt)

**Comment by S-Dafarra** [comment]
This seems the same issue of https://github.com/robotology/icub-tech-support/issues/1321

cc @emilianob80 @Fabrizio69

**Comment by S-Dafarra** [comment]
Let me stress that this does not happen at startup, but only after doing some motions with the shoulder

**Comment by emilianob80** [comment]
After checking the wiring, the connectors of the ethernet lines and some CAN cables were redone. The problem is solved
