### ISSUE TITLE
Left wrist yaw encoder issue

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1328]
### Device name 🤖

iCubGenova09

### Request/Failure description

The left wrist yaw encoder measures 4000deg, although it is moving when moving the joint

### Detailed context

![image](https://user-images.githubusercontent.com/18591940/158455219-2d71f9fa-3729-4177-a284-e881da6c7e7a.png)

**Comment by Uboldi80** [comment]
we fixed 2 wiring problems in joints 5 and 6 of the left wrist, one of which was on a solder of a cable of joint 5 EA.
we tested the setup several times and the problem seems to be solved.
