### ISSUE TITLE
iCub neck cable broken due to a sudden harware fault

### ISSUE THREAD

**Issue by lunagava** [robotology/icub-tech-support#1329]
### Device name 🤖

iCub[Genova][02]

### Request/Failure description

I was calibrating the cameras with a tablet in front of iCub, when the robot suddenly fell down. During the fall, one of the neck cables broke, so that the head is no more able to stay still. 

### Detailed context

Since it is the second time it happens due to a sudden hardware fault, I think we have to investigate the problem.  I attach you the log file from the yarplogger 
[log_icub-head_yarprobotinterface_2375.txt](https://github.com/robotology/icub-tech-support/files/8314276/log_icub-head_yarprobotinterface_2375.txt)
 

### Additional context

![IMG_5114](https://user-images.githubusercontent.com/45895918/159233247-5785f91f-208f-474e-ada6-03a58e512a54.jpg)

**Comment by GiacomoVassallo13** [comment]
Hi, the crimp of neck cable had come out of the tensioner. The wiring has been restored correctly and the cables tensioned.
I proceed with the closure of the issue.

cc: @gsisinna @lunagava @Uboldi80 @Fabrizio69
