### ISSUE TITLE
iCubGenova01 - Left hand skin not responding

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1333]
### Device name 🤖

iCubGenova01

### Request/Failure description

The skin of the left hand (palm and fingertips) do not respond when touched.

### Detailed context

The skin of the left hand (palm and fingertips) do not respond when touched.

**Comment by Uboldi80** [comment]
I fixed a lot of short circuit in both hands.
I have tested all the fingertips and seems to work well.
