### ISSUE TITLE
[iCubGenova04] non-critical errors from all boards while position controlled

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1334]
### Device name 🤖

iCubGenova04

### Request/Failure description

During the last experiment the robot remained position controlled on the pole for long time. I was periodically monitoring the logger, and after some time an error appeared on all board. Meanwhile the error, the robot was always position controlled and apparently fine. 

I would like to understand the origin of this error and eventually correct it.

### Detailed context

Here a screenshot of the logger (I didn't find anything better in the robot laptop for now: if I will find it, or I'll manage to reproduce the error, I'll add the full log to the issue)

Here the error description
![ERRORS_WIND_TUNNEL_2](https://user-images.githubusercontent.com/12396934/160408654-8342b364-88bc-4e81-ac77-127df4f9ac4f.png)

As you can see, it happens several time on all boards
![ERRORS_WIND_TUNNEL](https://user-images.githubusercontent.com/12396934/160408638-defb57f4-7772-4810-bc6d-909e87c403b9.png)

**Comment by Uboldi80** [comment]
following verification, the problem no longer occurred
probably the cause could be attributable to a session of many hours in the wind tunnel.
