### ISSUE TITLE
[iCubGenova03] - Short circuit in the right hand wiring

### ISSUE THREAD

**Issue by Uboldi80** [robotology/icub-tech-support#1336]
### Device name 🤖
iCubGenova03

### Request/Failure description

Today we noticed a problem during the setup test.
We found a short circuit inside the cable that connect the FTC BOARD and the MTB in the forearm.

This problem causes spikes when using the right hand skin.

cc. @GiuliaScorzaAzzara   @lindalastrico  @reafrancesco

**Comment by gsisinna** [comment]
Maintenance for iCubGenova03 will be scheduled on **April 13**.

@GiuliaScorzaAzzara let us know if it works for you and your team, thanks!

cc @Uboldi80

**Comment by gsisinna** [comment]
@Uboldi80 replaced the RTP cable patch (right_hand) but we noticed that the whole hand palm skin patch still not working. We're closing this issue and opening an other for the next session.

cc @lindalastrico @GiuliaScorzaAzzara
