### ISSUE TITLE
iCubGenova01 - Left thumb distal moves correctly only in one direction

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1337]
### Device name 🤖

iCubGenova01

### Request/Failure description

After the calibration, the left thumb distal stays in the following configuration:

![image](https://user-images.githubusercontent.com/6014499/161258758-f514c335-9a23-47d5-8b97-e326fa7f54a4.png)

If I try to move it from the `yarpmotorgui` the finger closes but does not open.

**Comment by Uboldi80** [comment]
I noticed that between the curtain and the pulley near the motor there was dirt that tended to rub the cable preventing it from moving freely.
I removed what I found and cleaned out the venue.

**Comment by xEnVrE** [comment]
Thanks @Uboldi80 

Closing as the issue has been solved
