### ISSUE TITLE
Left wrist tendons loose

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1340]
### Device name 🤖

iCubGenova09

### Request/Failure description

During the XPrize semifinals, we noticed that the left wrist is a bit loose.

### Detailed context

In addition, it seems the encoder looses the calibration from time to time

**Comment by gsisinna** [comment]
The wrist has been fixed.  The cables were tensioned and the magnet that was causing the calibration drift was fixed.

See https://github.com/ami-iit/robots-configuration/commit/25afb2d6a4843c732d8c1acb1f1aafeb9eb78d97
