### ISSUE TITLE
[iCubGenova07] - Right thumb broken due to self collision

### ISSUE THREAD

**Issue by GiuliaScorzaAzzara** [robotology/icub-tech-support#1344]
### Device name 🤖

iCubGenova07

### Request/Failure description

During the execution of a demo the robot self collided causing the break of the oppose joint in the right thumb.

### Detailed context

![WhatsApp Image 2022-04-05 at 12 27 57](https://user-images.githubusercontent.com/58737156/161735127-aa46f620-d4a6-4c93-985e-2f2be203fd79.jpeg)

**Comment by gsisinna** [comment]
Hi @GiuliaScorzaAzzara,
we can schedule the maintenance for this issue on Wednesday 13th (this week). 

Is the robot available?

Thanks!

cc @Uboldi80

**Comment by GiuliaScorzaAzzara** [comment]
Hi @gsisinna,
It is available in the morning, thanks! 
See you on wednesday!

**Comment by gsisinna** [comment]
The thumb has been restored and here there are the new configuration files for the right_arm:
[iCubGenova07.zip](https://github.com/robotology/icub-tech-support/files/8480273/iCubGenova07.zip)

I will make a pull request after a general check of the files online that are misaligned with respect to the local ones.

cc @Uboldi80 @GiuliaScorzaAzzara
