### ISSUE TITLE
Index and middle proximal right arm still to check

### ISSUE THREAD

**Issue by lunagava** [robotology/icub-tech-support#1352]
### Device name 🤖

iCub[Genova][02]

### Request/Failure description

Check proximal fingers of the right hand

### Detailed context

During issue #1346, @GiacomoVassallo13 observed that proximal fingers have still some problems to solve.

**Comment by GiacomoVassallo13** [comment]
Hi, the proximal thumb tendon that was twisted by the pulley has been replaced. I took advantage of also tensioning the proximal index and middle fingers which were loose.
I continue with the closure of the issue.


cc: @lunagava @Uboldi80 @gsisinna @Fabrizio69
