### ISSUE TITLE
iCubGenova04 - Right foot FT sensor cable and connection check

### ISSUE THREAD

**Issue by HosameldinMohamed** [robotology/icub-tech-support#1356]
### Device name 🤖

iCubGenova04

### Request/Failure description

There are 2 issues in the connection between the EMS board `EB9` and the FT sensor:

- The first is slight damage to the FT sensor cable. It didn't harm the connection but it is worth checking. Please see the first picture.
- The second is a cut in the connector between the board and FT. Please see the second picture.

### Detailed context

This happened during a balancing test with the robot, where a spike in the `r_ankle_roll` joint was detected. And the robot wasn't able to start after that.

The error on the logger was:

```
[ERROR]  from BOARD 10.0.1.9 (right_leg-eb9-j4_5), src CAN2, adr 0, time 477s 414m 441u: (code 0x00000018, par16 0x320d par64 0x000000000000021c) -> SYS: EOtheCANservice could not add a CAN frame in tx fifo. In par16 there is frame.id and frame.size (in most significant nibble). In par64 there is the frame.data. + .
[ERROR]  from BOARD 10.0.1.9 (right_leg-eb9-j4_5), src CAN2, adr 0, time 477s 417m 126u: (code 0x00000019, par16 0x4001 par64 0x0000000000000000) -> SYS: EOtheCANservice could not tx frames on CAN bus. In par16 there is: on msb the size of txfifo, on lsb a code. + .
[WARNING]  from BOARD 10.0.1.9 (right_leg-eb9-j4_5), src LOCAL, adr 0, time 477s 417m 281u: (code 0x0000000d, par16 0x02d0 par64 0x400102cf02fc01b8) -> SYS: the TX phase of the control loop has last more than wanted. In par16: TX execution time [usec]. In par64: num of tx can2 and can1 frames and latest previous execution times of TX, RX, DO [usec] + .
```

**We can open a dedicated ticket for that if preferred.**

I was checking the damage on the FT cable so I accidentally cut the cable of the connector.

### Cable damaga
![20220421_124545](https://user-images.githubusercontent.com/45564317/164447668-849a3bf7-f2ab-41bf-b94f-c27370c5b99d.jpg)

### Connector
![20220421_125239](https://user-images.githubusercontent.com/45564317/164447684-21656942-fed9-4e75-afe9-84735823ba1e.jpg)

**Comment by gsisinna** [comment]
We fixed and crimped the cables. We tested the setup and everything seems ok!

cc @Uboldi80
