### ISSUE TITLE
Encoder invalid data on right ankle 

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1357]
### Device name 🤖

iCubGenova04

### Request/Failure description

After performing the yoga demo, the right ankle joints went in hardware fault. We checked the logger and there was the following message:

![image](https://user-images.githubusercontent.com/12396934/164507060-bfb036d9-3513-49ff-ba76-016cfde833d0.png)

### Detailed context

here the full logger:

[log_icubgenova04_21-04.txt](https://github.com/robotology/icub-tech-support/files/8532752/log_icubgenova04_21-04.txt)

**Comment by Uboldi80** [comment]
We noticed that the cable 9N2 was demaged and a cable to NEI board for sensor 10T0 was unsoldered.
![MicrosoftTeams-image (19)](https://user-images.githubusercontent.com/80786976/164698553-11b2dd1f-8e30-452a-89af-db6370f876b6.png)
@ emiliano80 took care of restoring the wiring.
The setup has been tested with @gabrielenava  and appears to be working.
