### ISSUE TITLE
Right arm shoulder joints go in hardware fault while moving

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1358]
### Device name 🤖

iCubGenova04

### Request/Failure description

the problem is not so easy to reproduce, but it happens quite often while running the yoga demo.

the only message I saw in the logger refers to communication problems with the board:

```
 926.623695 <ERROR> A 0.250000 sec timeout occured in embObjMotionControl::checkRemoteControlModeStatus(), BOARD right_arm-eb3-j0_3 IP 10.0.1.3, joint 1, current mode: idl, requested: pos
 926.623728 <ERROR> failure of embObjMotionControl::checkRemoteControlModeStatus(j=1, targetmode=pos) for BOARD right_arm-eb3-j0_3 IP 10.0.1.3 after 17 attempts and 0.260479 seconds
 926.623736 <ERROR> setControlModesRaw(const int n_joint, const int *joints, int *modes) could not check with checkRemoteControlModeStatus() for  BOARD right_arm-eb3-j0_3 (IP 10.0.1.3)   joint  1  mode  pos
 926.623743 <ERROR> embObjMotionControl::checkRemoteControlModeStatus(2, 7565168) is unable to check the control mode of BOARD right_arm-eb3-j0_3 IP 10.0.1.3 because it is now in HW_FAULT
 926.633748 <ERROR> embObjMotionControl::checkRemoteControlModeStatus(3, 7565168) is unable to check the control mode of BOARD right_arm-eb3-j0_3 IP 10.0.1.3 because it is now in HW_FAULT

```

### Detailed context

here the full logger, there are also the messages related to #1357 that occurred too

[log_icub-head_yarprobotinterface_3512.txt](https://github.com/robotology/icub-tech-support/files/8533303/log_icub-head_yarprobotinterface_3512.txt)

**Comment by Uboldi80** [comment]
we encountered a problem with the ethernet patch.
@emilianob80  restored the wiring which was also isolated.
the green cable of the eth line touched the sock.
in addition, we have taken steps to fix the right elbow joint as best as possible, which due to vibrations began to oscillate dangerously.

**Comment by HosameldinMohamed** [comment]
Hi @Uboldi80 we are still experiencing issues with the right arm.

It could be a different problem that what was reported in this issue.

This time, the left arm goes to hardware fault from the startup. In the logger there's this error, from the startup..

```
	21.597584	ERROR			unable to complete calibration: joint 0 in 'hw_fault status' inside doneRaw() function

```
