### ISSUE TITLE
[iCubGenova08] Right thumb distal getting loose

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1360]
### Device name 🤖

iCubGenova08

### Request/Failure description

The distal joint of the right thumb is getting loose and very likely it's about to break.

An urgent technical intervention is required as we are in the testing phase in the rehabilitation center.

### Detailed context

Often, the calibration does not complete well because the thumb remains closed. Attached you can find the logs.

### Additional context

![bpico](https://user-images.githubusercontent.com/3440640/165264854-1b345f50-e1f5-4853-b6cc-3a21e3a1203a.jpg)

[bpico_26Apr22.txt](https://github.com/robotology/icub-tech-support/files/8561575/bpico_26Apr22.txt)

**Comment by Uboldi80** [comment]
Hi @ddetommaso.
We could pass by you in Boggiano Pico for Monday 2/05

**Comment by ddetommaso** [comment]
Hi @Uboldi80 

that's perfect! Please let's confirm this.
@Nicolasr3 will be there.

Many thanks,
Davide

**Comment by gsisinna** [comment]
Today we checked all the tendons for the right hand and from a mechanical point of view everything seems ok. We tried with @Nicolasr3 several startups and demos with the cube.

We noticed also that after each demo the joint velocity for the fingers goes to zero, then we think this might be correlated with some difficulties controlling the joints as refereed.

cc @Uboldi80 @ddetommaso
