### ISSUE TITLE
MAIS timeout on left hand

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1361]
### Device name 🤖

iCubGenova09

### Request/Failure description

The left index proximal goes continuously to hardware fault. The logger reported a MAIS timeout.

### Detailed context

There is a MAIS timeout and the left index proximal goes to hardware fault.

**Comment by Uboldi80** [comment]
I have replaced the LTP on the right hand.

**Comment by S-Dafarra** [comment]
> I have replaced the LTP on the right hand.

Was it the left or the right?

**Comment by Uboldi80** [comment]
sorry in the left hand!
