### ISSUE TITLE
Fix FT sensor cable on the iCub3 left arm

### ISSUE THREAD

**Issue by paolo-viceconte** [robotology/icub-tech-support#1362]
### Device name 🤖

iCubGenova09

### Request/Failure description

During https://github.com/ami-iit/lab-events-demos/issues/212, we had issues in starting the robot since the the left-arm FT sensor cable had been damaged by the upper arm cover. 

### Detailed context

Pictures of the damaged cable are available [here](https://github.com/ami-iit/lab-events-demos/issues/212#issuecomment-1111010096).

For the purposes of the demo, the issue was temporary fixed by @gsisinna @Uboldi80. However, it would be useful to implement a more permanent solution for this issue.

**Comment by fbiggi** [comment]
@Uboldi80 sostituito FT 45 S/N 82 CON S/N 92

CC @gandoo @Fabrizio69 @maggia80 


![WhatsApp Image 2022-04-28 at 08 11 19](https://user-images.githubusercontent.com/20420331/165688825-562f1f60-20a9-4aca-9003-46ca5b8dc539.jpeg)





![WhatsApp Image 2022-04-28 at 08 11 18](https://user-images.githubusercontent.com/20420331/165688730-4bb7860c-f330-4793-93d2-19c1d752db1e.jpeg)

**Comment by Uboldi80** [comment]
The FT has been replaced ant tested!
thanks @fbiggi  and @Gandoo!

**Comment by S-Dafarra** [comment]
Just for future reference, here some pictures of the issue taken by @SanderRuijters:

![IMG_20220427_111253](https://user-images.githubusercontent.com/24605789/165529268-b88b0cf3-5262-4400-85ca-5f388bceb7b0.jpg)
![IMG_20220427_111301](https://user-images.githubusercontent.com/24605789/165529293-e940afdb-b244-4f3c-89bf-979f8f5e4ba1.jpg)
![IMG_20220427_111404](https://user-images.githubusercontent.com/24605789/165529307-bc43b11d-a71d-4004-aee5-d7c88c5b8369.jpg)
![IMG_20220427_111435](https://user-images.githubusercontent.com/24605789/165529319-807abc06-5735-43c0-adc8-3420dfbafad4.jpg)
