### ISSUE TITLE
Left leg hip pitch tendon broken

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1365]
### Device name 🤖

iCubGenova04

### Request/Failure description

the left leg hip pitch tendon got broken during an hovering test. 

### Detailed context

the robot was trying to hover, it failed and the leg got damaged. it seems it is the only (visible) damage.

### How does this issue affect my work?

the iRonCub experiments of this week cannot be performed until the robot is repaired.

**Comment by Uboldi80** [comment]
I have replaced the pitch cable.
now it is necessary to test it
