### ISSUE TITLE
Right leg pitch and roll tendons broken

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1368]
### Device name 🤖

iCubgenova04

### Request/Failure description

same as https://github.com/robotology/icub-tech-support/issues/1365, but this time is the right leg hip tendon that broke and not the left. 

### Detailed context

we modified the setup to try avoiding the issue, but we did not succeed. However it seems we understood the reason why it happens: the leg hits the platform on which the robot stands when it looses control during flight. next time we'll try to avoid the robot to hit it.

### How does it affect you?

blocking further iRonCub experiments. 

it affects an upcoming yoga demo for this Friday (cc @DanielePucci)

**Comment by Uboldi80** [comment]
The tendon has been replaced.
