### ISSUE TITLE
iCubErzelli01: right arm thumb distal not configured

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1370]
### Device name 🤖

iCubErzelli01

### Request/Failure description

The calibration of the right arm does not complete properly, because the thumb distal get stuck in a position out of range.

### Detailed context

As shown in the yarpmotorgui the joint 10 remains not configured.

### Additional context

[log_pc104_yarprobotinterface_2437.txt](https://github.com/robotology/icub-tech-support/files/8669019/log_pc104_yarprobotinterface_2437.txt)
![ymg](https://user-images.githubusercontent.com/3440640/167829109-89924937-6768-4151-a83a-c08ac2d6dc37.jpg)

### How does it affect you?

We cannot proceed further for recruiting internal participants for an experiment planned to start on the 16th of May.

**Comment by gsisinna** [comment]
@Uboldi80 replaced the proximal thumb tendon and the system has been tested. Closing.

cc @ddetommaso
