### ISSUE TITLE
General Maintenance of R1 SN003

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-tech-support#1372]
### Device name 🤖

R1SN003

### Request/Failure description

Important:
- check the status of the elbow belt in right arm (repaired during an emergency @fbiggi, but the belt was not tightened)
- check the status of the left wrist (broken)

Optional:
- check the status of the neck belt (not tightened)
- check the status of both the hands (not closing properly, tendon broken or recalibration needed)the 

### Detailed context

Required before 22/05. The robot will be packed for shipment on the 23rd evening.

**Comment by maggia80** [comment]
issue occurred in the right upperarm: ![image](https://user-images.githubusercontent.com/6987330/168624713-4d6b281f-2804-4d36-8496-cdc4dc2c3194.png)
![image](https://user-images.githubusercontent.com/6987330/168624779-f3a3f3bc-0b97-4c90-ac14-950bdd29263b.png)

parts delivered for replacing the broken shaft:

![image](https://user-images.githubusercontent.com/6987330/168625365-7d354045-2803-4d09-bbca-ead6dfaf16c6.png)

**Comment by fbiggi** [comment]
inizio intervento ore : 0600 
termine intervento ore: 13:30 
@Uboldi80  se abbiamo ok da @randaz81 chiudiamo le issues

c @Fabrizio69 @maggia80

**Comment by Uboldi80** [comment]
I just speeched with @marco93 and then, seems the robot work well.
