### ISSUE TITLE
Robot not starting

### ISSUE THREAD

**Issue by marco-monforte** [robotology/icub-tech-support#1373]
### Device name 🤖

iCubGenova02

### Request/Failure description

The robot doesn't start.

### Detailed context

Checking from the FirmwareUpdater in the icub-head, only few boards are detected.

### How does it affect you?

Cannot run experiments on the robot

**Comment by Uboldi80** [comment]
I checked and restored the Ethernet line connectors on the back (E3-E4 cables)
I also restored the fake battery which had a break on the power supply cable connection side.
We tested the robot by verifying that all the boards were present on FirmwareUpdater and launching the interface a couple of times.
