### ISSUE TITLE
Tendon broken of left elbow 

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1374]
### Device name 🤖

iCubGenova04 (iRonCub)

### Request/Failure description

Fix left elbow tendon.

### Detailed context

With @gabrielenava, we were debugging https://github.com/ami-iit/component_ironcub/issues/626 and we had to be sure that the joint moved "fast enough" so that we could see data diversity at each sample. For this reason, we put the elbow in idle and move it "fast" (but actually, not that fast) and acquired data. During this fast motion, we heard "tac" and we broke the tendon of the left elbow.

### Additional context

![IMG_4722](https://user-images.githubusercontent.com/5045846/168880817-5fcfed69-6729-46d0-90aa-83b27794cf54.jpeg)

### How does it affect you?

Cannot run experiments

**Comment by Uboldi80** [comment]
Today, Me and @GiacomoVassallo13 have replaced the tendons number 9 and 10 of left elbow.
