### ISSUE TITLE
Screw blocked inside left ear 

### ISSUE THREAD

**Issue by lunagava** [robotology/icub-tech-support#1382]
### Device name 🤖

iCubGenova02

### Request/Failure description

We disassembled the helmet for a photoshoot with the European commission. The screw was longer to work better with the iCub helmet and a portion remained outside making it unaesthetic. 

### Detailed context

We tried to unscrew, but we need further assistance to solve it.

**Comment by GiacomoVassallo13** [comment]
Buogiorno, la vite bloccata sulla testa di iCub `e stata rimossa.  Si tratta delle viti che tengono la faccia, collocate dalle orecchie. 

![bbdhbeheeseh](https://user-images.githubusercontent.com/70649516/174598171-d7086681-a21b-40c6-85f2-1f31dc2deb46.PNG)

Queste erano state sostituite con viti a testa cilindrica piu lunghe per sorreggere il supporto camera. Cio ha fatto si che una volta rimosso il cascetto, nel tentativo di stringere la vite quest ultima si `e bloccata facendo torcere a sua volta il supportino in acciaio, cod. 5203 (revisione zero) Alias RC_IIT_023_P_018

![sdfghyu98o65isiwiwi6w5uwuw](https://user-images.githubusercontent.com/70649516/174599081-95557eba-cbe5-4fdd-86e5-e8301d77a065.PNG)

Quest' ultimo avvitato al telaio tramite il pezzo in alluminio Alias: RC_IIT_023_P_012 cod. 5198 ( revisione non identificata ma obsoleta ) con filettatura M3.

![saetghyjkjhyfu7kit u](https://user-images.githubusercontent.com/70649516/174600109-1fd3222e-d7fa-4783-ba22-628e66fffc69.PNG)

Questo ha causato la rottura della filettatura interna al pezzo di alluminio, in questo modo vite e supporto giravano  a vuoto.

![IMG-20220620-WA0037 685](https://user-images.githubusercontent.com/70649516/174600803-56903eb0-4ff3-4392-ac60-4f9e1fe975b0.jpeg)

cc: @lunagava @Fabrizio69

**Comment by GiacomoVassallo13** [comment]
Per risolvere il problema sono stato costretto a tagliare al testa alla vite, cosi da poterla spingere all interno della testa cosi da poter aprire la cover ed strarre il supporto in acciaio.
A quest ultimo sono state ripassare le filettature e attualmene risulta in buono stato.

![IMG-20220620-WA0033 688](https://user-images.githubusercontent.com/70649516/174602402-9e3a6fa2-4f9e-4b93-ba54-0139bb1e7ce7.jpeg)
![IMG-20220620-WA0034 687](https://user-images.githubusercontent.com/70649516/174602435-755f957d-c2e8-4e7c-8188-511cf4961e2d.jpeg)

cc: @Fabrizio69

**Comment by GiacomoVassallo13** [comment]
Il pezzo in alluminio Alias: RC_IIT_023_P_012 cod. 5198 `e stato ripristinato, il foro e' stato allargato ed e' stato inserito un helicoil.
I  pezzi sono stati rimontati sul telaio. Duratente l' operazione il connettore delle espressioni facciali e' stato rifatto poiche rimasto danneggito. Attualmete `e stayo tutto ripristinato e le cover faccia rimontate sul robot.
L intervento `e concluso procedo con la chiusura della issue.

cc: @lunagava @Fabrizio69
