### ISSUE TITLE
l_elbow joint 3 2FOC quadrature encoder phase broken

### ISSUE THREAD

**Issue by marco-monforte** [robotology/icub-tech-support#1384]
### Device name 🤖

iCubGenova02

### Request/Failure description

Joint 3 of the left arm does not move.

### Detailed context

When launching the yarprobotinterface, joint 3 (elbow) does not move and turns red in the yarpmotorgui. It can be put in idle, but as soon as it runs, it goes red again. The error message sounds bad: "l_elbow joint 3 2FOC quadrature encoder phase broken".

![image](https://user-images.githubusercontent.com/32684998/174799261-175a9433-645f-40a7-bfa3-0f6b82f65806.png)

**Comment by Uboldi80** [comment]
I fixed the joint connector on the 2FOC 1B1.
