### ISSUE TITLE
iCubGenova09 right leg ankle encoder disconnected 

### ISSUE THREAD

**Issue by mebbaid** [robotology/icub-tech-support#1385]
### Device name 🤖

iCubGenova09

### Request/Failure description

The encoder of the right leg ankle wiring is cut/disconnected as per the picture. Consequently startup calibration is not complete.

![PXL_20220621_134334961 MP](https://user-images.githubusercontent.com/36491318/174816795-b80933de-ca60-4f7d-9dd3-c0443587835b.jpg)

### Detailed context

After unpacking the robot which arrived from Rimini, and upon first start-up we noticed that the ankle is not calibrating. Upon expecting the `yarpmotorgui`, indeed the right_leg ankle was in idle and didn't calibrate. Moving the ankle manually, the `motor position` value changes but not the `encoder` value. Visual inspection of the right leg shows the disconnected cable as per the attached picture.

**Comment by Uboldi80** [comment]
connector was fixed
