### ISSUE TITLE
iCubGenova01 - Left index proximal broken

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1387]
### Device name 🤖

iCubGenova01

### Request/Failure description

During an experiment involving force control with tactile sensors, we pressed too much causing breakage of the left index proximal tendon.

**Comment by GiacomoVassallo13** [comment]
The left index proximal tendon was been replaced. Also the thub proximal was been replaced because the knot at the end of the tendon had come out of the passage hole.

cc: @gsisinna @xEnVrE @Fabrizio69

**Comment by xEnVrE** [comment]
Thanks @GiacomoVassallo13 

We will wait until the robot has been tested for closing the issue

**Comment by Uboldi80** [comment]
Today i tested the left index and then it seem to work well.
