### ISSUE TITLE
iCubGenova01 - Cannot detect MC4 board in the left arm

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1389]
### Device name 🤖

iCubGenova01

### Request/Failure description

As per the screenshot below, the MC4 board in the left arm (i.e. `<CFW2<1>`) cannot be detected.

![Screenshot from 2022-06-30 16-01-05](https://user-images.githubusercontent.com/6014499/176697116-9759e500-7726-47df-aa7b-4fb700e77855.png)

**Comment by Uboldi80** [comment]
I fixed a lot of problem on the can line in the shoulder and in the forearm.
I tested the robot with @xEnVrE  and the problem is solved.
