### ISSUE TITLE
yarprobotinterface not starting

### ISSUE THREAD

**Issue by marco-monforte** [robotology/icub-tech-support#1393]
### Device name 🤖

iCubGenova02

### Request/Failure description

The yarprobotinterface doesn't start.

### Detailed context

Boards return an error message requiring a firmware update, even tho nothing has been touched since Monday, last day the robot has been turned on and working

### Additional context
The following message shows up for several boards (if not all of them)

![image](https://user-images.githubusercontent.com/32684998/177736003-ca2cbd3f-f4f0-448d-b791-1ec0cb92ecc5.png)

### How does it affect you?

Can't use the robot

**Comment by gsisinna** [comment]
Today we realigned the Firmware versions of all boards and recompiled the robotology superbuild. There were incorrect firmware versions for the installed robotology distro (2022.05.0).

I remind you to be careful during these updates and refer to the [software versioning table](https://icub-tech-iit.github.io/documentation/sw_versioning_table/2022.05.0/) in the official documentation. [Here](https://github.com/robotology/icub-firmware-build/releases/tag/v1.25.0) for the right icub-firmware-build release.

Now the `yarprobotinterface` starts and it is possible to use the robot.

cc @Uboldi80 @sgiraz
