### ISSUE TITLE
Right thumb distal does not calibrate

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1395]
### Device name 🤖

iCubGenova09

### Request/Failure description

When running the robot, the right thumb distal does not move and it does not calibrate.

### Detailed context

I also tried to reboot the robot and the motors, but it did not help

**Comment by Uboldi80** [comment]
I fixed the 3M2 connector from the Mc4 Eb28 board and i fix another problem on the FTC on the MAIS board.
