### ISSUE TITLE
Support in installing new lenses on the robot camera

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1397]
### Device name 🤖

iCubGenova09

### Request/Failure description

We would like to test new lenses on the robot head

### Detailed context

We would need some support in adjusting the bulb in order to fit the new lenses

cc @emilianob80

**Comment by emilianob80** [comment]
Lenti sostituite con quelle fornite da @S-Dafarra. E' stata rimossa la vitina di ritenuta lente dal porta lente perchè insieme alla lente nuova era presente la ghiera di ritenuta. 
Le lenti sono state testate e funzionano. 

@Uboldi80 puoi chiudere la issue
