### ISSUE TITLE
Check and replacement shoulder tendons

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1399]
### Device name 🤖

iCubGenova04

### Request/Failure description

The left arm tendon broke when the robot was position controlled.
All shoulder tendons must be checked and, if necessary, replaced if they have reached the mechanical limit stop

### Detailed context

 We were tuning low-level position control gains, and the tendons were already very worn.

### How does it affect you?

Blocks further iRonCub experiments

cc @DanielePucci

**Comment by gsisinna** [comment]
A mechanical check was performed during the last weeks by @GiacomoVassallo13 and @Uboldi80:

- Checked shoulder actuators (harmonic group)
- Tendon replacement for both shoulders
- Arms calibration (joints 0,1,2,3) has been changed to calibration type 12

I removed all the deltas in the calibration and now with the new calibration type 12 you just need to put the raw values in the calibrator files without using the excel file.

Thanks!

cc @gabrielenava @DanielePucci @maggia80 @Fabrizio69
