### ISSUE TITLE
iCubGenova09 `r_wrist` vibrating heavily

### ISSUE THREAD

**Issue by mebbaid** [robotology/icub-tech-support#1401]
### Device name 🤖

iCubGenova09

### Request/Failure description

While on home position, the `r_wrist_pitch` seems to start randomly "vibrating".

### Detailed context

The right arm wrist behaves in the way shown in the video below;

https://user-images.githubusercontent.com/36491318/180006854-7ee92561-57fd-442d-ab84-2798c8e1ab28.mp4

and the `yarpmotorgui` view shows;

https://user-images.githubusercontent.com/36491318/180007028-2cbf81a8-3f84-4daf-a274-5832701a5801.mp4

### How does it affect you?

We were able to carry on with our experiments, however this may affect scheduled upcoming demos

**Comment by gsisinna** [comment]
We found a broken capacitor in the AEA board. We replaced it and now the wrist work well.

@mebbaid
