### ISSUE TITLE
General maintenance

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1402]
### Device name 🤖

iCubErzelli01

### Request/Failure description

We would need a general check on robot arms, torso and head possibly before the end of August.

### Detailed context

- Overall tightening of cables, electrical connections and other generic check up.
- Check range of motion of JOINT 4 for right and left arm.
- Reduce vibration on both robot arms.
- Face expressions module often doesn't work. Need a few restarting of the robot to make it work.

**Comment by gsisinna** [comment]
With @ddetommaso we planned the check after the 8th of August.

cc @Nicolasr3

**Comment by gsisinna** [comment]
Today I performed a general check of the robot, and the above forearm was calibrated to eliminate the asymmetry with the other arm. Several cables from the wrist and left shoulder were tightened, but there do not seem to be any obvious problems affecting the functioning of the robot.

Thanks @ddetommaso @Nicolasr3
