### ISSUE TITLE
Update and general maintenance

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1403]
### Device name 🤖

iCubErzelli02

### Request/Failure description

We would need to update the entire robot (head and boards) and do a general check possibly before mid-August.

### Detailed context

- Complete update of the robot head and boards
- Overall tightening of cables, electrical connections and other generic check up
- Upgrade os and YARP version

**Comment by gsisinna** [comment]
Hi @ddetommaso, I give you here some references to update the robotology-superbuild as per the official documentation:

1. [Update](https://github.com/robotology/robotology-superbuild#update)
2. [Superbuild installation on icub-head](https://icub-tech-iit.github.io/documentation/sw_installation/icub_head_superbuild/#superbuild-installation-on-icub-head)

As for the firmware you will have to align according to the version you choose for robotology-superbuild, so assuming you upgrade to the latest version you will have to follow [this](https://github.com/robotology/icub-firmware-build#firmware-versioning-table) versioning table.

Then you can follow the [Firmware Documentation](https://icub-tech-iit.github.io/documentation/icub_firmware/firmware/firmware/) and update the iCub boards. Here a summary of the main steps:

1. Clone the last release of [iCub Firmware Build](https://github.com/robotology/icub-firmware-build) inside the icub-head
2. From the robot laptop: `ssh -X icub-head`
3. And launch the GUI with `FirmwareUpdater -a`
4. For each board you will have to put first in `maintenance mode` and then upload the last firmware from the repo you cloned before
5. When you finish the firmware uploads you can restart the boards and test the robot

This is with regard to the software components (robotology-superbuild and firmware). We remain available for any remote help and to schedule as already proposed in-person interventions for the coming months.

cc @maggia80

**Comment by ddetommaso** [comment]
Many thanks @gsisinna!
I think we can proceed autonomously with the update process as far as the robot will be available (from next week onward).
As mentioned earlier if you guys can do a general check by the end of August this would be optimal.

**Comment by gsisinna** [comment]
Perfect @ddetommaso, we remain available for any needs and on days 8-9-10 of August we can allocate time for a general check based on your availability.

**Comment by gsisinna** [comment]
See also https://github.com/robotology/icub-tech-support/issues/1410 for left wrist issue.

**Comment by gsisinna** [comment]
As agreed, the firmware and software update part will be handled independently, and today the work on the left wrist was completed (see https://github.com/robotology/icub-tech-support/issues/1410). In addition to that blocking problem, several checks were performed such as:

- electrical connections and skin patches
- cameras
- tighten some wrist and shoulder cables
- board presence and sensors
- proximal cables pulled (thumbs)
- fixed chips from the FTC connector

However, we remain available for any firmware or software side issues related to the procedure as per the official guide.

Thanks!

cc @ddetommaso @Nicolasr3 @Fabrizio69 @maggia80
