### ISSUE TITLE
``r_wrist_yaw`` encoder diverges

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1404]
### Device name 🤖

iCubGenova09

### Request/Failure description

The ``right_wrist_yaw`` encoder seems to diverge. When we started the robot, the joint was ok, but after about an hour, it reads 2196 degrees

### Detailed context

![image](https://user-images.githubusercontent.com/18591940/180482563-c797e30a-e32a-4df6-a63e-c864521bc0ec.png)

cc @mebbaid @GiulioRomualdi @isorrentino

**Comment by mebbaid** [comment]
Perhaps this is linked to #1401

**Comment by gsisinna** [comment]
Today we checked all the magnets in the right wrist joints and replaced one. We re-calibrated joints 5 and 6 by removing the old deltas and everything seems fine!

cc @S-Dafarra
