### ISSUE TITLE
iCubGenova09 startup fails

### ISSUE THREAD

**Issue by paolo-viceconte** [robotology/icub-tech-support#1406]
### Device name 🤖

iCubGenova09

### Request/Failure description

When trying to startup the robot after the battery replacement, both the torso and the hip roll were not configured. 

### Detailed context

@mebbaid and I checked the firmware updater: 
![firmware_updater](https://user-images.githubusercontent.com/41757826/182134903-6e4ac399-c2b5-47c5-b487-40958bc4dc0e.png)

without noticing any particular issue. The calibration fails as you can see:

https://user-images.githubusercontent.com/41757826/182135456-13b514da-a6bb-4204-b6d5-a95619eceaf3.mp4

**Comment by mebbaid** [comment]
Seems that after restarting the boards, the robot started normally. Maybe we can close this issue  @paolo-viceconte .
