### ISSUE TITLE
Right shoulder tendons exited

### ISSUE THREAD

**Issue by HosameldinMohamed** [robotology/icub-tech-support#1409]
### Device name 🤖

iCubGenova04

### Request/Failure description

While the robot was moving the arms for FTs in-situ calibration test, the tendons exited from the right shoulder.

### Detailed context

Please see the picture below.

### Additional context

![20220805_132919](https://user-images.githubusercontent.com/45564317/183068723-18e039dd-8382-4a11-8a13-c82ec654a79f.jpg)

### How does it affect you?

It blocks Arms FTs in-situ calibration experiments.

**Comment by maggia80** [comment]
@HosameldinMohamed if no one is available you could check the documentation here and try to follow it: https://icub-tech-iit.github.io/documentation/icub_tendons/shoulder_elbow/

**Comment by HosameldinMohamed** [comment]
> @HosameldinMohamed if no one is available you could check the documentation here and try to follow it: https://icub-tech-iit.github.io/documentation/icub_tendons/shoulder_elbow/
> 
> 

Great, thanks!

**Comment by HosameldinMohamed** [comment]
Cable put back with @vpunithreddy
![20220805_185532](https://user-images.githubusercontent.com/45564317/183125076-f80bdf2f-9520-45ee-ac73-e7eb08f8c0c4.jpg)
!

**Comment by HosameldinMohamed** [comment]
Apparently, our intervention caused some problems. We did not put the motors in the initial position when putting back the tendons.

We will write more details about it.

The problem was found and fixed by @GiacomoVassallo13, see https://github.com/robotology/icub-tech-support/issues/1412#issuecomment-1209419807
