### ISSUE TITLE
Left arm tendon broken

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1410]
### Device name 🤖

iCubErzelli02

### Request/Failure description

One of the tendon of the wrist (left arm) broke during a demo.

### Detailed context

(please if needed ask us for further investigations)

### Additional context

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/3440640/183069014-f70e821b-5a66-4a40-baca-3ad68becc3f8.jpg)

**Comment by gsisinna** [comment]
Today I disassembled the arm in question as it is necessary to recreate custom cables for the active wrist differential mechanism.

cc @Uboldi80 @Fabrizio69 

![image](https://user-images.githubusercontent.com/36999962/183393862-c6922805-87c2-49d5-b9c1-23fd055f25b0.png)

**Comment by gsisinna** [comment]
Yesterday with @GiacomoVassallo13's help we regenerated the wrist cables by creating new custom ones and restored the differential mechanism:
![photo1660048053](https://user-images.githubusercontent.com/36999962/183646807-59f67a38-e321-43a2-80f6-d62f61b1ab38.jpeg)
Here is a video of the calibration and proper functioning of the left wrist:

https://user-images.githubusercontent.com/36999962/183647038-629b72fd-df8b-464d-8f35-1557c147d08c.mp4

cc @ddetommaso @Nicolasr3 @Fabrizio69 @maggia80
