### ISSUE TITLE
2 Left shoulder tendons broke

### ISSUE THREAD

**Issue by HosameldinMohamed** [robotology/icub-tech-support#1413]
### Device name 🤖

iCubGenova04

### Request/Failure description

2 left shoulder tendons broke while the robot was on the pole.

### Detailed context

A torso hardware fault happened causing the upper body to fall forward. As a result the left arm shoulder tendons broke down.

The cables we broke are **no. 1** and **no. 7**.

**Comment by HosameldinMohamed** [comment]
CC @GiacomoVassallo13

**Comment by GiacomoVassallo13** [comment]
Hi, curtains 1 and 7 that had broken have been restored. I continue with the closure of the issue.

cc: @gsisinna @Fabrizio69 @HosameldinMohamed
