### ISSUE TITLE
Left thumb oppose broken

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1415]
### Device name 🤖

iCubGenova09

### Request/Failure description

The left thumb oppose tendon seems broken. The motor in the palm rotates continuously but the joint does not move.

### Detailed context

We were testing the robot with some objects from the ANA Avatar Xprize and the right thumb oppose snapped. 

cc @GiacomoVassallo13

**Comment by GiacomoVassallo13** [comment]
Buongiorno il thumb oppose della mano sinistra e' stato ripristinato.

cc: @S-Dafarra @DanielePucci
