### ISSUE TITLE
Left and right wrist yaw encoders diverge

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1417]
### Device name 🤖

iCubGenova09

### Request/Failure description

After starting the robot, the joint goes almost immediately in HF because the encoder diverges.

### Detailed context

The encoder value diverges quickly to several thousand degrees.

**Comment by S-Dafarra** [comment]
Edited the title of the issue as this happened also on the right. See the following graph. I was not touching the arm at all (i was pushing on the legs)

![Screenshot from 2022-09-02 17-46-43](https://user-images.githubusercontent.com/18591940/188391787-2f82d22e-f8b5-486f-b073-f4a6beb2cc85.png)
![Screenshot from 2022-09-02 17-45-12](https://user-images.githubusercontent.com/18591940/188391792-cd311cde-259f-42c6-8884-c83c9c494d46.png)

**Comment by gsisinna** [comment]
Hi @S-Dafarra, have you seen this behavior after the check performed on the AEA boards?

**Comment by S-Dafarra** [comment]
> Hi @S-Dafarra, have you seen this behavior after the check performed on the AEA boards?

Hi @gsisinna, I haven't noticed since then!

**Comment by gsisinna** [comment]
Thanks!
