### ISSUE TITLE
Left hip pitch motor encoder got cut

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1418]
### Device name 🤖

iCubGenova09

### Request/Failure description

The left hip pitch motor encoder cable has been cut by the hand.

### Detailed context

We were performing a teleoperation test and by accident, the hand hit the motor holding, cutting the cable.

**Comment by DanielePucci** [comment]
Here is the picture 
![MicrosoftTeams-image (35)](https://user-images.githubusercontent.com/5045846/187963156-7c2408cd-ee7c-4e7d-b7f0-206940c0d6a1.png)

**Comment by emilianob80** [comment]
@S-Dafarra This morning I provided for the complete replacement of the E0 cable of the left leg. The sensor, testing it with the jogger, is now working.

![IMG_20220905_073245](https://user-images.githubusercontent.com/53729815/188367718-a3eedbae-e975-41f5-b14d-3a8d6a72fb77.jpg)

Chiudo la issue


cc: @pattacini @DanielePucci
