### ISSUE TITLE
Broken right shoulder tendons and arms' tendons loose

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1419]
### Device name 🤖

iCubGenova04

### Request/Failure description

during arms' FT data collection for calibration, one of the right shoulder tendon broke and another one exited from the guide. I have also noted that in general the arms' tendons look consumed and some of them are already loose, we may need a full check to avoid other cables to break soon

### Detailed context

cc @HosameldinMohamed

**Comment by gsisinna** [comment]
The cables have been replaced and pulled, it remains to test the robot together with the team guys 👍

cc @vpunithreddy @gabrielenava
