### ISSUE TITLE
Right hip pitch encoder broken 

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1420]
### Device name 🤖

iCubGenova09 

### Request/Failure description

![IMG_5599](https://user-images.githubusercontent.com/5045846/188609585-525368a4-6b3a-4165-93f1-709724dae4de.jpeg)

### Detailed context

While testing the teleoperation, the robot additional hook touched the cable

**Comment by emilianob80** [comment]
@DanielePucci solved. Elio is working on an extension of the cover to protect the cable

cc: @Fabrizio69
