### ISSUE TITLE
Loosy iCub3 left sole  

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1421]
### Device name 🤖

iCubGenova09 

### Request/Failure description

As per the video below: it would be great at this point to check all screws @gsisinna 

https://user-images.githubusercontent.com/5045846/188689449-443a98b7-a937-45d2-8316-d5fcd6a3d1f3.mp4

### Detailed context

I was randomly checking the robot and we found the problem in the video 

CC
@S-Dafarra @isorrentino @GiulioRomualdi

**Comment by gsisinna** [comment]
I removed the cover and tightened the screws holding the sole in place.
