### ISSUE TITLE
Left arm shoulder pitch and elbow tendons broke

### ISSUE THREAD

**Issue by HosameldinMohamed** [robotology/icub-tech-support#1422]
### Device name 🤖

iCubGenova04

### Request/Failure description

During F/T sensor calibration activities with additional weights, the arms tendons broke down again. The broke joints are the shoulder pitch and the elbow. I think the shoulder roll tendons exited too.

### Detailed context

We are stressing the robot with this experiment, even though the weight that broke the arm was tested before, we were repeating the tests increasing the weights gradually to reach that specific value. That probably wore the tendons out.

### Additional context

This piece fell off the robot

![image](https://user-images.githubusercontent.com/45564317/189087901-fe7e09e8-36ae-4723-9ee0-0954a3d3e2ad.png)

**Comment by HosameldinMohamed** [comment]
CC @gabrielenava @vpunithreddy

**Comment by gsisinna** [comment]
We replaced the two cables with @GiacomoVassallo13 and the robot has been tested with @HosameldinMohamed.

**Comment by HosameldinMohamed** [comment]
Thanks guys!!
