### ISSUE TITLE
right wrist hardware fault

### ISSUE THREAD

**Issue by Nicolasr3** [robotology/icub-tech-support#1423]
### Device name 🤖

iCubErzelli02

### Request/Failure description

After running the module yarprobotinterface, during the calibration the right wirst never reached his position. 

![icub_1](https://user-images.githubusercontent.com/44875110/189629262-7bf2871d-dc3f-4e88-a389-389e9885f440.jpeg)

### Detailed context

We are perfoming an experiment where iCub needs to press several buttons in front of it, with the right hand.

### Additional context

Here some picture of the state of the cables wirst.
![icub_6](https://user-images.githubusercontent.com/44875110/189629455-51bd0fea-455c-4bfe-8ea9-d7e5c501d044.jpeg)
![icub_5](https://user-images.githubusercontent.com/44875110/189629465-757f6a16-b1aa-447f-a582-29efa68e503f.jpeg)
![icub_4](https://user-images.githubusercontent.com/44875110/189629468-f73e579b-5e61-4195-abc4-1a360fdf559f.jpeg)
![icub_3](https://user-images.githubusercontent.com/44875110/189629472-154012fa-e494-42a9-aa44-face17d1b862.jpeg)
![icub_2](https://user-images.githubusercontent.com/44875110/189629475-37a2eb9d-7838-40ec-abe3-9e508e13dc72.jpeg)

The yarpmotorgui is plotting this error on the joint 6 of the right arm:

![icub_log](https://user-images.githubusercontent.com/44875110/189629700-18536b6b-4fea-498d-baab-9d0ab0f41452.jpeg)

### How does it affect you?

Now we stopped the data collection of the experiment until the robot wirst is repared.
It would be really helpfull if the issue could be solved soon, so we can restart the data collection.

**Comment by gsisinna** [comment]
Hi @Nicolasr3,
I will be there tomorrow 👍

The robot can be left in the room where you currently use it and connected to the network.

**Comment by gsisinna** [comment]
This morning I replaced the AEA electronic board for the wrist yaw movement. Now the robot is working again and below is the video of the calibration including the wrist:

https://user-images.githubusercontent.com/36999962/189867902-ab3bad9f-66d6-424a-84ea-93368d0a6ff4.mp4

cc @Nicolasr3 @ddetommaso @Fabrizio69 @maggia80
