### ISSUE TITLE
[iCubGenova09] Left pinky broken

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1425]
### Device name 🤖

iCubGenova09

### Request/Failure description

While using the hands the left pinky got broken 

### Detailed context

The finger remains in this configuration 

![20220914_122042.jpg](https://user-images.githubusercontent.com/16744101/190129287-2d668609-4f29-41fb-bc45-16ccda782d70.jpg)

### Additional context

cc @mebbaid @S-Dafarra

**Comment by gsisinna** [comment]
The tendon has been replaced, thanks @GiacomoVassallo13!
