### ISSUE TITLE
R1SN003 neck pitch does not work properly

### ISSUE THREAD

**Issue by elandini84** [robotology/icub-tech-support#1426]
### Device name 🤖

R1SN003

### Request/Failure description

R1SN003 neck cannot go upwards and when going in the opposite direction is it moves past the wanted amount of degrees.

### Detailed context

We tried different times to move R! head downwards and then up again but it never worked. The head just stays down unless some moves it manually in that direction.

Fixing this issue is pretty important since on the 20th of September (next Tuesday) we have an important demo.

**Comment by fbiggi** [comment]
ciao @elandini84 
domani mattina intervengo su r1

cc @Fabrizio69 @maggia80

**Comment by fbiggi** [comment]
repositioning and adjustment of the neck strap
testing performed together with @ elandini84
total hours 3:25 minutes

cc @Fabrizio69 @maggia80

**Comment by elandini84** [comment]
The neck now works as expected, thanks a lot @fbiggi
