### ISSUE TITLE
[iCubGenova09] The left_arm_eb25_j8_11 eth goes down when the arm moves

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1428]
### Device name 🤖

iCubGenova09

### Request/Failure description

While teleoperating the ETH monitor link went down and we lost the communication with the robot. 

### Detailed context

![Screenshot from 2022-09-16 17-38-37](https://user-images.githubusercontent.com/16744101/190680789-65556136-cfbe-43e5-a9a8-12c93c9f3876.png)

### Additional context

cc @S-Dafarra @isorrentino @RiccardoGrieco

**Comment by gsisinna** [comment]
I found a weak molex connector in the EB25. I replaced it and after the mechanical maintenance we can test the robot.
