### ISSUE TITLE
iCubGenova01 - Skin is not working with few exceptions

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1429]
### Device name 🤖

iCubGenova01

### Request/Failure description

As per the title, the skin of the palm of the right hand and that of the forearm do not respond to external stimuli

**Comment by xEnVrE** [comment]
I updated the issue title as many other parts stopped working.

Specifically, at the moment, the following **do not work**:
- left arm: all parts
- right arm:
  - arm
  - forearm
  - palm
  - ring
  - medium (works but it has spikes every so often)

**Comment by Fabrizio69** [comment]
iCubGenova01 will be dismissed soon, hence closing.
