### ISSUE TITLE
[R1SN003] - Left wrist broken

### ISSUE THREAD

**Issue by ste93** [robotology/icub-tech-support#1430]
### Device name 🤖

R1SN003

### Request/Failure description

Unfortunately the left wrist is broken, it seems that one of the part of the tripod is broken

### Detailed context

the wrist is stuck in a non linear position and it doesn't move

**Comment by fbiggi** [comment]
insert the METERSPRINGS_T30900 springs in their seats
checked the tightening of the pins CER_009_P_073
Tripod calibration check is recommended
It seems that a joint has gone over the edge


![20220923_071024](https://user-images.githubusercontent.com/20420331/191899835-35b406e8-2980-461a-a462-89dfe8ededb1.jpg)

I proceed with the reassembly of the wrist

**Comment by fbiggi** [comment]
@ste93 
robot ready
after your check please close the issues

**Comment by ste93** [comment]
Thank you @fbiggi , I will check the robot tomorrow.

**Comment by ste93** [comment]
working perfectly, thank you @fbiggi

**Comment by fbiggi** [comment]
on 09/28/2022 the left forearm was reopened
the m1 engine was blocked in the downward stretch
perhaps the dirt was affecting the engine
