### ISSUE TITLE
Left arm shoulder tendon broke

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1431]
### Device name 🤖

iCubGenova04

### Request/Failure description

after starting up the robot, one of the left shoulder tendons immediately broke.

### Detailed context

cc @vpunithreddy @HosameldinMohamed 

### How does it affect you?

blocks iRonCub experiments

**Comment by gsisinna** [comment]
The cable 3 of the left shoulder has been replaced.
