### ISSUE TITLE
Clusterwidget: port /pc104 not responding

### ISSUE THREAD

**Issue by pfdominey** [robotology/icub-tech-support#1437]
### Device name 🤖

iCubDijon01

### Request/Failure description

We just got the iCub back from Genoa.  Thanks
Two problems
1. using the new console, the computer fails to establish aconnection with the router.  Do you recall if this worked correctly in Genoa?
2. As a backup, we try to connect with the console we used before, which was fully reinstalled and updated at the n-1 trip to Genoa.  This is because there was a backlog with Dell, and you did not have our new console, so you updated our console.  This is what we were using up unitl now.

This computer connects to the network, we can ping to the pc104.  Then we start the yarpmanager,in the cluster tab of the gui with the yarpmanager, run the nameserver.  We try to start icub-srv and pc104 (see photo) and the pc104 gives an error ""Clusterwidget port pc104 is not responding" and the icon remains red.

Can you please advise on these problems?
thanks
Peter
![20221003_153632](https://user-images.githubusercontent.com/32130758/193602304-dabcb92f-2017-43f0-8285-6a1f5727022f.jpg)

### Detailed context

explained above:  
in the Cluster Management Window the pc104 does not connect, and the icon stays red.

IN the GUI window it says that that yarprun was successfully executed on the pc104, but in the cmd window, there is a failure, and the in the gui the icon remains red.  See attached screen shot.
![20221003_153632](https://user-images.githubusercontent.com/32130758/193603595-093b12b6-2d5c-4494-875c-efd98751dedb.jpg)

**Comment by pfdominey** [comment]
got the new console to connect by changing the network parameters as shown in the first photo

still have the problem with the pc104 icon staying red
![20221003_165811](https://user-images.githubusercontent.com/32130758/193612695-54a34a03-f529-48a5-ba56-ad6e4bc852c2.jpg)
![20221003_163730](https://user-images.githubusercontent.com/32130758/193612704-fd0eeff1-0e6e-48e4-9fa8-2d226389d985.jpg)

**Comment by pfdominey** [comment]
Hi @gsisinna 
Can you help with this?  We cannot use the robot.
I suspect that there is an ip address error somewhere.  Probably very simple to fix, but I dont know how to do it!!
thanks
cheers
Peter

**Comment by valegagge** [comment]
Hi @pfdominey,

I suggest you do a simple test:
connect to pc104 by ssh from your laptop and then give the command:
`yarprun --server /pc104`.

In this way, we check that ssh is configured correctly and the yarp command works as expected.

Please report here the output of both commands. 
Thanks!
cheers 
Valentina

**Comment by pattacini** [comment]
Hi @pfdominey 

While doing as @valegagge suggested, you may also check whether from the pc104 (right after the ssh) you can see the YARP network by running:
```console
yarp where
``` 

If the YARP server isn't detected, we will need to change the pc104 configuration.

Also, note down whether while ssh-ing into pc104 you're prompted with providing the password.

**Comment by pfdominey** [comment]
hi!
Here's what happens:
icub@icubsrv:~$ ssh pc104
iCub LIVE image for PC104 version 7.10-21.04.27
Based on buster amd64
Build on 27-Apr-2021
Linux pc104 4.19.0-16-rt-amd64 #1 SMP PREEMPT RT Debian 4.19.181-1 (2021-03-19) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Oct  5 14:45:52 2022 from 10.0.0.1
Setting up yarp and iCub env vars
icub@pc104:~$ yarprun --server /pc104
-bash: yarprun: command not found
icub@pc104:~$

**Comment by pfdominey** [comment]
so it seems that yarp is not running on the pc104?

**Comment by pattacini** [comment]
Hi @pfdominey 

You should be using the laptop we sent you. There's no guarantee that the old one can be used alongside. Was that the case with the test?

>using the new console, the computer fails to establish aconnection with the router. Do you recall if this worked correctly in Genoa?

We don't provide routers. So, you can do the test by connecting the robot ethernet cable straight to the laptop console (or you can use a switch in the middle).

cc @gsisinna

**Comment by pfdominey** [comment]
we are using the new laptop you sent us

**Comment by pfdominey** [comment]
we are using the switch you provided

**Comment by pfdominey** [comment]
I can ping to the pc104 and ssh to it, as seen in the screen output above

**Comment by pfdominey** [comment]
but if I type "yarp" I get a response "yarp : command not found"

**Comment by gsisinna** [comment]
hi @pfdominey can you try to follow [this](https://icub-tech-iit.github.io/documentation/icub_operating_systems/other-machines/icub-server-laptop/?h=ssh#install-the-ssh-keys-for-password-less-login-on-icub-head) steps for ssh keys? (with the new laptop)

it is really strange that you don't find yarp, and the new laptop sent was tested with the robot and worked.

Thanks, 
waiting for your feedback

**Comment by pattacini** [comment]
>we are using the new laptop you sent us

Ok 👍🏻 

>we are using the switch you provided

This is strange; maybe it's a USB/ETH adapter instead?

>so it seems that yarp is not running on the pc104?

Most likely, YARP is there but not "exposed" somehow.

The output of the following commands may help:
1. `cat /etc/fstab` to be run on pc104
2. `echo ${PATH}` to be run on pc104

**Comment by gsisinna** [comment]
Also @pfdominey , open a terminal in the new laptop (connected to the robot network) and type this command:

`ip a`

**Comment by pfdominey** [comment]
icub@pc104:~$ cat /etc/fstab
overlay / overlay rw 0 0
tmpfs /tmp tmpfs nosuid,nodev 0 0
icub@pc104:~$

**Comment by pfdominey** [comment]
icub@pc104:~$ echo ${PATH} 
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
icub@pc104:~$

**Comment by pfdominey** [comment]
> Also @pfdominey , open a terminal in the new laptop (connected to the robot network) and type this command: `ip a`

<pre><font color="#4E9A06"><b>icub@icubsrv</b></font>:<font color="#3465A4"><b>~</b></font>$ ip a
1: lo: &lt;LOOPBACK,UP,LOWER_UP&gt; mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s31f6: &lt;BROADCAST,MULTICAST,UP,LOWER_UP&gt; mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether b4:45:06:49:b8:b7 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.1/24 brd 10.0.0.255 scope global noprefixroute enp0s31f6
       valid_lft forever preferred_lft forever
    inet6 fe80::2607:a7b4:b501:c0/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: wlp0s20f3: &lt;BROADCAST,MULTICAST,UP,LOWER_UP&gt; mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether f8:b5:4d:fe:e2:87 brd ff:ff:ff:ff:ff:ff
    inet 192.168.43.101/24 brd 192.168.43.255 scope global dynamic noprefixroute wlp0s20f3
       valid_lft 2032sec preferred_lft 2032sec
    inet6 fe80::f089:d2c4:f5de:69af/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
<font color="#4E9A06"><b>icub@icubsrv</b></font>:<font color="#3465A4"><b>~</b></font>$ 
</pre>

**Comment by pattacini** [comment]
>this is the router
black cable comes from from the rack and is from the pc104 and the grey cable connects to the console

I missed out the rack @pfdominey 👍🏻 
So, you have a switch yep.

Judging from the output you posted, it's very likely that PC104 is not mounting the partition that contains YARP, which in turn is provided by the server.

We would need to schedule a remote session eventually.
In the meantime, could post the output of the following command?
- `cat /etc/exports` (to be run on icubsrv)

**Comment by pfdominey** [comment]
is it possible that the pc104 is not looking in the right place for the partition that is provide by the server?
I think I had to do a yarp --write at the beginning which might have changed an ini file or something?
any other things I could try?
thanks

**Comment by pfdominey** [comment]
One other thing that may be important: at first the console could not connect to the switch.

I manually changed the network settings IPv4 to address 10.0.0.1 and dns automatic

could this cause a problem for the pc104?

**Comment by pfdominey** [comment]
since everything was working in Genoa, it seems strange that its not working here, and probably something simple.

**Comment by pfdominey** [comment]
Would you be available Monday afternoon for a video session and you could connect to the console by teamviewer and ssh to the pc104 and see whats wrong?

**Comment by pattacini** [comment]
>```
>/exports/code 10.0.0.0/255.255.255.0(rw,sync,no_subtree_check)
>/exports/local_yarp 10.0.0.0/255.255.255.0(rw,sync,no_subtree_check)
>```

The server does correctly export the YARP code although the PC104 is unable to mount it.

>is it possible that the pc104 is not looking in the right place for the partition that is provide by the server?

That's the most probable hypothesis yep

>I think I had to do a yarp --write at the beginning which might have changed an ini file or something?

If `yarp --write` worked then it means that you found YARP. Likely, you launched it on the server. However, here the problem seems to be the file system, thus not the YARP network. At any rate, `yarp -write` is required from time to time when the underlying ethernet is changed.

>I manually changed the network settings IPv4 to address 10.0.0.1 and dns automatic

This is actually particularly weird as the laptop should have been already configured with the proper options. Anyway, the settings you used look good as the PC104 expects to mount from and talk to 10.0.0.1 (although the content of `/etc/fstab` was incorrect).

>Would you be available Monday afternoon for a video session and you could connect to the console by teamviewer and ssh to the pc104 and see whats wrong?

I think that we can organize the session. Let me verify with our IT manager. Most presumably, we will be available as our internal tests will be over. Stay tuned, I will confirm this.

**Comment by pattacini** [comment]
Hi @pfdominey 

I can confirm we can schedule a remote session on Monday 10 in the afternoon.
@davidetome and @davidelasagna will be dealing with it.

Does the slot 14:30-16:00 work for you?
If so, I can email you all the invitation.

**Comment by pfdominey** [comment]
Hi - Yest this slot works.
I am ready now if you want :)

**Comment by pfdominey** [comment]
Thanks for working on this strange problem.
I am available any time tuesday and wednsday to try again by teamviewer.
cheers
Peter

**Comment by pfdominey** [comment]
last words for the evening!
Hope to see you tomorrow

Scanning dependencies of target iDyn
[  8%] Building CXX object src/libraries/iDyn/CMakeFiles/iDyn.dir/src/iDyn.cpp.o
[  8%] Building CXX object src/libraries/iDyn/CMakeFiles/iDyn.dir/src/iDynInv.cpp.o
[  8%] Building CXX object src/libraries/iDyn/CMakeFiles/iDyn.dir/src/iDynBody.cpp.o
[  8%] Building CXX object src/libraries/iDyn/CMakeFiles/iDyn.dir/src/iDynTransform.cpp.o
Assembler messages:
Fatal error: can't create CMakeFiles/iDyn.dir/src/iDynTransform.cpp.o: Input/output error
make[5]: *** [src/libraries/iDyn/CMakeFiles/iDyn.dir/build.make:102: src/libraries/iDyn/CMakeFiles/iDyn.dir/src/iDynTransform.cpp.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:2857: src/libraries/iDyn/CMakeFiles/iDyn.dir/all] Error 2
make[3]: *** [Makefile:130: all] Error 2
make[2]: *** [CMakeFiles/ICUB.dir/build.make:109: src/ICUB/CMakeFiles/YCMStamp/ICUB-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:1298: CMakeFiles/ICUB.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
icub@pc104:/usr/local/src/robot/robotology-superbuild/build-pc104$

**Comment by pattacini** [comment]
Hi @pfdominey 

We'll get back to you asap!
Updating the dependencies resulted in some progress at least.

Now the problem is:
```
Assembler messages:
Fatal error: can't create CMakeFiles/iDyn.dir/src/iDynTransform.cpp.o: Input/output error
```

It seems related to the disk space, somehow.
Tomorrow, could you please run the following on PC104?
```console
df -h
```
reporting here the outcome.

Thanks!

**Comment by pfdominey** [comment]
Will do!  I will do it around 8h45 or so.
thanks again!
cheers

**Comment by pfdominey** [comment]
Let me know when you want me to connect to the pc104 and teamviewer :)

**Comment by pattacini** [comment]
Hi @pfdominey 

After some struggling, we finally managed to make the robot start up correctly.

The remaining issues are related to the issue of `ctpService`.
It would help us a lot to have the following material:
- A video of the robot failing while controller with `ctpService`.
- The XML file launching the `ctpService` services.
- The bash script with the calls to `ctpService`.
- The log of the `yarprobotinterface` while the robot fails.

@gsisinna could assist in this.

**Comment by pfdominey** [comment]
Thanks for the continued efforts!

For ctpServices, I launch 4 seperate consoles and make these commands, respectively in the 4:

ctpService --robot icub --part right_arm
ctpService --robot icub --part left_arm
ctpService --robot icub --part head
ctpService --robot icub --part torso

Once these are running I then use the program:
protocol-balanced_fixing.sh
I send the .sh file by email because .sh is not allowed

from a console I execute:
./protocol-balanced_fixing.sh home
this works ok,  then I execute
./protocol-balanced_fixing.sh point6Right
in the video, we see this fail, with the wrist snapping down


[yarprunlog_12_10_2022_14_53_15-wrist-fail.log](https://github.com/robotology/icub-tech-support/files/9765039/yarprunlog_12_10_2022_14_53_15-wrist-fail.log)

**Comment by pfdominey** [comment]
more info:  here is the video of the joint failure

then in the second video, the wrist should be in the same position ("home" in the .sh script), but we see that it has fallen down

https://user-images.githubusercontent.com/32130758/195350253-10f3b6e3-6886-4b9b-8b44-ff600be16fd6.mp4


https://user-images.githubusercontent.com/32130758/195350594-234261dd-8636-4573-a204-4e64a770f7d6.mp4

**Comment by pattacini** [comment]
Thanks heaps @pfdominey for the useful info!

>I send the .sh file by email because .sh is not allowed

You can zip it and enclose in the issue.

**Comment by pfdominey** [comment]
the script is a bit messy.  what we use are the functions  seqA-seqJ, home, home_look, home_down, calibrate

each of he sequences of pointing movements seqA-seqJ each has 10 seperate pointings

**Comment by pfdominey** [comment]
can you see the videos?

**Comment by gsisinna** [comment]
> can you see the videos?

No @pfdominey, there no videos uploaded.

Thanks!

**Comment by pattacini** [comment]
>can you see the videos?

Yep, thanks 👍🏻 

Could you please try the following to be sure that we can log everything relevant?

On the PC104, launch the `yarprobotinterface` with the magic below that serves to redirect the output to a file:

```console
yarprobotinterface > output.log 2>&1
```

Finally, post here the file `output.log` produced.

**Comment by pfdominey** [comment]
ok you want me to run yarprobotinterface from the pc104 with the log file, and then duplicate the problem again?

**Comment by gsisinna** [comment]
Yes @pfdominey, by replicating the problem and extracting the log we would have all the useful information about it. Thanks

**Comment by pfdominey** [comment]
in this case, the wrist failed, fell down,  at the end of the calibration.  We did not have to use ctpServices
the 4 ctp services were not running.
I do not know how to transfer the log file from the pc104.  

can you tell me how to do that?

**Comment by pfdominey** [comment]
in the mean time I am going to shet everything off and then try again to make sure it was not due to an undefined state

**Comment by pattacini** [comment]
The latest failure may be due to the fact that you launched the yarprobotinterface not from the intended path.

Do this then:

```console
ssh pc104
cd /usr/local/src/robot/robotology-superbuild/src/robots-configuration/iCubDijon01
yarprobotinterface > output.log 2>&1
```

Afterwards, you should be able to retrieve the file `output.log` straight from the laptop from the following path:
```console
/exports/code/robotology-superbuild/src/robots-configuration/iCubDijon01
```

**Comment by pfdominey** [comment]
ok - when starting the robot from this directory, the wrist does not fail
now using ctpservices
the first use of ctpservice to move to our first (home) position causes the wrist to fall
[third-log-file.log](https://github.com/robotology/icub-tech-support/files/9765901/third-log-file.log)

**Comment by pfdominey** [comment]
here is a video where we have done this
ssh pc104
cd /usr/local/src/robot/robotology-superbuild/src/robots-configuration/iCubDijon01
yarprobotinterface > output.log 2>&1

the robot startup is good.  We then exeute this command
icub@icubsrv:~/pointing_sequences$ ./protocol-balanced_fixing.sh home
and at the wrist fails

https://user-images.githubusercontent.com/32130758/195372530-9c828772-a6aa-4c1e-bc07-620f74fb6332.mp4

**Comment by pfdominey** [comment]
in case the video is not visible, here is a link
https://youtu.be/1AlHn0kfhbs

**Comment by pattacini** [comment]
Do you have the `output.log` to share here?

**Comment by pfdominey** [comment]
it is above
https://github.com/robotology/icub-tech-support/files/9765901/third-log-file.log

**Comment by pfdominey** [comment]
Experiment 1 - starting the robot from yarpmanager gui
The wrist 'drops' during the calibration process - no need to invoke ctpservice
[yarprunlog_13_10_2022_10_15_14.log](https://github.com/robotology/icub-tech-support/files/9772382/yarprunlog_13_10_2022_10_15_14.log)

**Comment by pfdominey** [comment]
We just did testing with @gsisinna and everything is working
apparently there was only a problem with the red icon in the gui
there was the message
yarprun successfully executed on pc104

we then tested an updated set of movements that solicity joint 6 with smaller amplitudes, and we checked that movements were correct, and motorgui showed correct results

everything is working!  I will now proceed with some final testing before restarting our experiments next week.  After that I can close the issue

**Comment by gsisinna** [comment]
Thank you @pfdominey, I am glad that now the movements are going better and it seems to me that from the modification of the script you use for your tests it is going much better!

**Comment by pfdominey** [comment]
I can now happily say that we did extensive testing, did a restart of everything, and ...... the problem is closed!
Thanks @gsisinna and everyone on the team in Genoa!
We will start our experiments again on Monday!

**Comment by pattacini** [comment]
Glad that iCubDijon01 is back operative!

Thanks @davidelasagna @davidetome @gsisinna @Nicogene @traversaro!
