### ISSUE TITLE
[iCubGenova09] Battery went in protection and we cannot rechanrge it 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1438]
### Device name 🤖

iCubGenova09

### Request/Failure description

While debugging we kept the robot attached to the battery and unfortunately the power went to 0%. As a consequence the battery went in protection. Now we cannot recharge it anymore.  

### Detailed context

The battery went in protection mode

### Additional context

cc @S-Dafarra @DanielePucci @isorrentino @paolo-viceconte

**Comment by maggia80** [comment]
the battery is charging now. I left the cable to restart the battery mounted on the power supply with the correct setting
