### ISSUE TITLE
Right hand not working properly and left hand to be checked

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1440]
### Device name 🤖

iCubGenova09

### Request/Failure description

The right hand of the robot is having several issues

### Detailed context

Here the issues:
- right index distal broken
- right middle distal nearly broken
- right thumb oppose in a bad shape
- right thumb oppose hall sensor not working

**Comment by paolo-viceconte** [comment]
After today's integration tests, the following issues affect the robot:

1. The skin of the right index, middle, ring and pinky fingers does not work
2. The right wrist prosup and thumb proximal were often in HF due to hard limit reached
3. The robot battery does not recharge
4. The robot battery switch is not fixed to the cover and goes out while the robot walks

cc @DanielePucci @pattacini @S-Dafarra @GiulioRomualdi

**Comment by S-Dafarra** [comment]
> 2\. The right wrist prosup and thumb proximal were often in HF due to hard limit reached

This was probably due to the encoder, because it was possible to recover them afterwards

**Comment by emilianob80** [comment]
> > 2. The right wrist prosup and thumb proximal were often in HF due to hard limit reached
> 
> This was probably due to the encoder, because it was possible to recover them afterwards

the motor has been tested with the jogger and presents no problems. The encoder reads correctly

cc: @maggia80

**Comment by emilianob80** [comment]
> After today's integration tests, the following issues affect the robot:
> 
> 1. The skin of the right index, middle, ring and pinky fingers does not work
**T.B.D.**

> 2. The right wrist prosup and thumb proximal were often in HF due to hard limit reached
**wrist motor and the encoder are working correctly. The proximal thumb problem has been identified as mechanical (@GiacomoVassallo13 is working on it). It appears to be a loose tendon problem and therefore functioning is impaired

> 3. The robot battery does not recharge
**fixed**

> 4. The robot battery switch is not fixed to the cover and goes out while the robot walks
> **fixed**

> cc @DanielePucci @pattacini @S-Dafarra @GiulioRomualdi @maggia80 @Fabrizio69

**Comment by GiacomoVassallo13** [comment]
Hi, all the joints of right hand have been reworked. The proximal tendon windings have been ordered and stretched. No cables were replaced, as no damage was found. I am now going to check the left hand.

cc: @DanielePucci @pattacini @S-Dafarra @GiulioRomualdi @maggia80 @Fabrizio69

**Comment by pattacini** [comment]
The right hand is now working again.
