### ISSUE TITLE
Battery seems not charging 

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1441]
### Device name 🤖

iCubGenova09

### Request/Failure description

After some tests for the ANA Avatar XPRIZE, the battery seems not to charge (emitted current equal to zero) while the battery level is about 30%

### Detailed context

None

**Comment by isorrentino** [comment]
As soon as I turned off the motors and the head, I tried again and it starts charging. I don't know if this can help to understand what is going on.

**Comment by emilianob80** [comment]
The battery does not actually charge either normally or with the "wake-up" charge. For this reason it was decided to replace it with the new one in stock and investigate the problem on that one later.

cc: @maggia80

**Comment by emilianob80** [comment]
La batteria nuova carica

cc: @maggia80 @DanielePucci

**Comment by emilianob80** [comment]
La vecchia batteria é sotto test e sembra funzionare anche lei ora
