### ISSUE TITLE
Issues with the left hand skin

### ISSUE THREAD

**Issue by paolo-viceconte** [robotology/icub-tech-support#1443]
### Device name 🤖

iCubGenova09

### Request/Failure description

During today's integration tests, the skin of the left hand was not working. Both the fingers and the palm.

### Detailed context

Please see the above

### Additional context

cc @DanielePucci @S-Dafarra @GiulioRomualdi

**Comment by pattacini** [comment]
@emilianob80 fixed the problem.
We needed to remake a wire.
