### ISSUE TITLE
Strange noise coming from the ankles/knees when walking

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1444]
### Device name 🤖

iCubGenova09

### Request/Failure description

As per the title

### Detailed context

As per the title

**Comment by maggia80** [comment]
![image](https://user-images.githubusercontent.com/6987330/194669566-87c9ad60-fe10-4ec3-9ea3-21e8c974bcd8.png)

**Comment by emilianob80** [comment]
Bella soluzione. Ho anche dei modelli differenti di tappi nel caso quelli sopra fossero scomodi :-)

**Comment by DanielePucci** [comment]
Thanks for the nice suggestions above, we believe, however, that the problem is similar to the first video in (your, btw, issue) https://github.com/ami-iit/component_ANA-Avatar-XPRIZE/issues/775, which @maggia80 was able to reproduce, see https://github.com/icub-tech-iit/task-force-miscellanea/issues/97#issuecomment-998785553

The noise we hear is then **different** from that reported in https://github.com/icub-tech-iit/task-force-miscellanea/issues/97#issuecomment-997829140
