### ISSUE TITLE
Left wrist yaw encoder issues

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1445]
### Device name 🤖

iCubGenova09

### Request/Failure description

After some use, the left wrist encoder yaw indicates more than 300degs

### Detailed context

We were doing some gentle motions while holding a light bottle.After a while, the encoder started reading strange values and the joint went into hardware fault

cc @DanielePucci @isorrentino @pattacini @maggia80 @emilianob80

**Comment by emilianob80** [comment]
@S-Dafarra on Monday morning I will wire a sensor on the bench in order to replace it completely on Monday or, if there is no time, in Los Angeles as soon as the robot is available.

cc: @DanielePucci @maggia80

**Comment by S-Dafarra** [comment]
Just to be sure, were you referring to this issue, or to https://github.com/robotology/icub-tech-support/issues/1446?

**Comment by emilianob80** [comment]
> Just to be sure, were you referring to this issue, or to #1446?

I was referring to the problem of the encoder pulse (subject of the issue). Regarding the FT sensor problem comment in the reference question

cc: @pattacini @maggia80 @DanielePucci

**Comment by maggia80** [comment]
the value read by the AEA encoder could go from 0 to 360 degrees. If it reads a number that is in this range it's quite probable that is reading correctly. 
We should check if the magnet is blocked or if it's loose and rotates.

**Comment by maggia80** [comment]
the magnet was rotating inside its housing. @Gandoo glues it properly. 

We need to calibrate the left wrist yaw once in LA.

cc: @davidetome

**Comment by davidetome** [comment]
> the magnet was rotating inside its housing. @Gandoo glued it properly.
> 
> We need to calibrate the left wrist yaw once in LA.
> 
> cc: @davidetome

I guess we also need to adjust its position before calibrating the joint, am I right @maggia80 ?

**Comment by maggia80** [comment]
> > the magnet was rotating inside its housing. @Gandoo glued it properly.
> > We need to calibrate the left wrist yaw once in LA.
> > cc: @davidetome
> 
> I guess we also need to adjust its position before calibrating the joint, am I right @maggia80 ?

no, the wrist yaw it's read by an AEA and we don't need to adjust it.

**Comment by davidetome** [comment]
> no, the wrist yaw it's read by an AEA and we don't need to adjust it.

yep! I was confusing w/ the fingers
