### ISSUE TITLE
Left pinky sometimes does not calibrate

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1447]
### Device name 🤖

iCubGenova09

### Request/Failure description

The left pinky finger does not calibrate properly

### Detailed context

During calibration, the left pinky closes but it does not open.

**Comment by maggia80** [comment]
what's the value of joint position after calibration? 
Could you move the pinky after calibration if you enable it from the motorgui?

**Comment by S-Dafarra** [comment]
> what's the value of joint position after calibration? Could you move the pinky after calibration if you enable it from the motorgui?

It was not calibrated. We did not check the value, but it was not crazy. Now it seems to calibrate, so probably it is just slightly miscalibrated

**Comment by emilianob80** [comment]
It seems unnecessary to intervene on the HW. Do I consider this issue closed @S-Dafarra  @maggia80 ?

cc: @DanielePucci  @pattacini

**Comment by S-Dafarra** [comment]
Probably it is just matter of tweaking the joint calibration
