### ISSUE TITLE
Left wrist pronosupination becomes uncontrollable and then it goes to HF

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1449]
### Device name 🤖

iCubGenova09

### Request/Failure description

After some time, the left wrist pronosupination starts having large tracking errors, and then it goes to HF mentioning that the joint is outside the limits.

### Detailed context

The encoder seems to diverge and then the joint is no more controllable.

**Comment by maggia80** [comment]
@S-Dafarra do you remember the value read by the pronosup joint?

**Comment by S-Dafarra** [comment]
> @S-Dafarra do you remember the value read by the pronosup joint?

Unfortunately no, but it slowly went out of the pronosup limits
