### ISSUE TITLE
[iCubGenova09] Right index distal broken

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1450]
### Device name 🤖

iCubGenova09

### Request/Failure description

The right index distal got broken while teleoperating

### Detailed context

cc @DanielePucci @S-Dafarra

**Comment by maggia80** [comment]
@GiacomoVassallo13 when we will be in LA, please first check in which place the tendon is broken. We should understand if the tendon is more subject to damage wrt the standard coated one. Or if the failure is at the level of the knot.
