### ISSUE TITLE
Left wrist behaving not correctly 

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1451]
### Device name 🤖

iCubGenova09

### Request/Failure description

Unfortunately we just noticed that the left wrist does not follow the reference positions, although is up and running. It seems like it slides internally

### Detailed context

As above

**Comment by emilianob80** [comment]
@S-Dafarra The problem seems to be due to the magnet which was not glued in its seat and therefore moved in certain operations. Problem fixed. Tested with the jogger and working

cc: @maggia80 @DanielePucci @gaurvigoyal

**Comment by Gandoo** [comment]
on the carbon palm the spacers are broken, fixed and reassembled after gluing the magnet

![20221010_062716](https://user-images.githubusercontent.com/53341641/194803315-d403d6da-9a9f-4b00-968f-8e365d416102.jpg)

![20221010_062130](https://user-images.githubusercontent.com/53341641/194803323-373b5bf8-13c3-4acc-91c6-f06a410398c6.jpg)

cc: @maggia80 @DanielePucci @gaurvigoyal
