### ISSUE TITLE
Torso roll tendon is loose

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1452]
### Device name 🤖

iCubGenova04

### Request/Failure description

While performing some tests for the wind tunnel experiment of 3-4 November, we noted that the torso roll tendon was loose.

Even after tightening with the help of @GiacomoVassallo13 the situation did not improve. Probably the tendon is a bit deformed.

### Detailed context

If the operation of replacing the tendon is too long, we can perform it after the robot comes back from wind tunnel.

**Comment by GiacomoVassallo13** [comment]
Hi. Sorry if I'm late. The problem was solved and the tendon tensioned. I continue with the closure of the issue.

@cc: @Fabrizio69 @gabrielenava
