### ISSUE TITLE
R1 does not start

### ISSUE THREAD

**Issue by marcoaccame** [robotology/icub-tech-support#1458]
### Device name 🤖

R1

### Request/Failure description

I open a ticket from what @randaz81 has told me. Pls @randaz81 complete or change the following info as you like.

On October 20, I receive from @randaz81 the following picture telling that yarprobotinterface does not start w/ latest devel.

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/7148284/201318671-7d53d75d-eeec-474c-9fee-6ebdef500608.png)

Following this piece of news, in iCub Tech we did tests on our setups and we did not see the problem.

Nevertheless, as today, `yarprobotinterface` on R1 still does not start if devel is used over docker. 

### Detailed context

pls @randaz81 attach:
- a log, 
- a screenshot of `FirmwareUpdater` w/ info about the FW versions of the ETH boards.
- the SHAs of `icub-main` and `icub-firmware-shared`.

### Additional context

The system uses `docker`.

**Comment by randaz81** [comment]
About the boards' firmware:
![image](https://user-images.githubusercontent.com/2869969/201889019-6e0ee6a8-dd70-40d9-b5b2-921c498da41b.png)

This is the SHA of icub-main which is **working**:
![image](https://user-images.githubusercontent.com/2869969/201889347-4bbba9ea-58d2-4b5f-ba2c-e0ebc1237cba.png)

This is the SHA of icub-firmware-shared which is **working**:
![image](https://user-images.githubusercontent.com/2869969/201889492-7a8c3c57-bd99-4b54-a7ec-1453e99e41e1.png)

If I use the latest devel for icub-main/icub-firmware-shared instead, I get the cryptic error mentioned above.

Please provide support.

**Comment by pattacini** [comment]
As agreed w/ @randaz81, we will start processing this request the next week as we're now busy w/ ergoCub SN000.

**Comment by marcoaccame** [comment]
Thanks @randaz81. I will look at that as soon as possible.

**Comment by pattacini** [comment]
Hi @randaz81 

We experienced a very similar problem while fiddling with the ergoCub binaries, which were not up-to-date and pretty much of the same age as yours.

However, by flashing the very latest devel versions of the binaries, we didn't spot the problem again.
Thus, while we're doing our investigation to narrow down the cause, you may consider flashing the latest devel.

**Comment by marcoaccame** [comment]
Hi all, here are some tests on the latest distros.

@sgiraz and I have verified  `yarprobotinterface` in various distros starting from `2022.08.0` until the latest `2022.09.1`. 

We tested two different setups: 

- one with an `ems`  running the multiple FT service (laptop, `ems `board, `strain2 `board), 
- one with an `mc4plus` running the MC service (laptop, `mc4plus `board, DC motor).

They all behaved in the correct way. In here a summary of the results



| DISTRO    | RESULT | YARP   | icub-main | icub-fw-shared | icub-fw-build | ems   | mc4plus |
| --------- | ------ | ------ | --------- | -------------- | ------------- | ----- | ------- |
| 2022.09.1 | OK     | v3.7.2 | v1.28.1   | v1.27.0        | v1.27.0       | v3.54 | v3.52   |
| 2022.09.0 | OK     | v3.7.2 | v1.28.1   | v1.27.0        | v1.27.0       | v3.54 | v3.52   |
| 2022.08.1 | OK     | v3.7.2 | v1.28.1   | v1.27.0        | v1.27.0       | v3.54 | v3.52   |
| 2022.08.0 | OK     | v3.7.2 | v1.27.0   | v1.26.0        | v1.26.0       | v3.53 | v3.51   |



For more details see the page of the label required for each DISTRO: https://icub-tech-iit.github.io/documentation/sw_versioning_table/#software-versioning-table

**Comment by sgiraz** [comment]
Hi @randaz81, 

To solve the problem reported, you may try to use even the latest devel versions or one of the distros reported above.
Please provide us with feedback.

cc @pattacini @marcoaccame

**Comment by marcoaccame** [comment]
> Hi @randaz81,
> 
> To solve the problem reported, you may try to use even the latest devel versions or one of the distros reported above. Please provide us with feedback.
> 
> cc @pattacini @marcoaccame

And yes, the latest devel versions of `icub-main`, `icub-firmware-shared` and `icub-firmware-build` also work. We have testde them w/ `YARP` v3.7.2.

**Comment by marcoaccame** [comment]
Today w/ @randaz81 and @sgiraz we updated to the latest devel and the robot starts correctly.

So, for now I will close the issue.
