### ISSUE TITLE
iCubGenova11 - The right arm fingers do not complete the calibration

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1459]
### Device name 🤖

iCubGenova11

### Request/Failure description

As per the title, the finger of the right arm do not complete the calibration procedure.

They close but they don't go back in the home configuration as they should. 

Please check out the picture below.

![image](https://user-images.githubusercontent.com/6014499/201765296-e4400b4c-bf7a-4ad3-b00c-61c58ade1e2a.png)

### How does it affect you?

We cannot perform grasping action with the right arm.

**Comment by xEnVrE** [comment]
This evening we tried the robot after the maintenance activity. Sometimes, the right hand fingers still do not calibrate.

**Comment by AntonioConsilvio** [comment]
I fixed this problem, I tried `yarprobotinterface` and it never failed.

cc @Fabrizio69
