### ISSUE TITLE
iCubGenova11 - Cannot perform the arms fine calibration

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1461]
### Device name 🤖

iCubGenova11

### Request/Failure description

This evening we tried performing the arms fine calibration together with @AntonioConsilvio.

However, we found that, at the moment, a combination of the low level joints calibration + the software limits do not allow reaching one of three configuration as per https://icub-tech-iit.github.io/documentation/icub_robot_calibration/icub-robot-calibration-v2.x/#arms-fine-calibration.

Specifically, we cannot move the `*_shoulder_roll` joints below 15 degrees which would allow us to reach the configuration depicted in the documentation website:

![image](https://user-images.githubusercontent.com/6014499/201776902-37fb6275-33b6-4109-a087-30418fc0ad42.png)

Is it safe to change the software mechanical limits below 15 degrees?

### How does it affect you?

We cannot perform the arms fine calibration which is required in order to properly use the forward kinematics of the robot.

**Comment by maggia80** [comment]
it seems that the draft calibration was very far from the initial position. To proceed with the fine calibration, you could disable the joints and move them in the correct position by hand. Alternatively, it's better to do the calibration again for the first 4 joints.

**Comment by xEnVrE** [comment]
I think this can be closed as the fine calibration has been performed today during the general maintenance activity of the robot.

**Comment by pattacini** [comment]
Just reopening this task, as we need to understand the interference between the torso and the upper arm covers.

As a quick workaround, the torso front cover can be removed.

Need to plan this w/ @Fabrizio69 and @AntonioConsilvio.

cc @xEnVrE

**Comment by xEnVrE** [comment]
Today, with the help of @pattacini, the fine calibration has been performed successfully while the cover was not in place on the robot.

Next, we verified, with some surprise, that the torso front cover can be actually reinstalled even when the joints are in the {-90, 15, 15, 90} calibration configuration without collisions.

**Comment by AntonioConsilvio** [comment]
Good job! 

I am closing this issue, if you have problems on this topic, you can reopen it @xEnVrE.

cc @pattacini @Fabrizio69 @maggia80
