### ISSUE TITLE
iCubGenova11 - Warped range of motion for both thumb opposition joints

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1462]
### Device name 🤖

iCubGenova11

### Request/Failure description

The range of motion of both hands thumb opposition is warped in that when commanding the joint towards 90 degrees the joint moves way beyond 90 degrees (check out the picture)

![image](https://user-images.githubusercontent.com/6014499/202026751-df08e7d9-1eee-482b-8cf7-9a1364c76936.png)
> this is the **left** hand

We also noticed that while using the finger the range is still warped but it expands or decompresses. I.e., sometimes we can only move between say, ~12 degrees and 25 degrees. Some other times it expands to a different range between say, ~12 degrees and ~ 50 degrees.

For this reason, it seems that it is not just an offset in the calibration. Rather, the magnet of the hall effect sensor might be not properly placed as the readings are not linear with respect to the joint motion.

**Comment by pattacini** [comment]
This should be fixed.
Could you confirm that @AntonioConsilvio?

**Comment by AntonioConsilvio** [comment]
Yes @pattacini, I turned the magnet in both thumbs, and recalibrated. I tried several times and seems work without problems.

cc @Fabrizio69

**Comment by pattacini** [comment]
Well done!
Closing then.
