### ISSUE TITLE
Left pinky distal tendon broken

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1469]
### Device name 🤖

iCubGenova09

### Request/Failure description

The tendon of the left pinky is broken.

### Detailed context

It got broken while in Rome for a demo

**Comment by GiacomoVassallo13** [comment]
Hi, the distal pinkie tendon has been replaced.

cc: @S-Dafarra @AntonioConsilvio

**Comment by S-Dafarra** [comment]
It is working as expected
