### ISSUE TITLE
[ R1SN003 ] - Left Wrist tripod seems broken, does not moving

### ISSUE THREAD

**Issue by ste93** [robotology/icub-tech-support#1475]
### Device name 🤖

R1SN003

### Request/Failure description

When starting the robotinterface the left wrist is not moving, it fails the calibration. 

### Detailed context

(log in description)

### Additional context

[yarprunlog_06_12_2022_17_21_15.log](https://github.com/robotology/icub-tech-support/files/10168798/yarprunlog_06_12_2022_17_21_15.log)

**Comment by ste93** [comment]
@elandini84

**Comment by maggia80** [comment]
cc: @fbiggi

**Comment by fbiggi** [comment]
@elandini84 @ste93 
R1 SN003 ripristinato 
La cinghia del motore M0 era fuori sede
Dopo il rispristino abbiamo provato la calibrazione con @ste93 e movimenti con motorgui con esito POSITIVO



![20221213_093810](https://user-images.githubusercontent.com/20420331/207288475-7e36063e-1865-4165-8eb2-a8c231357107.jpg)
![20221213_093840](https://user-images.githubusercontent.com/20420331/207288488-829c387e-2c0f-447b-8790-c06127f4c293.jpg)

@AntonioConsilvio chiudo la issues come detto F2F 

CC @maggia80 @Fabrizio69 @randaz81
