### ISSUE TITLE
iCubGenova11 - Several problems with fingers joints. 

### ISSUE THREAD

**Issue by fedeceola** [robotology/icub-tech-support#1476]
### Device name 🤖

iCubGenova11

### Request/Failure description

As per title, iCubGenova11has several problems with fingers joints.

### Detailed context

Today @AntonioConsilvio, @xEnVrE and me made some tests on iCubGenova11. We noticed the following issues with the fingers:
- `r_little-fingers` moves in the range 0-270 degrees, but on the encoders we can read values in the range 50-270 degrees.
- `l_little-fingers` has the same problem as `r_little-fingers`.
- Left index doesn't move when moving the `l_hand_finger`.
- There is a misalignment between the values set for `r_thumb_oppose` and the feedback in the `yarpmotorgui`. See screenshot below.
![image](https://user-images.githubusercontent.com/32268209/207079076-aae93540-c8f9-4df6-b86a-d69ab8d397c3.png)
- The same problem occurs also for `l_thumb_oppose`, `l_hand_finger`and `r_hand_finger`.
- `r_middle-proximal` doesn't reach the value of 90 degrees. See screenshot below.
![image](https://user-images.githubusercontent.com/32268209/207080004-729b90f5-ca23-4a40-bedf-ee982ec1d9bc.png)

**Comment by fedeceola** [comment]
Hi @maggia80, thanks for the reply. 
I just made some additional tests. The problem seems to be in the slider of the `yarpmotorgui`.

https://user-images.githubusercontent.com/32268209/207266661-74e156e9-f33a-49a9-aedb-5eacddaa0d65.mp4

When I give a target position to the `r_thumb_oppose`, `l_thumb_oppose`, `l_hand_finger`and `r_hand_finger` joints the blue target rectangle moves on the right. For all the other joints this doesn't occur.

**Comment by AntonioConsilvio** [comment]
Hi, @fedeceola and I decided on Wednesday afternoon 21 to recalibrate ring and pinky of both hands.

cc @Fabrizio69

**Comment by xEnVrE** [comment]
Hi @AntonioConsilvio,

Regarding the issue 

>  r_middle-proximal doesn't reach the value of 90 degrees.

could it also be a calibration problem?

Do you think is it possible to also calibrate this finger this Wednesday?

Thanks

**Comment by AntonioConsilvio** [comment]
> Hi @AntonioConsilvio,
> 
> Regarding the issue
> 
> > r_middle-proximal doesn't reach the value of 90 degrees.
> 
> could it also be a calibration problem?
> 
> Do you think it is possible to also calibrate this finger this Wednesday?
> 
> Thanks


Hi @xEnVrE, I am not sure if it is a calibration problem, I have another idea, however I will definitely try on Wednesday.

**Comment by AntonioConsilvio** [comment]
Hi @xEnVrE @fedeceola , we recalibrated the little finger of both hands. Also, we pulled the abduction steel cables of both hands.

Now the proximal middle can reach 90 degrees. 

So the problems of this issue have been solved as much as possible.

cc @maggia80 @Fabrizio69
