### ISSUE TITLE
Right arm shoulder tendon broken

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1484]
### Device name 🤖

iCubGenova04

### Request/Failure description

The right arm shoulder tendon broke while the robot was moving to the home position on the pole.

### Detailed context

cc @DanielePucci @S-Dafarra 

### How does it affect you?

we have a demo on Monday, would it be possible to repair the robot today or tomorrow morning?

**Comment by AntonioConsilvio** [comment]
Hi @gabrielenava, @GiacomoVassallo13 and I replaced damaged cables (7 and 8) with two new ones. 

I await feedback on the operation of the robot.

cc @Fabrizio69

**Comment by gabrielenava** [comment]
hello @AntonioConsilvio 

we tested the robot by running the Yoga++ demo several times. it worked with no issues!

thanks again, we can close the issue
