### ISSUE TITLE
iCubGenova11 - One of the neck belts seems damaged

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1486]
### Device name 🤖

iCubGenova11

### Request/Failure description

We noticed that one of the neck belts seems damaged. See the following picture.

![image](https://user-images.githubusercontent.com/6014499/213407897-ea9278d3-8d76-47b9-984a-db85ed595fe9.png)

We were wondering whether it is the case to substitute it.

**Comment by AntonioConsilvio** [comment]
Hi @xEnVrE, me and @GiacomoVassallo13 replaced the damaged neck belt with a new one. We tried it and it seems work without any problem. 

Should the new belt cause problems, you can reopen this issue.

cc @Fabrizio69

**Comment by xEnVrE** [comment]
Thanks @AntonioConsilvio @GiacomoVassallo13
