### ISSUE TITLE
iCubGenova09 – Jumps on the estimated yaw angle provided by the robot IMU

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1487]
### Device name 🤖

iCubGenova09

### Request/Failure description

I collected the orientation data coming from the robot imu mounted on the FTs and I noticed some jumps on the yaw angle. This may be related to #1485.

### Detailed context

We collected the data as follows:
1. we put the robot on the pole
2. We collected the data using the multianalogsensor interface

Let us now define ${}^0 R_{imu}$ the orientation coming from the IMU w.r.t. the IMU inertial frame (denoted with 0). Let us now introduce $I$ the inertial frame considered by the kinematics. We would like to compare ${}^I R _ {imu}$ with $\prescript{I}{}{R} _ {expected}$ that is computed by the forward kinematics. ${} ^ I R_{imu}$  is given by $${}^I R_{imu} = {}^I R_{0} {}^0 R _{imu}$$ 
where ${}^I R _{0}$ is computed using the first readout of the imu as 
$${}^I R _{0} = {}^I R _{imu}(0)  {}^0 R _{imu}(0)^\top$$ 

We collected two datasets:
1. The joints move from the homing configuration to a configuration where all leg joint positions are equal to 0. The associated dataset is called **`2023_01_12_13_16_07.mat`**
2. I set the leg joints configuration to 0 then I put the hip roll and pitch joints in idle so I can manually move the leg. This experiment (suggested by @traversaro) allows us to have the pitch and roll angle of the IMU in the legs equal to the one on the foot. The associated dataset is called **`2023_01_18_16_39_51.mat`** 

Both the datasets can be found here: [datasets.zip](https://github.com/robotology/icub-tech-support/files/10458253/datasets.zip)

What follows are the plots associated with the experiment (1) (dataset **`2023_01_12_13_16_07.mat`**)

| `r_leg`| `r_foot_front` | `r_foot_rear`|
|:--:|:--:|:---:|
| ![rpy](https://user-images.githubusercontent.com/16744101/213495380-e39ebbb0-acfa-448b-806d-f7d379e42300.png) | ![rpy](https://user-images.githubusercontent.com/16744101/213495421-263e3de6-60ac-4f39-8878-d7ae27f6028e.png) | ![rpy](https://user-images.githubusercontent.com/16744101/213495608-fd1b98b3-2c38-4dcb-b901-315c77a70b8b.png) |
| **`l_leg`**| **`l_foot_front`** | **`l_foot_rear`**|
| ![rpy](https://user-images.githubusercontent.com/16744101/213497725-1fc9e2cb-87e5-45ed-8667-d99913a1012b.png) | ![rpy](https://user-images.githubusercontent.com/16744101/213497407-3868f767-d92f-4c47-b94a-68df569143cc.png) | ![rpy](https://user-images.githubusercontent.com/16744101/213497618-b3b34e2d-266e-4f5b-9518-30316c82678a.png)  |

As you can notice in the `left leg` the **yaw** angle jumps several times, as far as I can notice in the following plot (please notice that is the same plot as the **`l_leg`** plot in the above table with some labels) the jumps are not due the wrapping of the angle between (-180 +180 or 0 360). On the other hand, the roll angle jumps between +180 to -180 (and this is expected)

Moreover as far as I know at the instant in which the yaw jumps we are not in a **gimbal lock situation**.

![image](https://user-images.githubusercontent.com/16744101/213502947-e85749ed-1073-45ab-91ce-14079c539b29.png)

Since the strange jumps seem to appear only on the yaw axis we decide to substitute the yaw angle with the one provided by the forward kinematics. So I defined 
 $${}^I R_{imu, fk} = R_{z}^{fk} R_{y}^{imu}  R_{x}^{imu}$$ then I compared ${}^I R _ {imu}$ and ${}^I R_{imu, fk}$ with $\prescript{I}{}{R} _ {expected}$, as you can notice in the following videos when the yaw angle is forced to be the one provided by the forward kinematics the two frames almost coincide.

<details><summary>Videos of the dataset <b><tt>2023_01_12_13_16_07.mat</tt></b> </summary>
<p>

| | IMU   | IMU w/ yaw correction |
|:---:|:---:|:---:|
| `r_leg` | <video src="https://user-images.githubusercontent.com/16744101/213488713-81be6426-6574-42db-adfe-a7a5f1771048.mp4"> |  <video src="https://user-images.githubusercontent.com/16744101/213488647-8eed7c4a-faad-4018-9eb8-68738ca2b2d1.mp4"> |
| `r_foot_front` | <video src="https://user-images.githubusercontent.com/16744101/213488853-9d121461-94ee-4627-8dc5-898f562a4859.mp4">  | <video src="https://user-images.githubusercontent.com/16744101/213488795-1d2e38e7-6ec8-4862-9219-527160b40737.mp4"> |
| `r_foot_rear` | <video src="https://user-images.githubusercontent.com/16744101/213488911-bba4237a-8ced-4546-aa47-c733e6e92b9f.mp4"> |  <video src="https://user-images.githubusercontent.com/16744101/213488964-f81d9ba2-c876-4ec1-9d0a-62e1df62ca80.mp4"> |
| `l_leg` | <video src="https://user-images.githubusercontent.com/16744101/213515197-8f4fbe3a-a545-4205-a9c7-6141d6692fb9.mp4"> |  <video src="https://user-images.githubusercontent.com/16744101/213512508-ce5be07a-a211-433e-9629-8ac61141c028.mp4"> |
</p>
</details>

<details><summary>Videos of the dataset <b><tt>2023_01_18_16_39_51.mat</tt></b> </summary>
<p>

| | IMU   | IMU w/ yaw correction |
|:---:|:---:|:---:|
| `r_leg` | <video src="https://user-images.githubusercontent.com/16744101/213484329-6f2ea6d9-9e52-47a0-bdc7-82cf0680a5c0.mp4"> |  <video src="https://user-images.githubusercontent.com/16744101/213483960-7723c18d-000c-42c6-8623-b09db3fc3382.mp4"> |
| `r_foot_front` | <video src="https://user-images.githubusercontent.com/16744101/213484812-b8af13ee-8e20-41c9-b1eb-69e575e7b81c.mp4">  | <video src="https://user-images.githubusercontent.com/16744101/213484656-c2f5307d-6727-4ae3-8e7b-3548eaf45757.mp4"> |
| `r_foot_rear` | <video src="https://user-images.githubusercontent.com/16744101/213485100-4494d270-2081-459a-8197-4f79e1a74c12.mp4"> |  <video src="https://user-images.githubusercontent.com/16744101/213484995-a9393246-5c96-432b-87ab-2efe60cd3bab.mp4"> |

</p>
</details>

⚠️ I was wondering if this behavior is connected to #1485 given the fact that the magnetometer value is mostly used to detect the yaw. 

### Additional context

Similarly to https://github.com/robotology/icub-tech-support/issues/1485 I opened the issue in tech-support but I don't think it is an issue specifically related to the iCubGenova09.

cc @pattacini @traversaro @G-Cervettini

**Comment by traversaro** [comment]
Apparently the issue is happening just on FT58, and not on FT45 . Did you checked which version of firmware is loaded on these devices?

**Comment by traversaro** [comment]
Apparently the issue is happening just on FT58, and not on FT45 . Did you checked which version of firmware is loaded on these devices?

**Comment by traversaro** [comment]
Apparently the issue is happening just on FT58, and not on FT45 . Did you checked which version of firmware is loaded on these devices?

**Comment by traversaro** [comment]
Another thing that I think could be interesting is to plot in the same figure the yaw from the sensor and the one from the kinematics.

**Comment by GiulioRomualdi** [comment]
> Another thing that I think could be interesting is to plot in the same figure the yaw from the sensor and the one from the kinematics.


Hi @traversaro as you suggested I show you the plots of the rpy angle provided by the IK and the rpy extracted by ${} ^ I R_{imu}$
⚠️ ⚠️ As discussed in https://github.com/robotology/icub-tech-support/issues/1487#issue-1549606868 ${}^I R _ {imu}$ is not directly provided by the imu but is given by
 $${}^I R_{imu} = {}^I R_{0} {}^0 R _{imu}$$ 
where ${}^I R _{0}$ gives us the possibility to align the orientation provided by the IMU to the FK orientation at the initial time instant.

Here are the plots, as you can notice the roll and pitch angles of the IMU follow the one evaluated by the FK. On the other hand, there is a mismatch regarding the yaw. In details on the `leg` imus (FT58), there are some jumps, while on the feet imus (FT45) the signal seems to be smooth but once the $yaw_{FK}$ increases the $yaw_{IMU}$ decreases and vice-versa.


| `r_leg`| `r_foot_front` | `r_foot_rear`|
|:--:|:--:|:---:|
| ![rpy_imu_fk](https://user-images.githubusercontent.com/16744101/213728988-4ae78e84-dcf6-4df8-b6e7-abb8388ac383.png) | ![rpy_imu_fk](https://user-images.githubusercontent.com/16744101/213729040-8b4cdf4d-4b81-4cb2-8df7-2fcc51e6dcd0.png) | ![rpy_imu_fk](https://user-images.githubusercontent.com/16744101/213729096-e0050711-b04e-4a0f-896f-9ca76f8515c6.png) | 
| **`l_leg`**| **`l_foot_front`** | **`l_foot_rear`**|
| ![rpy_imu_fk](https://user-images.githubusercontent.com/16744101/213729159-bec36780-4e1e-4cf5-b1e4-27f64123c981.png) | ![rpy_imu_fk](https://user-images.githubusercontent.com/16744101/213729187-64360cdf-e332-4644-b7c5-088cd11ab04b.png) | ![rpy_imu_fk](https://user-images.githubusercontent.com/16744101/213729214-338f1e8e-83d3-4bd0-9966-fc2456517501.png) |

**Comment by traversaro** [comment]
By the way, sorry for the random suggestsions, but if the joints after the leg FT sensor and before the foot are constant, another thing that it would be interested to check is to plot {}^{l_foot_front} R_{l_foot_rear} and {}^{l_foot_front} R_{l_leg} . They should be constant, but if they are not constant something wrong is going on.

**Comment by AntonioConsilvio** [comment]
Hi @traversaro @GiulioRomualdi, we are organizing to address this issue in early February.

cc @maggia80 @Fabrizio69 @pattacini

**Comment by pattacini** [comment]
Just planned for this sprint!

**Comment by Nicogene** [comment]
We noticed similar jumps on yaw also inspecting the eul data with reading from the [simulink model](https://github.com/icub-tech-iit/ft-sensors-simulink)


![immagine](https://user-images.githubusercontent.com/19152494/218687442-25ae70e4-4dad-4780-8b81-93a8dd13d401.png)

**Comment by Nicogene** [comment]
Alongside @mfussi66, we managed to use `ft-sensor-simulink` for reading imu data from the `rfe` board. The magnetometer **does not** stream all zeros, and on the yaw of the Euler angle, we do not have unexpected jumps.

Here is the plot of the Euler angles:


![immagine](https://user-images.githubusercontent.com/19152494/220414115-6929bd81-9580-4e61-b713-2deb21c077cf.png)

**Comment by GiulioRomualdi** [comment]
That's wonderful! This activity was pivotal for enabling the usage of the feet imu in the walking infrastructure! Really thank you!

Cc @G-Cervettini @DanielePucci

**Comment by DanielePucci** [comment]
Super cool, thanks @Nicogene @marcoaccame

**Comment by Nicogene** [comment]
The fix has been delivered also in terms of binaries:
- https://github.com/robotology/icub-firmware-build/pull/77

I think we can close the issue 🚀 

cc @GiulioRomualdi
