### ISSUE TITLE
Right arm shoulder tendons broke

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1491]
### Device name 🤖

iCubGenova04

### Request/Failure description

several right shoulder tendons got broken during an iRonCub experiment

### Detailed context

after switching off the controller, the arm started to oscillate and this lead to the tendons to broke before we were able to fault the robot

### How does it affect you?

we have a demo and more experiments on Monday

**Comment by DanielePucci** [comment]
@Fabrizio69 @maggia80 unfortunately, on Monday late afternoon and Wednesday we have two important demos https://github.com/ami-iit/lab-events-demos/issues/236 and https://github.com/ami-iit/lab-events-demos/issues/237 

Let us know you can help with fixing the robot, thanks

**Comment by AntonioConsilvio** [comment]
Hi @DanielePucci, we will fix this issue this morning.

cc @Fabrizio69 @gabrielenava @maggia80

**Comment by AntonioConsilvio** [comment]
Hi @gabrielenava, @GiacomoVassallo13 and I replaced damaged cables (6, 7 and 8) with three new ones.

I await feedback on the operation of the robot.

cc @Fabrizio69

**Comment by DanielePucci** [comment]
Thank you all guys, it was important to have the robot fully working today

**Comment by gabrielenava** [comment]
>I await feedback on the operation of the robot.

it is working fine now, thanks @AntonioConsilvio!
