### ISSUE TITLE
iCubGenova11 - Problem with r_hand joint. #1492

### ISSUE THREAD

**Issue by fedeceola** [robotology/icub-tech-support#1494]
### Device name 🤖

iCubGenova11

### Request/Failure description

The `r_hand` joint moves in the wrong way. Fingers are open when its position is set to 60° and closed when set to 0°. 

### Detailed context

-

**Comment by pattacini** [comment]
Related to #1492.

**Comment by AntonioConsilvio** [comment]
Hi @fedeceola this problem has been solved, I rotated the magnet being read by the adduction hall sensor (2B2H3). Then I reversed the PID and now the adduction moves in the right direction. 

cc @Fabrizio69 @sgiraz
