### ISSUE TITLE
Right wrist tendon out of place

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1496]
### Device name 🤖

iCubGenova09

### Request/Failure description

One of the wrist tendons is out of place, probably damaged.

### Detailed context

During the visit of the Osaka group, there were a lot of energic handshakes and one tendon broke.

![image](https://user-images.githubusercontent.com/18591940/216274985-5eee4a5b-b6c0-4293-9731-5115c2ee3fae.png)

**Comment by sgiraz** [comment]
Hi @S-Dafarra,

@GiacomoVassallo13 is going to take a look at it today.

**Comment by AntonioConsilvio** [comment]
Hi @S-Dafarra, @GiacomoVassallo13 replaced the steel cable.

When you can, please send us feedback on the operation of the robot.

cc @sgiraz

**Comment by S-Dafarra** [comment]
Hi @AntonioConsilvio, it seems functional! Thanks
