### ISSUE TITLE
Broken tendon in right thumb (does not calibrate distal thumb)

### ISSUE THREAD

**Issue by GiuliaScorzaAzzara** [robotology/icub-tech-support#1497]
### Device name 🤖

iCubGenova07

### Request/Failure description

During the initial calibration, the robot does not calibrate the distal thumb in the right hand. 

### Detailed context

We noticed that the tendon is broken (i.e., the cable is cut). It is necessary to replace the cable.

**Comment by sgiraz** [comment]
Hi @GiuliaScorzaAzzara,

We gonna check it asap.
Stay tuned!

**Comment by sgiraz** [comment]
The maintenance activity is planned for Wednesday, 15 at 2 p.m.

**Comment by AntonioConsilvio** [comment]
Hi @GiuliaScorzaAzzara, @GiacomoVassallo13 and I replaced the distal tendon of the thumb. We tested the robot and it seems to work without any problems.




https://user-images.githubusercontent.com/114915464/219090033-df4ee2e8-88c1-4d86-b097-761ba0d2a938.mp4


cc @sgiraz
