### ISSUE TITLE
Face expression stopped to work

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1498]
### Device name 🤖

ergoCubSN000

### Request/Failure description

Face expression of the robot stopped to work.

### Detailed context

In order to enable wbd on `ergocub-torso`, we have installed the robotology-superbuild dependencies using the [`install_apt_dependencies.sh`](https://github.com/robotology/robotology-superbuild/blob/master/scripts/install_apt_dependencies.sh) script. While doing this, however, the following message was raised:
![photo1675931605](https://user-images.githubusercontent.com/35487806/217758978-eff2a35e-90cc-4e8b-bf7b-d85b535a79eb.jpeg)
we continued, but after a while we realized the face expressions stopped to work (I guess it was the service that was supposed to be restarted). After restarting the robot motors and CPU, the face expression seems to be still off.

cc @GiulioRomualdi @mebbaid

**Comment by pattacini** [comment]
@AntonioConsilvio reported that by unplugging and then plugging the HMDI back again solved the problem.
We should better inquire about the root cause of this.

**Comment by lrapetti** [comment]
Thanks for checking, for me the issue can be close and we will monitor if it happens again!
