### ISSUE TITLE
iCubGenova09 – Communication issues on left arm CAN

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1499]
### Device name 🤖

iCubGenova09

### Request/Failure description

The robot left arm does not calibrate properly. In particular, the shoulder yaw, elbow and pronosupinaton seem to have issue calibrating. In particular, the left shoulder yaw seems to have issues.

I have tried rebooting the robot three times, but I had three different results.
Looking at the last logger, I noticed the following errors repeated many times:
```
[ERROR]  from BOARD 10.0.1.1 (left_arm-eb1-j0_1), src LOCAL, adr 9, time 179s 429m 73u: (code 0x0000003d, par16 0x0000 par64 0x0000000000002000) -> SYS: a service has detected that some CAN boards have stopped transmission. In sourceaddress the eOmn_serv_category_t, in par64 LS 32 bits the bit mask of lost board (CAN1 in MS 16 bits and CAN2 in LS 16 bits), in in par64 MS 32 bits the time in ms since last contact + .
```

### Detailed context

Here the log associated with the last run
[left_arm_issue.txt](https://github.com/robotology/icub-tech-support/files/10700123/left_arm_issue.txt)

Here the logs from the previous two runs, were the calibration was also not successful
[log_icub-head_yarprobotinterface[robotinterface]_1326.txt](https://github.com/robotology/icub-tech-support/files/10700126/log_icub-head_yarprobotinterface.robotinterface._1326.txt)
[log_icub-head_yarprobotinterface[robotinterface]_1807.txt](https://github.com/robotology/icub-tech-support/files/10700128/log_icub-head_yarprobotinterface.robotinterface._1807.txt)

### Additional context

Some days earlier, we were testing the left arm limits by moving the arm by hand. I wonder if this could have caused some cable to be pulled.

### How does it affect you?

We have tomorrow (Feb 10) around lunch time and we need the robot to do teleoperation.

cc @maggia80 @Fabrizio69 @DanielePucci @Gandoo @GiulioRomualdi @lrapetti

**Comment by AntonioConsilvio** [comment]
Hi @S-Dafarra, this problem should have been solved by replacing the CAN termination on 2FOC 1B1, which controls Yaw and Elbow.

The Robot has been tested and seems working correctly. 

cc @sgiraz
