### ISSUE TITLE
Right shoulder loses calibration over time  

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1501]
### Device name 🤖

ergoCubSN000

### Request/Failure description

While testing we noticed that the right shoulder loses calibration from time to time.

### Detailed context

As far as I know, @AntonioConsilvio already knows the issue and it seems to be related to the fact that the incremental calibration is missing  

### Additional context

cc @lrapetti @DanielePucci @mebbaid

**Comment by sgiraz** [comment]
![image](https://user-images.githubusercontent.com/18039045/218957395-264d90f4-dcc2-4a55-929a-f89390a5ebab.jpeg)

**Comment by DanielePucci** [comment]
@sgiraz 
> Tomorrow @davidetome and I (maybe with the help of @ale-git) will try to apply the incremental calibration as done in `iCub3`.

Is this still confirmed for today? The loss of the arm calibration is making complex the preliminary experimental activities since we need to reboot the robot and change the configuration files manually from times to times during the day

**Comment by pattacini** [comment]
Hi @DanielePucci 

@sgiraz @davidetome @ale-git and @AntonioConsilvio are done with the incremental calibration of the right arm. They're now dealing with the left arm.

**Comment by pattacini** [comment]
Incremental calibration completed!
Thanks to @ale-git @sgiraz @davidetome 👍 

New values in conf files updated via:
- https://github.com/robotology/robots-configuration/pull/440
