### ISSUE TITLE
Neck joint cable broken 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1502]
### Device name 🤖

ergoCubSN000

### Request/Failure description

While testing the walking controller the neck cable got broken

### Detailed context

@sgiraz, @AntonioConsilvio, and @GiacomoVassallo13 blocked the neck with a plastic tie

### Additional context

cc @lrapetti @DanielePucci @mebbaid

**Comment by sgiraz** [comment]
![image](https://user-images.githubusercontent.com/18039045/218957321-8c6598fc-d863-499d-9c2b-763bc6a03afb.jpeg)

**Comment by pattacini** [comment]
The neck is back operational ✅
Thanks to @fbiggi @mpinaffo @sgiraz @mfussi66 @salvi-mattia.

We spotted that you were not using the latest set of PID gains, which goes in the direction of weighing robustness more than tracking performance.

We left the new gains in your fork (both in `src` for version control and in the installed dir).
Also, we recalibrated the AEA sensors, so you'll find these new values too.

@mfussi66 can you drop a pointer to the correct set?

**Comment by sgiraz** [comment]
Hi @mfussi66,

This morning the head has been fixed. Could you post the video here that proves the correct behavior when running the `ergoCub` head?

**Comment by mfussi66** [comment]
The most recent pid values to control roll and pitch of the head can be found here: https://github.com/robotology/robots-configuration/blob/master/ergoCubSN000/hardware/motorControl/head-eb20-j0_1-mc.xml#L50-L52

**Comment by pattacini** [comment]
> The most recent pid values to control roll and pitch of the head can be found here: https://github.com/robotology/robots-configuration/blob/master/ergoCubSN000/hardware/motorControl/head-eb20-j0_1-mc.xml#L50-L52

`devel` branch updated as well via:
- https://github.com/robotology/robots-configuration/commit/9ff9d9087682b222fa569310b9421f336e322a52
