### ISSUE TITLE
Robot not fixed properly on the pole

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1505]
### Device name 🤖

ergoCub

### Request/Failure description

After placing the robot on the pole we noticed the robot pelvis was not properly fixed (see video below).

### Detailed context

As suggested by @maggia80 it should be enough to tight the screw on the pole, we should verify if it gets properly fixed

https://user-images.githubusercontent.com/35487806/219438321-7d4d76f2-354f-4ee5-9821-e918b7c0ae76.mp4

cc @mebbaid @GiulioRomualdi

**Comment by Gandoo** [comment]
ciao al momento è stata accorciata la curvatura e il problema è quasi risolto, in aggiunta ho incollato uno spessore.
In attesa di una nuova staffa di ancoraggio

![6b885d4d-824b-4d46-96fa-cb272744a90e](https://user-images.githubusercontent.com/53341641/219588967-eac18a6c-8e60-4208-a036-e50bc095089c.jpg)

cc @maggia80 @sgiraz @AntonioConsilvio @DanielePucci @lrapetti

**Comment by sgiraz** [comment]
Well done @Gandoo! 🚀

**Comment by lrapetti** [comment]
At the beginning the fix seems to work out, but after a while it was moving again

https://user-images.githubusercontent.com/35487806/219676880-7e1b516f-33f1-4393-9eb0-023f2f4118f8.mp4

**Comment by sgiraz** [comment]
Hi @lrapetti,

Thank you for your feedback. Next sprint, we will probably deliver an improved lock mechanism.

**Comment by lrapetti** [comment]
> Hi @lrapetti,
> 
> Thank you for your feedback. Next sprint, we will probably deliver an improved lock mechanism.

Related to the pole we also want to ask for having the possibility to level the pole (e.g. by adjusting the height of the wheels), since it can band under the weight of the robot itself:

![bolla](https://user-images.githubusercontent.com/35487806/220120141-cd228a7a-cfef-4083-aecb-07e682c216cd.jpg)

**Comment by Elio75** [comment]
> At the beginning the fix seems to work out, but after a while it was moving again

To remove the backlash of the robot in the indicated area, we removed 0.4 mm on each side on the centering supports. It seems to have worked because the robot remains quite stable and does not move.

![image](https://user-images.githubusercontent.com/53298662/220607208-d00c31a7-e2ed-44b9-a5aa-2055b8aae97b.png)


CC @maggia80 @Fabrizio69

**Comment by AntonioConsilvio** [comment]
@lrapetti the backlash should be gone, however when you will use the robot, send us feedback about it.

cc @sgiraz @Elio75

**Comment by lrapetti** [comment]
> @lrapetti the backlash should be gone, however when you will use the robot, send us feedback about it.
> 
> cc @sgiraz @Elio75

We tested it just after the modification of the support and the robot was stable on the pole. I think we can close this, and we will inform you if we encounter the same issue next time the robot is on the pole.

Just as a reminder, if possible take in consideration https://github.com/robotology/icub-tech-support/issues/1505#issuecomment-1437018373 for the future iterations on robot poles
