### ISSUE TITLE
Hip pitch encoder broken

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1507]
### Device name 🤖

ergoCubSN000

### Request/Failure description

As shown in the picture the two connectors are broken

![photo1676643601](https://user-images.githubusercontent.com/35487806/219680623-4f2b6f34-0110-467b-a592-20bce1e0b560.jpeg)

### Detailed context

Trying to remove the robot from the pole, the two connectors of the hip pitch encoders got broken

cc @mebbaid @GiulioRomualdi @DanielePucci @S-Dafarra

**Comment by DanielePucci** [comment]
I do not know if there is anyone who might help us with this - we may proceed autonomously if someone from Tech provides with the crimpatrice.

@Fabrizio69 @maggia80

**Comment by Fabrizio69** [comment]
Hi @DanielePucci , Elio provided you the tool to crimp the the wires...
For the crimps and connectors you can ask to @Miche19 (with a warehouse ticket)

**Comment by lrapetti** [comment]
Thanks @Fabrizio69, it was actually the encoder on the EMS. We were able to find it with the link you provided.
For reference here is the schematic

<img width="674" alt="Screenshot 2023-02-17 at 16 26 28" src="https://user-images.githubusercontent.com/35487806/219695700-e042c4bd-fb5a-48d3-b23e-ad770f0dedcf.png">


cc @dariosortino @Gianlucamilani

**Comment by lrapetti** [comment]
The encoder cables were reconnected , however one of the pins of the connector was bent (distorto) and gave some issues.
After reconnecting and starting the robot, the right hip pitch encoder values from the `yarpmotorgui` were not changing, and the left hip pitch encoder was reading strange values (higher than the limit). Also the hip pitch calibration upon starting the robotinterface was not successful. We restarted the motors just to be sure, but the same issues persisted.

**Comment by AntonioConsilvio** [comment]
Hi @lrapetti, @Gandoo and I crimped the wires this morning, we did some testing and it seems to be working.

However, before closing the issue I am also waiting for your tests to be sure that the robot is working properly.

cc @maggia80 @Fabrizio69 @sgiraz @DanielePucci

**Comment by sgiraz** [comment]
I put this issue in review and waiting for feedback.

**Comment by DanielePucci** [comment]
We no longer got the issue, I think we can close it @sgiraz
