### ISSUE TITLE
iCubGenova11 - Left elbow is mechanically locked

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1508]
### Device name 🤖

iCubGenova11

### Request/Failure description

While doing experiments with iCubGenova11 for the ergoCub demos, @Woolfrey notified us that the left elbow suddenly stopped moving.

At the moment, the elbow motion seems blocked by something, a cable?, as can be seen in the following video:

https://user-images.githubusercontent.com/6014499/220168300-1d7bba22-18d1-4d97-9a74-ff5f390990d9.mp4

### Detailed context

@Woolfrey provided a video showing what the robot was actually doing when the block came into place.

https://user-images.githubusercontent.com/6014499/220293475-755262d4-d0fc-49fd-803b-08e05b691c8d.mp4

### How does it affect you?

We cannot test one of the demos for the ergoCub demos day.

**Comment by AntonioConsilvio** [comment]
Hi @xEnVrE, @GiacomoVassallo13 and I tightened the tensioners of the steel cables. It is working now. (also with `yarprobotinterface`)



https://user-images.githubusercontent.com/114915464/220305454-9b7432e7-1cd7-4dd5-862d-827a98b2ea6b.mp4


cc @sgiraz

**Comment by xEnVrE** [comment]
Thank you @AntonioConsilvio @GiacomoVassallo13
