### ISSUE TITLE
Feet FTs are not coherent with the model

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1509]
### Device name 🤖

ergoCubSN000

### Request/Failure description

Observing the mounting of the FTs on the feet they are not parallel, while in the model the FTs of each feet are parallel

### Detailed context

Here are the FTs mounted on the robot

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/35487806/220710542-c923f408-9d1c-4aa9-a860-d3659484b633.png)

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/35487806/220710550-4e2d2302-de20-44ff-8e1f-454d5daa06f6.png)

Here are the FTs frame in the CAD
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/35487806/220710951-018994dd-bc3b-437c-8473-b41ddbc6720f.png)
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/35487806/220710954-6153c966-0362-42b7-b497-9e1f6cd83ba4.png)

**Comment by lrapetti** [comment]
cc @GiulioRomualdi @mebbaid @DanielePucci

**Comment by lrapetti** [comment]
We don't know if the problem is in the model or in the mounting of the FTs themself @sgiraz @pattacini

**Comment by pattacini** [comment]
We will start addressing this tomorrow morning.

**Comment by salvi-mattia** [comment]
since the model derives directly from the cad 
they are consistent.

in fact in the cad we can see that they are parallel
![immagine](https://user-images.githubusercontent.com/43994292/220731028-0d91f9f3-bd28-4b3d-abce-187d44d28c97.png)

since we have to move the front sensor in order to be consistent with the CAD it can be done without unmounting the feet

**Comment by AntonioConsilvio** [comment]
Hi @lrapetti, @GiacomoVassallo13 and me rotated the FT sensor in the right position. Now they are as in the CAD.

cc @sgiraz

**Comment by sgiraz** [comment]
As per https://github.com/ami-iit/component_bipedal-locomotion/issues/5#issuecomment-1442011962 we consider the problem solved! 

Well done guys! 🚀
