### ISSUE TITLE
Right hip pitch not calibrating

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1510]
### Device name 🤖

ergoCubSN000

### Request/Failure description

The right hip pitch is not starting. 
Here is a video of the calibration step

https://user-images.githubusercontent.com/35487806/220715315-38e525ad-6480-4a1c-b88f-eebd917873de.mp4

### Detailed context

We noticed the first time the problem when moving the leg from the `yarpmotorgui`

https://user-images.githubusercontent.com/35487806/220715583-d6db115e-6c97-4f0c-84cb-aad1234a1c2f.mp4

**Comment by AntonioConsilvio** [comment]
Hi @lrapetti, there was a screw loose, touching the mechanical part of the torso and preventing pitch calibration.

![Image](https://user-images.githubusercontent.com/114915464/220954537-01877497-513c-4649-93c7-ff62f03171d5.png)

The damaged screw was replaced, and now the robot works.

cc @sgiraz

**Comment by sgiraz** [comment]
We also replaced all the LCORE's wires!
