### ISSUE TITLE
iCubGenova11 - Problem with r_shoulder_yaw.

### ISSUE THREAD

**Issue by fedeceola** [robotology/icub-tech-support#1514]
### Device name 🤖

iCubGenova11

### Device name 🤖

iCubGenova11

### Request/Failure description

During an experiment, the `r_shoulder_yaw` went on hardware fault, although it was in a feasible position. After this, when the `yarprobotinterface` is launched, all the r_shoulder joints remain in idle. Moreover, with the robot turned off, it is not possible to manually move the `r_shoulder_yaw`. 

### Detailed context

-

**Comment by xEnVrE** [comment]
Hi @sgiraz,

I wanted to ask if it would be possible to check this robot today.

Thanks

**Comment by sgiraz** [comment]
Hi @xEnVrE , @AntonioConsilvio is going to reach you this morning!

**Comment by fedeceola** [comment]
Hi @sgiraz, @AntonioConsilvio, as @xEnVrE mentioned in #1512 we have a couple of deadlines for an iROS submission (on the 1st of March) and for the ErgoCub demos (6th of March). Do you think that iCub can be repaired before those days?

**Comment by sgiraz** [comment]
Hi @fedeceola,

Unfortunately we're having an emergency with `ergoCub` which currently has an higher priority.
We'll do our best to address your issue asap.

cc @AntonioConsilvio @GiacomoVassallo13

**Comment by xEnVrE** [comment]
Thanks for the update @sgiraz

**Comment by fbiggi** [comment]
Eseguita la seguente lavorazione
scabalggio
Cambio cuscinetto 618/4 
pulizia + aggiunta grasso nuovo su wave e flex 
Ispezione statore + pulizia disco ottico
Rimontaggio + chiusura secondo specifica Nm 
Prova di movimento manuale **conforme** in attesa di test di movimento elettrico

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/20420331/221871342-926ca8b0-3c04-4baf-bc5d-27bd53e735a3.png)
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/20420331/221871347-8932f48c-7098-4d8b-8e9f-4f5cfc579d4f.png)
@AntonioConsilvio @GiacomoVassallo13 @sgiraz @maggia80 @Fabrizio69

**Comment by xEnVrE** [comment]
This evening the robot was back in the robot arena.

We tried running the `yarprobotinterface` but it seems that something is wrong encoders-side as the shoulder did not calibrate:

![motorgui](https://user-images.githubusercontent.com/6014499/221946054-86823ae0-dfd8-48b8-ab7b-7caab87dcb5f.png)

the error message is `MC: AEA encoder invalida data.`

cc @sgiraz @AntonioConsilvio @fedeceola

**Comment by sgiraz** [comment]
Ok, it should be something ez to fix. @AntonioConsilvio will help you tomorrow (1st March) morning.

**Comment by AntonioConsilvio** [comment]
Hi @xEnVrE @fedeceola, the problem should be in the cable that connects the yaw AEA to the EMS board (eb3) (cable name: R1S0).
The robot has been tested and it should work, however send a feedback to us when you will use the robot.

cc @sgiraz

**Comment by sgiraz** [comment]
Well done @AntonioConsilvio, I think we can close this issue!
Feel free to re-open if necessary.
