### ISSUE TITLE
Face expressions display flickers

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1516]
### Device name 🤖

ergoCubSN000

### Request/Failure description

While using the robot we had to fault it and we accidentally hit the head display.

After that, a band on the right part of the display was flickering and sometimes was completely blank.

![image](https://user-images.githubusercontent.com/6014499/221941375-80e2fef2-9048-4fd3-8d0d-218d13db4610.png)

After touching the display flat a bit, it came back normal but we noticed two columns of the display were not working:

![image](https://user-images.githubusercontent.com/6014499/221942178-8f3dca84-cbf7-45c8-8d4c-b8bc24ba4a92.png)

cc @lrapetti

**Comment by sgiraz** [comment]
cc @Nicogene @Fabrizio69 @maggia80

**Comment by maggia80** [comment]
I guess it's an hw issue. Let's discuss whether to change it now or after the demo.

**Comment by sgiraz** [comment]
We're going to replace the display with a new one asap.

cc @AntonioConsilvio

**Comment by sgiraz** [comment]
Display replaced by @AntonioConsilvio!
We saw during the INAIL demo it worked as expected.

Closing!
