### ISSUE TITLE
Weird tracking behavior for r_shoulder_roll

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1517]
### Device name 🤖

ergoCubSN000

### Request/Failure description

While testing the joint control of the right arm, we noticed that the `r_shoulder_roll` joint was departing from time to time from the expected trajectory commanded by the user using `POSITION_DIRECT`.

Below you can see:
- the desired trajectory sent to the joint (orange) vs the actual joint configuration (blue)
![Screenshot from 2023-02-28 17-46-49](https://user-images.githubusercontent.com/6014499/221950277-c0a303bb-7f6b-4451-b849-174a7ee834ef.png)
- the PWM action (orange) and the motor current (blue)
![Screenshot from 2023-02-28 17-47-00](https://user-images.githubusercontent.com/6014499/221950337-ee9295cf-0653-42af-8002-be4f64f474ed.png)

As it can be seen, the joint is tracked well but at certain point it departs from the desired trajectory.

### Detailed context

.

**Comment by sgiraz** [comment]
cc @pattacini @Nicogene

**Comment by sgiraz** [comment]
Ok @xEnVrE, thanks for reporting!
Unfortunately, many demos are coming soon and we have a few critical issues to address before.

As soon as the demo on 6 March is over, we gonna check out the problem reported here.

**Comment by lrapetti** [comment]
Today it happened that the motor encoder was not reading, and after touching the connector it was back working. Probably it is worth to have a look at the connector, maybe changing it

**Comment by sgiraz** [comment]
> Today it happened that the motor encoder was not reading, and after touching the connector it was back working. Probably it is worth to have a look at the connector, maybe changing it

Hi @lrapetti any update on this?

**Comment by lrapetti** [comment]
Today @AntonioConsilvio fixed the connector, and we no longer experienced problems. Feel free to close this issue.

**Comment by sgiraz** [comment]
Ok, thanks! Closing.
