### ISSUE TITLE
Burning smell around right shoulder

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1519]
### Device name 🤖

ergoCubSN000

### Request/Failure description

While using the robot we noticed decreased performances, and we smelled burning. We immediately stopped the robot and turned off the battery

### Detailed context

We were performing teleoperated walking

**Comment by sgiraz** [comment]
☝🏻 Hi @lrapetti, may you paste the log of `yarprobotinterface` in the attachment here, please?

---

@AntonioConsilvio, on the right forearm we have to verify if there are faults on:
- motors 
- `amcbldc` boards
- `aea` encoders

Check also the elbow motors, please (probably we may use the jogger)

cc @MrAndrea @maggia80 @pattacini

**Comment by sgiraz** [comment]
@AntonioConsilvio checked the values of the resistors on the motor phases and it seems that a motor is damaged. The same one as the previous times.

**Comment by sgiraz** [comment]
Closing in favour of #1520
