### ISSUE TITLE
iCubGenova11 - Right hand palm skin power cable is damaged

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1521]
### Device name 🤖

iCubGenova11

### Request/Failure description

As requested by @AntonioConsilvio, this is to notify that during #1514 the power cable of the right hand palm skin got damaged.

**Comment by AntonioConsilvio** [comment]
Hi @xEnVrE, the damaged cable has been replaced and now the right hand palm skin work without any problems.

cc @sgiraz @fedeceola

**Comment by sgiraz** [comment]
Excellent! 🎉Closing.
