### ISSUE TITLE
Cable neck out of place

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1524]
### Device name 🤖

ergoCubSN000

### Request/Failure description

After https://github.com/robotology/icub-tech-support/issues/1523 and https://github.com/robotology/icub-tech-support/issues/1522, we decided to run anyways the teloperation demo.

While walking, the fault went out of the robot, and then the robot idled. While falling and kept by the crane, the head recoil made the cable of the neck go out  

![IMG_1229](https://user-images.githubusercontent.com/5045846/222787711-d6ecee65-fe36-4ff9-998a-3b780fb621f8.jpeg)

### Detailed context

Probably we should consider to re-design the neck mechanism

**Comment by sgiraz** [comment]
This morning, @fbiggi, @Gandoo, and @AntonioConsilvio completed the maintenance activity. The neck seemed fine during the `INAIL` demo.

However, we are aware that the neck needs to be improved in some ways.
