### ISSUE TITLE
ergoCubSN000 – Motor temperature suspiciously high around some joints

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1528]
### Device name 🤖

ergoCubSN000

### Request/Failure description

The ergoCub robot, since it's delivery, has been experiencing high temperatures of some motors. This happens, for instance, for the motors of the shoulder rolls. 

High temperature at the shoulders is a sort of new phenomenon with respect to iCub3, which did not show the temperature issue so clearly. One of the assumptions was that the ergoCub arms weigh more than those of iCub3 - same motors at the shoulders, but not experiencing the temperature issue - and this  would explain higher temperatures.

Clearly, this investigation should be done more carefully by looking at, for instance, motor currents. 

At the qualitative level, the iRonCub team @HosameldinMohamed @vpunithreddy @gabrielenava is currently performing the in-situ calibration of the iCub3 FT sensors at the arms https://github.com/ami-iit/element_ft-nonlinear-modeling/issues/66 and for this reason they installed weights on the iCub3 arms. 

And the temperature of the shoulder rolls on iCub3 stays relatively low even after some time with a relatively high weight. 
![IMG_1255](https://user-images.githubusercontent.com/5045846/224575034-e39bf481-4bc8-4450-96e6-f01279562578.jpeg)

CC 
@lrapetti @maggia80

**Comment by maggia80** [comment]
thanks @DanielePucci for reporting this. Yes, I agree with you we need to further investigate the behavior on ergoCub, starting from shoulder roll.

**Comment by DanielePucci** [comment]
Some other interesting experiments are collected at https://github.com/ami-iit/element_ft-nonlinear-modeling/issues/71

**Comment by DanielePucci** [comment]
While @GiulioRomualdi was performing the IMU location https://github.com/icub-tech-iit/tickets/issues/2684#issuecomment-1486890876, I passed by and I checked the motor temperature not only of the shoulders, but **but also of the torso**.

The temperature of the torso joint, to which we attach the temperature, is very high: I could not touch the plate behind the IMU - see below - for more than 2 seconds, and the robot walked only once ⚠️ So, I do not know if temperature effects may alter the IMU reading in the long run 

![image](https://user-images.githubusercontent.com/5045846/228580819-a6159bb3-4710-4722-81b1-b46789a0cfae.png)

CC
@sgiraz @pattacini @maggia80

**Comment by MrAndrea** [comment]
A motor had burned out. See: 
- https://github.com/icub-tech-iit/proto/issues/2204#issuecomment-1504919244
- https://github.com/icub-tech-iit/proto/issues/2202#issuecomment-1503722591

**Comment by sgiraz** [comment]
Hi @DanielePucci,

Are you still noticing high temperatures around the indicated joints?? If not, I guess we can close this issue.

**Comment by DanielePucci** [comment]
Yes, during yesterday demo https://github.com/ami-iit/lab-events-demos/issues/248 the shoulder motors were really at high temperature

**Comment by sgiraz** [comment]
We have reason to believe that the perceived heat on the shoulder joints may be generated by poor dissipation of the main torso board. We are implementing a solution to achieve better cooling. 


![Image](https://github.com/robotology/icub-tech-support/assets/18039045/700b30f4-4954-4f95-92d5-4f5aaa11bba4)


**N.B.** This is only a temporary workaround for `ergoCubSN000`

cc @maggia80

**Comment by sgiraz** [comment]
It seems that the new cooling fan system gets down the temperature of the joints mentioned above. Afaik on the next ergoCub the cooling system will be improved furtherly.
Closing, feel free to re-open if necessary.
