### ISSUE TITLE
iCubGenova04 – Torso tendons are very loose

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1531]
### Device name 🤖

iCubGenova04

### Request/Failure description

the torso tendons are very loose. the robot in position control oscillates a lot as soon as it is touched. At a first look, it does not seem there is something broken.

### Detailed context

https://user-images.githubusercontent.com/12396934/226630053-4c011519-705e-4a2f-8b1d-908937ff0d98.mp4

**Comment by GiacomoVassallo13** [comment]
Good morning, the tendon in the torso has been tensioned. To do this, the backpack had to be disassembled. The robot has been returned.

**Comment by sgiraz** [comment]
Well done @GiacomoVassallo13! 🚀
I think we can close this issue.
