### ISSUE TITLE
R1 Power Cable not working  

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-tech-support#1535]
### Device name 🤖

R1 SN001 Erzelli

### Request/Failure description

The robot is not properly charging its battery unless the male connector is pressed tightly into the robot plug.
So either the female connector on the robot, or the male plug on the cable from the power supply is damaged.

### Detailed context

---

**Comment by maggia80** [comment]
@randaz81 is the battery still capable of powering the robot? Otherwise could be the 20A fuse in series with the battery broken.

**Comment by randaz81** [comment]
yes. It seems that just the connector (male/female i do not know) is loose. Everything works if I keep the cable pushed in.

**Comment by Fabrizio69** [comment]
Hi @randaz81 ,
tomorrow morning @AntonioConsilvio will be in Erzelli to repair the charging cable. Thanks

cc: @sgiraz

**Comment by AntonioConsilvio** [comment]
Hello @randaz81, I solved the problem today. The problem was caused by the female connector. Now everything seems to be working properly.

https://user-images.githubusercontent.com/114915464/231489318-8ff769a5-8bfb-4271-8fca-86ef994b1c99.mp4

cc @sgiraz @Fabrizio69 @maggia80

**Comment by randaz81** [comment]
Thank you! We are going to check it asap!

**Comment by AntonioConsilvio** [comment]
Perfect. I await your feedback! @randaz81

**Comment by Fabrizio69** [comment]
Hi @randaz81, this was an urgent support request, do you have any feedback on this?

cc: @AntonioConsilvio

**Comment by randaz81** [comment]
The problem has been successfully fixed, thank you!
