### ISSUE TITLE
ergoCubSN000 - Right elbow motor encoder not working

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1536]
### Device name 🤖

ergoCubSN000

### Request/Failure description

The motor encoder of `r_elbow` is always reading zero.

### Detailed context

It happened since I started the robot with @CarlottaSartore

**Comment by AntonioConsilvio** [comment]
Hi @lrapetti some wires of the cable connecting the LCORE_5 to the 2FOC board (cable name: RAE3) were detached.

The cable has been fixed and the elbow joint has been tested. The motor ran without any problems during the test.

cc @sgiraz
