### ISSUE TITLE
ergoCubSN000 - Torso pitch not calibrating

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1538]
### Device name 🤖

ergoCubSN000

### Request/Failure description

The torso pitch of the robot is not starting, after going in overcurrent.

### Detailed context

While using the robot, the `torso_pitch` went in overcurrent, while we noticed the torso was very hot (more than usual). We restarted the pitch and it was working for a while and then it went again in hardware fault.

At this point, we turned off the robot and waited for ~1 hour, but after that, the torso pitch is going in hardware fault during the calibration.

Here is the log at the startup: [torso_overcurrent.log](https://github.com/robotology/icub-tech-support/files/11170391/torso_overcurrent.log)

After 3 trials, at the 4th launch, the calibration was successful but after few movements, the torso pitch went in HF again due to overcurrent and it was not possible to recover it. 

https://user-images.githubusercontent.com/35487806/230374358-73c39403-fe8e-41b4-b256-09716c006099.mp4

C.C. @CarlottaSartore

**Comment by CarlottaSartore** [comment]
@AntonioConsilvio  today changed the 2FOC with one with augmented limits (30 Ampere if I am not wrong) but the problem still persists

https://user-images.githubusercontent.com/56030908/230450412-676f37d7-8612-43b2-a320-b0b08a20f1a3.mp4

**Comment by sgiraz** [comment]
Hi guys,

Today, @AntonioConsilvio and @maggia80 spotted that the pitch torso's motor needs to be replaced.
We'll keep you updated about this activity.

cc @Fabrizio69

**Comment by pattacini** [comment]
We asked @DanielePucci and @lrapetti to perform a bunch of simulations in Gazebo to come up with some estimates of the required torque and velocity at the joint in question.

cc @traversaro @Fabrizio69 @maggia80 @fiorisi @salvi-mattia

**Comment by lrapetti** [comment]
Here is an initial simulation. Here is the visualization of the simulator:

https://user-images.githubusercontent.com/35487806/231452287-613d03b6-5d44-4988-8d12-2f811d468559.mov

I have used two different controller:
- **Case A** torso pitch is controlled in position direct (with constant reference), while the rest of the joints are controlled in torque. This is the configuration used with the real robot.
- **Case B** torso pitch is controlled in torque. The reason for this test is that the joint torque "measured" in position direct might be highly dependent on the low-level gains of the position PID.

Concerning the following plots:
- I plot the values for the torso pitch (top row) and hip pitch (bottom row).
- Torque is measured in Nm
- Velocity is measured in rad/s

## Case A
![torque](https://user-images.githubusercontent.com/35487806/231453175-05e99ebb-24bf-4511-9fda-f672d423999d.png)
![velocity](https://user-images.githubusercontent.com/35487806/231453180-056ba9ed-d88b-4bad-9850-21043119044d.png)


## Case B
![torque](https://user-images.githubusercontent.com/35487806/231453259-7dc82584-2aec-43d0-8982-a83b29457619.png)
![velocity](https://user-images.githubusercontent.com/35487806/231453263-12234d00-47cd-47f6-bf7f-e5cc2dd58700.png)

**Comment by lrapetti** [comment]
## Case C
We tested a third condition to simulate when the robot is hanging from the crane and we move the robot in the initial configuration. In order to do so:
- I have created a world where the robot is attached with a ball joint to the neck link which is somehow close to the centre of rotation
- I am controlling the robot in position direct


https://user-images.githubusercontent.com/35487806/231465540-7b583054-ec6c-4213-a28b-3802d0156c1e.mov

Here are the plots, same considerations from my previous comment are still valid
![torque](https://user-images.githubusercontent.com/35487806/231465843-bace4e5b-ca3c-4374-8085-c1ebdaeea653.png)
![velocity](https://user-images.githubusercontent.com/35487806/231465864-32d87119-9cfe-4b98-af21-74a56cc8ea18.png)

**Comment by pattacini** [comment]
Thanks @lrapetti for the bunch of useful simulations that helped us verify how the torso pitch joint is undersized for the quantities you logged.

After a T2T alignment, we decided that:
1. We will mount the 160:1 HD in place of the existing 100:1.
2. We will limit the currents.
3. @GiulioRomualdi will provide us with an estimate of the torso pitch angle at which we can block the joint.

@Fabrizio69 @AntonioConsilvio @sgiraz, updating the conf files to implement 1 and 2 software-wise is important.

**Comment by Elio75** [comment]
Inclination of the torso by 10°

To fix the 10° torso, I created a shoulder screw and modified and altered the waist flange and motor case of the Pitch joint.

![image](https://user-images.githubusercontent.com/53298662/231777124-2a15456e-3124-4fde-b5ac-1d770113fb11.png)

![image](https://user-images.githubusercontent.com/53298662/231777507-153fa7c6-6475-4343-931c-b6b14f1b7671.png)

![image](https://user-images.githubusercontent.com/53298662/231777596-b66e1549-5048-4817-9f45-55fd85e9c42a.png)

CC @maggia80 @pattacini @Fabrizio69 @fbiggi

**Comment by MSECode** [comment]
Changed `hip_roll` joint start-up position of the left-leg and the right-leg so that the `torso_pitch` has a little current consumption for keeping its start-up position at 0°.
In this manner there's no need to change nor the calibration order nor the firmware.
So that, `torso_pitch` does not reach any error in calibration and its consumption is close to zero at start-up position.

Check videos and images that will be uploaded soon by @AntonioConsilvio

cc: @ale-git @valegagge @AntonioConsilvio

**Comment by AntonioConsilvio** [comment]
We have found a start-up position that reduces power consumption of the torso pitch and arms roll.

How is the robot when it finish the calibration:
![NewCalib](https://user-images.githubusercontent.com/114915464/233364713-4498cdeb-d1f7-4074-9bb4-c199e9e69501.png)


cc @sgiraz

**Comment by valegagge** [comment]
@MSECode and I noticed that probably there are some ethernet connection issues between some boards. We're going deep. Stay tuned!

**Comment by valegagge** [comment]
> > @MSECode and I noticed that probably there are some ethernet connection issues between some boards. We're going deep. Stay tuned!
> 
> This is connected to the issue reported at #1544.
> It should be ok now, because "faulted" board was identified but ask confirmation to @AntonioConsilvio if it's fine now. 
> The problem was related to eth issues most likely due to electromagnetic disturbances. 

@MSECode you are right! My comment was related to #1544. Thanks for adding yor comment! 😀

**Comment by sgiraz** [comment]
In summary we have:
- replaced the faulted motor of the `torso- pitch`
- locked the `torso-roll` at 10° 
- changed the startup position in order to minimize start-up consumption.

I think we can close this issue.
Thanks to all for the contribution!
