### ISSUE TITLE
iCubGenova07 – left shoulder cable 8 broke during reaching action

### ISSUE THREAD

**Issue by reafrancesco** [robotology/icub-tech-support#1542]
### Device name 🤖

iCubGenova07

### Request/Failure description

left shoulder cable 8 broke during reaching action.

### Detailed context

left shoulder cable 8 broke during reaching action.
The shoulder was fixed and only n.1 of cable 8 is left in the spare set.

Considering the frequency of such issue it is worth considering ad-hoc inspection of the left shoulder.

**Comment by sgiraz** [comment]
Hi @reafrancesco,

This should be the tendon you mean, right?

[![shoulder_elbow](https://user-images.githubusercontent.com/18039045/234026218-ca875491-a9f1-4d34-8c77-3cabcf63f211.png)][1]

We'll discuss your request internally and let you know asap.

cc @GiacomoVassallo13 @fbiggi @Fabrizio69 


[1]: https://icub-tech-iit.github.io/documentation/icub_tendons/shoulder_elbow/#2-left-shoulder

**Comment by reafrancesco** [comment]
Yes this is the correct one and obviously we need some spare ones since we have repaired it frequently in the last months.
Thanks,
Francesco

**Comment by sgiraz** [comment]
Ok, we are going to send you spare cables type-7 and type-8 as requested.
Therefore, we plan to do a check to understand the possible reason for this frequent failure.

cc @Fabrizio69

**Comment by sgiraz** [comment]
Hi @reafrancesco, 

Today we are going to ship the tendons. You should receive them next week.

cc @AntonioConsilvio

**Comment by sgiraz** [comment]
Given the absence of feedback, I assume you have received the tendons.
Closing.
