### ISSUE TITLE
R1 yarprobotinterfaces does not start

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-tech-support#1548]
### Device name 🤖

R1SN003

### Request/Failure description

yarprobointerface does not start.

### Detailed context

The head board (x.x.x.10) does not respond anymore

**Comment by randaz81** [comment]
`problem fixed by replacing the board`

This comment can be deleted

**Comment by Fabrizio69** [comment]
> `problem fixed by replacing the board`
> 
Replaced the MC4-PLUS board with cod.5443.D S/N:284. We can close this issue.

cc: @AntonioAzocar @AntonioConsilvio @sgiraz
