### ISSUE TITLE
[iRonCub3] left leg hip roll does not calibrate

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1549]
### Device name 🤖

iCubGenova09

### Request/Failure description

With @AntonioConsilvio we tried to calibrate the robot, but the left leg hip roll did not calibrated.

### Detailed context

cc @vpunithreddy

**Comment by AntonioConsilvio** [comment]
Hi @gabrielenava, I and @AntonioAzocar fixed the cable called L_S1 that connect the AMO sensor to the EMS EB7.

The robot has been tested and now works without any problems.

cc @sgiraz

**Comment by sgiraz** [comment]
Well done guys! 
We can consider this issue concluded successfully!
