### ISSUE TITLE
[ergoCubSN000] The head is straight when the neck pitch is zero and the torso is fixed at 10 deg 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1550]
### Device name 🤖

ergoCubSN000

### Request/Failure description

I put the robot on the ground with the legs straight and I noticed that the robot's head is parallel to the ground when the joints are zero. This shouldn't be possible since the torso pitch is now fixed at 10 deg. 

### Detailed context

Here the picture

|  Real robot  | Model    |
|:----:|:---:|
|  <img src="https://user-images.githubusercontent.com/16744101/236151396-b9855336-be38-428b-b142-8186508ac375.jpg" height="600" width="auto"> | <img src="https://user-images.githubusercontent.com/16744101/236153216-383926a3-c9cb-4fdb-bf4c-68a18f036542.png"  height="600">   |

I don't know if this is wanted, however as far as I know it is not considered in the urdf and this causes the following issues:
1. whole body dynamics propagates the imu information to remove the FTs offset. The propagation is computed using the urdf of the robot plus the joints positions.
2. There is a mismatch between the robot model considered for the retargeting and the real robot
3. It may create issues when evaluating the pose (w.r.t the root frame) of objects detected by the camera  (@xEnVrE may comment on this)

 

### Additional context

cc @S-Dafarra

**Comment by pattacini** [comment]
Could it be that the head has been recalibrated in the wrong configuration, @AntonioConsilvio?

**Comment by sgiraz** [comment]
> Could it be that the head has been recalibrated in the wrong configuration, @AntonioConsilvio?

Hi @pattacini, yep! We talked F2F with @Nicogene, and we agree to recalibrate the head with the right calibration values.
In detail, the head has to be perpendicular to the ground when the torso is perpendicular as well.

**Comment by pattacini** [comment]
> In detail, the `head-pitch` has to be perpendicular to the ground when the `torso-pitch` is perpendicular as well.

If the torso pitch is blocked, it might be cumbersome to bring the torso-pitch perpendicular to the ground. Consider that recalibrating the head to make it visually "perpendicular" to the torso is also viable.

**Comment by AntonioConsilvio** [comment]
Hi @GiulioRomualdi, next week I will re-calibrate the neck.

cc @sgiraz

**Comment by sgiraz** [comment]
PR open here:
- https://github.com/robotology/robots-configuration/pull/512

**Comment by AntonioConsilvio** [comment]
This is how ergoCub appears with the new calibration:



![Image](https://github.com/robotology/icub-tech-support/assets/114915464/d5e601d0-2b37-41f3-87d6-322dd5c39e76)



cc @GiulioRomualdi @sgiraz
