### ISSUE TITLE
port /icubsrv is not responding && port /icub-head is not responding

### ISSUE THREAD

**Issue by jimingda** [robotology/icub-tech-support#1553]
### Device name 🤖

iCubShanghai01

### Request/Failure description

port /icubsrv is not responding && port /icub-head is not responding

### Detailed context

Dear all, when i compile the app icubSim below on the docker, and run the demo like position or velocity control, it works fine,
https://github.com/vvv-school/tutorial_joint-interface

optJoint.put("remote","/icubSim/left_arm");

------>

optJoint.put("remote","/icub/left_arm");

but when i change icubSim to icub as above, compile and want to run yarpmanager again, i got the following error message
(i install the hardware correctly except that the cpu and motor lighting is red)

12:43 # yarpmanager
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[ERROR] |yarp.os.Property| cannot read from ymanager.ini
[INFO] |yarp.os.Port|/tmp/port/1| Port /tmp/port/1 active at tcp://172.17.0.2:10002/
[WARNING] Cannot connect to /icubsrv
[ERROR] ClusterWidget: port /icubsrv is not responding
[INFO] |yarp.os.Port|/tmp/port/1| Port /tmp/port/1 active at tcp://172.17.0.2:10002/
[WARNING] Cannot connect to /icub-head
[ERROR] ClusterWidget: port /icub-head is not responding
QObject::connect: No such slot ApplicationViewWidget::onBuilderFloatChanged(bool)
QObject::connect: (receiver name: 'ApplicationViewWidget')
QRectF(-71,-16 142x32)

### Additional context

my phone +0086 13391266956
Anydesk  573 232 910

**Comment by pattacini** [comment]
This is a double posting, @jimingda.
Closing it in favor of https://github.com/orgs/robotology/discussions/620.
