### ISSUE TITLE
Left thumb adduction not moving

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1555]
### Device name 🤖

ergoCub S/N000

### Request/Failure description

The left thumb adduction does not move. It makes a weird noise, like a spinning motor and it can be moved by hand, but it cannot be controlled

### Detailed context

We were performing a teleoperation demo and that joint might have been stressed while trying to hold a box

**Comment by AntonioConsilvio** [comment]
Hello @S-Dafarra, I fixed the problem by changing some values in the configuration files and the cable that connect the FAP sensor to the MMA board.

A PR to update robots-configurations upstream is coming soon.

cc @sgiraz

**Comment by sgiraz** [comment]
PR open here:
- https://github.com/robotology/robots-configuration/pull/512
