### ISSUE TITLE
Right thumb open close does not move

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1556]
### Device name 🤖

ergoCub S/N000

### Request/Failure description

The right thumb OC seemed to have some issues  and it is not possible to control it

### Detailed context

We were performing some teleoperation demo and it was working fine. After some manipulation, it stopped working

**Comment by sgiraz** [comment]
PR open here:
- https://github.com/robotology/robots-configuration/pull/512
