### ISSUE TITLE
ergoCubSN000 - Left hand thumb, index and pinky open/close move on their own

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1558]
### Device name 🤖

ergoCubSN000

### Request/Failure description

The left hand thumb, index and pinky open/close joints move towards the mechanical limit irrespective of the actual position of the finger. 

### Detailed context

When the configuration is as follows:

![image](https://github.com/robotology/icub-tech-support/assets/6014499/cdf0d666-13e5-443c-93cc-8e3f3e5b1eeb)

the fingers move as per the video:

https://github.com/robotology/icub-tech-support/assets/6014499/8224c115-ccd8-4742-bfc5-d097b95edc72

**Comment by xEnVrE** [comment]
cc @AntonioConsilvio @lrapetti @Woolfrey

**Comment by sgiraz** [comment]
Cc @valegagge

**Comment by maggia80** [comment]
> I noticed that the fingers keep reading the same value even if they move.
> 
> However, when I restarted the yarprobotinterface the poblem seemed to have been resolved, in fact the fingers behaved and moved correctly.
> 
> However, after a few minutes the problem reappeared.
> 
> cc @sgiraz @valegagge @xEnVrE

@AntonioConsilvio did you check also the motor encoder reading? Does it count while the finger moves?

**Comment by AntonioConsilvio** [comment]
Hi @maggia80, I haven't checked because it hasn't happened again. 

When and if it happens again I will check.

cc @sgiraz

**Comment by sgiraz** [comment]
I put this issue on hold for a while, as it has not happened anymore.
Please let us know if it happens again.

cc @xEnVrE @AntonioConsilvio

**Comment by sgiraz** [comment]
Closing as it doesn't seem to have happened again. Feel free to re-open if necessary.
