### ISSUE TITLE
ergoCubSN000 – Loosy left elbow

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1560]
### Device name 🤖

ergoCub

### Request/Failure description

https://github.com/robotology/icub-tech-support/assets/5045846/90da2003-ef5c-46d1-bdcd-f376a97927b0

### Detailed context

none

**Comment by sgiraz** [comment]
### On the elbow

The 3 screws indicated below have been tightened:

![image](https://github.com/robotology/icub-tech-support/assets/18039045/473495f5-769f-4a8c-af64-26feda40d9d8)

--- 

Moreover, @Gandoo and @AntonioConsilvio spotted that also the following screws were loose, so they re-tightened them.

![image](https://github.com/robotology/icub-tech-support/assets/18039045/da3088cc-a6fc-436a-b27e-9a468da2025e)

After these maintenance activities, the issue should be solved.
We are waiting for your feedback.

cc @DanielePucci

**Comment by sgiraz** [comment]
Closing! Feel free to reopen if necessary.

cc @AntonioConsilvio
