### ISSUE TITLE
ergoCubSN000 – Suspicious "tac, tac" when touching the robot shoulders

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1561]
### Device name 🤖

ergoCub

### Request/Failure description

I passed by and I touched the (hot) ergoCub shoulders and I felt - not hear, so it was the haptic feedback - a suspicious "tac, tac", like when the screws of the harmonic drives of the ankles were untight - I am not sure however, that it comes from the ankles, probably left hip 

This was also checked by @Gandoo and @AntonioConsilvio 

https://github.com/robotology/icub-tech-support/assets/5045846/10f42959-e7da-4ab7-b6bf-10d8059e1c9e

### Detailed context

None

**Comment by sgiraz** [comment]
Closing this issue since it doesn't seem to be happening anymore.
Feel free to reopen it if necessary.

cc @Fabrizio69 @AntonioConsilvio @fbiggi
