### ISSUE TITLE
check for R1SN001 main battery replacement

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-tech-support#1564]
### Device name 🤖

R1SN001 Erzelli

### Request/Failure description

Pavis research team notified us that the battery charge of R1SN001 seems to be unexpectedly short. 
Currently, we do not have a quantitative measurement. 
However, this might be a trigger for us to check if we already have a replacement battery or if we need to order components (and their lead time)

### Detailed context

---

**Comment by maggia80** [comment]
@randaz81 we are going to open a purchase order for a new battery.

**Comment by maggia80** [comment]
@randaz81 we have issues in purchasing the replacement since the company is not producing anymore this battery pack. I'm searching for an alternative solution/provider

**Comment by AntonioConsilvio** [comment]
Hi @randaz81! The battery has arrived, we can proceed with the replacement.

We were planning to do this on Thursday 8th August.

To get to the robot, do the replacement and test the battery, we are autonomous.
But to test the robot's functionality, we need someone to start it.

Is someone available on Thursday?

cc @elandini84

**Comment by randaz81** [comment]
Top! Lets's do it!

**Comment by AntonioConsilvio** [comment]
Hi @randaz81, yesterday me and @fbiggi replaced the battery. The battery is working and the robot is powered correctly. 

Please give me feedback on the functioning of the robot when you test it!

**Comment by fbrand-new** [comment]
We tested the robot and can confirm that it is working correctly, thank you!
