### ISSUE TITLE
[iCubGenova09] - Boards not connected

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1566]
### Device name 🤖

iCubGenova09

### Request/Failure description

The robot iCub3 is temporarily back to iCub3 configuration (a part from the lower-arms that are not connected). We manged to run the robot in the previous day but now some bords are not reachable.

### Detailed context

Here is the output of the Firmwareupdater.

![photo1684762978](https://github.com/robotology/icub-tech-support/assets/35487806/a0514084-8933-4bcc-95ca-070158146048)

**Comment by lrapetti** [comment]
cc @CarlottaSartore

**Comment by AntonioConsilvio** [comment]
@CarlottaSartore Thanks for the feedback!
