### ISSUE TITLE
iCubGenova11 - Face expressions are misplaced

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1569]
### Device name 🤖

iCubGenova11

### Request/Failure description

As per the title. This happened after the fix due to #1568.

### Detailed context

As per the picture below:

![image](https://github.com/robotology/icub-tech-support/assets/6014499/1a2349e9-a019-40b6-b17c-5065fc120005)

the right eyebrow is misplaced.

**Comment by xEnVrE** [comment]
Thanks @AntonioConsilvio

**Comment by fedeceola** [comment]
Hi, I reopen the issue because the problem still occurs when turning on the robot.

![MicrosoftTeams-image (14)](https://github.com/robotology/icub-tech-support/assets/32268209/b6f47b2c-0ed0-4e58-b210-049f7d4915bc)

**Comment by AntonioConsilvio** [comment]
I glued the LED on the cover. Now the problem should no longer appear.
![MicrosoftTeams-image (6)](https://github.com/robotology/icub-tech-support/assets/114915464/dc64175a-a259-4a49-ab5f-4864c3450c9f)


cc @sgiraz

**Comment by xEnVrE** [comment]
Thanks @AntonioConsilvio

**Comment by sgiraz** [comment]
Closing as solved! Good job! 💪🏻
