### ISSUE TITLE
iCubGenova11 - Problem with r_thumb_proximal

### ISSUE THREAD

**Issue by fedeceola** [robotology/icub-tech-support#1571]
### Device name 🤖

iCubGenova11

### Request/Failure description

During an experiment, the `r_thumb_proximal` stopped working. After this, when the `yarprobotinterface` is launched, the calibration of the right hand is not completed.

### Detailed context

I guess that this may be the problem.

![MicrosoftTeams-image (10)](https://github.com/robotology/icub-tech-support/assets/32268209/40a60653-b6a1-4bbc-b489-f8700afd530e)

### How does it affect you?

I cannot run my experiments. I have an upcoming deadline on the 8th of June and I'd need help as soon as possible. Thank you.

**Comment by sgiraz** [comment]
Hi @fedeceola, 

Do you need to use the right hand for your experiment? Especially the r_thumb_proximal...

If this is not the case, you may try to remove the joint from calibration xml or start the yarpmotorgui with the --calib option.

If needed we may drop below some
guidelines to achieve these tasks.

Cc @Fabrizio69 @AntonioConsilvio

**Comment by fbiggi** [comment]
the tendon was restored and the sheaths were also replaced as they were damaged
I await your feedback
Thank you

![20230531_075224](https://github.com/robotology/icub-tech-support/assets/20420331/d7b7e7d5-6bdc-4460-8523-fffb2df659cb)
![20230530_161754](https://github.com/robotology/icub-tech-support/assets/20420331/1b330df4-d9ef-4568-8c54-ea7a231d84b1)

**Comment by fedeceola** [comment]
Hi @fbiggi, thanks for repairing the tendon!
Unfortunately, the right hand cannot complete the calibration when launching the yarprobotinterface. This is what can be seen from the yarpmotorgui.
![image](https://github.com/robotology/icub-tech-support/assets/32268209/2446e568-e05e-4f7f-86c2-472a73b46d73)
Please note that, while being in run mode both the r_thumb_oppose and the r_thumb_proximal, they do not perform any movement during the calibration.
I attach here also the log file from the yarplogger.
[yarprunlog_31_05_2023_09_55_13.log](https://github.com/robotology/icub-tech-support/files/11610207/yarprunlog_31_05_2023_09_55_13.log)
Thanks!

**Comment by sgiraz** [comment]
Hi @fedeceola,

From the log posted above we cannot see any diagnostic error.
You may try to copy the log from the `yarprobotinterface` instead of export the one from the `yarplogger`.

Furthermore, you may try to launch the `FirmwareUpdater -a` from the robot configuration files robot's folder and take note for the number of the ETH and CAN boards you can see. Remember that in order to see the CAN boards you have to put the the ETH one in maintenace mode. 

Maybe @davidetome and/or @marcoaccame may help you with this taks.

cc @AntonioConsilvio @Fabrizio69

**Comment by fedeceola** [comment]
Hi @sgiraz, I managed to complete the calibration by manually pushing the r_thumb_distal. However, after completing it, if the joint is perturbed while running, it goes in hardware fault because it reaches the hard limit. The encoder reads a value of -13 deg.

In the log of the yarprobotinterface there are no errors until the joint reaches the hard limit.

**Comment by valegagge** [comment]
Hi,
@MSECode and I gave a look at the log file. As @sgiraz said, it is not complete or clear, It would be better to have the log of `yarprobotinterface`.

We suggest retaking the calibration values and using them. 

@fedeceola: What do you mean by

> if the joint is perturbed while running 

?

**Comment by MSECode** [comment]
Whenever you'll try to re-run the calibration please ping me that I would like to come and see the procedure and so I can see the exact behaviour of the robots if any error happens

**Comment by fedeceola** [comment]
Hi @valegagge, here you can find the log of the yarprobotinterface.
[log_robotinterface.log](https://github.com/robotology/icub-tech-support/files/11614072/log_robotinterface.log)



By perturbing the joint, I mean this:

https://github.com/robotology/icub-tech-support/assets/32268209/10ecd565-3af4-4869-9d5f-21dc55dfd531

@MSECode, I can re-run the calibration now!

Thank you for the support!

**Comment by MSECode** [comment]
So, to share an update:
- Main problems were on `right_arm` joints number 8 and 10 (i.e. thumb oppose and thumb distal ). There were problems with the reaching of joint limits during the calibration procedure
- Following actions have been performed:
    - set the parameters `skipCalibration` to `true` and `useRawEncoderValues` to `true` so that we could re-check the raw values at the encoder when the joint is full open and full closed
    - raw values have been updated for those joints on the `calibrator` file
     calibration parameters 4 and 5 of the thumb oppose joint (number 8) 
     calibration parameters 4 and 5 of the thumb distal joint (number 10)
    - re-set values in general to `false`
    - calibration procedure restarted
- Now fingers calibrate successfully and joints moves correctly
- Following actions:
    - check if the updated values (obtained by bringing the joints in idle to the extremal positions) are good 
    
cc: @fedeceola @valegagge @fbiggi @sgiraz

**Comment by MSECode** [comment]
Just one thing @fedeceola.
Whenever you'll do the tests on the robot can you please add here the following files, before and after then modification on the vmin and vmax that I'd like to check a couple of things regarding the calibration procedure of the MAIS:
- `iCubGenova11/hardware/mechanicals/right_arm-eb28-j8_11-mec.xml`
- `iCubGenova11/calibrators/right_arm-calib.xml`

**Comment by sgiraz** [comment]
Well done guys!

I'll put the issue in review waiting for feebacks

**Comment by fedeceola** [comment]
Hi @MSECode, here you can find the requested files.
[files_issue.zip](https://github.com/robotology/icub-tech-support/files/11633409/files_issue.zip)

**Comment by fedeceola** [comment]
Hi, unfortunately there are still problems with the thumb_oppose and the thumb_proximal. When moving only one of the two joints, everything is ok. When moving the thumb_oppose to 90 deg and closing a few the thumb_proximal, this is the configuration reached by the thumb.
![MicrosoftTeams-image (13)](https://github.com/robotology/icub-tech-support/assets/32268209/259fc7c9-b0fb-47a2-96f2-ea811dd9f3f5)

Moreover, from the yarpmotorgui, the value of the r_thumb_oppose is 85, while it should be at least 100, and therefore the joint is not in hardware fault.

**Comment by MSECode** [comment]
Oks, I'll check that out on Monday 
Anyway I would expect the thumb_oppose to move between 10 and 90 degree because those are the limits defined on both motion control and mechanical configuration files. So it should go further than 85 but never reach 100. Then we can check the calibration vmin and vmax for the proximal, which we did not modify on Wednesday.

**Comment by fedeceola** [comment]
I set the calibration parameters for the thumb_oppose as they were before the modifications. We modified them because before the calibration the encoder of this joint was reading a value of 330 deg and the calibration was not starting. Now this problem doesn't occur anymore, and the joint behaves as expected (as before the tendon broke). I will do some tests with this configuration.

**Comment by fedeceola** [comment]
Yesterday I talked with @sgiraz and we agreed to wait running my experiments with the configuration mentioned in the last comment to avoid possible side effects. Is there somebody that can help me to check if everything is ok today? Thanks!

**Comment by valegagge** [comment]
@fedeceola , both me and @MSECode are in Cris. If you want we can help you.

**Comment by fedeceola** [comment]
@valegagge, @MSECode and me just checked the parameters and agreed to proceed with some experiments with this configuration.

**Comment by fedeceola** [comment]
The tendon has just broken again.

![MicrosoftTeams-image (15)](https://github.com/robotology/icub-tech-support/assets/32268209/f00e5dfa-1679-4791-9510-87c6c20954da)

Would it be possible to fix it tomorrow?

**Comment by sgiraz** [comment]
Well done guys! 
Closing.

**Comment by xEnVrE** [comment]
Was a re-calibration required to fix that? Are we supposed to open a PR in `robots-configuration` for that? @sgiraz

**Comment by fedeceola** [comment]
Thank you all for the support!

@xEnVrE we modified the calibration parameters for the r_thumb_distal. I can help with the PR on friday.

**Comment by xEnVrE** [comment]
PR opened https://github.com/robotology/robots-configuration/pull/528

**Comment by sgiraz** [comment]
PR merged!

cc @MSECode
