### ISSUE TITLE
iCubGenova11 - Right arm r_elbow AEA not working

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1577]
### Device name 🤖

iCubGenova11

### Request/Failure description

The right arm `r_elbow` encoder is not working as expected.

### Detailed context

![Screenshot from 2023-06-13 17-07-37](https://github.com/robotology/icub-tech-support/assets/6014499/7ed842e5-410f-48ad-811d-03e2294f82ee)

### Additional context

Please find here the log of the `yarprobotinteface`:

[log_icub-head_yarprobotinterface_3943.txt](https://github.com/robotology/icub-tech-support/files/11736389/log_icub-head_yarprobotinterface_3943.txt)

### How does it affect you?

We would need to repair this before Wednesday afternoon due to some demos on Thursday morning and afternoon. Thank you

cc @sgiraz @AntonioConsilvio @AntonioAzocar

**Comment by AntonioConsilvio** [comment]
Hi @xEnVrE, yesterday I found the cable R1S1, that connect the AEA sensor to the EMS EB3, broken under the shoulder tendon:
 
![Cable](https://github.com/robotology/icub-tech-support/assets/114915464/69f50cdd-12b2-453f-9bb4-5c7202c56eb0)


I and @Gandoo replaced the cable and tested the joint and it works.

https://github.com/robotology/icub-tech-support/assets/114915464/a0c31d33-4bea-4360-b0f8-83fd894437cb

Feel free to reopen the issue if the problem reappears.

cc @sgiraz

**Comment by xEnVrE** [comment]
Thanks a lot!! @AntonioConsilvio @Gandoo @sgiraz
