### ISSUE TITLE
ergoCub SN000 hands fail to calibrate

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1578]
### Device name 🤖

ergoCub S/N000

### Request/Failure description

Both ergoCub hands do not calibrate.

### Detailed context

The logger is complaining about a CAN board not transmitting data. The readings from motorgui appear constant in most fingers

**Comment by AntonioConsilvio** [comment]
Hi @S-Dafarra, yesterday I found the cable of the FAP (J31) of the thumb proximal detached. 

Then, I noticed that some open-closed joints fail to calibrate, so I reduced the final destination point that the fingers must reach to complete the calibration.

There will be a PR shortly.


cc @sgiraz @MSECode

**Comment by AntonioConsilvio** [comment]
PR here

- https://github.com/robotology/robots-configuration/pull/532
