### ISSUE TITLE
iRonCub3: timeout on ems board EB3

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1581]
### Device name 🤖

iCubGenova09 - iRonCub3

### Request/Failure description

We tried to start the robot to verify the status after #1579 

the `yarprobotinterface` fails with a timeout error on several boards, the first one that fails is the EMS `EB3`.

### Detailed context

Running `Firmwareupdater` confirmed that the only visible boards are the head and the left arm. I suspect there is a problem with the EMS 2 or 3 and then all the other boards in the chain are not seen because of that.

![right_arm_problem](https://github.com/ami-iit/component_ironcub/assets/83775281/13d462a5-d566-4bcd-819a-8cc623564c7e)

**Comment by gabrielenava** [comment]
title and first comment edited as EB3 is not on the right arm but on the chest.

**Comment by Gandoo** [comment]
ciao,  after a check because it worked at times there was the E26 cable connector on the EB3 board that lost the signal. I replaced crimp and connector, now it works

cc @gabrielenava @vpunithreddy @AntonioConsilvio @sgiraz @DanielePucci

**Comment by gabrielenava** [comment]
thank you! today I worked with the robot and everything was fine!

**Comment by AntonioConsilvio** [comment]
Good job guys! Closing ✔️

cc @gabrielenava @Gandoo @Fabrizio69
