### ISSUE TITLE
iCubGenova11 - Right thumb tendons broken

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1582]
### Device name 🤖

iCubGenova11

### Request/Failure description

While doing the demo for the FamilyDay, one of the tendons of the right thumb broke.

### Detailed context

At the moment we disabled the right arm to let the demos continue.

### Additional context

cc @mfussi66

**Comment by GiacomoVassallo13** [comment]
Hi. The proximal tendon of thumb has been replaced. Also replaced the sheaths that were damaged. . In addition I proceeded to stretch the proximal tendons of the middle and index finger, as well as the thumb oppose. 
While I was making the repairs I noticed that some screws on the fingers were loose so I proceeded to tighten them


cc: @Fabrizio69 @AntonioConsilvio @sgiraz

**Comment by xEnVrE** [comment]
Thanks @GiacomoVassallo13

**Comment by xEnVrE** [comment]
This week I will use the robot and give feedback on this.

**Comment by sgiraz** [comment]
I'm going to close this issue. Feel free to reopen if needed.
