### ISSUE TITLE
[iCubErzelli02] Right shoulder tendon broken (right arm)

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1583]
### Device name 🤖

iCubErzelli02

### Request/Failure description

one of the tendon broke and is out of its pulley

### Detailed context

-

### Additional context

![MicrosoftTeams-image (5)](https://github.com/robotology/icub-tech-support/assets/3440640/3fd387bd-a0a7-431d-897d-42f1e5d97d0e)

### How does it affect you?

Data collection is done. Thus, we have no urgency to fix the robot and we would ask you to intervene possibly on the days Thu 29th/Fri 30th.

**Comment by AntonioConsilvio** [comment]
Hi @ddetommaso, We agree to intervene on Friday 30th

cc @Fabrizio69

**Comment by AntonioConsilvio** [comment]
Hi @ddetommaso, me and @GiacomoVassallo13 replaced the tendon and tested the robot on Friday 30th.

The shoulder of the robot works properly now.

cc @Fabrizio69
