### ISSUE TITLE
ergoCubSN000 right thumb adduction not moving

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1589]
### Device name 🤖

ergoCub S/N000

### Request/Failure description

While shooting the robot while opening a light handle, the right thumb adduction stopped moving and it was not possible to recover ita

### Detailed context

The encoders seem to measure correctly, but the joint seems to push toward the limit and gets stuck

**Comment by sgiraz** [comment]
Hi @S-Dafarra,

This afternoon @AntonioConsilvio found an MMA's PCB fap connector of the right hand faulted. He replaced the MMA board with a new one. I don't remember if it was related to the adduction or OC, but surely it was a problem.
Please, let us know if you have the opportunity to try it. At any rate, we'll test it asap.

see also #1580

**Comment by AntonioConsilvio** [comment]
Today I tried adduction of the right thumb and it does not push to the limit and does not get stuck: 

https://github.com/robotology/icub-tech-support/assets/114915464/5907a415-0365-4689-97bc-0eb78aeb155b

cc @sgiraz
