### ISSUE TITLE
iCubGenova11 - Left thumb distal tendon broken

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1590]
### Device name 🤖

iCubGenova11

### Request/Failure description

As per the title, the left thumb distal tendon is broken.

### Detailed context

When the `yarprobotinterface` calibrates the robot, the noise of the motor spinning freely can be heard.

**Comment by xEnVrE** [comment]
Possibly related to #1575

**Comment by GiacomoVassallo13** [comment]
Hi. The thumb distal joint has been replaced. The tendom has been replaced and a finger tip cable has been re-soldered.
I attend feedback.

cc: @sgiraz

**Comment by sgiraz** [comment]
Hi @xEnVrE, 

I guess this issue has been solved. In this case I proceed closing the issue.
Feel free to reopen if necesary.

**Comment by xEnVrE** [comment]
Thanks @sgiraz @GiacomoVassallo13
