### ISSUE TITLE
[iCubErzelli01] Left arm thumb tendon broken

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1592]
### Device name 🤖

iCubErzelli01

### Request/Failure description

While preparing a demo with grasping the left hand thumb broke.

### Detailed context

-

### Additional context
[log_icub-head_yarprobotinterface_1200.txt](https://github.com/robotology/icub-tech-support/files/11950970/log_icub-head_yarprobotinterface_1200.txt)

_No response_

**Comment by sgiraz** [comment]
Hi @ddetommaso, may you provide more information about this issue?
Is because of a broken tendon, or the motor faulted, or something else? 
Maybe some pictures may help to identify the possible problems.

**Comment by ddetommaso** [comment]
> Hi @ddetommaso, may you provide more information about this issue?
> Is because of a broken tendon, or the motor faulted, or something else? 
> Maybe some pictures may help to identify the possible problems.

![IMG-20230704-WA0003.jpeg](https://github.com/robotology/icub-tech-support/assets/3440640/c43cf2d7-2629-45fd-a31e-5b64fc1e25ab)

**Comment by sgiraz** [comment]
Hi @ddetommaso,

The thumb joint of this robot has 3 different sub-joints: distal, proximal, and adduction
As we arrived on site, we spotted that the broken tendon was the adduction connected to motor M0.


![Image](https://github.com/robotology/icub-tech-support/assets/18039045/e9b951d5-b0ab-4c9d-8598-278be55b845a)


Following the procedure described in the [documentation][1] (section 2.2), @GiacomoVassallo13  replaced the broken tendon with a new one.
After the replacement, we tested the joint using the Jogger and now it seems to work correctly:



https://github.com/robotology/icub-tech-support/assets/18039045/f5eb1106-c08e-46a0-8a84-3dbad86ebff4



⚠️ We'd need to perform further tests (e.g. using the yarprobotinterface), but I didn't know the password for the `iCub` account of the workstation next to the robot, hence I couldn't test it more deeply. 
However, next Monday (10th Jul) we planned to finalize the test and complete the maintenance activity also on `iCubErzelle02`  that today was under usage.


cc @Fabrizio69 



[1]: https://icub-tech-iit.github.io/documentation/icub_tendons/wrist_hand_cabling_V2/#21-location

**Comment by ddetommaso** [comment]
Hi @sgiraz ,

thank you for the fix and the detailed explanation.
See you on Monday!

**Comment by sgiraz** [comment]
### Maintenance activity report 10/07/23

**Interventions:**
| Description | pictures | Note |
| :---: | :---: | :---: |
| Replaced motor 1B3M1  |  | it was faulted |
| neck harmonic drive screws tightened correctly | | they were loosen |


**Tests:**
| Tests | pictures | Note |
| :---: | :---: | :---: |
| left arm joints | | |
| whole robot | | |
| demo to be performed next Wednesday | | |

**Notes:**
- 


cc @Fabrizio69

**Comment by sgiraz** [comment]
Maintenance activity completed!
See also comment: https://github.com/robotology/icub-tech-support/issues/1570#issuecomment-1647587577
