### ISSUE TITLE
iCubGenova11 - Left thumb distal reads 90 degrees when fully open

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1593]
### Device name 🤖

iCubGenova11

### Request/Failure description

When considering #1575, it was noticed that once the calibration is completed the left thumb distal is reading ~ 90 deegres when the joint is fully open - which is of course wrong.

### Detailed context

A picture showing the weird configuration:

![image](https://github.com/robotology/icub-tech-support/assets/6014499/3f215829-30e3-423a-8835-c0bfd1d8c1fe)

**Comment by AntonioConsilvio** [comment]
Hi @xEnVrE, yesterday I found the cable of one of the left thumb hall sensors damaged, and therefore to be replaced.

cc @sgiraz

**Comment by xEnVrE** [comment]
Thanks, we can decide together the proper moment for fixing it.

**Comment by xEnVrE** [comment]
Hi @sgiraz @AntonioConsilvio can I ask of there ie any update on the schedule of this activity?

Thank you

**Comment by sgiraz** [comment]
Hi @xEnVrE,

As agreed, we scheduled the activity for tomorrow afternoon.

cc @AntonioConsilvio @GiacomoVassallo13

**Comment by xEnVrE** [comment]
Thanks for the fix @AntonioConsilvio @Gandoo

**Comment by AntonioConsilvio** [comment]
Hi @xEnVrE, I recalibrated and tested the distal joint of the left thumb. 

Now the joint is working properly. 

Remember to update the robots-configuration files:

- https://github.com/robotology/robots-configuration/pull/551

cc @sgiraz
