### ISSUE TITLE
iRonCub3 (iCubGenova09): torso pitch and yaw and left hip pitch do not start

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1596]
### Device name 🤖

iRonCub3 - iCubGenova09

### Request/Failure description

we were testing the robot after #1594 

the torso pitch and yaw and the left hip pitch do not start during the calibration phase. On the yarpmotorgui, we see:

![image](https://github.com/robotology/icub-tech-support/assets/12396934/fdc236cb-91ec-4ab5-bff0-5079ab1fbc9d)

![image](https://github.com/robotology/icub-tech-support/assets/12396934/d0262d29-422a-4434-8752-ba0bd77fc155)

despite the message `hard limit reached` for the torso joints, in the `yarplogger` we can see that all joints show the `AEA encoder invalid data` message (together with the hard limits reached one):

![image](https://github.com/robotology/icub-tech-support/assets/12396934/f62ab359-9a4c-4975-98af-832cab17c525)

### Detailed context

here the full logger:

[log_icub-head_yarprobotinterface[robotinterface]_1364.txt](https://github.com/robotology/icub-tech-support/files/11981059/log_icub-head_yarprobotinterface.robotinterface._1364.txt)

cc @STaliani @DanielePucci

**Comment by gabrielenava** [comment]
cc @Gandoo

**Comment by Gandoo** [comment]
![20230707_140401 (1)](https://github.com/robotology/icub-tech-support/assets/53341641/a4862201-9966-4982-9062-fd962d5fde28)

cc @gabrielenava

**Comment by sgiraz** [comment]
Hi @gabrielenava,

Has the problem been solved after @Gandoo's intervention?

**Comment by gabrielenava** [comment]
hello @sgiraz 

the problem is now solved! thank you

**Comment by sgiraz** [comment]
Nice! 🚀
Closing.
