### ISSUE TITLE
[ergoCubSN000] Robot not strarting

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1600]
### Device name 🤖

ergoCubSN000

### Request/Failure description

The `yarprobotinterface` is not starting.

### Detailed context

From `FirmwareUpdater` we noticed that it does not see the FT of the right upper leg.

**Comment by lrapetti** [comment]
@sgiraz and @AntonioAzocar are already on it, they found that the FT cable is broken

**Comment by sgiraz** [comment]
Closing as solved!
