### ISSUE TITLE
[ergoCubSN000] The robot does not start 

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1601]
### Device name 🤖

ergoCubSN000

### Request/Failure description

The robot does not start giving the errors in the logs. It was working fine and I just restarted it after changed a configuration file, so I do not know what could be happened.

### Detailed context

Here are the logs of the last two trials:

[log_ergocub-torso_yarprobotinterface_2934.txt](https://github.com/robotology/icub-tech-support/files/12064547/log_ergocub-torso_yarprobotinterface_2934.txt)
[log_ergocub-torso_yarprobotinterface_2399.txt](https://github.com/robotology/icub-tech-support/files/12064548/log_ergocub-torso_yarprobotinterface_2399.txt)

**Comment by sgiraz** [comment]
Hi @isorrentino,

The FW and SW of the whole robot were not properly updated, there were a lot of mismatches among the laptop, head, and torso. So, yesterday afternoon and today, @mfussi66, @martinaxgloria, @AntonioConsilvio, @MSECode, and I provided the necessary support to update everything. 

Unfortunately, we found some misalignments between the [config files][1] of ergoCub 1.0 S/N000 pointed by the [robotology-superbuil@v2023.05.2][2] and the FW binaries in [icub-firmware-build@v1.35.1]. We fixed these inconsistencies on the robot and I opened a PR that will be merged asap: 
- https://github.com/robotology/robots-configuration/pull/542

Finally, @AntonioConsilvio tried without success to fix an issue related to the impossibility to update the FW of the strain2 mounted on the right shoulder, but this is another story and we'd need more time to find the real (hidden) problem first.

After all the activities mentioned above, the robot starts correctly and includes almost all the latest bug fixes and improvements recently released from both SW and FW sides.

cc @Fabrizio69 @Nicogene 

[1]: https://github.com/robotology/robots-configuration/tree/v2.4.0/ergoCubSN000
[2]: https://github.com/robotology/robotology-superbuild/releases/tag/v2023.05.2
