### ISSUE TITLE
`ergoCubSN000` right knee encoder not moving

### ISSUE THREAD

**Issue by mebbaid** [robotology/icub-tech-support#1602]
### Device name 🤖

`ergoCubSN000`

### Request/Failure description

While the robot was on, the `right_knee` joint moved by itself and then went into hardware fault showing the error message i2t limit exceeded. When @S-Dafarra tried to move it , the motor position reads/changes while the encoder value doesn't move.

### Detailed context

Here is the log file

[log_ergocub-torso_yarprobotinterface_right_knee.txt](https://github.com/robotology/icub-tech-support/files/12083392/log_ergocub-torso_yarprobotinterface_right_knee.txt)

**Comment by S-Dafarra** [comment]
cc @CarlottaSartore @lrapetti

**Comment by AntonioConsilvio** [comment]
Hi @S-Dafarra @mebbaid, have you had problems with these joints again?

cc @sgiraz @CarlottaSartore @lrapetti

**Comment by mebbaid** [comment]
We will test this afternoon and confirm to you @AntonioConsilvio

**Comment by mebbaid** [comment]
We have the same situation on the `torso_yaw` today. The joint moved by itself, giving i2t error and encoder stopped moving even when moving the joint in idle. Below is a picture and the associated log

![MicrosoftTeams-image](https://github.com/robotology/icub-tech-support/assets/36491318/9028803e-7ca1-4ed3-b38e-c1ed9ea70456)


[log_ergocub-torso_yarprobotinterface_torso_yaw.txt](https://github.com/robotology/icub-tech-support/files/12160165/log_ergocub-torso_yarprobotinterface_torso_yaw.txt)

**Comment by AntonioConsilvio** [comment]
> We have the same situation on the `torso_yaw` today. The joint moved by itself, giving i2t error and encoder stopped moving even when moving the joint in idle.

Hi @mebbaid, we will look at it, but for the torso yaw problem It would be better to open a separate issue. 

By the way, do you think that the problem on the right knee is solved? If yes, we will proceed closing this issue.


cc @sgiraz @Fabrizio69 @S-Dafarra

**Comment by mebbaid** [comment]
No worries.
I commented on the same issue since it is basically the same problem of the encoders also affecting the same type of joint (yaw angle in both cases). But we can open a separate issue, if it is still necessary

**Comment by sgiraz** [comment]
Hi @mebbaid,

The problem in the right knee has been solved, so I am closing this issue.

> We have the same situation on the `torso_yaw` today.

I recommend you open a new issue to track the problem of the `torso-yaw` even if it is related to the same type of joint (yaw). From the point of view of maintenance is very important to have an issue for each intervention.
