### ISSUE TITLE
[ergoCubSN000] Boards support broken

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1604]
### Device name 🤖

ergoCubSN000

### Request/Failure description

The support of the boards on the torso back is broken,  plus one of the encoder cable is broken (possibly other cables got broken).

cc @CarlottaSartore 

### Detailed context

The robot felt on the back hitting the crane.

### Additional context

![photo1689767325](https://github.com/robotology/icub-tech-support/assets/35487806/1c7ea1b4-7f36-4f7d-80a0-1d419b4e5b2d)
![photo1689767325 (2)](https://github.com/robotology/icub-tech-support/assets/35487806/99ddf8de-a454-4f25-897d-2634e5ba632d)
![photo1689767325 (1)](https://github.com/robotology/icub-tech-support/assets/35487806/02fd4c75-c6b8-4800-b04a-9056a44b1c2b)

**Comment by AntonioConsilvio** [comment]
hi @lrapetti @CarlottaSartore, me and @GiacomoVassallo13 replaced all damaged holder boards.

Then, I fixed the damaged cable (WS0).

The robot has been tested and now works properly.

cc @sgiraz

**Comment by sgiraz** [comment]
Excellent job, everyone! 🚀
