### ISSUE TITLE
iRonCub3 (iCubGenova09): cable broken on the left shoulder

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1605]
### Device name 🤖

iCubGenova09

### Request/Failure description

One of the cables on the left shoulder got detached and needs to be crimped again.

### Detailed context

cc @vpunithreddy @DanielePucci 

### How does it affect you?

we cannot perform iRonCub experiments

**Comment by AntonioConsilvio** [comment]
Hi @gabrielenava, the cable LA_S1 was damaged. I fixed it and tested.

The robot shoulder works properly now, however give us a feedback after your experiments.

cc @sgiraz

**Comment by AntonioConsilvio** [comment]
Hi @gabrielenava, I guess that the issue has been solved. So, I procede closing the issue. 

Feel free to reopen if necessary.

cc @sgiraz
