### ISSUE TITLE
[ergoCubSN000] left wrist encoder not reading

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1606]
### Device name 🤖

ergoCubSN000

### Request/Failure description

The left wrist joint encoder is always showing `0`.

### Detailed context

The robot start, but the left wrist does not moved. When checking on the yarpmotorgui we can observe that the joint reading is always zero while the motor reading is changing.

**Comment by lrapetti** [comment]
After moving it (by @AntonioConsilvio) and restarting the motors, the problem is no longer occurring. I think we can close this.

**Comment by sgiraz** [comment]
> After moving it (by @AntonioConsilvio) and restarting the motors, the problem is no longer occurring. I think we can close this.

Ok, so I proceed to close this issue.

cc @AntonioConsilvio
