### ISSUE TITLE
[ergoCubSN000] Right Thumb detached during calibration at startup

### ISSUE THREAD

**Issue by SimoneMic** [robotology/icub-tech-support#1607]
### Device name 🤖

ergoCubSN000

### Request/Failure description

During calibration the right thumb got unattached from its pin, probably due to a loose grub screw

### Detailed context

![thumb-ergocub-detached](https://github.com/robotology/icub-tech-support/assets/86918431/5676b99e-a5b5-4556-9c92-593590832ffa)

**Comment by AntonioConsilvio** [comment]
Hi @SimoneMic I have successfully reassembled the thumb and tested.

Now the thumb works properly.

cc @sgiraz

**Comment by SimoneMic** [comment]
Closing
