### ISSUE TITLE
ergoCub 1.0 S/N:000 – Left ankle roll moved fastly to the joint limit and started to smell burnt going into hardware fault

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1619]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

While using the right leg of the robot the left ankle roll moved to the limit without any input and started to smell. Unfortunately, I did not have the log file (I forgot to run the `yarplogger`) and now I'm afraid to turn the robot on again, so I cannot take the log.

### Detailed context

As per the description.

**Comment by AntonioConsilvio** [comment]
Hi @isorrentino, after some tests we realised that the motor of the left ankle roller is burnt out. 

Tomorrow morning we will replace it.

cc @maggia80 @fbiggi @sgiraz

**Comment by AntonioConsilvio** [comment]
Hi @isorrentino, with the help of @fbiggi and @Gandoo, we replaced the burnt out motor with a new one.

The robot has been tested and it works properly now.


https://github.com/robotology/icub-tech-support/assets/114915464/d33ad346-0960-4b58-af01-21da67914286



⚠️ Remember to update robots-configuration with the new calibration value

Check the PR:

- https://github.com/robotology/robots-configuration/pull/557

cc @sgiraz @SimoneMic

**Comment by isorrentino** [comment]
Thank you all!
