### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Right elbow motor cable is broken

### ISSUE THREAD

**Issue by HosameldinMohamed** [robotology/icub-tech-support#1620]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

The cable that connects the right elbow motor is broken, see the image below. Two of the wires seem disattached from the connector of the motor.

### Detailed context

I removed the cover of the right arm to access the cable of the FT sensor. When I put the cover back the robot didn't start. When I removed it again I saw this broken cable.

### Additional context

![MicrosoftTeams-image](https://github.com/robotology/icub-tech-support/assets/45564317/e3e6ac37-a733-4ee8-93d8-6304df59291e)

### How does it affect you?

It blocks iRonCub experiments.

CC @gabrielenava

**Comment by HosameldinMohamed** [comment]
I updated the description, but I can't update the points..

**Comment by sgiraz** [comment]
Hi @HosameldinMohamed,

@AntonioConsilvio and @AntonioAzocar will try to fix it as soon as possible (today).

**Comment by AntonioConsilvio** [comment]
Hi @HosameldinMohamed, I fixed the broken cable (RE3).

Here the video of the test:

https://github.com/robotology/icub-tech-support/assets/114915464/3df16141-1ac7-44b6-80df-fd05f0b1be45

cc @sgiraz
