### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Broken encoder cable on right arm shoulder roll

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1624]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

during startup phase, the right shoulder roll was not starting. After looking at the robot, we noted that one of the cables of the right shoulder roll (motor) encoder got disconnected from the crimp.

### Detailed context

cc @AntonioConsilvio

**Comment by AntonioConsilvio** [comment]
Hi @gabrielenava, yesterday I fixed the damaged cable (RA_E1) that connect the LCORE5 to the 2FOC 2B0 board.

The robot has been tested and it works properly now!

cc @sgiraz
