### ISSUE TITLE
ergoCub 1.0 S/N:000 – Neck cable broken

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1629]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

One of the neck cable is broken and should be replaced.

![photo1693907073](https://github.com/robotology/icub-tech-support/assets/35487806/3c6e8989-138b-4926-9db3-a49352121364)

### Detailed context

The cable got broken while testing new walking controller and the robot abruptly shut down due to https://github.com/robotology/icub-tech-support/issues/1614

cc @mebbaid

**Comment by sgiraz** [comment]
Hi @lrapetti,

This morning @GiacomoVassallo13 will fix the broken tendon.

cc @AntonioConsilvio
