### ISSUE TITLE
ergoCub 1.0 S/N:000 – Right hand finger lever detached

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1630]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

We notice the lever of the right finger pending.

![photo1693910783](https://github.com/robotology/icub-tech-support/assets/35487806/cc1e1102-ab18-4e99-8aee-256adf01970b)

### Detailed context

This probably happened when the robot abruptly shut down due to https://github.com/robotology/icub-tech-support/issues/1614

**Comment by fbiggi** [comment]
@sgiraz 

dowel pin   ´M2.5x14 inserted
locking with LOCTITE 648 coaxial

![20230906_084927](https://github.com/robotology/icub-tech-support/assets/20420331/4f0fdc0e-8315-442d-ad89-fa299d0ec916)
![20230906_085143](https://github.com/robotology/icub-tech-support/assets/20420331/84b268e9-bff5-473b-ba09-29e0123c4553)

**Comment by sgiraz** [comment]
Well done @fbiggi.

Closing as solved!
