### ISSUE TITLE
ergoCub 1.0 S/N:000 – Fault not working

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1633]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

The fault is not working, nothing happens when pressed. 

### Detailed context

Pressing the fault button the robot does not go to idle.

**Comment by GiulioRomualdi** [comment]
Tested today and it was working

**Comment by sgiraz** [comment]
Nice! 

Any other feedback on this? Otherwise, I would close this issue.

**Comment by GiulioRomualdi** [comment]
Yesterday it was working

**Comment by sgiraz** [comment]
Ok guys,

Thanks for your feedback! 🙏🏻
I proceed to close this issue. If necessary we can re-open it.

cc @AntonioConsilvio
