### ISSUE TITLE
iCubErzelli02 S/N:036 – Full overhaul of the robot

### ISSUE THREAD

**Issue by sgiraz** [robotology/icub-tech-support#1638]
### Robot Name 🤖

iCubErzelli02 S/N:036

### Request/Failure description

As per https://github.com/robotology/icub-tech-support/issues/1570#issuecomment-1633662274, we are required to do a full overhaul of the robot before delivering it back to Erzelli.

>**Note**
>This activity has been planned and managed internally.

### Detailed context

In order to perform the whole overhaul of the robot we have to perform the following tasks:
- [x] Check the following tendons: shoulders, fingers, waist, and forearms
- [x] Check for faulted or locked the motors 
- [x] Check for faulted boards
- [x] Check for faulted wires (CAN, ETH, SPI encoders)	
- [x] Check for termination on mais boards and wherever they are needed
- [x] Check for broken supports and covers
- [x] Check for loosening and missing screws
- [x] Check for possible shortcircuits (notified shutdowns [here](https://github.com/robotology/icub-tech-support/issues/1570) and [here](https://github.com/robotology/icub-tech-support/issues/1315))

### Additional context

Possible imporvements:
- Remove from the configuration files the following (unused) joints:
  - [x] Whole lower body
  - [x] Skin all over the robot

#### Robot tests + SW updates
- [x] Update `robotology-superbuild`
- [x] Update FW of all the boards
- [x] `Yarprobotinterface` starts without errors
- [x] Every single joint is movable correctly both by hand and by Yarpmotorgui
- [x] Face expressions work
- [x] Cameras work

**Comment by AntonioConsilvio** [comment]
This is the PR for the configurations files (the robot is already up to date):

- https://github.com/robotology/robots-configuration/pull/565

The robot has been packed and it is ready for shipment:


![Shipment1](https://github.com/robotology/icub-tech-support/assets/114915464/247592b9-fa3e-4628-a3b9-1d038279e84c)
![Shipment2](https://github.com/robotology/icub-tech-support/assets/114915464/1cc93d5d-a6a2-47be-b480-b6d1e4aea35e)



cc @maggia80 @Fabrizio69 @sgiraz @ddetommaso @andreaderito @Andreamenini68

**Comment by sgiraz** [comment]
see also: https://github.com/icub-tech-iit/tickets/issues/3084
