### ISSUE TITLE
ergoCub 1.0 S/N:000 – One of the cables of the neck went out

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1639]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

During a walking experiment, one of the neck cables went out.

### Detailed context

Nothing

**Comment by AntonioConsilvio** [comment]
Hi @GiulioRomualdi, the cable had remained intact, it had only come out of the cable tensioners. I have restored the windings and the neck should work properly now.

However, give us a feedback after your tests.

cc @sgiraz

**Comment by mebbaid** [comment]
This happened again while walking with the normal walking controller.

![PXL_20230914_152057832 MP](https://github.com/robotology/icub-tech-support/assets/36491318/3e90aa5c-af02-42ca-a968-d4c5c273940b)

**Comment by mebbaid** [comment]
To go on with the experiments for our deadline we had to lock the neck using a fascette

**Comment by GiacomoVassallo13** [comment]
Hi. The broken cable hase been replaced. Replaced also the screw of tensionators.

cc: @Fabrizio69 @sgiraz @AntonioConsilvio

**Comment by sgiraz** [comment]
Super @GiacomoVassallo13!🚀

Closing!
