### ISSUE TITLE
iCubGenova11 S/N:050 – Left thumb distal tendon broken

### ISSUE THREAD

**Issue by martinaxgloria** [robotology/icub-tech-support#1640]
### Robot Name 🤖

iCubGenova11 S/N:050

### Request/Failure description

The thumb distal tendon of the left hand broke. 

### Detailed context

During some tests on iCubGenova11, running the yarprobotinterface I noticed that the left thumb was not calibrating and from the yarpmotorgui I saw that the thumb distal was in hardware fault.

**Comment by GiacomoVassallo13** [comment]
Hi. Today i replaced the damaged  thumb distal joint. The tendon has been  succesfuly replaced.

cc: @Fabrizio69 @AntonioConsilvio @sgiraz

**Comment by martinaxgloria** [comment]
Thank you @GiacomoVassallo13!

**Comment by sgiraz** [comment]
Thanks, @GiacomoVassallo13!

Closing as solved.
