### ISSUE TITLE
iCubGenova11 S/N:050 – Left arm wrist does not calibrate

### ISSUE THREAD

**Issue by PasMarra** [robotology/icub-tech-support#1647]
### Robot Name 🤖

iCubGenova11 S/N:050

### Request/Failure description

Today I tried to start up the robot, but the left wrist did not calibrate.
After opening the yarpmotorgui I realized that the encoder of the wrist are not working or seems to be. Moreover, the shoulder and other parts are not calibrating as well.

![image](https://github.com/robotology/icub-tech-support/assets/143645988/3311f63b-e78c-4b13-8389-06de39f03491)

### Detailed context

I have attached the log from the yarprobotinterface.
[log_icub-head_yarprobotinterface_1775.txt](https://github.com/robotology/icub-tech-support/files/12717455/log_icub-head_yarprobotinterface_1775.txt)

**Comment by sgiraz** [comment]
Hi PasMarra, the maintenance is scheduled for Wednesday 25th of October.

cc @GiacomoVassallo13 @AntonioAzocar @Fabrizio69

**Comment by sgiraz** [comment]
/remind 24 October Maintenance activity scheduled for tomorrow

cc @GiacomoVassallo13 @AntonioAzocar @Fabrizio69

**Comment by xEnVrE** [comment]
> 24 October Maintenance activity scheduled for tomorrow

Is the maintenance scheduled for October 25 then? Is not the robot involved in the demos for the PI16?

Thank you

**Comment by pattacini** [comment]
>Is not the robot involved in the demos for the PI16?

Yes!

cc @martinaxgloria

**Comment by martinaxgloria** [comment]
@xEnVrE the demos for the PI16 are on October 25th during the afternoon and iCubGenova11 is involved. 

@sgiraz could you move the maintenance activity to the day after, please?

**Comment by AntonioAzocar** [comment]
Hi @xEnVrE, I found the black cable of the AEA2 (**Name: AE6 2S2**) broken, so I re-soldered it.      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

![AEA](https://github.com/robotology/icub-tech-support/assets/130973726/fc307d28-8ed6-415f-910d-0b6827bcdf39)


The **left arm wrist** is working properly again, but we've found other problems.
As you can see in this photo, the thumb oppose has a problem to encoder that reads very high values.
We should do more test to understand better the problem.

![thumb oppose 1](https://github.com/robotology/icub-tech-support/assets/130973726/dbcfda3b-ae77-480f-8b61-a71063dc1a0d)

Thanks @martinaxgloria for your help!


cc @sgiraz @AntonioConsilvio

**Comment by xEnVrE** [comment]
Thanks for the update @AntonioAzocar.

Do you want me to open a dedicated issue in order to fix that so that we can close this one - as the wrist is now working as expected?

Thanks

**Comment by AntonioAzocar** [comment]
Yes, perhaps it would be better to have a dedicated issue, thanks!

cc @sgiraz

**Comment by sgiraz** [comment]
>The left arm wrist is working properly again, but we've found other problems.
As you can see in this photo, the thumb oppose has a problem to encoder that reads very high values.
We should do more test to understand better the problem.

Hi @xEnVrE feel free to open a new issue in order to track the problemi mentioned by @AntonioAzocar in the comment above.
I proceed to close this issue.
