### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Right knee electrical cable disconnected from the connector

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1650]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

An electrical cable associated with the right knee disconnected from its connector during robot startup. I presume it happened after multiple start and stop of the robot while we were debugging another issue.

cc @davidegorbani @DanielePucci 

### Detailed context

![msg185705904-63894](https://github.com/robotology/icub-tech-support/assets/12396934/5e0f10e3-1718-447f-9fe6-5562552c04d0)

**Comment by gabrielenava** [comment]
thank you @AntonioAzocar!

**Comment by sgiraz** [comment]
Well done @AntonioAzocar! 
Closing as solved.
