### ISSUE TITLE
ergoCub 1.0 S/N:000 – Right hip pitch gives AEA encoder invalid data

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1658]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

We noticed that after finish the calibration the r_hip_pitch goes in HF with the MC AEA encoder data

### Detailed context

![image](https://github.com/robotology/icub-tech-support/assets/16744101/c905914e-783d-4bce-9743-b9568f3314b8)

### Additional context

cc @G-Cervettini @isorrentino

**Comment by AntonioConsilvio** [comment]
Hi @GiulioRomualdi, I found the cable RLS0 (that connect the EMS EB6 with the AMO sensor) damaged.

II fixed it and the robot works properly now.

cc @sgiraz
