### ISSUE TITLE
iCubGenova04 (iRonCub1) S/N:031 – The battery charger of the lifting device of the robot is not working anymore

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1665]
### Robot Name 🤖

iCubGenova04 (iRonCub1) S/N:031

### Request/Failure description

the lifting device assigned to the robot run out of battery. The battery charger is broken, the light does not turn on and the battery does not charge.

### Detailed context

the robot will leave next week for a demo, and we need the lifting device to move it.

cc @DanielePucci

**Comment by maggia80** [comment]
@gabrielenava did you search for another battery charger? I guess we should have a spare one. Are you referring to the Molyft 150?

**Comment by gabrielenava** [comment]
The crane and battery charger are these one:

![MicrosoftTeams-image](https://github.com/robotology/icub-tech-support/assets/12396934/b8a7eec4-7679-4ca9-9eeb-0c8d2a843477)
![MicrosoftTeams-image (1)](https://github.com/robotology/icub-tech-support/assets/12396934/10894b54-042a-4e29-9e65-02b1cba8b075)
![MicrosoftTeams-image (2)](https://github.com/robotology/icub-tech-support/assets/12396934/d63bdee3-2100-4228-96f0-8c8506da056e)

Specifically for the demo, I was planning to take the iRonCub3 crane. But if there is a spare battery charger I am still interested!

**Comment by AntonioConsilvio** [comment]
Hi @gabrielenava, unfortunately we don't have any spare parts or possibilities to do maintenance on the crain.

Did you have any other questions or requests regarding this issue or do you think it can be closed?

**Comment by gabrielenava** [comment]
>Hi @gabrielenava, unfortunately we don't have any spare parts or possibilities to do maintenance on the crain.
>
>Did you have any other questions or requests regarding this issue or do you think it can be closed?

hello @AntonioConsilvio, in the end I am trying to purchase a new battery charger and resolve the problem in that way. I'll close this issue!

cc @HosameldinMohamed @Giulero
