### ISSUE TITLE
ergoCub 1.0 S/N:000 – Neck tendons broken

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1669]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

During a demo, the robot fell while walking and one of the neck tendons got snapped

### Detailed context

When falling, the ropes connecting to the crane make the robot twist. This leads the ropes to entangle a little bit with the robot head, which ends up holding the robot's weight. In this configuration, the tendons snap.

When it happened, we did not have time to fix it. Moreover, we run out of tendons.

**Comment by sgiraz** [comment]
Hi @S-Dafarra, thanks for you reporting!
@GiacomoVassallo13 is going to repair the neck tendons in the next few days.

**Comment by GiacomoVassallo13** [comment]
Hi @sgiraz @S-Dafarra  the neck tendon has been replaced.

cc: @Fabrizio69

**Comment by sgiraz** [comment]
Thank @GiacomoVassallo13!

 @S-Dafarra, I'll wait for your feedback before proceeding to close this issue.

**Comment by S-Dafarra** [comment]
Ho @sgiraz, I think you can proceed. In case I will open a new issue!

**Comment by sgiraz** [comment]
Ok, thanks! 
Closing.
