### ISSUE TITLE
iCubGenova11 S/N:050 – Right thumb tendon broken

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1670]
### Robot Name 🤖

iCubGenova11 S/N:050

### Request/Failure description

During some video shooting, one of the tendons of the right thumb brake.

### Detailed context

After running the `yarprobotinterface` we noticed that the thumb was not moving anymore. Later on, thanks to @AntonioConsilvio, we realized that one of the tendons of the right thumb was broken. Not sure about the exact DoF though.

**Comment by sgiraz** [comment]
Maintenance activity scheduled for next Monday (13th of November) from 9:00 to 11:00

cc @GiacomoVassallo13

**Comment by GiacomoVassallo13** [comment]
Hi. Today i replaced the broken thumb oppose tendon. @xEnVrE  I attend a feedback.

cc: @Fabrizio69 @sgiraz @AntonioConsilvio

**Comment by xEnVrE** [comment]
Thanks @GiacomoVassallo13 

I'll test it tomorrow.

@sgiraz @AntonioConsilvio is it safe to turn the robot as is without additional calibrations?

**Comment by xEnVrE** [comment]
I have tested it, it is fine. Closing.

Thanks again
