### ISSUE TITLE
iCubAnkara01 S/N:12 – Turning on motors switch causes S/D of power supply

### ISSUE THREAD

**Issue by EbruBaglan** [robotology/icub-tech-support#1671]
### Robot Name 🤖

iCubAnkara01 S/N:12

### Request/Failure description

xantrex XFR 60-46 goes into S/D when the motors' switch is turned on. 

### Detailed context

I have found an iCub in a research institution in Ankara, which is from around 20 years ago. Since I have done an internship at IIT, I thought of giving it a second life.

I have two power supplies at hand. From a previous mailing with iCub Tech, I received the following voltage and amp values to set.
- Xantrex XFR 35-35: 12/12.5V-15A
- Xantrex XFR 60-46: 40V-20A

First, I set the limits as these and then I powered the iCub. I have a switch for turning on/off the CPU and motors as seen in connection diagram. I turned on CPU and no problem. But the moment **I turned on the motors switch, xantrex XFR 60-46 goes into S/D**.

So I guess there is a problem with the motors and I am looking for a solution to spot the cause.

## Devices at Hand
-	iCubAnkara01 (iCub 1.x, version not exactly known)
-	Power Supply 1: xantrex XFR 35-35
-	Power Supply 2: xantrex XFR 60-46
-	iCub Laptop: DELL Latitude E4300

The model seems to be iCub 1.x as I learned from Marco Maggiali, which the documentation does not support anymore. You can find photos below to make sure. I even made a diagram of connections to spot the exact version of it, hopefully.

| <img src="https://github.com/robotology/community/assets/71343894/dc957a50-83e5-4004-897a-24b4884225ee" alt="drawing" width="150"/>  | <img src="https://github.com/robotology/community/assets/71343894/5defc9af-6299-482b-a2ae-f0a4c5280e39" alt="drawing" width="150"/>  | <img src="https://github.com/robotology/community/assets/71343894/98dc8e9d-6d35-4ffe-b899-8855905282f2" alt="drawing" width="450"/>  |
|---|---|---|
| iCubAnkara01  | The single output connection  |  The connection diagram |

Note: I have not pressed any button to start icub-head, is there any button in this model? According to the documentations, there is one in the newer models, but I do not know about this model.

Thank you so much in advance and hopefully this little guy will receive its second chance in life :)

**Comment by maggia80** [comment]
@EbruBaglan please check the datasheet of the power supply and please verify the OVP (overvoltage protection) [XANTREX - Power supply 2.8Kw XFR_60_46.pdf](https://github.com/robotology/icub-tech-support/files/13391873/XANTREX.-.Power.supply.2.8Kw.XFR_60_46.pdf)

Have you tried to press the S/D button? 

Could you take a picture of the back of the power supply?

**Comment by EbruBaglan** [comment]
Hello @maggia80,

I checked the OVP setting and S/D functionality from the datasheet and logged my previous steps/trials and some videos of how I set the OVPs and how the problem I face is occuring on a repo.

Below are the related videos of how I set OVP and the problem in the videos from [iCubAnkara01_resurrection](https://github.com/EbruBaglan/iCubAnkara01_resurrection). 
After the second video **I pushed IN the S/D button but nada, the LED is still on even if the button is IN.**

| [![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/xOZpz2rBuVQ/0.jpg)](https://www.youtube.com/watch?v=xOZpz2rBuVQ) |
|:--:|
| *Reviving the iCub - Step2.1: Setting Power Supplies* |

Here is the video of the issue:

| [![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/d_11lxKhAT4/0.jpg)](https://www.youtube.com/watch?v=d_11lxKhAT4) |
|:--:|
| *Reviving the iCub - Step2.2: Powering the Robot* |

Below is the SW1 switch at the rear panel. If you need other parts shown, tell me and I will upload right away.
  | <img src="https://github.com/robotology/icub-tech-support/assets/71343894/f0e02f65-8626-4552-8640-97f6c2b24296" alt="drawing" width="600"/> |
  |:--:|
  | *SW1 at rear panel* |

According to the datasheet, S/D functionality can also be set differently from the rear panel as follows.
  | <img src="https://github.com/EbruBaglan/iCubAnkara01_resurrection/assets/71343894/259a6b59-a970-4c43-9f41-036a8bd57f31" alt="drawing" width="600"/> |
  |:--:|
  | *S/D Function at page 63* |

And actually, in my first days of dealing with this power supply(w/o connecting to the robot), I faced an issue. S/D led was always ON, no matter what I did with the S/D button. And the way to solve it was to change the SW1-7 to the factory default (Check the [Day5 of the repo](https://github.com/EbruBaglan/iCubAnkara01_resurrection#day5) )

**Comment by maggia80** [comment]
@EbruBaglan sorry for the late reply. I think you should move the SW1-7 to the previous configuration. The bigger power supply (PS)should start with 0V. Once you switch ON the 12V PS and than you turn the two selectors (pc104 and motors), the bigger PS should be enabled, powering the motor cards

**Comment by EbruBaglan** [comment]
I think the order I powered the PS was the issue, and I think it is solved now, as both PS are okay (without S/D) and the leg LEDs are also on (pics below). Thank you! 

Are there other checks to make sure everything is powered without any problem? Or, if these are enough, I can ask further questions about moving the arms/legs in another issue, and we can close this issue.

  | PSs  | Leg LEDs |
  |---|---|
  | <img src="https://github.com/robotology/icub-tech-support/assets/71343894/a64bbec0-a64f-4015-af61-e624756ee47e" alt="drawing" width="450"/>  | <img src="https://github.com/robotology/icub-tech-support/assets/71343894/40c01478-4cdc-4033-b695-e5d09b7baf08" alt="drawing" width="150"/> |

**Comment by maggia80** [comment]
ok! great! You can go on with the tests without any problem

**Comment by EbruBaglan** [comment]
Okay! Thank you and see ya!
