### ISSUE TITLE
ergoCub 1.0 S/N:000 – Robot shaking

### ISSUE THREAD

**Issue by CarlottaSartore** [robotology/icub-tech-support#1675]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

The robot shakes when controlled in position.
 

### Detailed context

https://github.com/robotology/icub-tech-support/assets/56030908/eabdab12-155e-451d-92c1-a33afceb6ff9

https://github.com/robotology/icub-tech-support/assets/56030908/b3e30d7e-f0c3-4c64-8969-2c75750412ab

**Comment by CarlottaSartore** [comment]
C.C. @DanielePucci @lrapetti @fbiggi @S-Dafarra @GiulioRomualdi 
Maybe related to https://github.com/robotology/icub-tech-support/issues/1672

**Comment by CarlottaSartore** [comment]
@carloscp3009

**Comment by fbiggi** [comment]
Replacement of screws and tightening according to table
addition of LOCTITE 648 threadlocker
I await information on the correct functioning of the right leg
the same operation was performed on the left leg da @AntonioConsilvio @GiacomoVassallo13 

![image](https://github.com/robotology/icub-tech-support/assets/20420331/8e19f85c-4bae-44ef-93bd-37b0684b1c24)

![20231109_071347](https://github.com/robotology/icub-tech-support/assets/20420331/838719f0-ba01-4008-ae1e-9064fde9623c)
![20231109_072718](https://github.com/robotology/icub-tech-support/assets/20420331/a36345c8-ae0d-46c0-8ece-fd3eee25246f)
![20231109_075339](https://github.com/robotology/icub-tech-support/assets/20420331/8b1053f9-aac1-457a-b5b7-6c18de9daebf)
![20231109_081232](https://github.com/robotology/icub-tech-support/assets/20420331/34f918be-838e-4417-8878-c240c4d7fc1e)

@maggia80 @Fabrizio69 @sgiraz

**Comment by sgiraz** [comment]
Well done guys! 

I think that this issue can be closed.
Feel free to re-open if necessary.
