### ISSUE TITLE
ergoCub 1.0 S/N:000 – Connector of the right hip pitch encoder cable broken

### ISSUE THREAD

**Issue by paolo-viceconte** [robotology/icub-tech-support#1676]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

The connector of the cable of the right hip pitch encoder broke.

### Detailed context

While calibrating the robot, the cable of the right hip pitch encoder detached twice and then its connector broke.

**Comment by paolo-viceconte** [comment]
cc @DanielePucci @GiulioRomualdi @carloscp3009

**Comment by AntonioAzocar** [comment]
> The connector of the cable of the right hip pitch encoder broke.

Hi @paolo-viceconte the connector mentioned in this issue is this, right?



![AMO broken 1](https://github.com/robotology/icub-tech-support/assets/130973726/1a13caa6-f963-4e87-ad11-a90375b0dd6f)


Anyway, when can we intervernize with the AMO (cod. 6778.B) replacement?


cc @sgiraz @Fabrizio69

**Comment by paolo-viceconte** [comment]
> Hi @paolo-viceconte the connector mentioned in this issue is this, right?

Yes, I meant that one (I wanted to take a picture but that piece had been detached from the robot), i.e. the connector of this cable:

![photo_5935750034521964830_y](https://github.com/robotology/icub-tech-support/assets/41757826/f1672be7-db26-4697-97ae-501ced1aa22a)

> Anyway, when can we intervernize with the AMO (cod. 6778.B) replacement?

Whenever you can, from my side!

**Comment by AntonioAzocar** [comment]
I replaced the AMO board with the damaged connector and now the robot is working properly again.

cc @sgiraz @paolo-viceconte
