### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Torso roll joint jumps at random times to random positions

### ISSUE THREAD

**Issue by HosameldinMohamed** [robotology/icub-tech-support#1680]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

The torso roll joint jumps to a random position during normal operation. The trigger of this is still unknown, it happened during the moving of the legs joints.

### Detailed context

The video below shows one time when the problem occurred.

### Additional context

The same video shows also #1679.

https://github.com/robotology/icub-tech-support/assets/45564317/2461fd7f-0785-4f2c-9a6c-1ba5cc121b7c

### How does it affect you?

It blocks iRonCub experiments.

CC @gabrielenava @DanielePucci

**Comment by GiacomoVassallo13** [comment]
Hi. The faulted motor was the hip roll of right leg not the waist. 
The faulted motor has been replace wich a new one. 
I attach the photo of the replaced stator:

![Image](https://github.com/robotology/icub-tech-support/assets/70649516/03fe8742-3f80-4925-9022-b492e0984c70)

The optical disc was also replaced as it was worn ,and the correct reading was verified with the bench test.

Unfortunately, I would like to point out that the assembly is missing some components: in particular the front edges of the sprockets and a  piece of the belt tensioner.

![AAAAAAAAAAAAA](https://github.com/icub-tech-iit/proto/assets/70649516/65b80a80-d8fb-4b3a-a6a0-52aa32084fd6)

This components will be added the as they become available.

The motor group was reassembled on the robot. @AntonioAzocar will take care of the electronic wiring of the new engine.


cc: @Fabrizio69 @sgiraz @AntonioConsilvio

**Comment by gabrielenava** [comment]
to clarify: the issue that is tracking the hip roll problems is this one: https://github.com/robotology/icub-tech-support/issues/1652

while we opened this issue to understand why the torso roll sometimes jumps from one position to another, which is not correlated with the hip roll problem.

cc @sgiraz @Fabrizio69

**Comment by GiacomoVassallo13** [comment]
Thanks @gabrielenava

**Comment by HosameldinMohamed** [comment]
We started the robot and torso roll joint behaving as expected. The issue did not appear again for the whole period of the test!

**Comment by AntonioConsilvio** [comment]
Just for clarity, the cable found damaged and fixed by @AntonioAzocar was the cable that connects the optical encoder (LCORE5) with the 2FOC.

Since the robot has been tested, I will proceed with closing the issue, if the problem returns feel free to reopen this issue!

cc @sgiraz @HosameldinMohamed @gabrielenava
