### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Right shoulder pitch cable has one broken wire

### ISSUE THREAD

**Issue by HosameldinMohamed** [robotology/icub-tech-support#1684]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

We just saw that the cable that connects the optical encoder to the right shoulder motor `E1` that has one wire broken.

### Detailed context

The broken wire is the black one. We do not recall any activity that caused this issue.

The glue seems old and hardened.

### Additional context

![tmp_3693e845-686c-4071-9a57-43421e4a6588.jpeg](https://github.com/robotology/icub-tech-support/assets/45564317/9cc2f9eb-fbd1-4159-8846-0ed5ba184be7)

![tmp_c6a083b0-364a-44cc-9ab8-08ce658939cd.jpeg](https://github.com/robotology/icub-tech-support/assets/45564317/26f27afe-42e9-4c84-99db-049435545c76)

![tmp_c6a083b0-364a-44cc-9ab8-08ce658939cd.jpeg](https://github.com/robotology/icub-tech-support/assets/45564317/0307e1ee-3d1a-4e84-ab33-41e54d88ef7a)

![tmp_a509fcba-0aa2-40af-a3ed-385c4f05ae09.jpeg](https://github.com/robotology/icub-tech-support/assets/45564317/c0be6382-45de-4e85-914b-6679588a9769)

### How does it affect you?

It may block iRonCub experiments.

**Comment by HosameldinMohamed** [comment]
We will attempt a quick fix if we borrow the tools!

**Comment by HosameldinMohamed** [comment]
From https://github.com/icub-tech-iit/electronics-wiring-public/blob/master/icub3/pdf/iCub%203_10360_Upperbody%20Harness.pdf

Here's the type of connector and size (AWG):

![image](https://github.com/robotology/icub-tech-support/assets/45564317/4b8fb476-fddc-4799-ab41-79adeaa36f64)

**Comment by HosameldinMohamed** [comment]
With @pillai-s we crimped the broken cable! We started the robot and joint works as expected!

The fix is temporary because the repaired wire is shorter than the others. Also no glue is applied on connector.

In general the whole cable seems short so probably if a new crimping is necessary we might need to replace it!

**Comment by gabrielenava** [comment]
cc @Gandoo

**Comment by Gandoo** [comment]
ciao @gabrielenava  ho ripristinato il cavo e preparato i cavi spare

![627fff8a-3ac9-444d-9ee1-8680314d9437](https://github.com/robotology/icub-tech-support/assets/53341641/f97eb6a9-0663-41f6-84d6-6cebb37b7262)

![d3d0ad43-a8ee-4334-add0-43db50a3527c](https://github.com/robotology/icub-tech-support/assets/53341641/ab8e3207-27de-42d5-b63b-ff0a58e283f1)

![a1a6e186-8ebb-4f3a-8171-98c348788273](https://github.com/robotology/icub-tech-support/assets/53341641/7e195720-6577-43bf-8625-d786f25a070a)

cc @AntonioConsilvio @sgiraz
