### ISSUE TITLE
iCubGenova03 S/N:020 – Broken cables in iCub's shoulder

### ISSUE THREAD

**Issue by marco-matarese** [robotology/icub-tech-support#1685]
### Robot Name 🤖

iCubGenova03 S/N:020

### Request/Failure description

Cables 3, 4, and 6 of the iCub's right shoulder broke and need to be replaced.

### Detailed context

We broke and removed the cables 6, 4 and 3 of the iCub's right shoulder. Usually, we replace the 6 by ourselves, but replacing the 3 and 4 seemed more complex to handle. 

![photo1700061947](https://github.com/robotology/icub-tech-support/assets/36852323/296cdd5c-1bd2-404b-a126-723985873a3c)

**Comment by marco-matarese** [comment]
Hi, when can we schedule the intervention?

**Comment by sgiraz** [comment]
Hi @marco-matarese,

Actually, we have some urgent interventions and demo that require immediate attention, but if you agree we may schedule the maintenance for a day among the November 29th and December 1st.
Tomorrow I can propose you the exact possible days.

cc @AntonioConsilvio @GiacomoVassallo13

**Comment by sgiraz** [comment]
/remind on 29th November maintenance activity scheduled for tomorrow (cc @AntonioConsilvio @GiacomoVassallo13 @Fabrizio69)

**Comment by GiacomoVassallo13** [comment]
Hi. The broken tendon of left shoulder has been replaced. And the robot has been successfully tested.

cc: @AntonioConsilvio @sgiraz
