### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Chest IMU cable pulled out from sleeve and probably disconnected

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1689]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

The cable of the chest IMU pulled out of the sleeve during experiments with iRonCub, close to the connection with the chest IMU. The cables inside do not look disconnected or broken, nevertheless the IMU does not start anymore. We created a workaround with another (external) cable and the IMU is working fine, so we suspect that the cable not only exited the sleeve but also got damaged somehow.

### Detailed context

![MicrosoftTeams-image](https://github.com/robotology/icub-tech-support/assets/12396934/7fcf801e-db9c-429e-a776-757a2f0ad630)

**Comment by Gandoo** [comment]
fili strappati 

![5af72309-c891-43bb-ba22-84d61c1ea5cc](https://github.com/robotology/icub-tech-support/assets/53341641/910b3f16-f507-4b49-a3e3-4bc2e9b4587a)

**Comment by Gandoo** [comment]
ciao @gabrielenava  ho ripristinato il filo nero strappato e la schermatura del cavo che era saldata sul manicotto del connettore. Vi chiedo solamente di fare attenzione nello sconnettere il connettore dalla IMU facenso forza dove indicato dalla freccia e NON sul cavo per evitare di danneggiare il cavo. 
Grazie, Buona giornata!!

![9897de35-544e-476f-8179-f33ff1789f04](https://github.com/robotology/icub-tech-support/assets/53341641/502aae23-2ab7-4795-9dac-c287722d2658)

![3b37271e-cb88-4f6a-acf3-7fbb09cb6f42](https://github.com/robotology/icub-tech-support/assets/53341641/bb3a81be-b9fa-4e78-8b3a-b43d36a3a828)

cc @Fabrizio69 @DanielePucci @AntonioConsilvio @sgiraz

**Comment by sgiraz** [comment]
Ciao @gabrielenava,

Have you tested the IMU? I guess that is working now, isn't it? :) 

cc @Gandoo @AntonioConsilvio @Fabrizio69

**Comment by gabrielenava** [comment]
>Have you tested the IMU? I guess that is working now, isn't it? :)

ciao @sgiraz not yet, but there are some tests scheduled for tomorrow and I can verify the IMU

**Comment by gabrielenava** [comment]
I have tested the robot in these days and the IMU is working fine! thanks again! we can close the issue
