### ISSUE TITLE
iCubGenova11 S/N:050 – The left arm oscillates in certain configurations, probably due to the shoulder roll

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1691]
### Robot Name 🤖

iCubGenova11 S/N:050

### Request/Failure description

While testing a demo today I noticed that in certain configurations the left arm oscillates a lot making the robot possibly **unsafe**. At a certain point the should roll went in HF due to `i2t`.

FYI cc @enyen @GiuliaP 

### Detailed context

I was running a demonstration where the arm is controlled in Cartesian space. Along the planned trajectory there are configurations in which the arm oscillates a lot. The demonstration is not new and has been executed lots of times, hence we know it is safe. 

To me the problems seems very similar to what we had in https://github.com/robotology/icub-tech-support/issues/1488#issuecomment-1406316146. Hence, probably the encoder is not well connected.

### Additional context

I am attaching the `yarprobotinterface` log. 

[log_icub-head_yarprobotinterface_2668.txt](https://github.com/robotology/icub-tech-support/files/13491525/log_icub-head_yarprobotinterface_2668.txt)

### How does it affect you?

@gabrielecaddeo would need to use the left arm for a demonstration this Friday. Without the arm we can partially execute the demonstration. Thank you

**Comment by GiacomoVassallo13** [comment]
Hi @xEnVrE . The left shoulder roll  locked motor has been restored. The malfunction  was caused to the loose srews of wave generator of harmonic drive. 
The screws has been thight and the harmonic was cleaned and regreased.
The joint it' s ready to test.

cc: @Fabrizio69 @sgiraz

**Comment by xEnVrE** [comment]
Thanks @GiacomoVassallo13 

At the moment we cannot run the robot due to the following errors:

![Screenshot from 2023-11-29 14-44-53](https://github.com/robotology/icub-tech-support/assets/6014499/da7adb6c-df9f-4038-8773-74fc66783535)

Attaching the full `yarprobotinerface` log just in case: 

[log_icub-head_yarprobotinterface_2141.txt](https://github.com/robotology/icub-tech-support/files/13501261/log_icub-head_yarprobotinterface_2141.txt)

cc @sgiraz @AntonioConsilvio

**Comment by xEnVrE** [comment]
I tried again. It seems that the system detects the fault button as pressed - as if the fault line was interrupted somewhere:

![Screenshot from 2023-11-29 14-54-18](https://github.com/robotology/icub-tech-support/assets/6014499/22d81aaf-0aa5-4c32-ab27-1e7186747df0)

Full log: 
[log_icub-head_yarprobotinterface_2521.txt](https://github.com/robotology/icub-tech-support/files/13501292/log_icub-head_yarprobotinterface_2521.txt)

**Comment by sgiraz** [comment]
Hi @xEnVrE,


@AntonioAzocar is going to check for faulty cables... stay tuned!

**Comment by xEnVrE** [comment]
We have tested the motion of the `shoulder roll` and it was fine. Closing.

Aside: the robot did not started because of a malfunctioning torso IMU. I am going to open a new issue specifically for that. For the moment being we are commenting the relevant part inside the `icub_all_no_legs.xml` file inside `$ROBOT_CODE/src/robotology_superbuild/src/robots-configuration/iCubGenova11`.
