### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – EMS Ethernet cable disconnected

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1693]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

The ehternet cable of the EMS on the back of iRonCub3 disconnected.

### Detailed context

We tried to start the robot and it didn't start. Run `firmwareupdater`: we were not able to see all boards starting from EB5. 

We checked and saw that the Ethernet cable of a board on the robot back (I presume, EB5) disconnected from the  crimp.

### Additional context

![MicrosoftTeams-image](https://github.com/robotology/icub-tech-support/assets/12396934/44e3ee6d-642a-4474-b752-146872a3b842)

cc @DanielePucci @HosameldinMohamed 

### How does it affect you?

we need to pack the robot for wind tunnel tomorrow.

**Comment by HosameldinMohamed** [comment]
With @pillai-s we crimped the broken wire (the white one), and the ethernet network is restored.

We didn't change the rest of the wires in the cable so the white wire is shorter than the rest of them.

I don't have a picture of the robot, maybe you can add one?

CC @gabrielenava

**Comment by gabrielenava** [comment]
>I don't have a picture of the robot, maybe you can add one?

not really visible, but here the picture we took Friday:


![MicrosoftTeams-image (1)](https://github.com/robotology/icub-tech-support/assets/12396934/fc9b1d12-38a7-41aa-bb92-04f703c2228f)

**Comment by AntonioAzocar** [comment]
Hi @HosameldinMohamed , @gabrielenava !

As you can see in the picture, I fixed the **ETH** cable

![ETH_iRonCub3](https://github.com/robotology/icub-tech-support/assets/130973726/66405031-b7ea-493d-a41f-b9c688f92d6d)



cc @sgiraz @AntonioConsilvio

**Comment by sgiraz** [comment]
Well done @AntonioAzocar! 🙏🏻

I already discussed F2F w/ @gabrielenava!
The robot is working as expected.

Closing!
