### ISSUE TITLE
Right shoulder yaw motor moves suddenly when the lower arm is touched 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1696]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

While touching the lower arm the shoulder yaw started moving. The motor was controlled in position

### Detailed context

https://github.com/robotology/icub-tech-support/assets/16744101/3859c3be-e971-4439-9908-b925b8fe2e00

**Comment by AntonioConsilvio** [comment]
> @AntonioConsilvio let's change the https://github.com/robotology/robots-configuration/blob/master/ergoCubSN001/hardware/motorControl/right_arm-eb3-j2_3-mc_service.xml replacing `AMO` with `NONE`

Hi @maggia80, I did it and now it works properly.

cc @GiulioRomualdi
