### ISSUE TITLE
iCubGenova11 S/N:050 – Left wrist tendon broken

### ISSUE THREAD

**Issue by fedeceola** [robotology/icub-tech-support#1698]
### Robot Name 🤖

iCubGenova11 S/N:050

### Request/Failure description

As per title, while running some experiments the the tendon of the left wrist broke.

### Detailed context

-

### Additional context

![MicrosoftTeams-image (1)](https://github.com/robotology/icub-tech-support/assets/32268209/b4bdbd66-3f7c-467b-bbeb-fddb91d8599d)

**Comment by xEnVrE** [comment]
Dear all, there is a demonstration on December 20th for the OpenDay. Is there a plan for repairing the tendon of the wrist? Thank you

cc @sgiraz

**Comment by GiacomoVassallo13** [comment]
Hi @xEnVrE . Today I replace the broken wrist tendon. Actually the joint work well, now need to test it under control.  All of proximal has been tense, because they are involved in the extraction of the wrist motor.
I attend feedback after testingon control.

cc: @Fabrizio69 @sgiraz

**Comment by xEnVrE** [comment]
Hi @GiacomoVassallo13 I tested the robot now. Unfortunately it does not complete the calibration.

I am attaching the log of the `yarprobotinterface`: 
[log_icub-head_yarprobotinterface_1786.txt](https://github.com/robotology/icub-tech-support/files/13675501/log_icub-head_yarprobotinterface_1786.txt)

cc @sgiraz @AntonioConsilvio

**Comment by sgiraz** [comment]
Ho @xEnVrE,

What about the motorgui readings?
Do you spot any encoder stuck to a fixed value or with a wrong reading?

@GiacomoVassallo13 @AntonioAzocar I would chack the encoders connected to the eb24:

![image](https://github.com/robotology/icub-tech-support/assets/18039045/7bf404ee-3d3c-4d42-bdf8-372b5c3ca6e8)

**Comment by xEnVrE** [comment]
I tried to restart it again and now it worked - not sure what happened, maybe one of the board did not start properly? I tested re-running it several time from scratch and it worked.

I think we can close the issue.

Thanks @GiacomoVassallo13 @sgiraz
