### ISSUE TITLE
R1 S/N:003 – Robot shoulder wobbling after fall

### ISSUE THREAD

**Issue by elandini84** [robotology/icub-tech-support#1704]
### Robot Name 🤖

R1 S/N:003

### Request/Failure description

The robot left should shoulder is wobbling significantly if pushed or pulled by hand (even gently).

### Detailed context

The robot crate fell from the truck when the couriers where unloading it at Palazzo della borsa for the Edge 2023 event. After removing the robot from the crate, we checked it and found out about the shoulder. We then removed the torso covers to check if there were any visible damages. But we found none.
The robot should be checked in order to exclude any internal damage that could become worse moving the arm during demos or experiments.

### Additional context

This video shows the behaviour of the robot shoulder

https://github.com/robotology/icub-tech-support/assets/62991576/7f2c65c5-2a87-4af5-b6c9-fc5f7631cbf0

**Comment by fbiggi** [comment]
Below are the various interventions carried out
after uncovering the robot I went to enter 2 code spacers
wingst 10850 AS-1528
V4-40--_-_U5931_GP screws have been registered
arm play has been restored
Movement test performed together with @ste93 : test ok

![image](https://github.com/robotology/icub-tech-support/assets/20420331/9855c39a-f35d-4736-9d36-06f9c9bce423)


![20231214_083056](https://github.com/robotology/icub-tech-support/assets/20420331/7b25c601-81a9-479d-8d0d-002a5102477b)
![20231214_091954](https://github.com/robotology/icub-tech-support/assets/20420331/89b5274e-4e33-42a4-bd59-48489f6ba77f)
![WhatsApp Image 2023-12-14 at 11 17 55](https://github.com/robotology/icub-tech-support/assets/20420331/97792284-715f-448a-a657-562362b94fc2)

@maggia80 @sgiraz @Fabrizio69

**Comment by elandini84** [comment]
Thanks a lot @fbiggi.
We can consider the issue closed.
