### ISSUE TITLE
ergoCub 1.1 S/N:001 – Left and right ankle roll motors moving

### ISSUE THREAD

**Issue by G-Cervettini** [robotology/icub-tech-support#1706]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The left and right ankle roll motors seem to move when pushed.  

### Detailed context

This is the linked video. If you enable the audio, you can listen to the sound produced by the ankles.  

https://github.com/robotology/icub-tech-support/assets/101020439/b8aea16a-08f9-44da-8cdd-d0ec75508e7f

### Additional context

It occurred in the past as in https://github.com/robotology/icub-tech-support/issues/1662 and https://github.com/robotology/icub-tech-support/issues/1503

### How does it affect you?

cc @DanielePucci  @GiulioRomualdi

**Comment by DanielePucci** [comment]
We should understand a way to avoid this problem to recur. It may happen at demo time, and we may not spot the problem easily 

CC
@sgiraz @Fabrizio69 @maggia80

**Comment by maggia80** [comment]
@fbiggi fixed the issue yesterday. The length of the screw was a bit too much touching the bottom of the threaded hole instead of tightening the two parts.

**Comment by sgiraz** [comment]
> @fbiggi fixed the issue yesterday. The length of the screw was a bit too much touching the bottom of the threaded hole instead of tightening the two parts.

Thanks @fbiggi!
@fiorisi I suppose that some changes are needed on CAD, right? 

I consider this issue solved.

**Comment by fbiggi** [comment]
Hi, @sgiraz all changes to CAD have already been handled by Elio
