### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Broken cable on board 10.0.1.12

### ISSUE THREAD

**Issue by davidegorbani** [robotology/icub-tech-support#1707]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

We were starting the robot but it was not working and the logger showed the following error:

![Screenshot from 2023-12-15 12-00-38](https://github.com/robotology/icub-tech-support/assets/101326942/7efe00f6-fecc-4b71-88b7-1b4b65a647e1)

So we opened the right lower leg and foot cover and found out that the cable connecting the front FT to the board is broken:

![MicrosoftTeams-image](https://github.com/robotology/icub-tech-support/assets/101326942/d5495eb7-1ae7-4285-9ae7-684ded148f1f)

CC @gabrielenava 

### Detailed context

We broken the CAN2:1 cable from the `10.0.1.12` board to the FT sensor.

**Comment by davidegorbani** [comment]
@AntonioAzocar fixed it and not the robot is working.

**Comment by sgiraz** [comment]
Well done @AntonioAzocar!

Closing.
