### ISSUE TITLE
ergoCub 1.1 S/N:001 – Right little finger tendon got broken

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1716]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

While fixing https://github.com/robotology/icub-tech-support/issues/1713
@AntonioConsilvio noticed that the right little finger tendon was broken 

### Detailed context

.

**Comment by AntonioConsilvio** [comment]
Hi! I discovered that the pinky tendon on right hand was broken, slipping out of the pin-screw on the finger side. 
So me and @fbiggi restored it, but unfortunately it broke again.

So we restored the tendon a second time.

The finger worked briefly as it unscrewed the motor side pulley (as happened to the index finger in this [issue](https://github.com/robotology/icub-tech-support/issues/1713)).

Then we proceeded to properly tighten the pulley on the motor.

The robot has been tested and it is working properly now!

cc @maggia80 @fiorisi @Fabrizio69
