### ISSUE TITLE
ergoCub 1.1 S/N:001 – Problems when loading configuration files for torque control parameters

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1718]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

Today, we started with @isorrentino to work to test the Yoga demo on the real robot after the preliminary results in https://github.com/ami-iit/element_qp-reactive-control/issues/70. 

So, we started modifying the files for loading the parameters of torque control. See the commit https://github.com/ami-iit/robots-configuration/commit/f6fe83cf51cf5e385477fbe4fdc2bd043313191e

Unfortunately, these parameters seem not loaded in the motor gui 

![image](https://github.com/robotology/icub-tech-support/assets/5045846/2f62bfc6-85b5-49ff-9889-c0d7c13b12a4)

And we cannot at the moment test the torque control since adding them manually for all the joints is a very long process

### Detailed context

This is the output of yarprobotinterface 
[output_interface.txt](https://github.com/robotology/icub-tech-support/files/13988627/output_interface.txt)

@Nicogene @sgiraz @maggia80

**Comment by sgiraz** [comment]
Hi @DanielePucci,

The `Parser` seems to parse correctly the values set in config files:

```console
...

(stictionUp 0 0 0) (stictionDown 0 0 0) (kff 1 1 1) (viscousPos 0 0 0) (viscousNeg 0 0 0) (coulombPos 0 0 0) (coulombNeg 0 0 0) (velocityThres 0.1 0.1 0.1) (filterType 0 0 0) (ktau 176 176 -176)"), ("OTHER_CONTROL_PARAMETERS" [group] = "(deadZone 0.0049 0.0049 0.0049)")]

...
```

I'm not sure, but as a first quick view to the info provided, it could be a (wrong) cast from float to int that trunkates the 0.1 to 0. 
By the way,  we'll perform some tests in during our next sprint (starting from Monday 22).


cc @Nicogene

**Comment by sgiraz** [comment]
Hi @DanielePucci,

I fixed a bug in `icub-main` that was preventing the parsing of torque parameters when the (⚠️ deprecated) `kbemf` parameter was missing. Here's the PR that addresses the issue:
- https://github.com/robotology/icub-main/pull/935

cc @isorrentino @GiulioRomualdi @AntonioConsilvio

**Comment by DanielePucci** [comment]
Thanks a lot @sgiraz, hopefully tomorrow we are going to give it a try!

**Comment by isorrentino** [comment]
Today, @DanielePucci and I tested the PR. Now everything works fine. Thanks a lot.

**Comment by sgiraz** [comment]
Hi @isorrentino, @DanielePucci 

Thank you for your precious feedback.

I proceed closing this issue! ✅

Cc @Nicogene @AntonioConsilvio
