### ISSUE TITLE
ergoCub 1.1 S/N:001 – Neck cable broken

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1721]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

During the tests for the yoga, the robot was faulted and then the neck cable got broken

### Detailed context

See above

**Comment by fbiggi** [comment]
@DanielePucci 

Neck cord repaired
I await your info after movement tests

@Fabrizio69 @sgiraz @maggia80

**Comment by GiacomoVassallo13** [comment]
We waiting the feedback of testing in control.

cc: @Fabrizio69 @sgiraz

**Comment by sgiraz** [comment]
Hi @DanielePucci 

The neck has been successfully repaired by @fbiggi. The robot's current utilization suggests that the repaired neck is functioning properly, is it right?

cc @GiacomoVassallo13 @Fabrizio69 @AntonioConsilvio

**Comment by sgiraz** [comment]
Nice! 

Closing as solved, then! 

>[!Note]
>Investigations and improvements are under the way in order to avoid this issue asap.
