### ISSUE TITLE
ergoCub 1.1 S/N:001 – Neck cable broken

### ISSUE THREAD

**Issue by SimoneMic** [robotology/icub-tech-support#1722]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The neck tendon broke during a sudden movement of the torso due to an unexpected singularity during test grasping.

### Detailed context

![1 photo added](https://github.com/robotology/icub-tech-support/assets/86918431/8b125af2-33ab-43e9-9db4-e82052cc1dbf)

**Comment by GiacomoVassallo13** [comment]
Hi the broken tendon has been replaced.  i ttend a fedback of the testin in softwere.

cc: @Fabrizio69 @sgiraz @AntonioConsilvio @fbiggi

**Comment by mebbaid** [comment]
We didn't have any issues from the neck during our experiment that included walking with the neck joints controlled.

**Comment by sgiraz** [comment]
Ok, thanks @mebbaid. Closing!
