### ISSUE TITLE
ergoCub 1.1 S/N:001 – head not reachable and torso slow

### ISSUE THREAD

**Issue by mebbaid** [robotology/icub-tech-support#1724]
### Robot Name 🤖

None

### Request/Failure description

while doing some experiments on navigation with @SimoneMic  we lost connection with the head (which is needed for the nav stack).
We tried to ping the head but it is unreachable. In addition, pinging the torso takes on average 200 ms (which seems high)

### Detailed context

while doing some experiments on navigation with @  we lost connection with the head (which is needed for the nav stack).
We tried to ping the head but it is unreachable. In addition, pinging the torso takes on average 200 ms (which seems high)

![image](https://github.com/robotology/icub-tech-support/assets/36491318/9f3775e3-1a13-4388-81fc-2f14d03b7f39)

### How does it affect you?

This issue is blocking for running Navigation with the robot

**Comment by sgiraz** [comment]
Hi @mebbaid,

We can compare the ping time with other robots, but yep, 100+ ms seems high.
Maybe the output of a `[traceroute][1]` command may help us to track the network traffic between the laptop and the torso.

cc @AntonioConsilvio @davidelasagna @Nicogene 

[1]: https://linux.die.net/man/8/traceroute

**Comment by SimoneMic** [comment]
@GiulioRomualdi told me that after a complete reboot of the system (server, router and PCs) the ping has returned to acceptable levels.
However we need the head PC to be working quite soon, due to a demo that has been anticipated on the 31st.
We'd like to do some demo preparation tests on Monday (late) afternoon. 

Thank you and sorry for the pressing

**Comment by GiulioRomualdi** [comment]
I @SimoneMic this morning I checked the

**Comment by sgiraz** [comment]
> We'd like to do some demo preparation tests on Monday (late) afternoon.

Ok guys,

Please keep the network traffic monitored to see if the problem happens again.

**Comment by steb6** [comment]
Today we had a similar issue about slow connection speed with the torso:
```
traceroute to 10.0.2.2 (10.0.2.2), 30 hops max, 60 byte packets
 1  * ergocub-torso (10.0.2.2)  170.508 ms *
```
cc @SimoneMic

**Comment by sgiraz** [comment]
Hi guys,

Thanks for keep monitoring this issue, we'll futher investigate on it.

In the meantime, next time it happens, I would ask you to provide as much context info as possible such as CPU workload ([htop](https://www.man7.org/linux/man-pages/man1/htop.1.html) for the `torso` and [jtop](https://github.com/rbonghi/jetson_stats) for the `head`) and the network traffic ([vnStat](https://linux.die.net/man/1/vnstat))

**Comment by sgiraz** [comment]
Hi guys,

Any news on this? Is still the problem occurring?

cc @steb6 @SimoneMic @mebbaid

**Comment by SimoneMic** [comment]
Actually it seems to be working fine.
Haven't had this issue in a while now

**Comment by mebbaid** [comment]
>  If you agree, I would proceed to close the issue right now.

agreed. In case of things recurring down the line, we will open a separate issue and reference this one.

**Comment by sgiraz** [comment]
Hi @mebbaid 

Ok thanks!
Closing!
