### ISSUE TITLE
iCubGenova11 S/N:050 – Face expressions doesn't work

### ISSUE THREAD

**Issue by martinaxgloria** [robotology/icub-tech-support#1729]
### Robot Name 🤖

iCubGenova11 S/N:050

### Request/Failure description

Face expressions stopped to work.

### Detailed context

At the startup, the LED of the face expressions don't turn on anymore. In the past days, the cover of the head was opened, so maybe a cable was disconnected.

![photo1706605194](https://github.com/robotology/icub-tech-support/assets/114698424/9d934eae-1786-4757-95d3-5659977842ac)

**Comment by AntonioAzocar** [comment]
Hello! I redid the cable (SPI1_3) connecting the **RFE** to the **Left Eyebrow** board and the face expressions are working again!
Thanks @sgiraz and @AntonioConsilvio 

![image](https://github.com/robotology/icub-tech-support/assets/130973726/19260973-e0c1-4dcb-8c27-d10beb1b1e43)

**Comment by sgiraz** [comment]
Well done @AntonioAzocar! 🚀

Closing as solved.
