### ISSUE TITLE
ergoCub 1.1 S/N:001 – Neck broken

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1730]
### Robot Name 🤖

None

### Request/Failure description

Kindly ask to repair the neck cable. This is very important in view of tomorrow's demos 
* https://github.com/ami-iit/lab-events-demos/issues/296
* https://github.com/ami-iit/lab-events-demos/issues/297

### Detailed context

We were running some tests on the robot and the torque control seemed to not ask for enough torque around the torso pitch. So, the torso went forward and the robot had a flick (colpo di frusta) breaking the neck.

![IMG_3679](https://github.com/robotology/icub-tech-support/assets/5045846/3e386cb9-2d65-4e35-82b4-bf6f300ca271)

**Comment by sgiraz** [comment]
This morning @AntonioAzocar @fbiggi repaired the tendon.

**Comment by DanielePucci** [comment]
Thanks a lot @sgiraz. I think we can close this issue then.
