### ISSUE TITLE
ergoCub 1.1 S/N:001 – l_ankle_pitch went in harware fault while walking

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1734]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

Similarly to https://github.com/robotology/icub-tech-support/issues/1726 the robot went in hf while walking 

### Detailed context

Similarly to https://github.com/robotology/icub-tech-support/issues/1726 the message in the motorgui was "generic can error" I think due to https://github.com/robotology/icub-main/issues/937. The yarplogger saturated after few seconds with 
![image](https://github.com/robotology/icub-tech-support/assets/16744101/0ccabd7c-12ac-4ee3-ac8c-f83b204bd822)

### Additional context

This videos shows the experiment, as you can see the motor went in HF while walking 

[Screencast from 01-30-2024 05:16:50 PM.webm](https://github.com/robotology/icub-tech-support/assets/16744101/715712d3-0f65-40aa-b900-7e768300074e)

### How does it affect you?

Tomorrow we have https://github.com/ami-iit/lab-events-demos/issues/296 and next week we have an important demo in Rome

**Comment by AntonioConsilvio** [comment]
Since this issue is related to this one:

- https://github.com/robotology/icub-tech-support/issues/1726

It will be closed for the same reason, see comment:

- https://github.com/robotology/icub-tech-support/issues/1726#issuecomment-2098176076
