### ISSUE TITLE
ergoCub 1.1 S/N:001 – Robot going in overtemperature, which seems a false positive

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1738]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The `left_hip_roll` goes to overheating, which seem a false positive. 

### Detailed context

After deploying the firmare for checking the temperature on the left leg in https://github.com/MSECode/icub-firmware/tree/fix/temperatureReading, @Miche19 and @mebbaid were trying to walk. After few steps, the robot fell 

https://github.com/robotology/icub-tech-support/assets/5045846/2801b563-4a1e-4ac4-9dd7-390d7fadd5f9

By checking at the yarpmotorgui, it seems an overheating
![image](https://github.com/robotology/icub-tech-support/assets/5045846/40fe975a-e1a0-4e61-9786-05212609ae49)

However, it seems a `false positive` since by putting the joint in idle and back to run it immediately gets back to run.

We don't have additional temperature data.

**Comment by maggia80** [comment]
I would check the value of the temperature because it goes down quite rapidly.

https://icub-tech-iit.github.io/documentation/temperature_sensors/general/overview/?h=temper#how-to-read-the-motor-temperature

**Comment by DanielePucci** [comment]
This issue seems that was related to https://github.com/robotology/icub-tech-support/issues/1739. After cleaning the LCORE, we no longer had the overheating problem. The robot walked for about five minutes and the temperatures look consistent.
![image](https://github.com/robotology/icub-tech-support/assets/5045846/b9d2adb3-ba20-4b6f-9f9a-0a164469d07e)

So, actually the over temperature we got in the video above might have been true, and the protection system most likely worked!

On a side note, after https://github.com/robotology/icub-tech-support/issues/1739, the robot started walking much better and with less oscillations.

So, closing.

@GiulioRomualdi @isorrentino
