### ISSUE TITLE
ergoCub 1.1 S/N:001 – `letf_hip_roll` not calibrating

### ISSUE THREAD

**Issue by SimoneMic** [robotology/icub-tech-support#1739]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The robot doesn't finish the calibration of the left leg hip roll.

https://github.com/robotology/icub-tech-support/assets/86918431/61455f96-d0a5-438d-993a-0cc2d8d4a215

cc @DanielePucci 

### Detailed context

Log of the yarprobotinterface:
[log_ergocub-torso_yarprobotinterface_4957.zip](https://github.com/robotology/icub-tech-support/files/14128186/log_ergocub-torso_yarprobotinterface_4957.zip)

**Comment by DanielePucci** [comment]
@sgiraz cleaned the LCORE of the hip roll and the robot started working again. Thank you all, closing.
