### ISSUE TITLE
ergoCub 1.1 S/N:001 – Right thumb got detached from the hand

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1740]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

While testing the torque balancing, the robot collapsed; we pushed the fault button. During the process of catching it, the right thumb became detached from the hand.

### Detailed context

Probably there are some cables broken and the grub skewing got damaged.

### Additional context

![20240201_185127.jpg](https://github.com/robotology/icub-tech-support/assets/16744101/f8887cd8-0e65-4aae-8892-c8c99e753294)

**Comment by fbiggi** [comment]
Inserted LOCTITE 648 glue on S3-8--_-_I2338_B.
I await info after movement tests



![20240202_073726](https://github.com/robotology/icub-tech-support/assets/20420331/44c5f350-86ff-4e77-bbdc-14cf36633f14)
![20240202_073924](https://github.com/robotology/icub-tech-support/assets/20420331/1687f3f8-530f-4f55-8466-2811416825dd)


@sgiraz @Fabrizio69 @maggia80

**Comment by GiulioRomualdi** [comment]
Thank you, @fbiggi!

**Comment by fbiggi** [comment]
@GiulioRomualdi 
to position your thumb as you want for your experiments you must loosen the 2 screws as in the photo
The plug that connects the thumb to the palm must remain stationary
Please pass the info to your team


![image](https://github.com/robotology/icub-tech-support/assets/20420331/98b883fd-df67-4b84-96da-b54d019c6141)

@sgiraz @Fabrizio69 @maggia80 @AntonioConsilvio

**Comment by sgiraz** [comment]
Thanks @fbiggi for repairing the thumb! 🚀

I acknowledge that the broken thumb was an accident.

Anyway, consider the [suggestion above](https://github.com/robotology/icub-tech-support/issues/1740#issuecomment-1923247973) posted by @fbiggi in case you need to reposition the thumb-axis-rotation (not actuated).

Closing!

cc @GiulioRomualdi @AntonioConsilvio @SimoneMic @PasMarra @randaz81 @DanielePucci @Nicogene @Fabrizio69
