### ISSUE TITLE
iCubGenova03 S/N:020 – Unable to detect firmware version after updating pc104 OS

### ISSUE THREAD

**Issue by MissingSignal** [robotology/icub-tech-support#1747]
### Robot Name 🤖

iCubGenova03 S/N:020

### Request/Failure description

Dear support,

we updated the OS (USB-live) of our iCub head from _debian Stretch_ to _Buster_.
We then installed (on the head) the latest version of superbuild running yarp 3.9.
When starting the robot through yarprobotinterface we face an error related to CAN firmware.
Apparently the old firmware is no more compatible and needs an upgrade.
We kindly ask your support to upgrade the firmware properly. 
So far from the [FirmwareUpdater](https://icub-tech-iit.github.io/documentation/icub_firmware/firmwareupdater/firmwareupdater/) tool we are not able to detect the current firmware.
 

### Detailed context

We attach the screenshots of the error when running yarp robot interface
![screen1](https://github.com/robotology/icub-tech-support/assets/36140565/a6a4e87a-cceb-47e5-aca9-79a09d5de516)

**Comment by sgiraz** [comment]
Hi @MissingSignal,

Can you describe the way you have built the `robotology-superbuild`?

Can you post here the output of the following commands from the `icub-head` ( pc104 board ):
- `df -h` command
- `ls -lah /usr/local/src/robot`
- `git status` within the /usr/local/src/robot/robotology-superbuild/build-pc104


>[!Note]
>The `build-pc104` folder should have been created (manually) during the robotology-superbuild installation and should contain the built files from `icub-head`.

**Comment by MissingSignal** [comment]
Dear @sgiraz ,
I built the ```robotology-superbuild``` following this [guide](https://icub-tech-iit.github.io/documentation/sw_installation/icub_head_superbuild/).
In particular I compiled with the following flags:  

ROBOTOLOGY_USES_CFW2CAN          **ON** 
ROBOTOLOGY_ENABLE_ICUB_HEAD     **ON**
ROBOTOLOGY_USES_GAZEBO           **OFF**                                                                                                                                                                                                                                                                                   

Here I attach the output of the commands:

### df -h

```Filesystem      Size  Used Avail Use% Mounted on
udev            969M     0  969M   0% /dev
tmpfs           199M  3.1M  196M   2% /run
/dev/sda1       1.5G  1.2G  276M  81% /run/live/persistence/sda1
/dev/loop0      818M  818M     0 100% /run/live/rootfs/filesystem.squashfs
tmpfs           993M     0  993M   0% /run/live/overlay
/dev/sda2        13G  1.4G   11G  11% /run/live/persistence/sda2
overlay          13G  1.4G   11G  11% /
tmpfs           993M     0  993M   0% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           993M     0  993M   0% /sys/fs/cgroup
tmpfs           993M     0  993M   0% /tmp
tmpfs           199M     0  199M   0% /run/user/1000
```

### ls -lah /usr/local/src/robot
``` total 12K
drwxrwxrwx  1 root root 4.0K Feb  9 11:24 .
drwxr-xr-x  1 root root 4.0K Apr 21  2021 ..
drwxrwxrwx 13 root root 4.0K Feb  9 11:29 robotology-superbuild 
```

### git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ../.ci/all-options-enabled-cache.cmake
	modified:   ../.ci/initial-cache.gh.cmake
	modified:   ../.ci/install_debian_and_script.sh
	modified:   ../.ci/script.sh
	modified:   ../.github/dependabot.yml
	modified:   ../.github/workflows/build-docker-images.yml
	modified:   ../.github/workflows/ci.yml
	modified:   ../.github/workflows/generate-conda-packages.yaml
	modified:   ../.github/workflows/matlab-one-line-install-test.yml
	modified:   ../.github/workflows/release.yml
	modified:   ../.github/workflows/update-latest-releases.yml
	modified:   ../.gitignore
	modified:   ../CHANGELOG.md
	modified:   ../CMakeLists.txt
	modified:   ../LGPL.TXT
	modified:   ../README.md
	modified:   ../apt-python.txt
	modified:   ../apt.txt
	modified:   ../cmake/BuildBayesFilters.cmake
	modified:   ../cmake/BuildBlockFactory.cmake
	modified:   ../cmake/BuildCppAD.cmake
	modified:   ../cmake/BuildGazeboYARPPlugins.cmake
	modified:   ../cmake/BuildHumanDynamicsEstimation.cmake
	modified:   ../cmake/BuildICUB.cmake
	modified:   ../cmake/BuildICUBcontrib.cmake
	modified:   ../cmake/BuildLieGroupControllers.cmake
	modified:   ../cmake/BuildOpenVR.cmake
	modified:   ../cmake/BuildOpenXR.cmake
	modified:   ../cmake/BuildOsqpEigen.cmake
	modified:   ../cmake/BuildRobotTestingFramework.cmake
	modified:   ../cmake/BuildUnicyclePlanner.cmake
	modified:   ../cmake/BuildWBToolbox.cmake
	modified:   ../cmake/BuildYARP.cmake
	modified:   ../cmake/BuildYCM.cmake
	modified:   ../cmake/Buildbipedal-locomotion-framework.cmake
	modified:   ../cmake/Buildblocktest-yarp-plugins.cmake
	modified:   ../cmake/Buildblocktestcore.cmake
	modified:   ../cmake/Buildcasadi-matlab-bindings.cmake
	modified:   ../cmake/Buildcasadi.cmake
	modified:   ../cmake/Buildcer.cmake
	modified:   ../cmake/Builddiagnosticdaemon.cmake
	modified:   ../cmake/Buildergocub-software.cmake
	modified:   ../cmake/Buildevent-driven.cmake
	modified:   ../cmake/Buildfind-superquadric.cmake
	modified:   ../cmake/Buildfunny-things.cmake
	modified:   ../cmake/Buildgym-ignition.cmake
	modified:   ../cmake/Buildhimrep.cmake
	modified:   ../cmake/Buildhuman-gazebo.cmake
	modified:   ../cmake/BuildiDynTree.cmake
	modified:   ../cmake/Buildicub-basic-demos.cmake
	modified:   ../cmake/Buildicub-firmware-models.cmake
	modified:   ../cmake/Buildicub-firmware.cmake
	modified:   ../cmake/Buildicub-models.cmake
	modified:   ../cmake/Buildicub-tests.cmake
	modified:   ../cmake/Buildicub_firmware_shared.cmake
	modified:   ../cmake/Buildidyntree-matlab-bindings.cmake
	modified:   ../cmake/Buildidyntree-yarp-tools.cmake
	modified:   ../cmake/Buildiol.cmake
	modified:   ../cmake/Buildmanif.cmake
	modified:   ../cmake/BuildmatioCpp.cmake
	modified:   ../cmake/Buildmatlab-whole-body-simulator.cmake
	modified:   ../cmake/Buildmeshcat-python.cmake
	modified:   ../cmake/Buildmujoco-simulink-blockset.cmake
	modified:   ../cmake/Buildmujoco.cmake
	modified:   ../cmake/Buildnavigation.cmake
	modified:   ../cmake/Buildosqp-matlab.cmake
	modified:   ../cmake/Buildosqp.cmake
	modified:   ../cmake/Buildproxsuite.cmake
	modified:   ../cmake/Buildpyqtconsole.cmake
	modified:   ../cmake/Buildqhull.cmake
	modified:   ../cmake/BuildqpOASES.cmake
	modified:   ../cmake/Buildresolve-robotics-uri-py.cmake
	modified:   ../cmake/BuildrfsmTools.cmake
	modified:   ../cmake/Buildrobometry.cmake
	modified:   ../cmake/Buildrobot-log-visualizer.cmake
	modified:   ../cmake/Buildrobots-configuration.cmake
	modified:   ../cmake/Buildsegmentation.cmake
	modified:   ../cmake/Buildspeech.cmake
	modified:   ../cmake/Buildstereo-vision.cmake
	modified:   ../cmake/Buildtomlplusplus.cmake
	modified:   ../cmake/Buildwalking-controllers.cmake
	modified:   ../cmake/Buildwalking-teleoperation.cmake
	modified:   ../cmake/Buildwearables.cmake
	modified:   ../cmake/Buildwhole-body-controllers.cmake
	modified:   ../cmake/Buildwhole-body-estimators.cmake
	modified:   ../cmake/Buildyarp-device-openxrheadset.cmake
	modified:   ../cmake/Buildyarp-device-xsensmt.cmake
	modified:   ../cmake/Buildyarp-devices-forcetorque.cmake
	modified:   ../cmake/Buildyarp-matlab-bindings.cmake
	modified:   ../cmake/Buildyarp-openvr-trackers.cmake
	modified:   ../cmake/ConfigureFileWithCMakeIf.cmake
	modified:   ../cmake/Fetchonnxruntimebinaries.cmake
	modified:   ../cmake/IncludeUrl.cmake
	modified:   ../cmake/ProjectsTagsStable.cmake
	modified:   ../cmake/ProjectsTagsUnstable.cmake
	modified:   ../cmake/RobSupPurePythonYCMEPHelper.cmake
	modified:   ../cmake/RobotologySuperbuildLogic.cmake
	modified:   ../cmake/RobotologySuperbuildOptions.cmake
	modified:   ../cmake/YCMBootstrapFetch.cmake
	modified:   ../cmake/YCMLoadVcsYamlInfo.cmake
	modified:   ../cmake/template/addPathsToUserEnvVariables.ps1.in
	modified:   ../cmake/template/removePathsFromUserEnvVariables.ps1.in
	modified:   ../cmake/template/setup.bat.in
	modified:   ../cmake/template/setup.sh.in
	modified:   ../cmake/template/startup_robotology_superbuild.m.in
	modified:   ../conda/cmake/CondaGenerationOptions.cmake
	modified:   ../conda/cmake/FindOrBuildPackage.cmake
	modified:   ../conda/cmake/RobotologySuperbuildGenerateCondaRecipes.cmake
	modified:   ../conda/cmake/YCMEPHelper.cmake
	modified:   ../conda/cmake_recipe_template/bld.bat
	modified:   ../conda/cmake_recipe_template/build.sh
	modified:   ../conda/cmake_recipe_template/meta.yaml
	modified:   ../conda/conda_build_config.yml
	modified:   ../conda/metapackages_recipes_template/robotology-distro-all.yaml
	modified:   ../conda/metapackages_recipes_template/robotology-distro.yaml
	modified:   ../conda/multisheller/blockfactory_activate.msh
	modified:   ../conda/multisheller/blockfactory_deactivate.msh
	modified:   ../conda/multisheller/blocktest_activate.msh
	modified:   ../conda/multisheller/blocktest_deactivate.msh
	modified:   ../conda/multisheller/casadi-matlab-bindings_activate.msh
	modified:   ../conda/multisheller/casadi-matlab-bindings_deactivate.msh
	modified:   ../conda/multisheller/ergocub-software_activate.msh
	modified:   ../conda/multisheller/ergocub-software_deactivate.msh
	modified:   ../conda/multisheller/gazebo-yarp-plugins_activate.msh
	modified:   ../conda/multisheller/gazebo-yarp-plugins_deactivate.msh
	modified:   ../conda/multisheller/human-dynamics-estimation_activate.msh
	modified:   ../conda/multisheller/human-dynamics-estimation_deactivate.msh
	modified:   ../conda/multisheller/human-gazebo_activate.msh
	modified:   ../conda/multisheller/human-gazebo_deactivate.msh
	modified:   ../conda/multisheller/icub-contrib-common_activate.msh
	modified:   ../conda/multisheller/icub-contrib-common_deactivate.msh
	modified:   ../conda/multisheller/icub-main_activate.msh
	modified:   ../conda/multisheller/icub-main_deactivate.msh
	modified:   ../conda/multisheller/idyntree-matlab-bindings_activate.msh
	modified:   ../conda/multisheller/idyntree-matlab-bindings_deactivate.msh
	modified:   ../conda/multisheller/matlab-whole-body-simulator_activate.msh
	modified:   ../conda/multisheller/matlab-whole-body-simulator_deactivate.msh
	modified:   ../conda/multisheller/mujoco-simulink-blockset_activate.msh
	modified:   ../conda/multisheller/mujoco-simulink-blockset_deactivate.msh
	modified:   ../conda/multisheller/osqp-matlab_activate.msh
	modified:   ../conda/multisheller/osqp-matlab_deactivate.msh
	modified:   ../conda/multisheller/wb-toolbox_activate.msh
	modified:   ../conda/multisheller/wb-toolbox_deactivate.msh
	modified:   ../conda/multisheller/wearables_activate.msh
	modified:   ../conda/multisheller/wearables_deactivate.msh
	modified:   ../conda/multisheller/whole-body-controllers_activate.msh
	modified:   ../conda/multisheller/whole-body-controllers_deactivate.msh
	modified:   ../conda/multisheller/yarp-matlab-bindings_activate.msh
	modified:   ../conda/multisheller/yarp-matlab-bindings_deactivate.msh
	modified:   ../conda/multisheller/yarp_activate.msh
	modified:   ../conda/multisheller/yarp_deactivate.msh
	modified:   ../conda/pure_python_recipe_template/meta.yaml
	modified:   ../conda/python/generate_conda_recipes_from_metametadata.py
	modified:   ../doc/change-project-tags.md
	modified:   ../doc/cmake-options.md
	modified:   ../doc/conda-forge-overview.md
	modified:   ../doc/conda-forge.md
	modified:   ../doc/conda-powershell-troubleshooting.md
	modified:   ../doc/conda-recipe-generation.md
	modified:   ../doc/deprecated-installation-methods.md
	modified:   ../doc/developers-faqs.md
	modified:   ../doc/environment-variables-configuration.md
	modified:   ../doc/faqs.md
	modified:   ../doc/install-mambaforge.md
	modified:   ../doc/install-miniforge.md
	modified:   ../doc/matlab-one-line-install.md
	modified:   ../doc/unsupported-homebrew-installation.md
	modified:   ../doc/vcpkg-dependencies.md
	modified:   ../doc/wsl2-xserver-configuration.md
	modified:   ../packaging/windows/CMakeLists.txt
	modified:   ../packaging/windows/README.md
	modified:   ../packaging/windows/scripts/addPathsToUserEnvVariables.ps1
	modified:   ../packaging/windows/scripts/removePathsFromUserEnvVariables.ps1
	modified:   ../packaging/windows/scripts/setup.bat
	modified:   ../packaging/windows/scripts/setup.sh
	modified:   ../packaging/windows/scripts/update-env-variables.qs.in
	modified:   ../releases/2020.02.yaml
	modified:   ../releases/2020.05.feat-01.yaml
	modified:   ../releases/2020.05.yaml
	modified:   ../releases/2020.08.feat-01.yaml
	modified:   ../releases/2020.08.patch-01.yaml
	modified:   ../releases/2020.08.yaml
	modified:   ../releases/2020.11.yaml
	modified:   ../releases/2021.02.feat-01.yaml
	modified:   ../releases/2021.02.yaml
	modified:   ../releases/2021.05.yaml
	modified:   ../releases/2021.08.1.yaml
	modified:   ../releases/2021.08.yaml
	modified:   ../releases/2021.11.0.yaml
	modified:   ../releases/2021.11.1.yaml
	modified:   ../releases/2022.02.0.yaml
	modified:   ../releases/2022.02.1.yaml
	modified:   ../releases/2022.02.2.yaml
	modified:   ../releases/2022.05.0.yaml
	modified:   ../releases/2022.05.1.yaml
	modified:   ../releases/2022.05.2.yaml
	modified:   ../releases/2022.08.0.yaml
	modified:   ../releases/2022.08.1.yaml
	modified:   ../releases/2022.09.0.yaml
	modified:   ../releases/2022.09.1.yaml
	modified:   ../releases/2022.11.0.yaml
	modified:   ../releases/2023.02.0.yaml
	modified:   ../releases/2023.02.1.yaml
	modified:   ../releases/2023.02.2.yaml
	modified:   ../releases/2023.02.3.yaml
	modified:   ../releases/2023.05.0.yaml
	modified:   ../releases/2023.05.1.yaml
	modified:   ../releases/2023.05.2.yaml
	modified:   ../releases/2023.08.0.yaml
	modified:   ../releases/2023.11.0.yaml
	modified:   ../releases/latest.releases.yaml
	modified:   ../scripts/install_robotology_packages.m
	modified:   ../scripts/robotologyUpdateLatestReleases.sh

no changes added to commit (use "git add" and/or "git commit -a")```

**Comment by MissingSignal** [comment]
I think i found the error: 
we were not sourcing correctly the .bashrc_iCub file containing 
```export CFW2CANAPI_DIR=${DRIVER_ROOT}/cfw002/```  



I tried to recompile and now i get this error for CAN bus 1,2,3,4:
```[WARNING] Set baud rate not allowed from CanBusAccessPoint implementation
[INFO] using ICUB_CANMASKS_STRICT_FILTER option
[DEBUG] class 0 set
[DEBUG] class 1 set
[DEBUG] class 2 set
[DEBUG] class 3 set
[DEBUG] Can read/write buffers created, buffer size: 500
[INFO] CanBusResources::initialized correctly
[ERROR] recv buffer overrun ( 500 >=  500)
[ERROR] run()-pushReadMsg() failed on CAN bus 1
...
Registering new thread 0 out of 500


```

**Comment by sgiraz** [comment]
Hi @MissingSignal,

See the comment in https://github.com/robotology/icub-tech-support/issues/1674#issuecomment-1970628402

**Comment by sgiraz** [comment]
As of now, `iCubGenova03`:
- runs _debian Buster_ OS 
- use modern [robotology-superbuild v2024.02.00][1] instead of the old **separate** repositories installation
- has the `robotology-superbuild` installed inside the (16GB) USB live stick instead of mounting it from a dedicated desktop/laptop.

After discussing w/ @MissingSignal the pros and cons of having the `robotology-superbuild` installed within the (16GB) USB live stick, We agreed that on `iCubGenova03`, We try to go on w/ this desired configuration (similar to iCubHalfie01).  


Following up the activity reported in https://github.com/robotology/icub-tech-support/issues/1674#issuecomment-1979567657, I will add further support details in the next comments below.

cc @AntonioConsilvio @Fabrizio69 

[1]: https://github.com/robotology/robotology-superbuild/releases/tag/v2024.02.0

**Comment by pattacini** [comment]
Relative PR:
- https://github.com/robotology/robots-configuration/pull/625

**Comment by sgiraz** [comment]
Hi @pattacini,

I re-opened this issue because they probably need further support for this issue.

cc @AntonioConsilvio

**Comment by MissingSignal** [comment]
Dear @sgiraz and @AntonioConsilvio  I think my last [PR](https://github.com/robotology/robots-configuration/pull/625) already solved the "wrong general calibration order of the robot's joints" you mentioned in [#1647](https://github.com/robotology/icub-tech-support/issues/1674#issuecomment-1979567657). 
For this reason I think we can close this issue 👍

Here I attach a video of the new calibration order. 


https://github.com/robotology/icub-tech-support/assets/36140565/eea39066-056d-43b7-8674-efa07ea174b8

**Comment by sgiraz** [comment]
> Dear @sgiraz and @AntonioConsilvio I think my last [PR](https://github.com/robotology/robots-configuration/pull/625) already solved the "wrong general calibration order of the robot's joints" you mentioned in [#1647](https://github.com/robotology/icub-tech-support/issues/1674#issuecomment-1979567657).
> For this reason I think we can close this issue 👍

Hi @MissingSignal,

I didn't catch it this fix! Thank you for your effort! 🙏🏻

Closing then.

cc @AntonioConsilvio
