### ISSUE TITLE
ergoCub 1.1 S/N:000 – Loosen Neck

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1749]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

The neck seems to be loosen

### Detailed context

While the robot was walking, we saw some oscillatory motion of the robot head that were fishy. Visual inspection (see the video below) revealed that the neck is loosen 

### How does it affect you?

https://github.com/robotology/icub-tech-support/assets/5045846/7e9c6f8a-6164-4253-8f09-6e810ab37e35

**Comment by fbiggi** [comment]
the Harmonic Drive screws have been tightened
and re-tensioned the tendons

@Fabrizio69 @maggia80 @AntonioConsilvio @sgiraz

**Comment by Fabrizio69** [comment]
This is ergoCub1.1 S/N:001, I change the title and the OP, so that this issue can be used for the fail/break report
