### ISSUE TITLE
ergoCub 1.1 S/N:001 – Loosen left thumb

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1750]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The left thumb seems loosen.

### Detailed context

While going around the lab I started checking the robot and its hands and I discovered that the left hand thumb is loosen

### Additional context

https://github.com/robotology/icub-tech-support/assets/5045846/12166d8f-2c2d-4e9a-bd08-2d29061ddc6b

**Comment by SimoneMic** [comment]
I think that this should be labeled as ergoCubSN001, isn't it?

**Comment by DanielePucci** [comment]
Yes thanks, once we had also the colors in the robot name that helped avoid these mistakes

**Comment by fbiggi** [comment]
yesterday I adjusted the screw on the engine

**Comment by Fabrizio69** [comment]
...changed the name in the [OP](https://github.com/robotology/icub-tech-support/issues/1750#issue-2135042082) to avoid mistakes

**Comment by sgiraz** [comment]
Thanks @fbiggi! 

We discuss how to prevent these issues internally, if possible..

Closing as solved.

cc @AntonioConsilvio
