### ISSUE TITLE
 ergoCub 1.1 S/N:001 – Left-wrist fails to start or calibrate

### ISSUE THREAD

**Issue by vigisushrutha23** [robotology/icub-tech-support#1752]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Robot Name 🤖

ergoCub 1.0 S/N:001

### Request/Failure description

During an experiment involving bi-manual manipulation and navigation, we had to restart the robot due to `terminator` terminal crashing. When restarting the robot `left_wrist` throws 

```bash
 0.020122 <ERROR> from BOARD 10.0.1.31 (left_arm-eb31-j4_6) time=467s 663m 726u :  SYS: the EOtheInfoDispatcher could not accept a eOmn_info_properties_t item inside its transmitting queue. Number of lost items is  2.
```

Associated log is here 

[failed_comm_left_arm.txt](https://github.com/robotology/icub-tech-support/files/14301435/failed_comm_left_arm.txt)

cc @mebbaid @SimoneMic

### Detailed context

We tried to restart the whole setup (including the robot labtop `ergocub001-lap` and the issue persisted. We also tried running `yarpmotorgui --calib` but then we saw
![Screenshot from 2024-02-15 20-26-44](https://github.com/robotology/icub-tech-support/assets/5215434/c8bb1f43-586c-4b33-9885-53396b8fc70d)

![MicrosoftTeams-image(6)](https://github.com/robotology/icub-tech-support/assets/5215434/feb9e799-93ef-42e8-9a46-604e68b9b911)
![MicrosoftTeams-image(5)](https://github.com/robotology/icub-tech-support/assets/5215434/28018d77-25cf-4fdc-8fd5-32449aa47dec)

### How does it affect you?

This affects https://github.com/ami-iit/lab-events-demos/issues/299

**Comment by ale-git** [comment]
Is there an inversion in the connecting rod?

**Comment by vigisushrutha23** [comment]
I am not sure exactly what you mean so I can't confidently say it. What I can say is that after we home the robot, the left wrist bends inwards to a great extent when compared to the right. We confirmed that the config files were correct so the wrist calibration seemed off before the fault occurred but worked fine for one experiment.

**Comment by lornat75** [comment]
do we need a specific issue to track the process of fixing the wrist or this ticket is enough?

**Comment by vigisushrutha23** [comment]
Closing the issue based on @sgiraz 's comment. Will reopen in case we face the issue again.
