### ISSUE TITLE
ergoCub 1.1 S/N:001 – All the joints friction seems to be increased

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1755]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

Similar to https://github.com/robotology/icub-tech-support/issues/1753 and https://github.com/robotology/icub-tech-support/issues/1754 when unpacking the robot we noticed increased friction 
of some joints.

### Detailed context

In particular we noticed the friction increase of the following joints:
- right shoulder roll;
- both knees;
- right hip roll (with additional noise);

After some movement they seem a bit improved, in particular the shoulders.

**Comment by sgiraz** [comment]
Hi @GiulioRomualdi,

Yep, maybe we have to perform some cleanups!

cc @AntonioConsilvio @fbiggi

**Comment by sgiraz** [comment]
Hi @GiulioRomualdi,

We're going to clean the robot's box.
As of now, is the friction still present on the robot?

**Comment by GiulioRomualdi** [comment]
The robot seems working as expected. Thank you!
