### ISSUE TITLE
ergoCub 1.1 S/N:001 – Arm FTs cables damaged

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1756]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

We noticed that the cables of the FTs in both arms appear damaged. This causes the connection to be flaky and sometimes the ``yarprobotinterface`` does not start because the robot is not able to detect them

### Detailed context

See for example 
![Image](https://github.com/robotology/icub-tech-support/assets/18591940/bc6d8bd9-cd9e-4da7-8741-dc7222fe71b6)

The cable seems to be damaged by the robot's own movement

We noticed this issue while being in Bruxelles for a demo

**Comment by S-Dafarra** [comment]
> By the blue rubber cover I am wondering, is this ergoCubSN001 or the one in Rome?

Thanks for noticing. I made a mistake in selecting the robot from the dropdown menu

**Comment by sgiraz** [comment]
Hi @S-Dafarra,

Do you have any news on this issue? Did the strain2 board disappear anymore?
If everything is ok, I will proceed to close this issue.

cc @AntonioConsilvio @SimoneMic

**Comment by S-Dafarra** [comment]
> Hi @S-Dafarra,
> 
> Do you have any news on this issue? Did the strain2 board disappear anymore? If everything is ok, I will proceed to close this issue.
> 
> cc @AntonioConsilvio @SimoneMic

Hi @sgiraz, I haven't used the robot myself since we got back from the demo, and probably the arm FTs are still disabled at the moment.

**Comment by sgiraz** [comment]
Hi @S-Dafarra,

Did you have the opportunity to use the FTs in the last days?

**Comment by S-Dafarra** [comment]
They should have been enabled back, and we did not have any startup failure related to the FTs. I think we can close this, thanks!
