### ISSUE TITLE
ergoCub 1.1 S/N:001 – Password needed to enter the ergocub-torso and the ergocub-head in ssh

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1762]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

When doing shh on the `ergocub-torso` we need to enter the password.

We see the following message:

```
ergocub@ergocub001-lap:~$ ssh ergocub-torso 
sign_and_send_pubkey: signing failed for RSA "ergocub@ergocub001-lap" from agent: agent refused operation
ergocub@ergocub-torso's password: 

```

```
ergocub@ergocub001-lap:~$ ssh ergocub-head 
sign_and_send_pubkey: signing failed for RSA "ergocub@ergocub001-lap" from agent: agent refused operation
ergocub@ergocub-head's password: 

```

### Detailed context

This is a problem also when doing `yarp run` from `yarpmanager` on the `ergocub-torso`. It asks for the password in the terminal.

cc @AntonioConsilvio @sgiraz @davidelasagna

**Comment by GiulioRomualdi** [comment]
I fixed the issue with https://icub-tech-iit.github.io/documentation/icub_operating_systems/other-machines/icub-server-laptop/?h=ssh#install-the-ssh-keys-for-password-less-login-on-icub-head
