### ISSUE TITLE
ergoCub 1.1 S/N:001 – Neck Tendon Broken

### ISSUE THREAD

**Issue by rob-mau** [robotology/icub-tech-support#1764]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

In today's date, during a test whose purpose was to have the robot track a trajectory provided in 'position direct' mode with open-loop control, damage to the neck tendon occurred. In the initial stages of the movement, the robot lost balance, and likely due to the recoil caused by the inertia of the head, the cable snapped. Unfortunately, I do not have any logs or video recordings of the movement.
 
Here a couple of images of the broken cable:
 ![MicrosoftTeams-image (4)](https://github.com/robotology/icub-tech-support/assets/73101031/f09dd027-73af-479d-8191-7e139fd748d2)
 
 ![MicrosoftTeams-image (5)](https://github.com/robotology/icub-tech-support/assets/73101031/882b5325-35a5-418b-8895-bf093e1221b1)

### Detailed context

The robot was secured to the crane through the yellow safety slings. It doesn't seem that the head has hit the slings.

**Comment by AntonioConsilvio** [comment]
Hi! @fbiggi and I replaced the broken tendon. 

I tested the joint and it works properly now! Closing.
