### ISSUE TITLE
ergoCub 1.1 S/N:001 – Right shoulder roll lcore cable broken

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1765]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

While running an experiment the cable got broken

### Detailed context

![1709741231727227509180439244398](https://github.com/robotology/icub-tech-support/assets/16744101/ef2b809f-8079-4c83-82b6-4a9bfe8e0da7)

### Additional context

@AntonioConsilvio is checking the cable

**Comment by AntonioConsilvio** [comment]
HI @GiulioRomualdi, I fixed the cable of the LCORE5 of the right shoulder roll, and it works properly now!
