### ISSUE TITLE
ergoCub 1.1 S/N:001 – Shoulder pitch not calibrating

### ISSUE THREAD

**Issue by evelyd** [robotology/icub-tech-support#1767]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

We noticed that the right arm was not calibrating correctly, and found that the right shoulder pitch motor kept faulting during the calibration process.

### Detailed context

The right shoulder pitch motor seemed to fault due to too much current, and even after restarting the robot the behavior occurred. It turned out that it wasn't calibrating due to a cable being disconnected.

### Additional context

![Screenshot from 2024-03-08 11-08-30](https://github.com/robotology/icub-tech-support/assets/17877131/02b57441-5470-4ad5-a675-987328d9f3f7)

**Comment by AntonioConsilvio** [comment]
Hi, the broken cable is the RA_E0 that connect the 2FOC 1B0 to the LCORE5 of the right pitch joint. I fixed the cable and it works properly now!
