### ISSUE TITLE
ergoCub 1.1 S/N:001 – Neck joint broken

### ISSUE THREAD

**Issue by evelyd** [robotology/icub-tech-support#1768]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The neck roll joint cable broke.

### Detailed context

During a walking task, the neck suddenly broke. On closer inspection the cable snapped completely. The type of motion didn't require the neck to move very much.

### Additional context

![MicrosoftTeams-image(8)](https://github.com/robotology/icub-tech-support/assets/17877131/5bf168a5-e200-44bf-90b4-553a55faab12)

https://github.com/robotology/icub-tech-support/assets/17877131/5711d1a5-7585-43b6-95c6-79c7a70b5bf7

[robot_logger_device_2024_03_08_13_09_54.md](https://github.com/robotology/icub-tech-support/files/14538048/robot_logger_device_2024_03_08_13_09_54.md)

**Comment by Fabrizio69** [comment]
I think that this tendon was almost broken before the experiment you did...

**Comment by AntonioConsilvio** [comment]
Hi @evelyd, I replaced the broken tendon with e new one and tested the robot, it works as expected! Closing!

cc @sgiraz
