### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Backlash in the right shoulder arm support

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1769]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

There is backlash in the support of the right shoulder joints.

### Detailed context

When the robot arm is rigid (position control) and a person tries to move the shoulder joints, we can see a backlash between the shoulder and its support (in the figure below). This backlash is only on the right shoulder, while on the left shoulder is not present (maybe because of the intervention done in https://github.com/robotology/icub-tech-support/issues/1692)

![MicrosoftTeams-image (1)](https://github.com/robotology/icub-tech-support/assets/12396934/7c65b063-5ac7-4140-9e4b-7e3c0d2b6aa7)

I have tried to screw the accessible screws and the situation improved. I think it might be just a matter of screwing the remaining screws, but they are not accessible. We need to unmount part of the arm to do it, so I open this issue for asking support.

cc @DanielePucci 

### How does it affect you?

It affects iRonCub experiments.

**Comment by gabrielenava** [comment]
thank you @AntonioConsilvio!

**Comment by AntonioConsilvio** [comment]
Closing for this comment:

- https://github.com/robotology/icub-tech-support/issues/1792#issuecomment-2090763510
