### ISSUE TITLE
iCubGenova08 S/N:043 – [Thumb distal broken]

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1771]
### Robot Name 🤖

iCubGenova08 S/N:043

### Request/Failure description

The tendon of the thumb need to be replaced

### Detailed context

-

### Additional context

[yarprunlog_08_03_2024_15_13_55.txt](https://github.com/robotology/icub-tech-support/files/14539159/yarprunlog_08_03_2024_15_13_55.txt)
![MicrosoftTeams-image](https://github.com/robotology/icub-tech-support/assets/3440640/b94fb496-c289-43f8-90fc-e340f508a275)

### How does it affect you?

High impact considering the possibility of delaying data collection in clinical settings.

**Comment by sgiraz** [comment]
Ok @ddetommaso,

As agreed the maintenance activity is scheduled for tomorrow morning on-site (Boggiano Pico).
@AntonioConsilvio and @fbiggi will be in place to fix the thumb

cc @Fabrizio69

**Comment by sgiraz** [comment]
Well done guys! I think we can close this issue!

cc @ddetommaso
