### ISSUE TITLE
ergoCub 1.1 S/N:001 – neck cable broken

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1773]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

After https://github.com/robotology/icub-tech-support/issues/1768 @AntonioConsilvio fixed the neck we performed some walking experiment and the neck got broken again 

### Detailed context

See the picture of the neck cable
![20240308_155742.jpg](https://github.com/robotology/icub-tech-support/assets/16744101/7cef5faa-c646-4323-aab6-f259f82439ba)

### Additional context

I add the video of the robot while walking 

https://github.com/robotology/icub-tech-support/assets/16744101/6e11edb0-2556-46ec-a58e-7d37cad17c9c

**Comment by pattacini** [comment]
Hi @GiulioRomualdi 

Better off reducing the safety threshold you've been employing for the position-direct control of the neck, passing from 8 deg to let's say 4 deg. 

We could also look at the reference trajectories sent to the neck to verify if this threshold has ever played its role.

**Comment by GiulioRomualdi** [comment]
Hi @pattacini, to better understand what happened on the robot, I decided to plot the joint tracking, current, and PWM on the neck. Here are some plots:



## neck pitch
The following plot shows the neck pitch. The blue line represents the desired quantity we set as a position directive, while the orange one depicts the measured joint position. At t = 38s, the robot starts walking. Despite the required joint position being almost constant, the error increases.

The neck broke at t = 47.29s without any abrupt change in the reference.

![image](https://github.com/robotology/icub-tech-support/assets/16744101/26eb401e-fa48-478a-bc04-167d94ae5be6)

## neck roll

This plot is similar to the neck pitch.


![image](https://github.com/robotology/icub-tech-support/assets/16744101/08ec15dd-76b9-4f45-bf60-e493ea7d256c)


## neck yaw 

Unlike the neck pitch and roll, the tracking of the yaw is better.


![image](https://github.com/robotology/icub-tech-support/assets/16744101/faa77901-17b2-4d5e-bdd2-a27445ca3da6)

## PWM

![image](https://github.com/robotology/icub-tech-support/assets/16744101/cb0a3886-10a5-427f-8410-8f49972c1041)

## Currents

When the neck broke, there was a spike in the current. We may consider limiting the maximum amount of current that the joint can deliver. In this case, the tracking will worsen, but at least we can preserve the joint.


![image](https://github.com/robotology/icub-tech-support/assets/16744101/eb169f3c-e127-46f8-9493-c767f2710842)


cc @DanielePucci

**Comment by pattacini** [comment]
Nice reporting @GiulioRomualdi 👍🏻 

The errors on the pitch and the roll are higher because the mechanism is significantly different from the yaw, although they are in the range of 1.7 deg, at first sight, and probably mainly due to the vibrations due to the walking. Just speculating.

Your reference inputs seem ok: no big jumps 👍🏻 

True that there's a spike in the current of the roll, but there's also a command voltage rising up to > 75% for the same joint and then falling to -100%, whereas the pitch remains kind of more limited.

It'd be interesting to have a look at that, cc @sgiraz.

> We may consider limiting the maximum amount of current that the joint can deliver. In this case, the tracking will worsen, but at least we can preserve the joint.

It could be a viable workaround.

cc @maggia80

**Comment by pattacini** [comment]
A couple of comments more.

> [!important]
MC4Plus doesn't provide current control meaning that the safety action that we can undertake here is to limit the PWM output and not to fiddle with the current limits.

>It'd be interesting to have a look at that to verify if those spikes are a mere consequence of the breakage cc @sgiraz.

The spike in the current could stem from the fact that the tendon broke up on the part of the coupled mechanism that is controlled by one specific motor only, say M0 (or M1), but the other motor M1 (or M0) still sees the opposite part of the mechanism engaged and thus is asked to deliver high current because of the high error.

To verify this hypothesis, @sgiraz, we could check whether the motor that underwent the spike in current is the one corresponding to the part of the mechanism opposite to the broken tendon.

Don't know if I've been clear enough 😄

**Comment by sgiraz** [comment]
@fbiggi and @AntonioConsilvio are going to perform tendon replacement tomorrow morning. 

>[!Important]
>Before removing the broken tendon they will identify its location.

cc @pattacini

**Comment by fbiggi** [comment]
the broken tendon and the "A"


![image](https://github.com/robotology/icub-tech-support/assets/20420331/0b4ffd32-40f3-4b0f-84bf-8148c8d63093)


@Fabrizio69 @sgiraz @pattacini

**Comment by pattacini** [comment]
Thanks @fbiggi 👍🏻 
We will use this info to proceed further with the investigation.

**Comment by fbiggi** [comment]
![Cattura](https://github.com/robotology/icub-tech-support/assets/20420331/a149e14e-5eca-4481-a70a-11c57885f95c)
![20240313_121350](https://github.com/robotology/icub-tech-support/assets/20420331/5c294d59-b94f-4ec9-a0bd-3cdc11884f00)
![20240313_121340](https://github.com/robotology/icub-tech-support/assets/20420331/94c79113-ad5d-4dd4-8290-a64f2b1ee8ea)
![20240313_075608(0)](https://github.com/robotology/icub-tech-support/assets/20420331/0d5f9220-0905-498d-8a04-128ccfc22517)

![Cattura](https://github.com/robotology/icub-tech-support/assets/20420331/3d9a918e-e1bc-40fc-9f02-f12369b90301)

**Comment by pattacini** [comment]
I aimed to recreate this condition with our [Digital Twin](https://github.com/icub-tech-iit/ergocub-design-head) (DT).

### 🔲 Partial results

![image](https://github.com/robotology/icub-tech-support/assets/3738070/98630228-44b8-4a13-a605-4d37424ac4fa)

https://github.com/robotology/icub-tech-support/assets/3738070/c36484ab-2496-4043-a18c-928e6dd602df

At `t = 2 s` I simulated a fault by disconnecting the torque delivered to the revolute joint `motor_revolute0` in the RC_IIT_10_A_004 subsystem. Essentially, I wasn't able to manipulate the tendons directly, so I tried to stop delivering the torque of M0.

#### 🔳 Naming convention of motors M0 and M1 in the DT:

| M0 | M1 |
| :---: | :---: |
| <img width="251" alt="M0" src="https://github.com/robotology/icub-tech-support/assets/3738070/7e1032eb-e5e3-43a4-88c8-e93c38679e08"> | <img width="269" alt="M1" src="https://github.com/robotology/icub-tech-support/assets/3738070/1507f4da-57c7-4d45-9cc2-d77c3254bc34"> |

The profiles of pitch and roll rise up as in the logs posted from the real system.
Obviously, the voltage V0 and the current I0 undergo most of the big changes whereas V1 and I1 stay reasonable.

A few points to inspect.

### 🔲 The Motor

>The broken tendon is the one driven by the motor placed in the bottom-rear of the neck.

This should M1 instead, according to the DT naming convention, correct? @sgiraz @fbiggi 

### 🔲 The Tendons
In the real system, we have [2 tendons](https://icub-tech-iit.github.io/documentation/icub_tendons/neck/#1-mechanical-assembly-of-the-2-tendons): A and B.

This is the tendon circuit in the DT:

![image](https://github.com/robotology/icub-tech-support/assets/3738070/433dfb58-1d0d-4831-a0d9-f824bb2852f8)

I've never really gone into these fine details, I might be wrong, but it looks we have one single tendon circuit.

Perhaps, @mfussi66 and/or @salvi-mattia can add some comments here.

### 🔲 The electrical quantities (V and I)
- For the DT, we have the voltage and the current of the motors
- In the logs from the real system, voltages and currents are maybe remapped to the pitch and roll joints, somehow?

We'd need to check if these quantities are actually remapped or, instead, copied out to the joints in their order while retaining their meaning for the motor order.

cc @Nicogene

**Comment by mfussi66** [comment]
> Perhaps, @mfussi66 and/or @salvi-mattia can add some comments here.

The one-loop solution was the most simple to implement with the best results. 
Alternatively, one could actually mimick the real mechanism by using two cables, attached to the ends by [anchors](https://it.mathworks.com/help/sm/ref/beltcableend.html). At the time, I had problems understanding where to attach those ends. Ideally, they should be connected to the "grains" components, but I had no idea how to make the cable do those weird twists and turns.

**Comment by pattacini** [comment]
>The one-loop solution was the most simple to implement with the best results at the time.

Clear 👍🏻

**Comment by sgiraz** [comment]
Hi @pattacini,

After consulting @ale-git, we can confirm that from the firmware side, the Voltage and Current parameters are forwarded to the `yarprobotinterface` via UDP without doing any king of coupling.
Just for reference I drop a code snipped below:

![image](https://github.com/robotology/icub-tech-support/assets/18039045/6f90f047-f1e2-4598-988a-078eb649a65c)

If these electrical values are not manipulated (coupled) by `yarp` and/or `icub-main` the resulting pitch, roll and yaw have to be considered (logically mapped) as M0, M1 and M2.

>[!Note]
>As discussed F2F we have to consider that, in a coupled system, when a motor lose the connection w/ the transmission the other motor needs to compensate the load increasing the current absorbed.

**Comment by pattacini** [comment]
Hi @GiulioRomualdi 

By any chance, do you have the whole log tho share here?
Something like the archives you store on Hugging Face?

**Comment by pattacini** [comment]
> By any chance, do you have the whole log to share here?
> Something like the archives you store on Hugging Face?

@GiulioRomualdi handed me the data.

**Comment by pattacini** [comment]
>>From the https://github.com/robotology/icub-tech-support/issues/1773#issuecomment-1988494371, it's not clear what happens to the position references after the fault though.

The log doesn't contain data on the commanded position setpoints.

>do you have the logs of the motor positions (not just the joint positions)?

Pitch and roll motor positions are not retrieved correctly, apparently. We do have just the motor position of the yaw joint.

![image](https://github.com/robotology/icub-tech-support/assets/3738070/a32fd155-7008-4209-b436-95d6af727d57)

**Comment by pattacini** [comment]
In #1781, the neck cable broke up mostly in the same way as reported here: after a short while, when lifting the left foot.

**Comment by AntonioConsilvio** [comment]
> In #1781, the neck cable broke up mostly in the same way as reported here: after a short while, when lifting the left foot.

In addition to always breaking during the same movement (when the lifting of the left foot), we are still verifying the tendon breaking point, which is always the same, about 2.8cm (these are two different tendons):

![cavo A](https://github.com/robotology/icub-tech-support/assets/114915464/79dcefc1-356e-47c5-992b-3ccc2eec3a94)

![CAVO A 1](https://github.com/robotology/icub-tech-support/assets/114915464/003f147c-6e46-425f-a011-038283f93026)



For now, we have only been able to verify the breaking point of tendon "[A](https://icub-tech-iit.github.io/documentation/icub_tendons/neck/#23-route-cable-a)''.

cc @Fabrizio69 @pattacini @GiulioRomualdi

**Comment by pattacini** [comment]
Seems a quite important piece of information that we can use to double-check the components at stake in the CAD.

**Comment by pattacini** [comment]
@fbiggi reported that this is the zone where tendon A breaks:

![image](https://github.com/robotology/icub-tech-support/assets/3738070/d4dbcab6-c1d0-4e81-9747-caacd76978cb)

The tendon breaks at 28 mm.

cc @LawProto

**Comment by salvi-mattia** [comment]
if we suppose the tensioner to be in the middle of its range.
28mm along the cable should be as shown in picture
wich appears not to be any parcticular place.
do we know where was the tensioner approximately placed?

![immagine](https://github.com/robotology/icub-tech-support/assets/43994292/81886b26-4b9a-4883-a269-708799ffed0d)

**Comment by Lawproto** [comment]
Thinking-out-loud considerations aside, my report is very similar to @salvi-mattia's.

https://github.com/icub-tech-iit/proto/issues/2788#issuecomment-2017589596

**Comment by pattacini** [comment]
The geometry with which the cable at the length 2.8 cm interacts may vary during operations because of the movements of the pulleys.

Therefore, @salvi-mattia and I were thinking of making a sign on the cable already mounted and then visually inspecting the parts the tendon will "interact" with while moving the neck.

**Comment by S-Dafarra** [comment]
Other related ticket: https://github.com/robotology/icub-tech-support/issues/1783 (not when walking, but it was shaking)

**Comment by pattacini** [comment]
We decided to proceed as follows: 
1  Replace the two tendons with those with a slightly larger diameter of 0.9 mm.
2. Inspect the physical mechanism to verify that the distances stated in the CAD among the various pulleys are respected.
3. Make a sign on the tendon A at the correct distance of 28 mm.
4. Carry out tests. In details:
    - Let the neck move via robotmotorgui and verify the interaction of the marked point with the mechanics.
    - Apply vibrations to the neck (manually or semi-automatically) and record a movie with the high frame rate camera to spot possible critical issues.

**Comment by pattacini** [comment]
The new tendon prototypes seem to be working more robustly, being also less flexible.

While the pitch bends frontward, the length of the tendon marked with the sign (where it broke 3 times in a row) gets very close to the point where the tendon itself leaves the first pulley to engage the second pulley.

The frontal pulley was also kind of worn out on the border. We repolished it with sandpaper.

**Comment by pattacini** [comment]
Hi @AntonioConsilvio @S-Dafarra 

Probably, we can close this long-standing issue.
If we'll have further problems, we can refer to a brand-new ticket, possibly citing this.

**Comment by AntonioConsilvio** [comment]
Great @pattacini!

Thank you all for the support and feedback, hopefully the new tendons will bring an improvement!
