### ISSUE TITLE
ergoCub 1.1 S/N:001 – Left shoulder roll AMO cable broken

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1777]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The cable of the left shoulder roll AMO got disconnected.

### Detailed context

During experiments with @carloscp3009 and @isorrentino, we saw that the left shoulder roll increased without reasons - the robot was standing without doing much, just moving a little the arms. Then, I touched the cable of the AMO shoulder roll, left, and actually the joint started moving.

⚠️ That cable did not have glue, differently from the right one @sgiraz @AntonioConsilvio 

### Additional context

https://github.com/robotology/icub-tech-support/assets/5045846/8febee6b-e831-45cd-b9ae-e43fd428e190

**Comment by AntonioConsilvio** [comment]
Hi @DanielePucci, I fixed the cable! 

Please, give us a feedback when you will use the robot. Thank you!

cc @isorrentino @carloscp3009

**Comment by DanielePucci** [comment]
I do not know if we are still using the LCORE on the robot. I leave the space to @GiulioRomualdi  for a feedback on this

**Comment by GiulioRomualdi** [comment]
We use the amo

**Comment by AntonioConsilvio** [comment]
As you are using the AMO and the robot is working properly, I will proceed with closing the issue! Thank you! 🚀
