### ISSUE TITLE
iCubGenova08 S/N:043 – Right thumb distal broken

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1780]
### Robot Name 🤖

iCubGenova08 S/N:043

### Request/Failure description

During the robot calibration the right hand does not calibrate properly and it gets stuck. 

### Detailed context

Today starting the robot the issue appears even if I didn't notice any breakage in the joint in the previous sessions.

https://github.com/robotology/icub-tech-support/assets/3440640/a7604449-b0e6-4715-b5d3-a3dc6953c85f

### Additional context

![Screenshot from 2024-03-21 13-17-42](https://github.com/robotology/icub-tech-support/assets/3440640/f4f5c5c5-5f06-41de-95ad-fe8cb7abcf1e)

### How does it affect you?

The impact is severe because we need to start testing in about a week.

**Comment by AntonioConsilvio** [comment]
Hi @ddetommaso, @fbiggi and I replaced the broken tendon with a new one. We also replaced the sheath, because it was broken. The robot has been tested and it works properly now! 🚀

https://github.com/robotology/icub-tech-support/assets/114915464/7f3d6810-43f8-42c3-8cdf-9c6ec5b348b1

cc @Fabrizio69
