### ISSUE TITLE
iCubTokyo01 S/N:022 – missing screws on new face - servo motor

### ISSUE THREAD

**Issue by julijenv** [robotology/icub-tech-support#1782]
### Robot Name 🤖

iCubTokyo01 S/N:022

### Request/Failure description

On our freshly received new face, the rotating arm attached to the servo motor is detached. Apparently the screw is missing.

### Detailed context

After some time operating, the blinking starts to do not behave as intended. I could hear the servo spinning but not the eyelids moving. After unmounting I discover the problem,
Will it be possible to get the missing screw?
I also noticed that the screws mounting on the servo motor and branches activating the eyelid are hexagonal, from what I recall, they should be crossed.
can I get all the information for those screws in order to buy them if you cant provide them to me.
I would also be happy to receive information on how to recalibrate the eyelid when I will be remounting everything.
let me know,
best

### Additional context

![WhatsApp Image 2024-03-25 at 13 21 28_5caa9c5d](https://github.com/robotology/icub-tech-support/assets/7140395/e6b6774e-6743-4a91-82b0-bc1a72be5ecb)
![WhatsApp Image 2024-03-25 at 13 21 28_26278558](https://github.com/robotology/icub-tech-support/assets/7140395/01887ae4-c3a1-433e-9bef-e5e5ad413f87)

### How does it affect you?

I reattached the old head meanwhile as we are currently showcasing the robot.

**Comment by AntonioConsilvio** [comment]
Hi @julijenv, the screw that holds the leverage mechanism to the motor shaft has unscrewed. The screw is a cross screw M1.6x4.

The other 'hexagonal' screws are Torx screws, in case you have the torx screwdrivers you can disassemble and reassemble them without any problems, or replace them with cross screws if you prefer. (Actually, you should be able to unscrew torx screws even with a cross screwdriver in case you don't have the torx screwdriver).

However, the missing screw has the parameters mentioned above: cross M1.6x4.

![Vite-cover](https://github.com/robotology/icub-tech-support/assets/114915464/52f7bc22-1c0b-4d5c-84d4-60ab13de4de2)

**Comment by julijenv** [comment]
Hi @AntonioConsilvio ,
can you tell me if the thread distance is American or European, from what I recall it is an American screw, can you take a picture of the normal M1.6x4 next to that black screw or confirm they are the same.
thanks in advance

**Comment by AntonioConsilvio** [comment]
Hi @julijenv, You may be right, the thread should be American. 
However, we tried fitting an M1.6x4 metric instead of the official black screw on a servomotor, and it fit without any problems!

![IMG_20240328_102600](https://github.com/robotology/icub-tech-support/assets/114915464/1442a901-1e7c-42df-8047-69dce9a43b21)

So in case you are only equipped with metric screws, you can try using those. 
But yes, the official screw should have the American thread.

**Comment by julijenv** [comment]
Dear @AntonioConsilvio ,
I succeeded in reput back in place everything, thanks for the overall details,
best,
Julien
