### ISSUE TITLE
ergoCub 1.1 S/N:001 – Left shoulder roll hardware limit bent

### ISSUE THREAD

**Issue by G-Cervettini** [robotology/icub-tech-support#1788]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The left arm calibration is slightly compromised by a bent pin acting as HW limit.

### Detailed context

The fact itself that the pin is bent might suggest that a slightly bigger diameter pin could be a better solution.

### Additional context

![MicrosoftTeams-image](https://github.com/robotology/icub-tech-support/assets/101020439/1ba0f4b4-5a10-4186-8c1f-cd760d71a733)

### How does it affect you?

Left arm calibration quality is reduced.

**Comment by AntonioConsilvio** [comment]
Hi @G-Cervettini! @fbiggi and @Gandoo replaced the damaged hardware limit with a new one. The robot has been tested and it works properly now! Closing!
