### ISSUE TITLE
ergoCub 1.1 S/N:001 – Right leg ankle roll hardware fault due to overheating at startup

### ISSUE THREAD

**Issue by SimoneMic** [robotology/icub-tech-support#1790]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

`r_ankle_roll` goes into HW fault for overheating when launching the yarprobotinterface.
I have tried turning on and off the motors and restarting it four times, but the error occurred nonetheless.
I am attaching the pictures below in detailed context.

### Detailed context

`robots-configurations` branch is in devel.
The usual error that occurs is: 
```
[ERROR] from BOARD 10.0.1.7 (right_leg-eb7-j4_5) time=283s 433m 172u :  src LOCAL, adr 0,(code 0x02000012, par16 0x0001 par64 0xfffffffffffffc8a) -> MC: overheating. Temperature hardware limit exceeded. The motor has been turned off to prevent it from being damaged by overheating. In par16 = ID of the joint. In par64 0xFFFF is the mask of the raw tmperature feedback. .
```
I attach also the full log
[overheating_error.txt](https://github.com/robotology/icub-tech-support/files/14853973/overheating_error.txt)
![Screenshot from 2024-04-03 16-19-49](https://github.com/robotology/icub-tech-support/assets/86918431/54dc45ed-97da-4c49-a45e-aa6168bb0f26)

Robot fotos in additional context

### Additional context

![20240403_161335](https://github.com/robotology/icub-tech-support/assets/86918431/4a16786a-b08d-4acb-ad6e-f72983ec1caa)
![20240403_162717](https://github.com/robotology/icub-tech-support/assets/86918431/1c5ce7c6-254d-4258-a38e-111109b67a42)
![20240403_162722](https://github.com/robotology/icub-tech-support/assets/86918431/f1d2b7ec-137f-45b6-928b-216d64425c77)

**Comment by GiulioRomualdi** [comment]
cc @MSECode and @valegagge

**Comment by valegagge** [comment]
Hi @SimoneMic,
did the error occur after or during the calibration?
Thanks

**Comment by SimoneMic** [comment]
During the calibration

**Comment by AntonioConsilvio** [comment]
Hi! This problem was due a damaged cable that connect the TDB sensor to the 2FOC board. We fixed the cable and it works properly now!
