### ISSUE TITLE
iCubGenova08 S/N:043 – [Right thumb distal broken]

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1794]
### Robot Name 🤖

iCubGenova08 S/N:043

### Request/Failure description

During the robot calibration the right hand does not calibrate properly and it gets stuck.

### Detailed context

The issue appears without having noticed any critical problem in the previous sessions. It's important to mention that the problem seems recurring. 

### Additional context

![image](https://github.com/robotology/icub-tech-support/assets/3440640/b7ba86f8-3c5b-4391-9a5e-4b05ac493b93)

https://github.com/robotology/icub-tech-support/assets/3440640/dd0929d0-0061-4845-b69c-0bcd5f625cf1

### How does it affect you?

The impact is severe because we need to start testing soon.

**Comment by ddetommaso** [comment]
Please let us know a possible date of the intervention, possibly no later than the 10th of May.
cc @lornat75

**Comment by AntonioConsilvio** [comment]
Hi @ddetommaso, @AntonioAzocar and I replaced the broken tendon in 9th May. We tested the robot and it works properly now!

https://github.com/robotology/icub-tech-support/assets/114915464/5e1ff1af-60ae-47ce-a164-eb33d3f65912

Closing!
