### ISSUE TITLE
R1 S/N:003 – R1 skirt is stuck

### ISSUE THREAD

**Issue by mga-97** [robotology/icub-tech-support#1795]
### Robot Name 🤖

R1 S/N:003

### Request/Failure description

R1 skirt, which is attached to the robot torso through a set of three elastic bands, does not come up smoothly when the torso elongates. Sometimes the skirt gets stuck in the lower position and obstructs the lidar view.

### Detailed context

- the elastic bands need to be replaced
- (optional) the rails needs some lubricant

**Comment by AntonioConsilvio** [comment]
cc @fbiggi

**Comment by fbiggi** [comment]
the three elastics have been replaced
tested the movement with @elandini84 

![20240520_102505](https://github.com/robotology/icub-tech-support/assets/20420331/22a5c8a5-6cb3-48e8-89f3-45cdc4426a94)
![20240520_102514](https://github.com/robotology/icub-tech-support/assets/20420331/28894228-4bca-44e0-8c1a-495d6d2f8d91)

**Comment by AntonioConsilvio** [comment]
Since the robot test was successfully completed, I proceed to closing the issue.

Well done @fbiggi! 🚀

cc @mga-97 @elandini84
