### ISSUE TITLE
R1 S/N:003 – the wheels of R1 shipment box (trolley) need to be replaced

### ISSUE THREAD

**Issue by mga-97** [robotology/icub-tech-support#1796]
### Robot Name 🤖

R1 S/N:003

### Request/Failure description

The transportation of R1 box is difficult.

### Detailed context

At least one wheel of the cart is broken and needs to be replaced.

**Comment by fbiggi** [comment]
@AntonioConsilvio I send the R1 cart restoration problem

https://github.com/icub-tech-iit/proto/issues/2854

**Comment by AntonioConsilvio** [comment]
Well done @fbiggi @Gandoo! 🚀 Closing!
