### ISSUE TITLE
R1 S/N:003 – Wireless fault not working properly

### ISSUE THREAD

**Issue by elandini84** [robotology/icub-tech-support#1800]
### Robot Name 🤖

R1 S/N:003

### Request/Failure description

The wireless external fault button does not work. If the receiver board is connected, the robot is always in a fault state

### Detailed context

The robot cannot work with the external fault button connected to the robot. Yarprobotinterface log shows for all the joints the "External fault button pressed" error message even if the wireless button is not pressed.

### How does it affect you?

This situation does not allow us to use the external fault which is a valuable tool for our tests in Turin next week.

**Comment by valegagge** [comment]
Hi @AntonioConsilvio,
 me and @andresoll we are aligned on this issue. Please contact us when you start working on it.

cc @Fabrizio69

**Comment by AntonioAzocar** [comment]
Hi!
This morning, I and @andresoll  did the work on the robot and on disassembling the wiring we found this connector slightly detached from the fault board and that is why the fault was giving problems.
In fact, once it was reconnected properly, it no longer gave any problems and to prevent it from coming loose again I put a drop of glue on it.
Maybe Andrea will give more information

![connettore fault R1](https://github.com/robotology/icub-tech-support/assets/130973726/f5f0d0c2-892e-4522-bbc8-9b57c160e018)

cc @Fabrizio69 @valegagge

**Comment by andresoll** [comment]
thank you @AntonioAzocar, I asked @ste93  to prove that everything is working properly. This morning I will go to the robot arena to verify that everything is working. 

cc @valegagge

**Comment by AntonioConsilvio** [comment]
Hi guys! Any feedback on this issue?

cc @AntonioAzocar @andresoll @ste93
