### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Chest IMU cable connector broke

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1801]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

The chest IMU cable got pulled right before the connector, and the IMU does not start anymore.

### Detailed context

We tried with the external cable and the IMU starts. So I think it is something similar to what happened in https://github.com/robotology/icub-tech-support/issues/1689.

cc @DanielePucci 

### How does it affect you?

It blocks iRonCub experiments.

**Comment by Gandoo** [comment]
![db66a23e-7f88-4715-a1ad-eb440f55f1b3](https://github.com/robotology/icub-tech-support/assets/53341641/f79c8191-f08e-4b9c-afba-f9e58beb0bc8)

![5a4c72a7-a9a6-4fc4-94af-053b05fbd1b3](https://github.com/robotology/icub-tech-support/assets/53341641/61539a49-22a3-46de-8627-732d86713029)

**Comment by Gandoo** [comment]
![1ef5268a-ab61-46b4-ab5e-db0778a34bf3](https://github.com/robotology/icub-tech-support/assets/53341641/90bac47a-9c31-415b-a332-35f0b4f5d68b)

**Comment by AntonioConsilvio** [comment]
Hi @gabrielenava! @Gandoo fixed the broken cable. The IMU has been tested and works properly now! 

> [!Note]
> We found the cables coiled inside the connector, they may have been coiled because it may look like the connector has to be inserted inside the IMU with a rotation. Actually, it should only be inserted (pushed in), so be careful not to rotate the connector as this could cause the cables to break inside!

Closing!

**Comment by gabrielenava** [comment]
thank you, I'll notify everyone not to rotate the connector, and hopefully this problem should not happen again!
