### ISSUE TITLE
ergoCub 1.1 S/N:002 – All torso joints in HF with generic motor error

### ISSUE THREAD

**Issue by carloscp3009** [robotology/icub-tech-support#1804]
### Robot Name 🤖

ergoCub 1.1 S/N:002

### Request/Failure description

We were conducting some test on the robot that implies walking with a payload (Empty box) after a minute the robot went in Generic Motor Error in all torso joints.

https://github.com/robotology/icub-tech-support/assets/44415073/90d65b76-1e63-4b27-b375-9ce5bbf18277

### Detailed context

Here an screenshot from the motor GUI

![image](https://github.com/robotology/icub-tech-support/assets/44415073/fa4ad6a1-5d3e-4c20-9a90-4921cacbc4ab)

This time the motor currents and PWM for the torso seem to be streamed correctly.
![image](https://github.com/robotology/icub-tech-support/assets/44415073/b3bb7ad0-ec15-487b-9bc9-50867aedb39c)

### Additional context

Here the mat file containing the logging data:
[robot_logger_device_2024_05_08_11_47_17.zip](https://github.com/robotology/icub-tech-support/files/15247224/robot_logger_device_2024_05_08_11_47_17.zip)

And here the yarprobtinterface: 
[interface_generic_motor_error.txt](https://github.com/robotology/icub-tech-support/files/15247038/interface_generic_motor_error.txt)

### How does it affect you?

We have some demos the next week and a video shooting, without crane, tomorrow

cc @GiulioRomualdi @DanielePucci @S-Dafarra

**Comment by valegagge** [comment]
Hi @carloscp3009 ,
from the log you attached it seems there are some CAN bus errors.

![image](https://github.com/robotology/icub-tech-support/assets/4233231/a1ab3222-3b42-4bd8-a2af-25240e6dc2ed)


In addition, I noticed that there was a calibration fault on joint 4 of the right leg.
The calibration file you used is the one that is on the devel branch of the robotology?

cc @AntonioConsilvio

**Comment by AntonioConsilvio** [comment]
Hi!

Thanks for the suggestion @valegagge.

You are right, in fact the problem was caused by the CAN termination resistor not making good connection.

@AntonioAzocar and I fixed this problem, the robot works properly now!

Thank you!

cc @carloscp3009
