### ISSUE TITLE
ergoCub 1.1 S/N:002 – Robot Neck Tendon broken

### ISSUE THREAD

**Issue by SimoneMic** [robotology/icub-tech-support#1806]
### Robot Name 🤖

ergoCub 1.1 S/N:002

### Request/Failure description

While walking during experiments the robot lost balance and while falling the neck tendon broke.

### Detailed context

See attached video:

https://github.com/robotology/icub-tech-support/assets/86918431/bb8b84ee-92ec-4781-9a1e-62e20f535382

**Comment by AntonioConsilvio** [comment]
HI @SimoneMic, @AntonioAzocar and I replaced the tendon and tested the robot, the robot works properly now!
