### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Broken wire on the jetpack electronics

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1807]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

A cable in the jetpack electronics is broken. It is the cable that connects the turbine to the fault button, so the turbine does not start.

I brought the electronics downstairs, would it be possible to fix it tomorrow morning?

cc @DanielePucci 

### Detailed context

It is the cable in the picture:

![MicrosoftTeams-image](https://github.com/robotology/icub-tech-support/assets/12396934/754e41a2-5315-43e5-9c3e-1ba8aafdab03)

### How does it affect you?

It blocks iRonCub experiments

**Comment by Fabrizio69** [comment]
Hi @gabrielenava , I'm looking for electronics to understand the problem. Where can I find it?

**Comment by Gandoo** [comment]
ciao @gabrielenava il filo di Fault che era staccato è stato ripristinato.

![3d0d474a-a2de-450e-9951-be4a437606b8](https://github.com/robotology/icub-tech-support/assets/53341641/1700cd30-7973-46ae-a35c-4b13e7fde0e9)

![9cc25761-32ef-43cc-8cc3-8a56493a74a2](https://github.com/robotology/icub-tech-support/assets/53341641/16e9d8f0-05c1-4510-8e92-83f743bb7062)

cc @Fabrizio69 @AntonioConsilvio @DanielePucci

**Comment by gabrielenava** [comment]
thank you @Gandoo!

we tested with a spool test and the turbine pump started this time, so the electronics should be fixed! we'll further verify this afternoon by turning on the turbines, but to me we can already close the issue!
