### ISSUE TITLE
ergoCub 1.1 S/N:001 – Right wrist slightly bent

### ISSUE THREAD

**Issue by SimoneMic** [robotology/icub-tech-support#1823]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

In home position both wrists should be in the same position, if not perfectly symmethrical, at least more or less aligned.
Instead, the right wrist start slightly bent outwards. When on the yarpmotorgui all the joints references are in the same zero position.

### Detailed context

As you can see from the pictures both wrists should be in the same orientation, this means that there could be a wrong encoder reading, or an issue in the zeroing/calibration procedure.

![Selected photo (7)](https://github.com/robotology/icub-tech-support/assets/86918431/fdebc5da-6498-43ac-9f34-b13632a9ccc6)

![Screenshot from 2024-06-06 11-16-30](https://github.com/robotology/icub-tech-support/assets/86918431/d33dec3c-3d2a-4800-93a9-2a60d7ec8ac7)

![Screenshot from 2024-06-06 11-17-17](https://github.com/robotology/icub-tech-support/assets/86918431/7023ba86-b70d-4793-a320-4d5d0ddc4448)

**Comment by AntonioConsilvio** [comment]
Hi @SimoneMic, the belt of one of the wrist motors broke.

![IMG_20240610_091924](https://github.com/robotology/icub-tech-support/assets/114915464/042efac9-dd30-4d3f-8e45-1c1343724a64)


We removed the lowerarm from the robot and we already started with the replacement.

cc @maggia80 @S-Dafarra @fbiggi

**Comment by AntonioConsilvio** [comment]
Hi @SimoneMic, @fbiggi and @AntonioAzocar replaced the broken belt successfully. I calibrated the wrist with new values and tested the joints, It works properly now!

Here the PR with the new calibration values:

- https://github.com/robotology/robots-configuration/pull/655

Thank you everyone for the help! 🚀

cc @S-Dafarra
