### ISSUE TITLE
ergoCub 1.1 S/N:001 – Neck lossened

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#1825]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

It seems that the neck of the robot is loosen 

### Detailed context

While walking, the robot shaked a little and then we relised that the neck was loosened 

https://github.com/robotology/icub-tech-support/assets/5045846/669cb71e-94b4-496b-a678-3db6deea130e

**Comment by AntonioConsilvio** [comment]
Hi @DanielePucci, me and @Gandoo tightened the tendons and the situation improved. The robot has successfully performed the last few demos so I am going ahead with closing the issue!
