### ISSUE TITLE
iCubGenova11 S/N:050 – Left Thumb Proximal Tendon Broken

### ISSUE THREAD

**Issue by fedeceola** [robotology/icub-tech-support#1829]
### Robot Name 🤖

iCubGenova11 S/N:050

### Request/Failure description

As per title the proximal tendon of the left thumb is broken.

### Detailed context

As per title the proximal tendon of the left thumb is broken.

**Comment by AntonioConsilvio** [comment]
Hi! I replaced the broken tendon and tested the robot. It works properly now! 🚀

Closing! ✅
