### ISSUE TITLE
ergoCub 1.1 S/N:001 – Neck tendons broken

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1832]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The neck tendons broke caused by a wrong starting calibration of the left shoulder roll.

### Detailed context

Log of the yarprobotinterface

[log_ergocub-torso_yarprobotinterface_7194.txt](https://github.com/user-attachments/files/15909957/log_ergocub-torso_yarprobotinterface_7194.txt)

**Comment by AntonioConsilvio** [comment]
HI @isorrentino! Me and @ replaced the broken tendon with a new one and tested the robot. Now it works properly!


> [!Warning]
> Just one important suggestion. If the neck tendon is broken, the pitch and roll joints (0 and 1) have to be disabled from the configuration files, because otherwise the motor keeps running and the tendon rolls around the gearbox.
>
> In fact, because of this we had to remove the head from the robot and disassemble the joint in order to remove the broken tendon. 

Closing! ✅

cc @S-Dafarra @GiulioRomualdi
