### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Left ankle roll goes in hw fault during calibration

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1834]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

The left ankle roll does not calibrate, and has this behavior:

https://github.com/robotology/icub-tech-support/assets/12396934/694a9408-2049-420e-b4f1-c2ece6a1dcf2

after few seconds the joint goes in HW fault saying that the i2t limit is exceeded:

![Screenshot from 2024-06-20 11-03-08](https://github.com/robotology/icub-tech-support/assets/12396934/619e74e1-bf99-4ea5-8202-7b818e2e4433)

same message in the logger:

>	277,976408	ERROR			from BOARD 10.0.1.8 (left_leg-eb8-j3_5) time=772s 331m 244u :  MC: i2t limit exceeded. The motor has been turned off to prevent it from being damaged by overheating due to a continuous high current. (Joint=l_ankle_roll (NIB=2))

### Detailed context

I have quickly checked the cabling and I did not spot anything broken. Might be an internal problem (motor - harmonic drive)?

### How does it affect you?

Blocks iRonCub experiments 

cc @DanielePucci

**Comment by AntonioConsilvio** [comment]
Hi @gabrielenava, me and @AntonioAzocar worked on this problem. 

The problem was due to the optical disc, in fact the optical disc was dirty.

We cleaned it and now the joint works properly. Closing! 🚀
