### ISSUE TITLE
ergoCub 1.2 S/N:002  – Left ankle roll goes in hw fault during calibration

### ISSUE THREAD

**Issue by mebbaid** [robotology/icub-tech-support#1835]
### Robot Name 🤖

ergoCub 1.1 S/N:002

### Request/Failure description

The `l_ankle_roll` goes in hardware fault with message

```
 45.978694 <ERROR> from BOARD 10.0.1.9 (left_leg-eb9-j4_5) time=563s 487m 605u :  MC: hard limit reached. The joint position is outside its hardware boundaries. (Joint=l_ankle_roll (NIB=1))
```

### Detailed context

The `l_ankle_roll` goes in hardware fault with message

```
 45.978694 <ERROR> from BOARD 10.0.1.9 (left_leg-eb9-j4_5) time=563s 487m 605u :  MC: hard limit reached. The joint position is outside its hardware boundaries. (Joint=l_ankle_roll (NIB=1))
```

Associated log
[l_ankle_roll_limit_reached.txt](https://github.com/user-attachments/files/15912983/l_ankle_roll_limit_reached.txt)

Associated message in motorgui
![Screenshot from 2024-05-10 14-34-27](https://github.com/robotology/icub-tech-support/assets/36491318/59b17103-caeb-4b64-bca2-958034069c58)

The error persists as long as we are using the `amo` encoder in the calibrators. If we set that to `none`, the error is no longer, but the ankle roll is clearly no calibrated and prevents us from running experiments

The error persists even if we restart the motors.

### How does it affect you?

It blocked us from running experiments on the robot with @illkid3 and @giotherobot

**Comment by AntonioConsilvio** [comment]
Hi! I found the connector of the AMO sensor quite detached:

![IMG_20240620_140944](https://github.com/robotology/icub-tech-support/assets/114915464/ca9a5fc5-dabf-428f-9998-2fbaef55084b)

I restored the connection and it works properly now! Closing 🚀
