### ISSUE TITLE
iCubErzelli02 S/N:036 – Issue with pinky of the right arm

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1836]
### Robot Name 🤖

iCubErzelli02 S/N:036

### Request/Failure description

During calibration the right hand take a while to start closing fingers and then, during the closing, the fingers get stuck

### Detailed context

similar to previous issue #1805 

### Additional context

[log_icub-head_yarprobotinterface_1846.txt](https://github.com/user-attachments/files/15924301/log_icub-head_yarprobotinterface_1846.txt)

### How does it affect you?

We have an important demo on the 10th of July. If possible please we would ask you to schedule the intervention between the 2nd and the 5th of July. As soon as you schedule the intervention please send a notification to us.

**Comment by ddetommaso** [comment]
My colleague Mateusz will be the reference person in Erzelli in the next following days cc @mmwozniak

**Comment by AntonioConsilvio** [comment]
Check the comment:

- https://github.com/robotology/icub-tech-support/issues/1841#issuecomment-2199739173

**Comment by AntonioConsilvio** [comment]
Closing due this comment:

- https://github.com/robotology/icub-tech-support/issues/1841#issuecomment-2210334608
