### ISSUE TITLE
ergoCub 1.3 S/N:002 – Left ankle roll Hardware limit pin detached from the mechanical structure

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1838]
### Robot Name 🤖

ergoCub 1.2 S/N:002

### Request/Failure description

Today @S-Dafarra tried the walking controller and noticed that the robot was not able to walk anymore. 
After some tests we noticed that the problem was related  to the left ankle roll pin (the one used for the calibration that was detached)

### Detailed context

Here is the picture of the PIN

![20240625_142821](https://github.com/robotology/icub-tech-support/assets/16744101/68409b2e-b0f3-4e87-996a-adfbfa4c8a14)

### Additional context

@AntonioConsilvio glued the pin. We recalibrated the robot and we tested the walking. Everything was working as expected (PR to be opened)
```patch
diff --git a/ergoCubSN002/calibrators/left_leg-calib.xml b/ergoCubSN002/calibrators/left_leg-calib.xml
index 9433981ff..e7a78ceeb 100644
--- a/ergoCubSN002/calibrators/left_leg-calib.xml
+++ b/ergoCubSN002/calibrators/left_leg-calib.xml
@@ -20,7 +20,7 @@
     <param name="calibration3">                       0.0            0.0          0             0          0       0        </param> 
     <param name="calibration4">                       0.0            0.0          0             0          0       0        </param>
     <param name="calibration5">                       0.0            0.0          0             0          0       0        </param>
-    <param name="calibrationZero">                    109.27         110.848      81.65         6.38       -46.624 25.808   </param>
+    <param name="calibrationZero">                    109.27         110.848      81.65         6.38       -46.624 27.187   </param>
     <param name="calibrationDelta">                   0              0            0             0          0       0        </param>
     <param name="startupPosition">                    90             80           0             -95        0       0        </param>
     <param name="startupVelocity">                    10.0           10.0         10.0          10         10      10       </param>
```

**Comment by AntonioConsilvio** [comment]
Hi! the hole where the hardware limit is mounted has become ovalised and therefore the hardware limit is no longer stationary.

![IMG_20240627_105418](https://github.com/robotology/icub-tech-support/assets/114915464/84e29e84-fa03-4458-a42c-001d9a786c5a)

We are now re-working the part so that we can fix the hardware limit so that it works properly again.

**Comment by AntonioConsilvio** [comment]
Hello, the replacement part has arrived, but unfortunately there was a manufacturing error and the part will not fit on the robot.

As the robot is working properly, we will close this support issue and monitor the issue internally.
