### ISSUE TITLE
iCubErzelli02 S/N:036 – Right shoulder tendon broken

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1841]
### Robot Name 🤖

iCubErzelli02 S/N:036

### Request/Failure description

one of the tendon broke and is out of its pulley

### Detailed context

![shared image](https://github.com/robotology/icub-tech-support/assets/3440640/83142a4c-ce89-4bfe-afa0-edabab9f0cf6)
![shared image (1)](https://github.com/robotology/icub-tech-support/assets/3440640/65011761-ea19-44d9-acc6-0c0ac790e950)

### How does it affect you?

We have participants scheduled for the next 2 following days and we might need to cancel them and reschedule them as soon as the robot is fixed. Additionally, we have an important demo on the 10th of July. If possible please we would ask you to schedule the intervention as soon as possible. As soon as you schedule the intervention please send a notification to us.

**Comment by ddetommaso** [comment]
My colleague Mateusz will be the reference person in Erzelli in the next following days cc @mmwozniak

**Comment by mmwozniak** [comment]
**How does it affect us**:
We are currently collecting data for a paper to be submitted to the Humanoids conference (deadline for finished article 15.07) and we need to finish data collection as soon as possible. Originally we planned to finish data collection this Friday

**Comment by AntonioConsilvio** [comment]
Hi @mmwozniak @ddetommaso, we planned to carry out the maintenance work on Thursday 4 July!

**Comment by AntonioConsilvio** [comment]
Hi @ddetommaso @mmwozniak, @fbiggi and I have replaced the broken tendon with a new one.
We tested the robot and it is now working properly! 🚀

In addition, @mmwozniak performed the experiment and it worked properly! 

Closing! ✅
