### ISSUE TITLE
ergoCub 1.1 S/N:001 – Neck tendon broken

### ISSUE THREAD

**Issue by evelyd** [robotology/icub-tech-support#1843]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The neck tendon snapped during locomotion testing.

### Detailed context

When this happened, the neck roll motor went into fault. We stopped the experiments following this occurrence.

## Neck tendon
![IMG_4265](https://github.com/robotology/icub-tech-support/assets/17877131/40c0191d-a26a-495d-9c48-add65d08b5f4)

## Log
[log_ergocub001-lap_yarpmotorgui_36744.txt](https://github.com/user-attachments/files/16034642/log_ergocub001-lap_yarpmotorgui_36744.txt)

**Comment by evelyd** [comment]
@GiulioRomualdi @EhsanRanjbari  @isorrentino

**Comment by AntonioConsilvio** [comment]
Hi @evelyd, @fbiggi and me replaced the broken tendon with a new one and tested the robot. It is working properly now! 

Closing! 🚀
