### ISSUE TITLE
ergoCub 1.0 S/N:002 – right arm not calibrating

### ISSUE THREAD

**Issue by LoreMoretti** [robotology/icub-tech-support#1846]
### Robot Name 🤖

ergoCub 1.0 S/N:002

### Request/Failure description

The right arm does not calibrate. 

### Detailed context

I have tried to restart the `yarprobotinterface` multiple times also restarting the motors, but it did not help. The right arm still does not calibrate.

### Additional context

Here the log:
[log.txt](https://github.com/user-attachments/files/16110759/log.txt)

### How does it affect you?

I cannot use the robot

**Comment by AntonioConsilvio** [comment]
Hi @LoreMoretti, the right arm did not calibrate for two reasons:

1. One of the three AEA3 connectors on the wrist had disconnected
    I reconnected it and it worked correctly.


2. This screw had unscrewed:

    ![IMG_20240708_143703 (1)](https://github.com/robotology/icub-tech-support/assets/114915464/bb87a5a6-2fc9-4489-b2ba-dcc5036af577)

    The unscrewed screw was clashing mechanically and did not allow the elbow to reach the hardware limit, so the joint did not 
    calibrate.

    ![IMG_20240705_171416](https://github.com/robotology/icub-tech-support/assets/114915464/07ae4302-8989-4d30-b51a-60f39699af04)
  
   I replaced screw with a new one.

Now the robot is working properly! 
Closing! 🚀
