### ISSUE TITLE
ergoCub 1.1 S/N:001 – Cable A of the neck broken

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1848]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

While walking the neck cable got broken 

### Detailed context

Here the picture of the cable

![20240708_162806.jpg](https://github.com/robotology/icub-tech-support/assets/16744101/06866c5e-a4c0-4225-b886-305dcd237b4c)

### Additional context

@AntonioConsilvio explained to me that there are only two new cables available that need to be preserved for the demo. Still there are old cables (thinner) that can be used.

**Comment by AntonioConsilvio** [comment]
Hi @GiulioRomualdi, @fbiggi and I replaced the broken tendon, but with a tendon with a smaller diameter (0.81mm) as the larger ones (0.9mm) are about to finish. Closing!
