### ISSUE TITLE
ergoCub 1.1 S/N:002 – Right thumb comes out of its socket during teleoperation

### ISSUE THREAD

**Issue by mebbaid** [robotology/icub-tech-support#1849]
### Robot Name 🤖

ergoCub 1.1 S/N:002

### Request/Failure description

The right thumb came out of its socket during a teleoperation session. The thumb was still functional and controllable. We continued the experiment putting the thumb back in its place, but it was kind of loose.

### Detailed context

The following pictures put in light the issue

![2 photos added](https://github.com/robotology/icub-tech-support/assets/36491318/a50f634d-f3cc-4436-8278-3ce6e87bf00b)

### How does it affect you?

It makes certain tasks during teleoperation (e.g. hand shakes and manipulation) not possible.

**Comment by AntonioConsilvio** [comment]
Hi @mebbaid, we glued the thumb to the hand, the robot is working properly for the time being.

> [!Warning]
> The probable cause of the detached thumb is the manual rotation. Never rotate the finger without loosening the screws first.
>
> However, the piece is being redesigned.

Closing! ✅
