### ISSUE TITLE
ergoCub 1.1 S/N:001 – Right thumb broken

### ISSUE THREAD

**Issue by PasMarra** [robotology/icub-tech-support#1851]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

Right thumb does not calibrate. Moreover, there are a couple of disconnected cable hanging from it.

### Detailed context

I've found the right thumb as in the images below. It does not calibrate and there are some cables coming out from it.

### Additional context

![image](https://github.com/user-attachments/assets/f398e75d-2338-4fac-a568-dff86943bbbd)

![shared image](https://github.com/user-attachments/assets/1bb13e4a-c14a-4074-9ea3-47c79a06e89a)

![shared image(1)](https://github.com/user-attachments/assets/e741d3ae-11e9-4fed-9ba0-7c1e1ef38353)

**Comment by AntonioConsilvio** [comment]
Hi @PasMarra, the thumb came off (a known problem) from the robot and the cables became disconnected.

@fbiggi glued the thumb to the hand and I reconnected the cables, the robot is working properly for the time being.

> [!Warning]
> The probable cause of the detached thumb is the manual rotation. Never rotate the finger without loosening the screws first.
>
> However, the piece is being redesigned.

Closing! ✅
