### ISSUE TITLE
ergoCub 1.1 S/N:001 – Neck cable broken

### ISSUE THREAD

**Issue by CarlottaSartore** [robotology/icub-tech-support#1853]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The neck cable broke during the experiments 

### Detailed context

the neck cable got broken

**Comment by AntonioConsilvio** [comment]
Hi @CarlottaSartore, I replaced the broken tendons and tested the robot. It is working properly now! ✅

> [!Note]
> Both tendons were broken. 😕
