### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Neck tendon exited the guide

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1855]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

During iRonCub experiments one of the tendon  of the neck joints exited the guide.

### Detailed context

it is the joint in the picture. Would it be possible to fix it? otherwise the head tilts during the experiments and may cause more damages
![image](https://github.com/user-attachments/assets/70dc1a84-dc24-4cd0-a0da-09929f877705)

cc @DanielePucci 

### How does it affect you?

head tilts during iRonCub experiments and may cause more damages

**Comment by AntonioConsilvio** [comment]
Hi @gabrielenava, I replaced the damaged tendon with a new one.

Please, give me a feedback when you know if it works properly!

**Comment by gabrielenava** [comment]
thanks @AntonioConsilvio, this problem is fixed and the neck works now!

**Comment by AntonioConsilvio** [comment]
Closing! 🚀
