### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Ethernet port does not work anymore

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1856]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

The ethernet port on the robot broke.

### Detailed context

While performing iRonCub experiments, the icub-head became unreachable. We noted that the ethernet connection was down. We tried to replace the ethernet cable, but still we were not able to reach the robot. We concluded that the ethernet port on the robot broke.

### How does it affect you?

blocks iRonCub experiments @DanielePucci

**Comment by Gandoo** [comment]
aieie!!  connettore Eth sulla scheda danneggiato, provvedo alla sostituzione

![3156a063-7bfc-487b-a1f2-cf74d7d9a404](https://github.com/user-attachments/assets/5581a879-827e-4436-bfbf-809664d9f2de)

cc @gabrielenava @AntonioConsilvio

**Comment by Gandoo** [comment]
Sostituito il connettore Eth suklla scheda, eseguito la verifica col tester e sembra funzionare. Rimonto il tutto.

![7a2adfc3-5dde-42d1-99fb-236acd2c25c6](https://github.com/user-attachments/assets/0b301ee9-2302-44b5-84b2-710916d5860b)

![1221322e-530d-456f-bec2-f763be944823](https://github.com/user-attachments/assets/ba0bdff1-5a45-44f3-a3cc-66a1b2e23763)

cc @gabrielenava @AntonioConsilvio

**Comment by AntonioConsilvio** [comment]
We tested the robot and the ethernet is working properly now! Good job @Gandoo! 🚀
