### ISSUE TITLE
ergoCub 1.1 S/N:001 – Left Shoulder Pitch not calibrating

### ISSUE THREAD

**Issue by LoreMoretti** [robotology/icub-tech-support#1858]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The left shoulder pitch does not calibrate.

### Detailed context

I have launched the calibration multiple times, but the same issue persists.

### Additional context

![image](https://github.com/user-attachments/assets/a0be18c4-39c0-46ac-a427-4ba3ad7c6c21)

[left_shoulder_pitch_not_calibrating.txt](https://github.com/user-attachments/files/16330905/left_shoulder_pitch_not_calibrating.txt)

### How does it affect you?

If you need whole-body control you cannot use the robot

**Comment by AntonioConsilvio** [comment]
Hi @LoreMoretti, is the problem still present on the robot?

**Comment by LoreMoretti** [comment]
Hi @AntonioConsilvio, the problem seems solved. Thanks!
