### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Broken cable on left shoulder

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1860]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

An electronic cable on the left shoulder motor lost the crimp and broke.

### Detailed context

After the fixes of #1855 and #1856, we noted that the left shoulder electronic cable that goes to the shoulder roll motor exited the crimp and broke.

**Comment by AntonioConsilvio** [comment]
HI @gabrielenava, I fixed the broken cable (cable of LCORE 5 sensor). ✅

Please, give me a feedback about the robot!

**Comment by AntonioConsilvio** [comment]
Thank you for the feedback! Closing! 🚀
