### ISSUE TITLE
ergoCub 1.1 S/N:001 – Left shoulder yaw goes immediately to overcurrent

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1866]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

While teleoperating, the left shoulder yaw went into hardware fault and it was not possible to recover. It goes continuously in overcurrent.

### Detailed context

Here the full log: 
[left_shoulder_yaw.txt](https://github.com/user-attachments/files/16416923/left_shoulder_yaw.txt)

The encoders seem to be moving normally

**Comment by Gandoo** [comment]
![cad7f9ad-4328-4937-bec8-57aaaf0bcc4f](https://github.com/user-attachments/assets/3ca6648c-193f-4eda-8e9c-c58985d4c309)

**Comment by Gandoo** [comment]
> Maybe we could use some glue to seal that screw and avoid it from happening again?

ciao @S-Dafarra ...This screw has been placed with threadlocker for safety.

**Comment by AntonioConsilvio** [comment]
Great job! 

Closing! 🚀
