### ISSUE TITLE
ergoCub 1.1 S/N:001 – Robot does not turn on

### ISSUE THREAD

**Issue by LoreMoretti** [robotology/icub-tech-support#1867]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The robot does not turn on.

cc @maggia80 @isorrentino 

### Detailed context

Few seconds after connecting the robot to the power, it turned off (i.e. all displays and LEDs were turned off). Most likely it was still  absorbing power, since after a bit we saw smoke coming out of the torso and we smelled burning.

### How does it affect you?

The robot cannot be used.

**Comment by Gandoo** [comment]
è stata sostituita la scheda 4B0 perché danneggiata la parte del motore M2 rotazione spalla.
il robot è in arena, eseguita l'accensione per vedere se ci fossero ancora problemi di fuori uscita di fumo sembrerebbe ok.

![6d0848b6-312f-4b9a-8335-0c50b32f8749](https://github.com/user-attachments/assets/37923f28-2d72-488d-a91e-ec5263e11f4f)

cc @CarlottaSartore @maggia80 @DanielePucci @Fabrizio69

**Comment by Gandoo** [comment]
ciao, durante l'accensione la scheda Batt dava subito alimentazione ai motori anche se non accesi e il pulsante rimaneva lampeggiante verde. Ho smontatato la scheda e sostituito un mosfet che era in corto, ora è stata ripristinata.

![813dc6d9-ad3e-4efe-a41d-120984cd763c](https://github.com/user-attachments/assets/a7df2991-b1ea-4c22-a930-1001f147c816)

![7acd51d1-36e2-42ad-b7b0-83b2650f6c71](https://github.com/user-attachments/assets/17fe7117-ec2a-4bd4-9823-d633782b6341)


cc @S-Dafarra  @CarlottaSartore @maggia80 @DanielePucci @Fabrizio69 @isorrentino

**Comment by AntonioAzocar** [comment]
Hi!
The [BAT board](https://github.com/robotology/icub-tech-support/issues/1867#issuecomment-2260365975) kept giving a lot of problems due to the [2FOC](https://github.com/robotology/icub-tech-support/issues/1867#issuecomment-2260056608) burning out and I had to replace it again because there was another short circuit in this one.
Now with the new BAT board mounted it works properly!

cc @maggia80 @S-Dafarra

**Comment by AntonioConsilvio** [comment]
Good job!

Closing! ✅
