### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Right shoulder cables got disconnected

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1868]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

During an experiment, the robot had a sudden motion with the right arm and some cables got disconnected from the crimp. See also the picture below.

### Detailed context

![image](https://github.com/user-attachments/assets/c72aadee-949a-457c-9f62-5dc513f8c328)

cc @AntonioAzocar

**Comment by AntonioAzocar** [comment]
I fixed the two broken cables of the right shoulder and now i delivered the robot to @gabrielenava  for testing.

![ironcub3 maintenance](https://github.com/user-attachments/assets/1277aa81-861b-4ce5-98f9-f340a5ef6896)

**Comment by gabrielenava** [comment]
I have tested the robot and everything works now! I can move the joints in the yarpmotorgui. The problem is fixed, thank you!

**Comment by AntonioConsilvio** [comment]
Good job @AntonioAzocar! Closing 🚀
