### ISSUE TITLE
ergoCub 1.1 S/N:001 – Broken neck cable

### ISSUE THREAD

**Issue by CarlottaSartore** [robotology/icub-tech-support#1869]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

During today experiments the neck got broken 

### Detailed context

During today experiments neck got broken.

C.C. @mebbaid

**Comment by AntonioConsilvio** [comment]
Hi @CarlottaSartore, I replaced the broken tendon and tested the robot. It is working properly now! Closing! ✅
