### ISSUE TITLE
iCubErzelli02 S/N:036 – Right hand issues with thumb and pinky

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1874]
### Robot Name 🤖

iCubErzelli02 S/N:036

### Request/Failure description

Right hand joints 8,9,10,12,15 appears NOT CONFIGURED. Encoders seem working.

### Detailed context

During calibration the right hand does not close as the left one. After a minute or so, the hand closes and remains stuck in that position (see picture attached).

### Additional context

[log_icub-head_yarprobotinterface_1763.txt](https://github.com/user-attachments/files/16603283/log_icub-head_yarprobotinterface_1763.txt)
![Screenshot from 2024-08-13 19-31-28](https://github.com/user-attachments/assets/12216631-6eec-45eb-adad-ffbf2f528c3c)
![1723570879572](https://github.com/user-attachments/assets/441a48f7-4c38-4044-aa79-5f705ac9d8d7)

### How does it affect you?

We are in process of implementing an important demo and both hands are needed fully working. We would need the the fix as soon as possible.

**Comment by AntonioConsilvio** [comment]
Hi! @fbiggi and me replaced the broken tendon of the ring, and replaced a damaged motor of the right thumb proximal.

A minor problem has arisen on the thumb distal of the right hand, which, if you consider it necessary, I would suggest opening another issue.

The problems relating to this issue have been resolved, closing! ✅
