### ISSUE TITLE
ergoCub 1.0 S/N:000 – Hip of the robot seems a bit loose

### ISSUE THREAD

**Issue by mebbaid** [robotology/icub-tech-support#1876]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

We were trying to test the walking on the robot. As soon as we do prepare the robot starts to shake aggressively as seen in the first video below. 
:warning: note that we needed to fault the robot by the motor buttons because the fault button is not working (this video is the second try so we learned the hard way).

https://github.com/user-attachments/assets/2b6e7a79-7aa9-4f4e-a0de-45bcf3411f32

### Detailed context

Looking at the hip joint, it seemed that there is a lot of play when moving the joint before engaging the motor. (Compare the tests between SN001 and SN000 in the videos below)

https://github.com/user-attachments/assets/3e99d5f6-07c2-4986-b17f-c173be2702cb

https://github.com/user-attachments/assets/a6d48319-2092-4eec-bf6f-760f00f7f63e

### Additional context

This issue blocks walking and consequently most demos
cc @giotherobot @S-Dafarra

**Comment by AntonioConsilvio** [comment]
Hi! @fbiggi and I disassembled the left hip roll motor to tighten these screws that were causing the play in the joint:


https://github.com/user-attachments/assets/66c84b2b-9e03-443b-ab1d-f8f0d7bde757

Now the robot is working properly! Closing!
