### ISSUE TITLE
ergoCub 1.0 S/N:000 – Fault button not working

### ISSUE THREAD

**Issue by mebbaid** [robotology/icub-tech-support#1877]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

During tests for teleoperation and walking we needed to fault the robot as it was behaving weirdly (see #1876 ) but the button was not functioning so we had to directly switch off the motors

### Detailed context

During tests for teleoperation and walking we needed to fault the robot as it was behaving weirdly (see #1876 ) but the button was not functioning so we had to directly switch off the motors

### Additional context

cc @giotherobot

**Comment by steb6** [comment]
@mebbaid I just tested the fault button and it seems to work properly now

**Comment by mebbaid** [comment]
Great! then we can close this issue.
