### ISSUE TITLE
iCubErzelli01 S/N:032 – Neck yaw broken

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1882]
### Robot Name 🤖

iCubErzelli01 S/N:032

### Request/Failure description

The neck_yaw joint seems broken. The joint appears loose if I move manually the head with both the robot on and off.

### Detailed context

There are not evident cables broken in the neck and, when the motor is on after calibration you can hear a not usual spinning noise coming from the faulty part. 

### Additional context

https://github.com/user-attachments/assets/a58ca262-ee19-4930-bc8f-db4b90e178da

### How does it affect you?

High impact. The robot is currently in use for an experimental protocol and we cancelled participants for today and the next days.

**Comment by ddetommaso** [comment]
My colleague Giulia will be the reference person in Erzelli for this issue in the next following days cc @GiuliaSiri

**Comment by GiuliaSiri** [comment]
Hi, are there any updates on when you plan to come and fix the robot?
Thank you, 
Giulia

**Comment by AntonioConsilvio** [comment]
Hi @GiuliaSiri, Unfortunately we had some high priority activities planned for this week.

We will try to provide support next week. We will let you know the date.

**Comment by GiuliaSiri** [comment]
Ok Antonio, thanks for the reply.
Let me know for next week.

**Comment by AntonioConsilvio** [comment]
Hi @GiuliaSiri! If you agree, we would like to intervene tomorrow. We will arrive in the morning and we will be autonomous to find the robot and start the intervention. Then we will need someone to test the robot.

**Comment by GiuliaSiri** [comment]
Hi Antonio, 
Tomorrow I will be in Erzelli, same floor as the blue iCub to test another experiment with some colleagues. I will be available any time, text me on teams if it is possible.

**Comment by AntonioConsilvio** [comment]
Hi @ddetommaso @GiuliaSiri! me and @fbiggi intervened by opening the yaw mechanism and found the screw holding the Flex Wave loose.

We tightened the screw and applied Loctite to prevent it from unscrewing again.

We tested the robot and it works properly now!

>[!Note]
> I had to recalibrate the joint, see PR:
>
> - https://github.com/robotology/robots-configuration/pull/676
