### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Jetpack cables disconnected

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1883]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

During indoor tests, some cables that connect to the fault button on the jetpack got disconnected. We would need help to solder them.

### Detailed context

they are the cables in the picture:

![shared image](https://github.com/user-attachments/assets/46063e61-5369-45ac-89c5-7575078906ed)

### Additional context

cc @davidegorbani @HosameldinMohamed @DanielePucci 

### How does it affect you?

we cannot perform iRonCub experiments

**Comment by AntonioConsilvio** [comment]
Hi @gabrielenava, @Gandoo fixed this problem and and improved the positioning of the connector, which should prevent the problem from recurring.

Anyway, please give me feedback if you can!

**Comment by gabrielenava** [comment]
thenk you @AntonioConsilvio and @Gandoo, we tested the electronics and works! I close the issue!
