### ISSUE TITLE
ergoCub 1.1 S/N:001 – [Broken neck]

### ISSUE THREAD

**Issue by fils99** [robotology/icub-tech-support#1884]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

During today experiments the neck got broken.

### Detailed context

The break was caused by a sudden movement of the robot.

### Additional context

Every time I try to launch `yarprobotinterface`, the neck fails to move and makes strange noises.

**Comment by AntonioConsilvio** [comment]
Hi! @fbiggi and me replaced the broken tendon with a new one. The robot is working properly now. Closing🚀

**Comment by fils99** [comment]
Thanks guys!
