### ISSUE TITLE
ergoCub 1.1 S/N:001 – Left hipt roll does not calibrate when starting the robot

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1885]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The left hip roll does not calibrate correctly during the startup phase.

### Detailed context

No details.

**Comment by AntonioConsilvio** [comment]
Hi! I fixed the cable of the hip roll AMO sensor. The robot is working properly now, Closing! ✅
