### ISSUE TITLE
ergoCub 1.0 S/N:000 – The cable of the neck broke

### ISSUE THREAD

**Issue by PasMarra** [robotology/icub-tech-support#1896]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

The cable of the neck broke during the calibration.

### Detailed context

https://github.com/user-attachments/assets/973423a3-51f3-4af8-a489-a1e7dc644330

**Comment by fedeceola** [comment]
Hi @AntonioConsilvio, we will need to use the robot quite intensively next week for the ICRA deadline (15th of September). Would it be possible to fix the robot as soon as possible?

cc @lornat75

**Comment by enyen** [comment]
# Cound not start robot calbration

Following the broke down of the neck, ergocub startup cmd has been switched to 
```commandline
yarprobotinterface --config ergocub.xml --disable_tags "(disable_head)"
```
But got error message, ad unable to start
![](https://github.com/user-attachments/assets/955c28b9-f07d-4e60-9dc9-2ff5fbbcc35b)

**Comment by lornat75** [comment]
We need the robot for the ICRA deadline (15/9, can somebody check and see if it can be repaired? thanks @AntonioConsilvio

**Comment by enyen** [comment]
yarprobointerface fail to perform calibration because one board is not detected @AntonioConsilvio 

![Screenshot from 2024-09-10 18-05-22](https://github.com/user-attachments/assets/dcc32d04-a735-43cd-8250-97819eac8437)

![Screenshot from 2024-09-10 18-04-54](https://github.com/user-attachments/assets/5f12f64a-0bec-4d4d-9f12-976bf33d3ad3)

**Comment by AntonioConsilvio** [comment]
HI! Sorry for the late reply.

On Thursday I replaced the broken tendon and fixed the ETH problem.

The robot starts and works properly. Closing!

cc @lornat75 @PasMarra @enyen @fedeceola
