### ISSUE TITLE
R1 S/N:003 – Issue with Left Arm Roll Joint

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-tech-support#1898]
### Robot Name 🤖

R1 S/N:003

### Request/Failure description

From time to time, during the launch of yarprobotinterface, or during normal arm movements, the roll pitch joint moves autonomously and reaches the upper joint limit. I suppose there is an issue with encoder readings.

### Detailed context

The issue can be reproduced just playing with yarpmotorgui.
Currently, we disabled the whole robot arm by setting to zero all PID gains.

**Comment by AntonioConsilvio** [comment]
The robot received a complete hardware upgrade to the arms.

This issue refers to the old hardware, so it is no longer present on the robot.

Closing!
