### ISSUE TITLE
ergoCub 1.1 S/N:001 – Right shoulder roll Hardware Fault

### ISSUE THREAD

**Issue by carloscp3009** [robotology/icub-tech-support#1899]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

Right Shoulder Roll Hardware Fault

### Detailed context

We were about to conduct some experiments and the right shoulder roll went into hardware fault immediately after the robot moved because of i2c error. We put the join on idle and move it manually and it went into hardaware fault saying it has reached the limit when it was actually far from it. 

CC. @GiulioRomualdi @mebbaid 

![image](https://github.com/user-attachments/assets/fd769ccc-f24a-4e51-ae18-b112c195253d)

### How does it affect you?

I can not conduct the experiments

**Comment by carloscp3009** [comment]
https://github.com/user-attachments/assets/be16ead5-4c2f-466d-84a1-03341e45f5d4

**Comment by AntonioConsilvio** [comment]
Hi! I am closing this issue in favour of:

- https://github.com/robotology/icub-tech-support/issues/1901
