### ISSUE TITLE
ergoCub 1.1 S/N:001 – Right fingers not moving

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1902]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The right fingers, except the thumb, do not move, neither through motorgui.

### Detailed context

One connector is disconnected. Not sure if it is related to the encoders or the skin

![image](https://github.com/user-attachments/assets/35eac834-f965-4c1f-afec-2a31c81247e0)

cc @mebbaid

**Comment by AntonioConsilvio** [comment]
Hi @S-Dafarra! With the help of @edersonferrante @filippoborgogni we replaced all fingers tendons because they were broken and reconnected the cable that you see in your picture (middle fingertip). We tested the robot and it is working properly now. Closing! ✅
