### ISSUE TITLE
ergoCub 1.0 S/N:000 – Middle finger stucked in right hand

### ISSUE THREAD

**Issue by PCHands** [robotology/icub-tech-support#1905]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

After 100 times of grasping, this happened

### Detailed context

Motor kept driving it to the joint limit

### Additional context

![1](https://github.com/user-attachments/assets/936a9a86-6847-45f4-aa1d-bb540caab834)

**Comment by AntonioConsilvio** [comment]
Hi! I replaced the broken cable that connect the middle sensor (FAP) to the MMA board. The robot is working properly now. Closing! 🚀
