### ISSUE TITLE
ergoCub 1.1 S/N:001 – Robot does not start

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1908]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The board 10.0.1.2 is not communicating. With FirwareUpdater I'm not able to see any board attached.

![Screenshot from 2024-09-20 10-56-32](https://github.com/user-attachments/assets/f947ccc3-f2a4-4bb1-bce5-4ced41669f0f)

### Detailed context

[log_ergocub-torso_yarprobotinterface_24682.txt](https://github.com/user-attachments/files/17072649/log_ergocub-torso_yarprobotinterface_24682.txt)

**Comment by S-Dafarra** [comment]
The issue seems on the left arm FT whose cable got damaged. The issue of no CAN boards visible from FirmwareUpdater seems due to the usual issue thaat it is not possible to detect CAN boards using FirmwareUpdater from the torso

**Comment by S-Dafarra** [comment]
With https://github.com/icub-tech-iit/robots-configuration/commit/a182c7355a7ddbbf00525f8e7ff54e3f714c997e I have removed both arm FTs and the robot starts

**Comment by S-Dafarra** [comment]
Cc @Gandoo

**Comment by Gandoo** [comment]
ciao @AntonioConsilvio   I disconnected the left ft sensor at Can-FT and the right one from EB1. Need to consider replacing both FTSensors because the cable has come out of the housing and they might be stripped or torn, consequently the 5Vdc might give problems.

cc @isorrentino @DanielePucci

**Comment by AntonioConsilvio** [comment]
Hi, there are already two issues (one in each arm) regarding the malfunctioning of FTs. I therefore proceed to close this issue in favour of:

- https://github.com/robotology/icub-tech-support/issues/1909
- https://github.com/robotology/icub-tech-support/issues/1923
