### ISSUE TITLE
ergoCub 1.1 S/N:001 – Right arm FT broken

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1909]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The right arm FT does not seem to be working

### Detailed context

The cable entering the sensor is in bad shape.

**Comment by filippoborgogni** [comment]
We replaced it with the FT sensor S/N:134.
We tested the robot and it works.
Closing!
