### ISSUE TITLE
iCubGenova04 (iRonCub1) S/N:031 – Right elbow cable got broken

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1910]
### Robot Name 🤖

iCubGenova04 (iRonCub1) S/N:031

### Request/Failure description

While testing the walking controller on iCubGenova04 (iRonCub1) the right cable of the elbow got broken

### Detailed context

I think this is due to the high backlash in the shoulder, as the joint goes into resonance while walking, causing the cable to break.

### Additional context

![20240920_174137](https://github.com/user-attachments/assets/ec9b2bb0-d871-4e4b-af92-dd63a2a46ec1)
![20240920_174128](https://github.com/user-attachments/assets/d981f722-c856-47c6-b5b4-804bf7058132)

### How does it affect you?

This will affect the important demo of next week 

@S-Dafarra @DanielePucci @maggia80 @Fabrizio69

**Comment by Gandoo** [comment]
ciao @AntonioConsilvio On Friday the 20th I fixed the left elbow cable and checked the tendon tensions on the right shoulder but there seems to be problems on the mechanical

@Fabrizio69 @DanielePucci

**Comment by AntonioConsilvio** [comment]
Hi! With the help of @Fabrizio69 and @Elio75 we replaced the broken tendon of right elbow. The elbows works as expected now! Closing ✅
