### ISSUE TITLE
ergoCub 1.0 S/N:000 – LCD of the face is broken

### ISSUE THREAD

**Issue by steb6** [robotology/icub-tech-support#1915]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

the lcd (face) of the robot is completely black

### Detailed context

while using the robot, the screen started jiggling for a while and now it is completely black.

**Comment by steb6** [comment]
@AntonioConsilvio could this be fix before the end of the week? thanks

**Comment by SimoneMic** [comment]
The LCD is still broken, and we need it at the Festival della Scienza.
Sorry for bothering you so much, thank you!

cc  @lornat75 @maggia80

**Comment by filippoborgogni** [comment]
Hi, @SimoneMic, we replaced the flat cable that connects the display  to the MIP-1000 board because it was damaged.
For the moment the robot works!

**Comment by SimoneMic** [comment]
During the demos the LCD behaved properly and everything went fine!

We can close this issue
Thank you!
