### ISSUE TITLE
iCubGenova11 S/N:050 – Right ring finger doesn't close well

### ISSUE THREAD

**Issue by martinaxgloria** [robotology/icub-tech-support#1916]
### Robot Name 🤖

iCubGenova11 S/N:050

### Request/Failure description

During some grasping tests, I found out that the ring finger of the right hand doesn't close as expected.

Edit: we also noticed that the thumb oppose moves in a strange way when calibrating, causing the calibration to fail for most of the joints of the right hand

### Detailed context

The ring finger closes before the pinky, so the grasp is not performed optimally.

### How does it affect you?

We are not able to perform the Stanford demo as well.

cc @Nicogene

**Comment by fbiggi** [comment]
Tendini ripristinati 
Fingertip ripriatinatio e risaldati da @Gandoo 

![image](https://github.com/user-attachments/assets/fcf4d711-3032-4bfb-908c-fae31ba41536)


![image](https://github.com/user-attachments/assets/234cb0ad-bf10-44eb-962b-23d26b8d3e19)

@Fabrizio69 @AntonioConsilvio

**Comment by martinaxgloria** [comment]
Until this morning, the issue about the ring/pinky seemed to be solved, but after a few calibrations of the hand, the problem of the tendon appeared again. 

cc @maggia80 @Nicogene @pattacini @Fabrizio69

**Comment by Gandoo** [comment]
ho risaldato i fili sui 2 Fingertip che si erano staccati durante la sostituzione dei tendini.

![Image](https://github.com/user-attachments/assets/9eae8d45-2d73-4bcb-b5a0-fa88c30415b4)

cc @fbiggi @martinaxgloria  @Fabrizio69

**Comment by Gandoo** [comment]
C'era un problema con l'abduzione del pollice Destro, si accostava tutto al palmo e non permetteva la riuscita della calibrazione. 
Ho verificato il cablaggio e movimento con la Jogger e alla fine mi si è staccato il filo bianco del sensore di Hall sul connettore Molex della scheda. Ricrimpato i fili, sostituito il Molex e riprovato a fare i movimento con jogger e funziona perfettamente.
In seguito @martinaxgloria ha verificato con @AntonioConsilvio i valori e in seguito la calibrazione ha cominciato ad andare a buon fine.

**Comment by AntonioConsilvio** [comment]
During testing, the ring tendon broke. So I replaced the broken tendon.

The robot worked properly and the fingers closed at the same time. 
Now the robot has shipped to Stanford so I am proceeding with the closing of the issue. 🚀
