### ISSUE TITLE
ergoCub 1.1 S/N:001 – Right thumb OC does not move

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1917]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The right thumb open/close does not seem to move.

### Detailed context

I have checked from motorgui and it seems that the encoder is constantly at zero. The motor encoder instead seems to be working fine.

Also the calibration had some issue at the beginning.

**Comment by AntonioConsilvio** [comment]
Hi @S-Dafarra, I replaced the cable that connect the magnetic encoder (FAP) to the MMA board. Now the robot is working properly. 🚀

Closing! ✅
