### ISSUE TITLE
ergoCub 1.1 S/N:001 – Left wrist mechanically broken

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1919]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

One of the wrist arms is mechanically broken.

### Detailed context

During teleoperation we heard a crack and the wrist got broken. It is possible that the arm was pushing the leg against the tight, although it was not pushing that hard.

![image](https://github.com/user-attachments/assets/2efde955-b2b4-4c50-a143-75383fda5a1a)

**Comment by AntonioConsilvio** [comment]
Hi @fbiggi fixed this issue and the wrist is working properly now, Closing! ✅
