### ISSUE TITLE
ergoCub 1.1 S/N:001 – Right middle and pinky finger not moving

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1920]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The right middle and pinky fingers cannot be moved from motorgui

### Detailed context

The joint encoder on the right middle seems stuck to 0, while the pinky encoder does seem to read something. Nonetheless, neither the pinky moves from motorgui

**Comment by filippoborgogni** [comment]
Hi @S-Dafarra,
@edersonferrante and I replaced the tendons and we tested the robot. 

Closing! 🚀
