### ISSUE TITLE
ergoCub 1.1 S/N:001 – Ethernet connector does not clip and does not seem to always work

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1921]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The ethernet connector in the back of the robot seems a bit loose, and the ETH cable does not clip in well. Also, no LED lights up when attempting to connect a cable.

### Detailed context

I tried with different cables, but the connector seems loose, maybe broken

**Comment by S-Dafarra** [comment]
The connection is a bit flaky but sometimes it works

**Comment by Gandoo** [comment]
https://github.com/robotology/icub-tech-support/issues/1944#issuecomment-2437750743

cc @S-Dafarra @DanielePucci
