### ISSUE TITLE
iCubGenova11 S/N:050 – Neck yaw hardware fault

### ISSUE THREAD

**Issue by martinaxgloria** [robotology/icub-tech-support#1922]
### Robot Name 🤖

iCubGenova11 S/N:050

### Request/Failure description

During the tests for the Stanford Demo, we noticed that the neck yaw went to hardware fault

### Detailed context

In certain positions of the head, the neck yaw went to HF MC overcurrent. I attached a figure of the cables that seem to be a little bit damaged.

![image](https://github.com/user-attachments/assets/8c5270c7-6f2a-4fcc-b243-b59389beda5b)

### Additional context

To see if it's the cause of the problem, @Gandoo put some insulated tape and the problem seemed to disappear

### How does it affect you?

Before the shipping of the robot, maybe it might be necessary to fix the cable properly to not have the same issue once in Stanford

cc @Nicogene @pattacini @Fabrizio69

**Comment by pattacini** [comment]
cc @ddetommaso

**Comment by pattacini** [comment]
As agreed with @Gandoo, he will be replacing the flat cable when the other maintenance intervention takes place to repair the finger tendon, meaning tomorrow or the day after tomorrow.

**Comment by Gandoo** [comment]
ciao @martinaxgloria @AntonioConsilvio   ho messo la guaina termorestringente sui cavi flat motori del collo M0 e M1 e del nastro isolamte a protezione del filo rosso 48Vdc del waist.

![b66d5485-d6a4-4b3d-b5f3-105bcab7fecb](https://github.com/user-attachments/assets/f0c7e56f-be2f-4579-a1c4-50ebbfe523df)

![b2d78d77-c9cc-43c4-96a9-4d74d8ad15be](https://github.com/user-attachments/assets/e07f5cea-412e-4edc-941e-56fae1fc8713)

cc @pattacini @Nicogene @ddetommaso @Fabrizio69

**Comment by pattacini** [comment]
Super! Thanks!
