### ISSUE TITLE
ergoCub 1.1 S/N:001 – [Left arm FT broken]

### ISSUE THREAD

**Issue by fils99** [robotology/icub-tech-support#1923]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The left arm FT does not seem to be working

### Detailed context

The left arm FT does not seem to be working

**Comment by filippoborgogni** [comment]
We replaced it with the FT sensor S/N:135.
We tested the robot and it works.
Closing!

**Comment by fils99** [comment]
Thanks!
