### ISSUE TITLE
ergoCub 1.1 S/N:001 – CAN Port disconnected

### ISSUE THREAD

**Issue by LoreMoretti** [robotology/icub-tech-support#1929]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The robot is not starting because the CAN1 port of the BOARD 10.0.1.8 board seems disconnected.

### Detailed context

During some experiments moving the left leg, it seems we lost connection to the CAN1 port of the BOARD 10.0.1.8

### How does it affect you?

The robot does not start.

**Comment by AntonioConsilvio** [comment]
Hi @LoreMoretti, @Gandoo fixed the CAN cable 8N1 because it was damaged. The robot is working properly now! Closing 🚀
