### ISSUE TITLE
R1 S/N:003 – R1 S/N:003 – Issue with Left Arm Pronosupination Joint R1 S/N:003

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-tech-support#1930]
### Robot Name 🤖

R1 S/N:003

### Request/Failure description

The joint does not move and it produces a slippage sound.

### Detailed context

The transmission/gearbox should be inspected

**Comment by AntonioConsilvio** [comment]
The robot received a complete hardware upgrade to the arms.

This issue refers to the old hardware, so it is no longer present on the robot.

Closing!
