### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Jetpack cable desoldered

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1933]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

One of the jetpack electronics cable desoldered from the related board (it is the one were we put some tape in the picture below):

![Image](https://github.com/user-attachments/assets/217a7c7a-c29d-4bee-9e3d-1751516d0dee)

would it be possible to fix it? At the moment, the robot is downstairs in the AMI area.

### Detailed context

cc @Fabrizio69

**Comment by Gandoo** [comment]
ho eseguito la riparazione del filo danneggiato risaldandolo sul pin del connettore.
ciao @gabrielenava poi ci farai sapere se funziona. Grazie

![Image](https://github.com/user-attachments/assets/864a3d9e-2794-42dc-b259-ea3523f33e2a)

cc @filippoborgogni  @Fabrizio69  cc @AntonioConsilvio

**Comment by gabrielenava** [comment]
Hello @Gandoo, I have tested it today and works, thank you!!

**Comment by AntonioConsilvio** [comment]
Good job @Gandoo, Closing! 🚀
