### ISSUE TITLE
iCubGenova08 S/N:043 – [Right thumb broken]

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1935]
### Robot Name 🤖

iCubGenova08 S/N:043

### Request/Failure description

During the robot calibration the right hand does not calibrate properly and it gets stuck.

For accessing the robot, clarification and additional information please refer to @SilviaMoretti and @Cater19

cc @AgnieszkaWykowska

### Detailed context

The issue appears without having noticed any critical problem in the previous sessions. It's important to mention that the problem seems recurring (see previous issues).

https://github.com/user-attachments/assets/ebbd2092-423f-45fd-88d4-b5a216a9a8ab

### Additional context

[log_icub-head_yarprobotinterface_1454.txt](https://github.com/user-attachments/files/17390692/log_icub-head_yarprobotinterface_1454.txt)

![Image](https://github.com/user-attachments/assets/84c8512e-90bb-426c-80a7-2787591e39c6)

### How does it affect you?

Critical! We are currently testing in the rehabilitation center and the issue with the robot is blocking for us.

**Comment by AntonioConsilvio** [comment]
Hi @ddetommaso, we understand the urgency, but unfortunately we do not have the availability to intervene this week.
However, we will try to intervene as soon as possible, we will update you next week.

**Comment by AntonioConsilvio** [comment]
Hi @ddetommaso, by rescheduling all the activities for these three days, we have been able to get availability tomorrow morning from 8am to 12pm. 

We have to return to CRIS in the afternoon.

Are you available tomorrow morning at 8 am?

cc @AgnieszkaWykowska @Cater19 @SilviaMoretti

**Comment by AgnieszkaWykowska** [comment]
Hi Antonio,

Thank you very much, this is very good news and very important for us.
I confirm that my team will be there in Boggiano Pico tomorrow at 8 AM.

Best wishes,
Agnieszka

--
Prof. Agnieszka Wykowska
Istituto Italiano di Tecnologia
Head of the Research Line “Social Cognition in Human-Robot Interaction”
Coordinator of Center for Human Technologies (CHT)
Address: via Enrico Melen 83, 16152 Genova, Italy
Phone: +39 010 8172242
Email: ***@***.******@***.***>
Website: https://www.iit.it/people/agnieszka-wykowska
Editor in Chief International Journal of Social Robotics<International%20Journal%20of%20Social%20Robotics>
TUM-IAS Hans-Fischer Senior Fellow<https://www.ias.tum.de/ias/wykowska-agnieszka/>





From: Antonio Consilvio ***@***.***>
Date: Wednesday, 23 October 2024 at 11:42
To: robotology/icub-tech-support ***@***.***>
Cc: Agnieszka Wykowska ***@***.***>, Mention ***@***.***>
Subject: Re: [robotology/icub-tech-support] iCubGenova08 S/N:043 – [Right thumb broken] (Issue #1935)

Hi @ddetommaso<https://github.com/ddetommaso>, by rescheduling all the activities for these three days, we have been able to get availability tomorrow morning from 8am to 12pm.

We have to return to CRIS in the afternoon.

Are you available tomorrow morning at 8 am?

cc @AgnieszkaWykowska<https://github.com/AgnieszkaWykowska> @Cater19<https://github.com/Cater19> @SilviaMoretti<https://github.com/SilviaMoretti>

**Comment by AntonioConsilvio** [comment]
Hi, me and @fbiggi repaired the broken tendon in the right distal thumb. We tested the robot and it is able to perform your demo. Closing! ✅

cc @AgnieszkaWykowska @ddetommaso @Cater19 @SilviaMoretti

**Comment by AgnieszkaWykowska** [comment]
This is great news! Thank you so much!
Agnieszka



From: Antonio Consilvio ***@***.***>
Date: Thursday, 24 October 2024 at 17:12
To: robotology/icub-tech-support ***@***.***>
Cc: Agnieszka Wykowska ***@***.***>, Mention ***@***.***>
Subject: Re: [robotology/icub-tech-support] iCubGenova08 S/N:043 – [Right thumb broken] (Issue #1935)

Hi, me and @fbiggi<https://github.com/fbiggi> repaired the broken tendon in the right distal thumb. We tested the robot and it is able to perform your demo. Closing! ✅

cc @AgnieszkaWykowska<https://github.com/AgnieszkaWykowska> @ddetommaso<https://github.com/ddetommaso> @Cater19<https://github.com/Cater19> @SilviaMoretti<https://github.com/SilviaMoretti>
