### ISSUE TITLE
ergoCub 1.1 S/N:001 – Robot left leg has play near the upper leg FT sensor

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1936]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

As per the title, the robot left leg has play near the upper leg FT sensor. @Gandoo discovered this while repeating a cable.

cc @Gandoo @fbiggi @fils99 

### Detailed context

https://github.com/user-attachments/assets/ea291b09-c747-4777-80d4-18fa60cc8469

https://github.com/user-attachments/assets/5b6e8efe-f852-483b-97fb-1c392025f2cc

**Comment by fbiggi** [comment]
cc @edersonferrante @filippoborgogni

**Comment by Gandoo** [comment]
ciao, abbiamo staccato l'elettronica, stavvato la gamba dal sensore FT, sostituito le 6 viti e messo il frenafiletti. Rimontato il tutto.


![Image](https://github.com/user-attachments/assets/7b5bd8ad-a3b5-4fe9-91e5-30267af888f1)

cc @isorrentino @DanielePucci @Fabrizio69

**Comment by edersonferrante** [comment]
Sostituito viti da 4x12 (Cod. 5933) e bloccate con la loctite 243 ( frena filetti) sulla piastra Alias ECUB_003_P_024, Cod. 15799.
Intervento effetuato con successo e gioco eliminato.
@filippoborgogni 


![Image](https://github.com/user-attachments/assets/b49cb07b-72bc-473b-8220-299e6415adce)

**Comment by AntonioConsilvio** [comment]
Good job guys 🚀 Closing! ✅
