### ISSUE TITLE
ergoCub 1.1 S/N:001 – Shoulder does not calibrate due to external fault error

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1938]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

Yesterday @fils99 turned on the robot, but the right arm was not calibrating due to the error external fault pressed.

### Detailed context

Today @Gandoo and @fbiggi take off the right arm to fix a tendon and will also investigate this problem.

cc @Gandoo @fbiggi @Fabrizio69 @mebbaid

**Comment by Gandoo** [comment]
ciao @fils99 effettivamente il problema esisteva, il filo bianco del Fault evidenziato nella foto si è sfilato dalla guaine, forse faceva un falso contatto a volte  non davaerrore Fault a volte si.
Credo che questo fosse il problema del Fault su EB22, EB24, EB30, 30B1 ed 30B2

![Image](https://github.com/user-attachments/assets/c42ff3cb-0921-472d-8fe6-09ecc9bc146a)

cc @isorrentino @Fabrizio69

**Comment by Gandoo** [comment]
smontato il ForeArm e smontato l'elettronica per poter sostituire ill tendine.

![Image](https://github.com/user-attachments/assets/f34c5454-93ff-48ea-9f72-337beb1d2f4e)


cc @fbiggi @Fabrizio69

**Comment by Gandoo** [comment]
in seguito è stata fatta la calibrazione da @isorrentino e risulta funzionante.

![Image](https://github.com/user-attachments/assets/e3b38e5f-bed6-4a1d-8cd6-04a432396545)


cc @Fabrizio69

**Comment by Fabrizio69** [comment]
I proceed with closing this issue
