### ISSUE TITLE
ergoCub 1.1 S/N:001 – Broken tendon in the right hand finger

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1939]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

As per the title.

### Detailed context

@Gandoo and @fbiggi are already investigating it.

cc @mebbaid @Fabrizio69

**Comment by Fabrizio69** [comment]
Hi @isorrentino, which finger on the right hand? After the previous corrective actions (modification of the tendon cable type), we need to trace the details of the problems if we want to evaluate these solutions. Thank you very much...

cc: @Gandoo, @fbiggi, @AntonioConsilvio

**Comment by fbiggi** [comment]
@AntonioConsilvio 

Right thumb tendon restored
The tendon did not break but only slipped out of the crimp on the engine side
Replaced and tested with positive results

![Image](https://github.com/user-attachments/assets/8531e63f-e101-4c6a-b045-e40ee54f184a)
![Image](https://github.com/user-attachments/assets/05465d6d-5562-4601-8242-a3eeae9d7cf5)


@Fabrizio69 @Gandoo @maggia80
