### ISSUE TITLE
ergoCub 1.1 S/N:001 – Neck tendon broken

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1945]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

As per the title

### Detailed context

cc @AntonioConsilvio @Fabrizio69 @fbiggi @mebbaid

**Comment by mebbaid** [comment]
I just tested the robot after the fix by @AntonioConsilvio and the neck and robot starts and is functional. Thanks

**Comment by AntonioConsilvio** [comment]
Thank you for the feedback, closing!
