### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Right jetpack FT sensor not detected

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1950]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

We tried to start the robot but the startup failed. Checking the logger, it turns out that the right jetpack FT sensor is not detected.

### Detailed context

Here is the message of the `yaprlogger`:

![Screenshot from 2024-10-29 15-05-04](https://github.com/user-attachments/assets/65a7a9ce-a617-4956-a6d4-f001062df6fc)

here is the result of `Firmwareupdater`: the sensor is not detected:

![Screenshot from 2024-10-29 15-06-29](https://github.com/user-attachments/assets/96c5733a-1337-4b4f-b80d-4036f64db4d7)

and here the cable connecting the FT. We inspected the cable to understand if it was damaged, but it does not seem so. We would need support to analyse the situation and understand why the ft is failing.

![Image](https://github.com/user-attachments/assets/5f4bfbab-4f55-4ba1-991e-12a05096d3ed)

**Comment by gabrielenava** [comment]
hello, we found another cable for the FT and replaced it, and the FT works! so, it was the cable despite it does not look damaged at first sight.

Before closing the issue, can we ask for a new cable as replacement? we took one from another setup.

**Comment by filippoborgogni** [comment]
Perfect. Closing!
