### ISSUE TITLE
iCubGenova08 S/N:043 – Right thumb issues

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1952]
### Robot Name 🤖

iCubGenova08 S/N:043

### Request/Failure description

During the robot calibration the right hand does not calibrate properly and it gets stuck.

For accessing the robot, clarification and additional information please refer to @SilviaMoretti and @Cater19

cc @AgnieszkaWykowska

### Detailed context

Today icub's right hand gave problems again so it was no longer possible to record. In particular, the problem again seems to concern the thumb and the index finger which are NOT CONFIGURED in the yarpmotorgui. We attach the log file and the screen of the joints of the right hand following the last calibration I had them do.

![Image](https://github.com/user-attachments/assets/e0ff3650-7c67-4fe0-92f6-b94de1f4890a)

### Additional context

![Image](https://github.com/user-attachments/assets/2852bd3f-dec9-48ef-a706-0a83f45a7a0a)
[log_icub-head_yarprobotinterface_1464.zip](https://github.com/user-attachments/files/17636312/log_icub-head_yarprobotinterface_1464.zip)

**Comment by AntonioConsilvio** [comment]
Hi @ddetommaso, we planned to carry out the intervention on Monday morning, from 8 a.m.

Are any of you available on that day?

cc @@AgnieszkaWykowska @SilviaMoretti @Cater19

**Comment by ddetommaso** [comment]
Hi @AntonioConsilvio,

thank you for the feedback. We'll check internally if this slot is suitable for the center and will give to you our availability as soon as possible.

cc @davideghiglino

**Comment by ddetommaso** [comment]
@AntonioConsilvio Mon 11th at 8:00AM is ok, @Cater19 will be available to allow you to make the intervention.

**Comment by AntonioConsilvio** [comment]
Hi, sorry for the delay in updating the issue, but we managed to resolve this issue on the date we agreed. Closing! 🚀
