### ISSUE TITLE
iCubLisboa01 S/N:004 – iCub lisbon issue list

### ISSUE THREAD

**Issue by Ryo-Naohara** [robotology/icub-tech-support#1953]
### Robot Name 🤖

iCubLisboa01 S/N:004

### Request/Failure description

List of current issues with iCubLisboa01 S/N:004

### Detailed context

1. Elbow force sensor, strain needs to be replaced (part already sent just needs to be installed)

![Image](https://github.com/user-attachments/assets/689276ab-4317-4bbb-93b0-a89841fa089a)

2. Planetary Gearheads Series 10/1 Variant 256:1 seems to have a defect when moving slowly sometimes it will get jammed.

![Image](https://github.com/user-attachments/assets/99ada631-d51a-4e84-94f3-7399003e8af2)
 
3. Accident with board connector, the robot accidentally fell to the right, ripping the emergency button connector

![Image](https://github.com/user-attachments/assets/d9235253-e35b-4f5e-bedc-e3e451b6a594)

4.Wrist encoder issues, either cable or encoder seem to be faulty

![Image](https://github.com/user-attachments/assets/b1a9a057-7a5f-4617-8159-c40159d43a9f)

5. One of the I/O's of the mc4 plus board 29 seems to not be able to supply power.
 ![Image](https://github.com/user-attachments/assets/8e6da77c-779e-4836-ab55-e209ec7b145e)

### Additional context

@plinioMoreno

**Comment by AntonioConsilvio** [comment]
Hi! For the replacement of the palm skin, we are already starting to work on it in an internal issue, you will be contacted directly when the material is ready! Closing! ✅
