### ISSUE TITLE
ergoCub 1.0 S/N:000 – Cannot calibrate the robot

### ISSUE THREAD

**Issue by steb6** [robotology/icub-tech-support#1956]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

Cannot calibrate the robot because of the following error:

![Image](https://github.com/user-attachments/assets/04ceb1be-db9f-415d-a56b-2f6df0c95647)

### Detailed context

[log_ergocub-torso_yarprobotinterface_2155.txt](https://github.com/user-attachments/files/17680292/log_ergocub-torso_yarprobotinterface_2155.txt)

**Comment by AntonioConsilvio** [comment]
Hi @steb6 @SimoneMic, I tested the robot and it works correctly, the problem did not occur to me. 
However, I am keeping the issue open to see if the problem will happen again.

**Comment by steb6** [comment]
Thanks @AntonioConsilvio , actually it might happen when the joints are close to the limit. I will update this issue when I use the robot again

**Comment by AntonioConsilvio** [comment]
Hi @steb6, do you know if this issue happened again? Thank you!

**Comment by steb6** [comment]
Hi @AntonioConsilvio, not really, we can close for now, thank you!
