### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Neck cable loosened

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1966]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

After today experiments, I noted that there is a neck cable which is loose, and the head moves weirdly by consequence. 

### Detailed context

Here is the cable I am referring to:

![Image](https://github.com/user-attachments/assets/ec1c6bd6-e80b-46ec-9efe-eb80c18fe547)

### Additional context

cc @S-Dafarra @DanielePucci

**Comment by AntonioConsilvio** [comment]
Me and @edersonferrante fixed the problem restoring the tendon routing.
