### ISSUE TITLE
iCubGenova02 left thumb touch sensor

### ISSUE THREAD

**Issue by mbarborinii** [robotology/icub-tech-support#1969]
### Robot Name 🤖

iCubGenova02 S/N:001

### Request/Failure description

Left thumb fingertip is not sending out signals. 

### Detailed context

We suppose it might be a wiring problem, but we honestly have no idea. Plus, we do not want to mess up 

### How does it affect you?

I get no deliverable done :(

**Comment by filippoborgogni** [comment]
Hi @mbarborinii !
We restored the left thumb touch sensor as requested and @lunagava tested it.
Closing ! ✅
