### ISSUE TITLE
ergoCub 1.0 S/N:000 – Current log file reading

### ISSUE THREAD

**Issue by mbarborinii** [robotology/icub-tech-support#1970]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

How to open/read/save the current log file while operating motor commands on icub

### Detailed context

How to open/read/save the current log file while operating motor commands on icub

**Comment by pattacini** [comment]
Hi @mbarborinii 

If your request is to ask for help for 

>How to open/read/save the current log file while operating motor commands on icub

This is not the right place where to file an issue.
Please, refer to https://github.com/robotology/community and possibly open a new discussion at https://github.com/robotology/community/discussions/categories/q-a.
