### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Ethernet connection is unreachable

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1972]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

After coming back from the Humanoids conference, we tried to turn on the robot to verify its status. Unfortunately, the `icub-head` ethernet connection does not work.

### Detailed context

We tried to change the ethernet cable, change the switch to which the ethernet was connected, change the server, change the laptop. None of this worked. We concluded that the network board on the robot probably got damaged and needs to be checked.

**Comment by HosameldinMohamed** [comment]
We opened the back cover and indeed the Ethernet connection was broken

**Comment by Fabrizio69** [comment]
⚒️ WIP:
- Previous fault with this board (cod.10143.A): see [this link](https://github.com/robotology/icub-tech-support/issues/1903) -> Solution: replaced board
- This time P2 connector (cod.1394) was torn off the PCB. This connector now is available in the warehouse, we'll try to replace it

**Comment by Fabrizio69** [comment]
## OLD CONNECTOR

![Image](https://github.com/user-attachments/assets/6cd97f53-077f-443f-aa7c-69d7e839f71f)

![Image](https://github.com/user-attachments/assets/7cb82e49-ae9e-4b78-8ba2-cb6c48582a4a)

![Image](https://github.com/user-attachments/assets/fc3d9954-f510-4d36-94d9-a63f2a780688)

## NEW CONNECTOR

![Image](https://github.com/user-attachments/assets/6f7b99dc-90bb-45f9-802a-2741cdf3af29)

**Comment by Fabrizio69** [comment]
@gabrielenava the particular is on my desk, ready for delivery

**Comment by gabrielenava** [comment]
thank you @Fabrizio69, we tested it and it works!

**Comment by Fabrizio69** [comment]
OK @gabrielenava , we can close this issue

cc: @AntonioConsilvio
