### ISSUE TITLE
ergoCub 1.0 S/N:000 – Right arm ft not found

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1980]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

The ft of the right arm is not found and is not possible to start the robot.

Here the error

![Image](https://github.com/user-attachments/assets/ed55fa8c-206e-4be2-b0aa-3dcc660cca2a)

### Detailed context

Here firmwareupdater

![Image](https://github.com/user-attachments/assets/09046ba4-f5cc-4454-80ef-f972f98ee24e)

**Comment by isorrentino** [comment]
cc @Gandoo @fbiggi

**Comment by Gandoo** [comment]
Ciao, @isorrentino  @AntonioConsilvio   the FT sensor has a cut cable, this problem has already been highlighted that the cable could be damaged.
I try to cut the cable where it is broken and solder it with a new cable, we don't have a FT sensor to replace

![Image](https://github.com/user-attachments/assets/cde033bc-1f34-4fbe-834f-b2e3e97cdf0c)

cc @Fabrizio69 @DanielePucci @maggia80

**Comment by Gandoo** [comment]
ciao @isorrentino
 i cut the FT sensor wire and soldered the wires together with a new wire, connected and awaiting testing.

![Image](https://github.com/user-attachments/assets/773e444c-e4cc-4daa-8bc6-a0513db36710)

![Image](https://github.com/user-attachments/assets/849a0002-57d8-4561-aeef-2ecbca05fc01)

![Image](https://github.com/user-attachments/assets/2fd8a03b-2cc6-4153-be33-e18d4ae9eb45)

cc @Fabrizio69 @DanielePucci @maggia80 @AntonioConsilvio

**Comment by isorrentino** [comment]
Thanks @Gandoo, I'm going to test it. I'll keep you updated here.

**Comment by isorrentino** [comment]
The robot starts without errors. Thanks again.

**Comment by isorrentino** [comment]
This is solved @AntonioConsilvio, I think the ticket can be closed.
