### ISSUE TITLE
ergoCub 1.0 S/N:000 – Right rear FT sensor is saturated

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1984]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

![Image](https://github.com/user-attachments/assets/22ab6c2c-62d0-4cf7-a8ab-f9f732c79d60)

While using the robot the FT started giving these values and saturation errors.

Is it possible to replace it?

### Detailed context

![Image](https://github.com/user-attachments/assets/19fb16bd-dc20-4e2e-beef-71bfecce2b4f)

### Additional context

cc @Gandoo

**Comment by isorrentino** [comment]
Cc @Gandoo

**Comment by Gandoo** [comment]
ciao @isorrentino @AntonioConsilvio As agreed we changed the two FTSensors from the left shoulder that works with the rear right foot which is broken

![Image](https://github.com/user-attachments/assets/d9db2b2d-90bb-4d51-ab10-aa8ebc08434f)

![Image](https://github.com/user-attachments/assets/c9e0824f-56c7-4cc9-a9f2-51a612188774)

![Image](https://github.com/user-attachments/assets/a63808f2-f305-40ad-a26f-aa1a3d3564be)

cc @filippoborgogni @Fabrizio69 @maggia80 @S-Dafarra @DanielePucci

**Comment by AntonioConsilvio** [comment]
Good job! I proceed with the closure of the issue as the problem has been resolved. ✅

We will then follow up with the replacement of the shoulder FT (when we have spare parts available) in an internal issue.
