### ISSUE TITLE
iCubShanghai01 S/N:049 – power button cover lost

### ISSUE THREAD

**Issue by jimingda** [robotology/icub-tech-support#1988]
### Robot Name 🤖

iCubShanghai01 S/N:049

### Request/Failure description

Hi, 

I've lost a power button cover like the one shown in the picture below. Could anyone provide the exact details about it so I can purchase a replacement?

Thanks.

![Image](https://github.com/user-attachments/assets/216d600d-3bec-4d3a-8268-3ec39f2fbf31)

### Detailed context

None

### Additional context

None

**Comment by filippoborgogni** [comment]
Hi @jimingda, 
the power button cover  you are looking for is not sold individually , but it is sold together with the power button.
You can buy it directly from Farnell's web site. 
The product code is 2280381 and the manufactured code is 1FS091. 
I enclose a screenshot of the site for easier understanding. Closing!

![Image](https://github.com/user-attachments/assets/04390820-287b-48fb-b114-3a9fd79dc9d7)

**Comment by jimingda** [comment]
Thank you. @filippoborgogni
