### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Ethernet connector disconnected

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1991]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

Same as https://github.com/robotology/icub-tech-support/issues/1972: the connector disconnected again from the board. Would it be possible to fix it?

![Image](https://github.com/user-attachments/assets/6d0990f9-8ddc-4758-bf04-a149a2ea6a34)
![Image](https://github.com/user-attachments/assets/d829d025-01e5-4d52-80db-8ed9f70ccb3b)

### Detailed context

cc @DanielePucci @Fabrizio69

**Comment by Fabrizio69** [comment]
Hi @gabrielenava , can you describe how it happened? This time the connector was soldered and we can't do better. At the moment I don't have a solution to permanently solve this strange problem in a place where there are not even moving parts...

**Comment by gabrielenava** [comment]
Concerning 

>Hi @gabrielenava , can you describe how it happened? This time the connector was soldered and we can't do better. At the moment I don't have a solution to permanently solve this strange problem in a place where there are not even moving parts...

I noted that the once mounted, the connector is very close to the metal support of the dummy battery (see the above picture). The support of the network board is in plastic, so, if one pushes too hard when connecting the ethernet and/or the support is pushed during iRonCub experiments, the connector will hit the metal support. This can explain why it broke twice in short time

![Image](https://github.com/user-attachments/assets/8947ff04-94e8-491b-82b4-39424bda388d)

anyways, @AntonioConsilvio gave me another network board and I mounted it on the robot. The ethernet connection now works, the problem is solved! we can close the issue

cc @Fabrizio69

**Comment by AntonioConsilvio** [comment]
Nice, closing! 🚀
