### ISSUE TITLE
ergoCub 1.1 S/N:001 – Female pin of the fault button detached from the board

### ISSUE THREAD

**Issue by rob-mau** [robotology/icub-tech-support#1996]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The female pin to which the fault button cable connects became desoldered from the board after the cable was inadvertently pulled during the crane's movement. It was not possible to reconnect the cable.

### Detailed context

During the crane's movement, the fault button cable got caught on something, and the male pin was inadvertently detached, while the female part was displaced within the torso cover. We then tried to reposition using a small screwdriver but it wasn't possible, and it was already detached. So we removed the back torso cover and realized the soldering was not intact. 
We left the cover disassembled and placed the female pin and all the screws in a small bag on the drawer unit at the entrance of the robot arena (picture attached).

### Additional context

![Image](https://github.com/user-attachments/assets/3e2bd768-79c7-48b5-b59a-7c65e17228b9)

![Image](https://github.com/user-attachments/assets/cf707d96-f328-4a61-8010-f8012d8d183d)

**Comment by SimoneMic** [comment]
I just want to mention that there are demos on Monday 16 Dec. and we need the robot to be operational, since also the other robots are in a bad shape.

Thank you!

cc. @AntonioConsilvio  @maggia80 @lornat75

**Comment by AntonioConsilvio** [comment]
@edersonferrante replaced the broken board. The robot is working properly now!
