### ISSUE TITLE
ergoCub 1.1 S/N:001 – Right knee vibrates while calibration

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#2000]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

We noticed that the right knee vibrates during calibration, preventing it from completing successfully.

### Detailed context

.

**Comment by filippoborgogni** [comment]
Hi @GiulioRomualdi !
I replaced the connectors of the amo's cable and I also found that the temperature sensor of hip pitch damaged. 
I fixed both and I tested the robot 
Closing! 🚀
