### ISSUE TITLE
Crazy movements of iCub head with iKinGazeCtrl

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/icub-tech-support#386]
### Description of the failure
iCub head rotates in a crazy way, after asking some commands to `depth2kin` module (e.g. `bind eyes 5.0`).

### Detailed conditions and logs of the failure
When I tried again to launch `iKinGazeCtrl`, I got the same problem even without asking any commands.

**Comment by traversaro** [comment]
Perhaps this was caused by https://github.com/robotology/yarp/issues/2038 ?
