### ISSUE TITLE
broken parts (leg and foot covers)

### ISSUE THREAD

**Issue by ChiaraBartolozzi** [robotology/icub-tech-support#395]
### Description of the failure
Two of the purple robot covers are broken. 

### Detailed conditions and logs of the failure
The cover of the leg (lower back -- IIT code 5747) is broken. 
The cover of the left foot is broken.
As temporary solution, we need to glue them, but we need to plan for replacements as they will probably work for a short time (the leg cover had been glued previously already).

**Comment by julijenv** [comment]
Sono state ordinate delle nuove cover???? @ChiaraBartolozzi , @Fabrizio69

**Comment by julijenv** [comment]
So far they have been glued
