### ISSUE TITLE
Right hand calibration required

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/icub-tech-support#406]
### Description of the failure
Joint no. 8 of the right arm does not reach 0.0 value

**Comment by julijenv** [comment]
Hi @giuliavezzani ,
from wat I recall, the joint 8 has the limit excursion set from 10 to 90 degrees so of course 0.0 is not reachable.

**Comment by julijenv** [comment]
Any news from that.

**Comment by giuliavezzani** [comment]
I couldn't test it intensively. I'll give you a feedback asap.
