### ISSUE TITLE
Improve internal documentation/tests for maintenance group 

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-tech-support#50]
Write up/update tests and documentation describing what needs to be done on a robot after its maintenance is complete and right before delivering the robot to the lab/customers.

We can benefit from the recently conceived [**`icub-tests`**](https://github.com/robotology/icub-tests) repository for that purpose (and we might want to extend it if necessary).

Tests include and are not limited to:
- gaze control
- reaching control
- force control
- red-ball demo
- skins
- fingertips
- hands
- legs
- ...

I would need the help of @randaz81 @DanielePucci @maggia80 and others.

**Comment by traversaro** [comment]
@pattacini I guess this issue probably needs to be moved somewhere else.

**Comment by pattacini** [comment]
Thanks @traversaro for pointing it out.
Actually, we've been dealing with these issues internally, already.
Closing then.
