### ISSUE TITLE
Timestamp missmatch from left_arm/stateExt:o and the rest of the  stateExt:o ports

### ISSUE THREAD

**Issue by fjandrad** [robotology/icub-tech-support#533]
### Description of the failure
When reading the timestamp provided by the ports 
/icub/left_arm/stateExt:o 
using :
 yarp read ... /icub/left_arm/stateExt:o envelope 

there is a time mismatch of around 300 seconds with respect to the other stateExt:o ports
![screenshot from 2017-09-06 15-20-46](https://user-images.githubusercontent.com/11043189/30114188-5d176286-9317-11e7-9b60-9200083392e5.png)

Could you help us understand why? and possible fix it ?
@marcoaccame @barbalberto

**Comment by traversaro** [comment]
Is this problem still there? Somebody that is currently using the robot can quickly check?
cc  @kouroshD @MiladShafiee @Yeshasvitvs @lrapetti

**Comment by fjandrad** [comment]
I think it used to happen randomly, I have not seen it much lately though.
