### ISSUE TITLE
Image icub-live-7.9 fails to connect to network

### ISSUE THREAD

**Issue by kt10aan** [robotology/icub-tech-support#598]
We did an upgrade of pc104 and icubsrv. 

While upgrading the pc104, after preparing the usb stick, we couldn't connect to pc104.
In more detail:

- The network consists of a simple switch, icubsrv has an IP of 10.0.0.1. netmask 255.255.255.0.
- The usb stick with the 7.0 image is booting fine on a virtual machine. No errors come up except of course the fact that it cannot ping icubsrv.

However, when we boot the usb stick on the PC104, we cannot connect to it. What's more, after a while, the light on the switch for the pc104 goes off (which makes me suspect that the pc104 hangs or that the network interface goes down).

I also tried editing the ``/etc/network/interfaces`` file on the usb stick, removing the DNS servers and gateway info, and also commenting out the existing ``eth0`` and renaming as ``eth0`` the existing ``eth1``. The same things happens.

When I prepared a usb stick with the 6.9 image, everything worked out of the box. Now our robot runs fine. So the issue is not urgent.

However, I would like to find out the reason for the connection failure (at least I suspect it is a connection failure, I do not have the VGA adapter to hook directly to pc104). It would be nice to upgrade to 7.0 in the near future.

Let me know if you need more debugging info.

**Comment by julijenv** [comment]
Hi @kt10aan , did u get an answer with the new release of the usb stick pc104??
some other post for the reconfiguration of your own network IPs could help you, example from barcelona: https://github.com/robotology/icub-support/issues/595
