### ISSUE TITLE
Feedforward having strange behavior

### ISSUE THREAD

**Issue by fjandrad** [robotology/icub-tech-support#625]
### Description of the failure
Doing torque control on feed forward has a strange behavior not seen before.

### Detailed conditions and logs of the failure
All torque kp values to 0, to have a feed forward behavior on the robot.
FT measurements on the legs set to stream raw data.
When starting the torque control the motors act fast immediately as if it was still using the ft measurements, which at that point are huge because is raw data.

If we set the values to calibrated values again this does not happen.

Before we were perfectly able to perform even the yoga demo while having all in feed forward now not even gravity compensation seems to work as before. It would seem that setting the torque kp to 0 does not eliminate all feedback from the sensors.

**Comment by randaz81** [comment]
EMS boards do not read torque measurements from the FT sensor, they use data coming from WBD.

**Comment by fjandrad** [comment]
Even if the data is coming from WBD is should not matter when we put the gains to 0. There should be no feedback at all independent of that WBD outputs. This is still an issue.

**Comment by DanielePucci** [comment]
Hi @fjandrad did this happen again?

**Comment by fjandrad** [comment]
We did not test it lately, although we did test it after May and it was still there.
