### ISSUE TITLE
robotinterface sometimes failes during calibration

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-tech-support#629]
### Description of the failure

robotinterface logs errors and randomly fails. When it does not fail it works perfectly. I suspect canbus message overflow during calibration.

### Detailed conditions and logs of the failure

attached log. 

[log_pc104_yarprobotinterface_3239.txt](https://github.com/robotology/icub-support/files/1908729/log_pc104_yarprobotinterface_3239.txt)

**Comment by lornat75** [comment]
@karinne-ics-tum

**Comment by julijenv** [comment]
any news on this matter??? @karinne-ics-tum
