### ISSUE TITLE
black images from left camera when eyes look far to the left

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-tech-support#630]
### Description of the failure
The problem is determinstic, when the eyes move to the left limit, the left camera goes black. It resumes as soon as the eyes move back. Probably the flat cable need to be changed.

**Comment by lornat75** [comment]
@karinne-ics-tum

**Comment by lornat75** [comment]
she may also need instructions on how to bend it... it is done with extreme skill :)

**Comment by julijenv** [comment]
Hi @karinne-ics-tum ,
Basically try to reproduce the bending that have the old one, and just try to make sure that whenever the eye move from left to right the flat cable don't get smashed, or fold wrongly or badly which could affect the integrity of the flat cable. Fix the flat cable on the side of the frame of the head at a height which prevent bending of the cable and finally putthe other extremity inside the connector and flatten the cable to be able to close the head cover.
let us know

**Comment by julijenv** [comment]
any news on this matter??? @karinne-ics-tum
