### ISSUE TITLE
Battery dummy bad contact

### ISSUE THREAD

**Issue by hu-yue** [robotology/icub-tech-support#651]
### Description of the failure

The dummy of the battery sometimes loses contact and the robot shuts down.

### Detailed conditions and logs of the failure

After switching the battery with the dummy, we realised that the dummy is losing contact sometimes, as we experienced a few times that the motors shut down due to lost contact of the dummy.
We saw that we need to push the dummy to establish the contact, as in the following GIF:
![dummy](https://user-images.githubusercontent.com/7060968/39890015-cec23160-5499-11e8-93ad-cc7a0f02d685.gif)

We saw later that the pins of the dummy are a bit pressed and might be the reason for the lost contact, we tried to straight them as in the following picture:
![img_20180510_212657](https://user-images.githubusercontent.com/7060968/39890070-f5fe694c-5499-11e8-9f53-94ad022d560a.jpg)

Still have to test whether this workaround solves the issue.

@julijenv @maggia80

**Comment by hu-yue** [comment]
It seems that the leds on top are now just broken, since they just don't turn on at all but the robot can be switched on without problems.

**Comment by DanielePucci** [comment]
We shall fine a more definite solution for this problem. What do you think @maggia80 @MrAndrea ?

**Comment by MrAndrea** [comment]
We have to rethink the connection between the battery and the robot, and make it more robust.

**Comment by kouroshD** [comment]
We had a similar issue in https://github.com/robotology/icub-tech-support/issues/779 , and to fix the connection problem, now we are using plastic screws.
