### ISSUE TITLE
The robot went in hardware fault while torque controlled

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#652]
### Description of the failure
While performing the Yoga, the robot fell and several parts of the robot got switched off. In particular only the left arm and the right arm wrist were still up and running.

### Detailed conditions and logs of the failure
Here attached a log:
[logFaultYoga.txt](https://github.com/robotology/icub-support/files/1999582/logFaultYoga.txt)

I tried to connect to the boards later but the FirmwareUpdater **was able** to see all the boards. The motor led was not blinking.

### Update
We noticed that the battery connection was not perfect. May this explain the faulty behavior? 

![battery-gif](https://user-images.githubusercontent.com/18591940/39982231-f4696caa-5753-11e8-837f-355da39a1cdc.gif)

![photo_2018-05-14_08-47-33](https://user-images.githubusercontent.com/18591940/39982084-79a86a0c-5753-11e8-902a-96e13d0a60d6.jpg)

### Update 2
The robot fell again, this time with a blinking motor led. Here the log:
[logFaultYoga2.txt](https://github.com/robotology/icub-support/files/1999690/logFaultYoga2.txt)

cc @julijenv @DanielePucci @hu-yue @gabrielenava @GiulioRomualdi @maggia80

**Comment by valegagge** [comment]
@S-Dafarra Have you already fixed this issue?

**Comment by S-Dafarra** [comment]
@maggia80 is currently trying to fixing it. It seems to be a connection problem either between the ``eb1`` and the ``eb24`` or between the ``eb24`` and the ``eb25``. Can you confirm?

**Comment by valegagge** [comment]
@S-Dafarra I read both logs and it seems that the problem is due to the ethernet cable that connects mc4plus with address 10.0.1.24 (eb24)  with mc4plus (10.0.1.25) eb25. Both boards are on left forearm.

Moreover, please ask to @julijenv to check the mais on left arm because it is often in error state.
(Probably the can cable in partially broken???....)

**Comment by valegagge** [comment]
About mais error.... i think the problem is due to the connection of mais to eb26.

**Comment by maggia80** [comment]
we checked the connection between MAIS and EB26 and EB25. The cables and crimps were good. 
We checked also ethernet connection between EB1 and EB24. EB25 and EB26. We crimped some wires between EB24 and EB25, but they weren't unconnected. We did it anyway to be sure the crimps were well done.

**Comment by S-Dafarra** [comment]
I think this issue can be considered solved. We will open another issue in case it occurs again.
