### ISSUE TITLE
Yarprobotinterface fails with embObjMotionControl error for EB3

### ISSUE THREAD

**Issue by dcam0050** [robotology/icub-tech-support#660]
### Description of the failure
`yarprobotinterface` fails during setting up of the robot. It seems like it cannot communicate with EB3 on 10.0.1.3

```
[WARNING]EthResource::serviceCommand() had a timeout of 0.5 secs when sending an activation request to BOARD EB3 with IP 10.0.1.3 
[ERROR]embObjMotionControl::open() fails to start mc service for board EB3 IP 10.0.1.3 : cannot continue 
yarpdev: ***ERROR*** driver <embObjMotionControl> was found but could not open
```

 or with its attached CAN boards

```[ERROR] from BOARD 10.0.1.3 (EB3) @ 180s 41m 341u: CAN discovery after 2328 ms has detected 4 missing eobrd_foc boards in CAN1:```

These are then followed by a lot of messages with the following error:

```[ERROR] from BOARD 10.0.1.3 (EB3), src CAN1, adr 0, time 76s 772m 732u: (code 0x00000018, par16 0x3001 par64 0x000000000005015b) -> SYS: EOtheCANservice could not add a CAN frame in tx fifo. In par16 there is frame.id and frame.size (in most significant nibble). In par64 there is the frame.data. + .```

The following is the full detailed log:
[icub_error.log](https://github.com/robotology/icub-support/files/2023125/icub_error.log)

Any input on how I can debug this issue?

**Comment by valegagge** [comment]
Hi @dcam0050 ,

the problem seems to be due to the lack of response of the MC4 CAN boards to the discovery made by the EMS. In details, during the startup phase, each ems verify that each CAN boards connected to is available with a "CAN dicovery" procedure.

In your case, none MC4 CAN board respoonds to this "CAN dicovery", so I think that maybe there is a problem to a CAN cable between ems and MC4 CAN boards.

To be sure of this hypotesis, please run FirmwareUpdater and check with it if the MC4 CAN boards are availble.
If you never have perform this task, please refer to section 4 of: 
https://github.com/robotology/icub-firmware-build/blob/master/ETH/FirmwareUpdater.readme.maintenance.of.eth.robots.txt

without update any firmware.

If the FirmwareUpdater can't find any MC4 CAN boards connected to ems with ip address 10.0.1.3 then the problem is due to a CAN cable broken.

**Comment by julijenv** [comment]
Hi @dcam0050 , did u have good news, or  do u need me to investigate the problem.
let me know

**Comment by julijenv** [comment]
Hi @dcam0050 , any news?!?!?!

**Comment by dcam0050** [comment]
Hey everyone, sorry for going dead. The issue was occurring intermittently and we were not using the iCub that frequently. We are now planning to use it again and the issue is happening consistently.

I've used ethLoader to discover all eth boards and then launched canLoader to find all attached can boards. The following is what I get. It seems like there are too few can boards attached but I do not remember how much there were originally.

![screenshot from 2018-08-23 13-40-22](https://user-images.githubusercontent.com/4288535/44525876-483f7600-a6da-11e8-8ec1-13a4a32c5fe5.png)

**Comment by julijenv** [comment]
Hi @dcam0050 ,
from what I can see the EB3 give you back just the board attached to the CAN2 but no reply from boards on CAN1, (2, 2FOC boards) could you check the connection at the level of this board?
![image](https://user-images.githubusercontent.com/7140395/44534520-4b495f00-a6f8-11e8-8d0e-d2cb49844f53.png)
let us know

**Comment by dcam0050** [comment]
In which part of the body is EB3 CAN 1 located?

**Comment by dcam0050** [comment]
Found 2B0 and 2B1 on iCub's back using the Motor Board placement pdf and have removed the back plate and the heatsinks labelled 2B0 and 2B1. My plan is to remove and note all wires and connectors for the 2FOC boards and then start testing continuity on the cables connecting EB3 to the 2FOC boards. Would that be correct?

**Comment by dcam0050** [comment]
![1535043795361374589782](https://user-images.githubusercontent.com/4288535/44540487-dd546600-a6fe-11e8-9814-eb4590c704ea.jpg)
![1535043828116-319256730](https://user-images.githubusercontent.com/4288535/44540510-f1986300-a6fe-11e8-8484-e32e2b840236.jpg)
![15350438559341299812946](https://user-images.githubusercontent.com/4288535/44540529-feb55200-a6fe-11e8-8275-6f1dc6a143f6.jpg)

**Comment by julijenv** [comment]
Hi @dcam0050 ,
first of all, why did you remove the heatsink?!?!? I could have sent you the exact position where to look at!!!
Hope you have some heat condictive paste to restore the boards heatsink system.
First, could you just make sure that when you turn on the motors switch that the boards turn ON and behave the same way as the than boards 1B0 and 2B0, I mean all the blinking leds.
the 2 2FOC boards are connected via c, I double check today and the document I sent you yeterday was not readable enough to identify the connetors. so here is one document you may follow to check th econnection in between can1 of EMS3 and 2B0 and 2B1.
[iCub 3_3.0.4_5672_Logic.pdf](https://github.com/robotology/icub-support/files/2317599/iCub.3_3.0.4_5672_Logic.pdf)
if you go on the page rightarm logic you will be able to see that you need to check from board EMS3 on port 7 the labelled wire 3N1 which goes to P4 on 2B0 and later the connection in between 2B0 and 2B1 from P3 on 2B0 to P3 on 2B1 labelled 3N1. Check if those cables have some wires broken, esepcially the first one in between EMS and 2FOC.
Here some pictures of EMS and 2FOC boards bot side with the connector labelled on it, like that you can restore the heatsink palte on the 2 2 FOC.
![img_20180824_103409](https://user-images.githubusercontent.com/7140395/44574638-43d29600-a78a-11e8-8a83-dbc8a1ea6fa8.jpg)
![img_20180824_103420](https://user-images.githubusercontent.com/7140395/44574641-4503c300-a78a-11e8-83c1-b63b49cfda5f.jpg)
![img_20180824_103324](https://user-images.githubusercontent.com/7140395/44574645-46cd8680-a78a-11e8-9112-390ac697b85b.jpg)
![img_20180824_103311](https://user-images.githubusercontent.com/7140395/44575042-60230280-a78b-11e8-8ea4-14fab8fee005.jpg)
let me know

**Comment by dcam0050** [comment]
OK so I've put the heatsinks back on after cleaning and reapplying thermal paste and I start the motors.
I've put an unlisted video here https://youtu.be/wLXkeziAuk0

It seems like they boot the same but then I left it for longer and now they are at a point where the 2FOC boards on the left of icub (1B0 and 1B1) flash orange at a low frequency while the boards on the right side (2B0 and 2B1) flash green at a high frequency.

Not sure how good the picture of the current state has turned out but it's this one below.
![20180824_153903](https://user-images.githubusercontent.com/4288535/44590917-29adad80-a7b4-11e8-9f1b-05fc65681822.jpg)

I'm assuming high frequency green means still trying to establish communication with EB3 board which means I now need to switch off icub, disconnect 2B0 and check continuity of cable connecting 2B0 with EB3. Is this correct?

**Comment by dcam0050** [comment]
Actually, I tried it again and 1B0 and 1B1 turned to low frequency orange because I was checking CAN devices through canLoader. When I checked CAN for 10.0.0.1, 1B0 and 1B1 turned low frequency orange and showed up. When I checked 10.0.0.3, 2B0 and 2B1 were unaffected and kept high-frequency green flashing.

I assume that still means I need to disconnect 2B0 and check comms with EB3 yes?

**Comment by dcam0050** [comment]
Hey @julijenv. I removed the cable and tested for continuity between connectors and there was continuity on all wires. So I put it back in again and what do you know, all the CAN boards are visible now! I've closed iCub up, tried booting and it boots correctly now! I'll close this issue for now and reopen it should it still be intermittent. Thanks for your help!

**Comment by dcam0050** [comment]
The CAN cable 3N1 between EB3 and 2FOC 2B0 is again working intermittently depending on how the wire is moved. We have some jst connectors to create a replacement cable but could you tell us the model number of the connectors (or their parameters) so we can replace like for like?

**Comment by julijenv** [comment]
Hi @dcam0050 ,
here is the harness of the connector, please
![image](https://user-images.githubusercontent.com/7140395/48784053-29a14900-ece2-11e8-9909-7434f474e164.png)
the connector are MOLEX picoblade female 6 contacts(Housing, Picoblade, 6 contacts, 1 row, female, p.1.25mm, Straight, w to w / w to b, nolock, nokey, 1A)
![image](https://user-images.githubusercontent.com/7140395/48784290-a8968180-ece2-11e8-889d-b7ddc1725129.png)

the crimps are :Crimp terminal, Picoblade, female contact, AWG28-32
![image](https://user-images.githubusercontent.com/7140395/48784357-d1b71200-ece2-11e8-863d-664217204c2d.png)
,hope this will help
