### ISSUE TITLE
Robot errors when run YARPROBOTINTERFACE

### ISSUE THREAD

**Issue by caicaixia** [robotology/icub-tech-support#760]
Hello guys,

Today we are doing experiments with iCub.  At beginning everything is ok.  Then we restart iCub after sometime, it can not run anymore.

When run `yarprobotinterface`, it shows many errors, and the robot can not connected anymore.
![icub_open_error2](https://user-images.githubusercontent.com/18044886/51246936-97a67b80-19c6-11e9-8552-84106c8913a2.png)

![icub_open_error22](https://user-images.githubusercontent.com/18044886/51246939-9bd29900-19c6-11e9-8cf9-196f5bd8417d.png)

what can we do now?

**Comment by caicaixia** [comment]
@julijenv , thanks very much. We will try to solve this problem after our demo next week.  Thanks again for your time.

**Comment by julijenv** [comment]
Hi @tasbolat1  and @caicaixia ,
Did you succeed to repair this cable?
let us know
