### ISSUE TITLE
Eye version/vergence calibration 

### ISSUE THREAD

**Issue by arrenglover** [robotology/icub-tech-support#765]
### Description of the failure

Calibration of the eye version and vergence in the calibrators/icub-head.xml changes the left eye and right eye individually instead.

### Detailed conditions and logs of the failure

This is not so much a failure, but it is not documented anywhere, so I thought to put a note here. However, calibrating the left eye and right eye individually is currently more difficult as the yarpmotorgui does not allow to control the eyes individually. It resulted in having to restart the yarprobotinterface multiple times to check and change the value in the file.

**Comment by arrenglover** [comment]
@valegagge - do you have any further information about this change to the calibration?

**Comment by julijenv** [comment]
@valegagge , could you try to help him in this matter. thx in advance
