### ISSUE TITLE
Face LEDs not installed

### ISSUE THREAD

**Issue by arrenglover** [robotology/icub-tech-support#773]
### Description of the failure

The LEDs for the eyebrows and mouth have not been installed yet.

**Comment by julijenv** [comment]
Hi @arrenglover,
I'll let you know, I check the availability of the pieces and I will mount them ASAP.

**Comment by julijenv** [comment]
Hi @arrenglover ,
did we put the facial expressions on the robot, sorry i totally forget if we did.

**Comment by arrenglover** [comment]
My understanding is that someone took the face just yesterday to install them. I don't know if it was completed or not.

**Comment by julijenv** [comment]
@arrenglover , @ChiaraBartolozzi , @marco-monforte , @Iaxama ,
At the moment the LEDs adn wiring calbes are all set ready to be installed. we are just wiating to receive the support of the LEDs that get plugged into the face.
@Fabrizio69 , could you please give them an estimate of the date on which probably arrive those supports. thx in advance

**Comment by Fabrizio69** [comment]
@julijenv the parts are available. You can request the material from Michelini.
I prepared the labels for the material withdrawal

**Comment by julijenv** [comment]
they have ben mounted and now @davidetome is looking to make them working properly.

**Comment by julijenv** [comment]
installed and verified. NOW WORKING.
thx @davidetome , @pattacini

**Comment by pattacini** [comment]
There was a missing `--from` in the command line, thus the conf file wasn't found.
