### ISSUE TITLE
Left wrist not working

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/icub-tech-support#826]
### Description of the failure

During the experiments today, we noticed that the left wrist of the robot is not starting correctly. When we checked we did not observe any broken cables but still the wrist fails to start.

@gabrielenava

**Comment by julijenv** [comment]
Hi @Yeshasvitvs and @gabrielenava , it is not enough information to be able to help you to find out which erson to get you in contact to set this issue up. Coul you please tell me if the encoder reading are ok. Wht color is the motrs of the wrist are in the yarpmotorgui. can you try to reabilitate them from yarpmotorgui.
let me know
