### ISSUE TITLE
Fingers not getting calibrated correctly

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/icub-tech-support#827]
### Description of the failure

On both the hands of the robot, the thumb, index and middle fingers are not getting calibrated correctly. They are always stopped in closed position.

@gabrielenava

**Comment by kouroshD** [comment]
@julijenv  Currently, when we start `yarprobotinterface`, `joint7: r_hand_fibger` stays in hardware fault, and `joint 14: r_middle_distal` is in `NOT CONFIGURED`. Can you check it please. Thank you.

**Comment by kouroshD** [comment]
@julijenv 
Today, when we were working with robot, at a certain point, the robot's right-hand figures start moving, while we did not send any command to the robot. Later, all the right-hand joint went into `hardware fault`, and we could not put them in `idle`.
This behavior happens two times today.
After the first time, I stopped the `yarprobotinterface`, and later we have trouble starting it.

**Comment by kouroshD** [comment]
> @julijenv Currently, when we start `yarprobotinterface`, `joint7: r_hand_fibger` stays in hardware fault, and `joint 14: r_middle_distal` is in `NOT CONFIGURED`. Can you check it please. Thank you.

@julijenv  any update? Thanks.
