### ISSUE TITLE
While having the an encoder broken the other joints connected to the EMS board are not stiff.

### ISSUE THREAD

**Issue by fjandrad** [robotology/icub-tech-support#830]
### Description of the failure
The robot fell while walking and broke an encoder ( right hip yaw) this keeps that joint in permanent hardware fault. We were ssuming that the other joints should be fine,  so we attempted to use the robot both in position control and in torque control. In both cases, the other joints connected to the mais board ( hip roll, hip pitch and knee ) are not able to retain the value set by the controller. Therefore the leg can be moved by hand even when it is supposed to be stiff and keep the same position value.

### Detailed conditions and logs of the failure
There does not appear an specific message in the log. Although @valegagge  and @randaz81 observed something on the 4th joint ( knee ) during their inspection of the broken encoder.

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/11043189/59335257-7e4af680-8cfc-11e9-83ac-a1fc3f02ca9c.gif)

**Comment by julijenv** [comment]
Hi @fjandrad ,
did someone check something on this matter?
MAIS board in the leg?!?!? MAIS are located into the hands, I guess you wanted to talk about another board.

**Comment by traversaro** [comment]
I think @fjandrad actually meant `EMS`.

**Comment by fjandrad** [comment]
Yeah sorry ems board xD. As far as I know they fixed the  broken encoder but did not check this behavior.

**Comment by julijenv** [comment]
hi @fjandrad ,
so I'd like to close some of the overall opened issue on GREENCH, could you let me know, if this one is settled now? if yes please close it.

**Comment by fjandrad** [comment]
As far as I know it has not been addressed at all. It happened when an encoder was broken. I do not know how to replicate the conditions to verify is still there.
