### ISSUE TITLE
iCub.Moscow.01 (#038) incorrect encoder data from joint 7 on right arm

### ISSUE THREAD

**Issue by svyatoslavdm** [robotology/icub-tech-support#842]
### Description of the failure
iCub.Moscow.01 (#038) incorrect encoder data from joint 7 on right arm

### Detailed conditions and logs of the failure
Encoder of joint 7 on right arm periodically send incorrect data as shown in the picture below:
![image](https://user-images.githubusercontent.com/6998547/61142551-b484bd00-a4d8-11e9-92fe-e48294093a57.png)

Any ideas how to fix it?

**Comment by julijenv** [comment]
Hi @svyatoslavdm ,
When the encoder give you this value (over the permitted range - abduction of fingers sshould be restricted to values in between 0 and 60 degrees - when the value is out of the boundaries the firmware put the motor in hardware fault to prevent from breaking), the important thing I would like to know  is : does the value change when you open or close the fingers abduction?
In the general case, there is a poor connection in between the sensor and the controlling board. Either on the sensor itself or on the connector attaccched to the controlling board (most of the time this side of the faulty cable- 90%). The sensor is located above the pinky finger (hall sensor) see picture below 
![image](https://user-images.githubusercontent.com/7140395/61232210-15590300-a72e-11e9-8291-ce592b074d08.png) up to the inside of the upper arm on the connector P3 labelled 2M3 . If you need more detail I attach here below the electrical connexion of this sensor.
![image](https://user-images.githubusercontent.com/7140395/61232486-af20b000-a72e-11e9-8328-d654466298bc.png)
Let me know your insights before opening the upper arm cover.
