### ISSUE TITLE
iCubGenova04: Torso roll cable broke

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/icub-tech-support#858]
### Description of the failure

While testing pHRI standup controller, the torso roll cable is broken on iCubGenova04.

CC @DanielePucci @lrapetti @GiulioRomualdi 

![photo_2019-09-17_18-32-36](https://user-images.githubusercontent.com/6505998/65076954-40fca180-d99a-11e9-92c6-99ecc2fb7b32.jpg)

**Comment by Yeshasvitvs** [comment]
The torso tendon is fixed. Thanks @julijenv 
Thanks @pattacini

**Comment by julijenv** [comment]
It has been used to repair the torso the following items
IITCODE Qta DEsciption
4768.1 x 1 : WAIST BACK CABLE 11
4769.1 x 1 : WAIST FRONT CABLE 12
