### ISSUE TITLE
Realsense stops working when the head looks down

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-tech-support#859]
### Description of the failure
When R1-mk2 bends its head down, the Realsense stops working.

### Detailed conditions and logs of the failure
This failure can be very easily reproduced by just fiddling with the `yarpmotorgui`. To bring the Realsense back to functioning we need a combination of:
- unplug/plug the cable
- power cycle the jetson

cc @vvasco @vtikha @Arya07 @fbiggi

**Comment by julijenv** [comment]
Hi @pattacini ,
with the help of @emiliano, we successfully restored the functionnality of the realSEnse.
cheers,

**Comment by pattacini** [comment]
Supercool guys! Thanks a lot!

cc @vvasco
