### ISSUE TITLE
Right arm elbow cover broken

### ISSUE THREAD

**Issue by francescolaneve** [robotology/icub-tech-support#861]
### Description of the failure
During an experiment for the thesis, while trying to reach home position the arm ended up in contact with the table leading to breakage of the right arm elbow cover.

### Detailed conditions and logs of the failure
I attach a picture showing the cover.
![pic2](https://user-images.githubusercontent.com/47743685/65257811-20e7f200-db02-11e9-8c49-433f1f2ef962.jpeg)
![pic1](https://user-images.githubusercontent.com/47743685/65257812-21808880-db02-11e9-9e02-3629993de3df.jpeg)

**Comment by julijenv** [comment]
@xEnVrE , @francescolaneve , which robot cover is broken R1 or R1-mk2?

**Comment by xEnVrE** [comment]
@julijenv R1-mk2

**Comment by julijenv** [comment]
@salvi-mattia ,can you please give some feedback of the work already done on this matter.
thx

**Comment by salvi-mattia** [comment]
hi all,
I spoke to maggia, we decided to order a new couple of these covers at MMWS and later paint them.

Togheter with julien we noticed there are some screws to be tightened

**Comment by salvi-mattia** [comment]
the parts have been ordered to mmws.
estimate delivery date: 18-oct-2019 from mmws
action to do at reception:
- painting
- assembling

**Comment by pattacini** [comment]
@vtikha @maggia80 have a look at one comment up 👀 
We're a bit tight then with the mission to Milan with R1-mk2.
Is there anything we can do about that?

**Comment by vtikha** [comment]
Plan B: in case it does not come through, can we "borrow" it from R1-mk1?

**Comment by julijenv** [comment]
@vtikha , you mean borrow from R1, no?

**Comment by vtikha** [comment]
@julijenv yes, take it from R1-mk1 just for the event.

**Comment by julijenv** [comment]
when will the event take place? @vtikha

**Comment by salvi-mattia** [comment]
there are some ready in our warehouse.
they are for the two R1 we will assemble in the future
if it's urgent we can borrow them

![immagine](https://user-images.githubusercontent.com/43994292/66112366-ffd7d480-e5ca-11e9-8e14-ab97860dc012.png)

**Comment by vtikha** [comment]
@julijenv 23-24 October

**Comment by julijenv** [comment]
@Fabrizio69 , puoi dare il tuo ok per prendere il pezzo a magazzino?

**Comment by salvi-mattia** [comment]
i componenti richiesti in officina sono pronti
per essere utilizzabili devono essere verniciati
capiamo se vogliamo mettere questi o farcene anticipare uno da @Fabrizio69 e poi rimpiazzarlo a magazzino con uno di questi.
IMHO sarebbe meglio tenere sui nostri quelli prototipati e verniciati e tenerci quelli di ARRK per i robot che "vendiamo"

**Comment by vtikha** [comment]
@salvi-mattia Abbiamo preso il componente ARRK da magazzino per montarlo per l'evento, per poi restituirlo. Intanto, OK per portare a verniciare quello stampato cosi quando ritorniamo siamo sicuri di avere un pezzo da montare su `R1-mk1`.

**Comment by salvi-mattia** [comment]
@maggia80 dunque procedo e porto i pezzi a verniciare

**Comment by Fabrizio69** [comment]
Provvedo a scaricare 1 pezzo cod.11912 - CER_021_P_033 assegnandolo al maintenance dell'R1 S/N:001

**Comment by maggia80** [comment]
@salvi-mattia si procedi se c'era già l'ordine.

**Comment by salvi-mattia** [comment]
mi è arrivata la quotazione
aperta issue su purchase (spero sia giusta)
https://github.com/icub-tech-iit/purchases/issues/54
@maggia80 dai un occhio se ritieni di approvarla

**Comment by salvi-mattia** [comment]
sono tornate le cover verniciate
le consegno a @julijenv 
andrebbe montata questa sul robot e restituita quella attualmente montata a michelini

**Comment by julijenv** [comment]
E stato cambiato con pezzi fatto stampare e dipinto via @salvi-mattia .
i pezzi di qualita piu scrsa sono tenuti da @salvi-mattia .
I pezzi di buona fattura sono state ridate a warehouse @simonemichelini

**Comment by pattacini** [comment]
cc @Miche19.
