### ISSUE TITLE
iCubGenova02: right shoulder cable broken

### ISSUE THREAD

**Issue by marco-monforte** [robotology/icub-tech-support#863]
### Description of the failure

Ciao Julien,
I'm sorry but I just broke the purple iCub right shoulder cable moving the joint close to one of its limits throught the motorgui.

![20191001_113403](https://user-images.githubusercontent.com/32684998/65950902-44cf0000-e43f-11e9-86bc-f8e79f50e817.jpg)

![20191001_113412](https://user-images.githubusercontent.com/32684998/65950927-4ef0fe80-e43f-11e9-9bb0-dfc9aecd5196.jpg)

**Comment by julijenv** [comment]
@marco-monforte , are they borken and just popped-out?

**Comment by marco-monforte** [comment]
Broken. Sorry, I didn't take the other ending part of the cable in the pics.

**Comment by julijenv** [comment]
It has bben changed the cable N1 of the shouder.

IITCODE Qta Description
4758 x 1 : Shoulder rotation cable N1

The robot has been tested and the funtionnality restored,
