### ISSUE TITLE
ethernet link resetting when head is moving

### ISSUE THREAD

**Issue by arrenglover** [robotology/icub-tech-support#864]
### Description of the failure

The icub-zynq ethernet connection resets under head motion.

### Detailed conditions 

I start the robotinterface and run an application called `head_control` that moves the head pitch and yaw randomly. At the same time I am logged into the `icub-zynq` (`ssh icub-zynq`). and use the `dmesg` command. I get the following output:
```
[  734.805945] macb e000b000.ethernet eth0: link down
[  736.853998] macb e000b000.ethernet eth0: link up (1000/Full)
[  740.949974] macb e000b000.ethernet eth0: link down
[  741.974028] macb e000b000.ethernet eth0: link up (1000/Full)
[  774.742170] macb e000b000.ethernet eth0: link down
[  776.790241] macb e000b000.ethernet eth0: link up (1000/Full)
[  779.862237] macb e000b000.ethernet eth0: link down
[  781.910290] macb e000b000.ethernet eth0: link up (1000/Full)
[  798.294342] macb e000b000.ethernet eth0: link down
[  800.342450] macb e000b000.ethernet eth0: link up (1000/Full)
```

Can we check the physical connection of the ethernet link of the ZCB in the robot head?

**Comment by arrenglover** [comment]
@julijenv can we have a look at this please? It is blocking us from using the robot motion and cameras at the same time. I opened it 7 days ago but didn't hear anything - is there some new protocol I should be following?
these guys should be made aware of the issue too (@aikolina @vvasco @Iaxama @marco-monforte)

**Comment by julijenv** [comment]
Hi @arrenglover , sorry I have been passing quite often to your robt to fix the face and people wer working on it, so I was like i didnt show up again. my bad.
I would nee you tomorrow to check that failure, when r u around??
let me know

**Comment by arrenglover** [comment]
@julijenv - I'm working on the robot from 9am - 2pm tomorrow. Let me check the problem still happens by myself to not waste your time (something might have changed if people have been working on the robot). I'll add a message here if I need your help.

**Comment by arrenglover** [comment]
@julijenv - thanks for coming this morning. I did have some troubles again today however, I'm not sure if it was from the ethernet connection, as first thought, or some problem with the ZCB. I've talked with @marco-monforte and @Iaxama to make sure we investigate exactly where the problem is coming from.
@ChiaraBartolozzi - this is the bug I was talking about. I'm not sure if it's ethernet related, or something in the HPU driver causing the Kernel to pause for a moment and the ethernet to drop. We'll keep investigating

**Comment by aikolina** [comment]
I switched off the event-cameras and tried to move the neck yaw and got the same error as @arrenglover (_i.e._ link up/down of eth0).

Not sure if this information is going to be useful, but I noticed that the error was happening frequently when moving the neck yaw between -20 and +20 degrees.

I also tried to move the head in idle manually and it seemed that the neck pitch and roll were more stiff compared to neck yaw.

**Comment by arrenglover** [comment]
@julijenv - I would like to do some experiments as soon as possible. Can you give me a time when we can look at this together? Thanks a lot.

**Comment by julijenv** [comment]
Hi @arrenglover , if you are around the robot I ll come to look for this issue right know.

**Comment by arrenglover** [comment]
@simeonedussoni @julijenv  - FYI: I had no problems all afternoon using the the temporary network cable.

**Comment by Gandoo** [comment]
ciao @julijenv @arrenglover @simeonedussoni   Ho sostituito il cavo e ricrimpato il connettore di rete. Ci sarebbe, se possibile, far modificare la staffa (vedi immagine) in modo che ci sia un po' di spazio e che i fili del connettore di rete non tocchino il metallo.
IL cavo che si e' rotto e che e' stato sostituito non e' adeguato a fare movimenti continui, come quelli che fa il collo, infatti si e' usurato dove ci sono passaggi in continuo movimento. 
![Testa  Viola](https://user-images.githubusercontent.com/53341641/67459415-d8f44780-f638-11e9-9c73-5c3a5bb1eda0.jpg)
@julijenv ho preso dal magazzino un pezzo con cod.13824 dovresti fare il tickets per poterlo scaricare su commessa.
@arrenglover @julijenv  appena possibile, fare test per vedere se il problema era effettivamente quello.

**Comment by julijenv** [comment]
it has been teste dand we can now confirm that the ethernet connexion is 1Gbit so everything ok.
