### ISSUE TITLE
Left wrist tendon very loose

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#865]
### Description of the failure
One of the tendons of the left wrist is very loose, causing high oscillations when moving it in position control.

@julijenv @GiulioRomualdi @kouroshD 

### Detailed conditions 
It is the tendon I am touching with the finger
![photo_2019-10-04_13-10-09](https://user-images.githubusercontent.com/18591940/66203312-5404b680-e6a8-11e9-83b1-108b88501386.jpg)

**Comment by julijenv** [comment]
done
