### ISSUE TITLE
Neck roll stuck

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#866]
### Description of the failure
We noticed that the roll joint and partially the pitch are almost stuck. They are very difficult to move by hand and cannot be controlled. When trying to move them with the ``yarpmotorgui``, the joint move just slightly and then it goes in hardware fault.

### Detailed conditions 
None

### Add log files of the failure
None

@julijenv

**Comment by pattacini** [comment]
I think this can be closed as today the task force sorted it out.
