### ISSUE TITLE
iCub shoulders broken cables

### ISSUE THREAD

**Issue by dariopasquali** [robotology/icub-tech-support#867]
Hello,

we broke a few cables on iCub shoulders but we don't have spare ones.
In particular, we need:
* 1x cable n°6
* 2x cable n°7
* 2x cable n°8

Could you please help us?

Thank you,
Dario

**Comment by julijenv** [comment]
Ciao Dario,
from our side we already gave 2 cables for each of the above metin requested cables.
Please see with @amaroyo .
I hope you dont ask me for more, right?!!?

**Comment by amaroyo** [comment]
@julijenv, we broke two eights.... We've experiments tomorrow, can we pass by quickly to get some?
Cheers,
Alex.

**Comment by julijenv** [comment]
it has been given to @amaroyo , the following items

IITCODE | Alias | Ver | Quantita | DEscription
-- | -- | -- | -- | --
4763 | RC_IIT_019_G_006 | 1 | 2 | SHOULDER ELEVATION CABLE 6
4764 | RC_IIT_019_G_007 | 1 | 2 | SHOULDER ROTATION CABLE 7
4765 | RC_IIT_019_G_008 | 2 | 2 | SHOULDER ROTATION CABLE 8
