### ISSUE TITLE
iCubGenova04 neck pitch joint goes frequently in Hardware Fault

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#868]
## Description of the failure
When moving the neck roll joint using the motorgui, the neck pitch goes frequently in hardware fault. We noticed that there is a consistent amount of friction in one of the two motors. This problem seems to be similar to https://github.com/robotology/icub-tech-support/issues/866 but the faulty motor seems to be the other one.

## Detailed conditions
See above

## Add log files of the failure
None

@julijenv @GiulioRomualdi @prashanthr05

**Comment by S-Dafarra** [comment]
For some reason, this does not seem to be happening a lot lately. I think we can close this and open a new one if it is occurring again.

**Comment by prashanthr05** [comment]
@S-Dafarra It did happen once (or maybe a few times) while we were testing Oculus-virtualizer retargeting for the research line evaluation demos.

Maybe @GiulioRomualdi @kouroshD could confirm this?

**Comment by S-Dafarra** [comment]
If so, we can reopen it.
