### ISSUE TITLE
CUDA machine not connecting to network

### ISSUE THREAD

**Issue by Iaxama** [robotology/icub-tech-support#870]
## Description of the failure
 After electricity went down, causing all machines on robot to shut down abruptly, the cuda machine does not connect anymore to the local network of the robot. 

## Detailed conditions
The ethernet interface does not get properly initialized. I have attached monitor and keyboard for debug and I could verify that the ethernet interface "eno1" was down. Connection did not restore even after manually running "sudo ip set eno1 up". 
As a workaround I have managed to connect by manually adding to the /etc/network/interfaces file the following lines:
auto eno1
iface eno1 inet static
address 10.0.0.40

The address is the one that was normally assigned to this machine anyway, so it should not generate any conflict, however I know this is not the way the network is usually configured, but for the moment is working.

**Comment by julijenv** [comment]
I dont reallly know how to help you on this at the moment.
I will try to hunt down @mbrunettini to know if he can give me an hand.

**Comment by Iaxama** [comment]
I have found the problem. Somehow resolveconf package got uninstalled. The package is required to properly set up the DNS server. After reinstalling it and adding the DNS settings in the /etc/network/interfaces file everything started to work again.

Here is the interface configuration:

auto eno1
iface eno1 inet static
   address 10.0.0.40
   netmask 255.255.255.0
   broadcast 10.0.0.255
   network 10.0.0.0
   gateway 10.0.0.1
   dns-nameservers 10.0.0.1 8.8.8.8
   dns-domain icub.local
   dns-search icub.local

**Comment by julijenv** [comment]
bravissimo @Iaxama , hats off!!!
