### ISSUE TITLE
ED-MTB 

### ISSUE THREAD

**Issue by ChiaraBartolozzi** [robotology/icub-tech-support#871]
## Description of the feature request

We need to reconnect the ED-MTB board to the hand of the purple robot. The cabling was already done, but Ali (a PhD student) needs to know which cable he has to connect where....

Grazie!
C

**Comment by julijenv** [comment]
ASAP ALi is around please bring him back to me to know if he needs the converter in between the 2 connectors or if he has it.
I will show him how to plug the board.

**Comment by simeonedussoni** [comment]
Hi @ChiaraBartolozzi the cable to connect the EDMTB is in place, as soon as Ali is around there he can plug it (in case of doubt we can show him) and start using.
