### ISSUE TITLE
Taxels addresses map ?

### ISSUE THREAD

**Issue by lucagl** [robotology/icub-tech-support#874]
I am implementing a new visualizer for the skin samples and events based on the location of the taxels. Is there any document with a table connecting the addresses of the samples/events  to the corresponding taxel on the skin patch?
It is very hard to reverse engineer this information and it doesn't seem there is an ordering of the addresses corresponding to an intuitive arrangement..
This issue was already addressed in event-driven-robotics/ed-skin, however I could not find a satisfactory answer and Chiara Bartolozzi suggested me to ask here. Maybe you can point me to a person that could help me.

**Comment by julijenv** [comment]
Hi @lucagl ,
from what i recall this has already been answered to someone else but I dont remember if it was on the github or somewhere else I need to check to give you the proper answer. be right back to you

**Comment by julijenv** [comment]
Hi @lucagl ,
could be please tell me which robot are you using?!?!
thx

**Comment by julijenv** [comment]
@simeonedussoni , can you help him?

**Comment by lucagl** [comment]
Hi @julijenv ,

I'm currently not using any robot but just the skin patch alone. The skin patches are those used habitually by Ali Dabbous (PhD room) @dabbous94

**Comment by simeonedussoni** [comment]
@julijenv sure
@lucagl and @dabbous94 here the map of the taxels in the 16-triangle patch you use
[taxelsinpatch.txt](https://github.com/robotology/icub-tech-support/files/3768415/taxelsinpatch.txt)
first column is the taxel index
second column x coordinate in mm
third column y coordinate in mm
as a reference see also the picture with the taxel drawn and the actual pcb juxtaposed
![taxels](https://user-images.githubusercontent.com/31098248/67502184-cc4a1080-f685-11e9-9e16-e3d10c138c24.png)

**Comment by julijenv** [comment]
Hi @lucagl ,
if you are plainly staisfied by the answer from @simeonedussoni please close the issue.
thx in advacne

**Comment by lucagl** [comment]
Thank you very much for your help and fast reply!
