### ISSUE TITLE
Problems with dragonfly left camera

### ISSUE THREAD

**Issue by Nicogene** [robotology/icub-tech-support#875]
## Brief description of the request/failure
The left dragonfly camera has launched with bayer 640x480 has some strange artifacts(no `camCalib` involved).
It appears a line in the middle of the image.

## Screenshot

![bug125](https://user-images.githubusercontent.com/19152494/67673420-4c1ff580-f97a-11e9-8418-09851c586c88.jpg)
![bug126](https://user-images.githubusercontent.com/19152494/67673424-4c1ff580-f97a-11e9-9e9a-e147400031a4.jpg)
![bug127](https://user-images.githubusercontent.com/19152494/67673425-4c1ff580-f97a-11e9-84df-daaac9f28b18.jpg)
![bug128](https://user-images.githubusercontent.com/19152494/67673426-4cb88c00-f97a-11e9-8ed2-2a93bca88bad.jpg)
![bug129](https://user-images.githubusercontent.com/19152494/67673427-4cb88c00-f97a-11e9-92f5-4a1ca9cff9ea.jpg)
![bug130](https://user-images.githubusercontent.com/19152494/67673428-4cb88c00-f97a-11e9-9f64-99de96646d68.jpg)

cc @ddetommaso

**Comment by julijenv** [comment]
Hi @Nicogene ,
It is the first time I see that.
Did you try without bayer ?
let me know

**Comment by Nicogene** [comment]
Unfortunately the only way to run 640x480 cameras is with bayer due to the limited bandwith of firewire. I will try if to run only the left camera and I will let you know.

**Comment by Nicogene** [comment]
With @xEnVrE we saw a similar problem on iCubV3. I don't remember if there was the bayer coding.

**Comment by xEnVrE** [comment]
It was @ 320 x 240 but I don't know whether the bayer coding is enabled in the dragon configuration files.

**Comment by xEnVrE** [comment]
> Unfortunately the only way to run 640x480 cameras is with bayer due to the limited bandwith of firewire. I will try if to run only the left camera and I will let you know.

We used cameras at 640x480 in `iCubGenova01` even without Bayer coding.

**Comment by Nicogene** [comment]
> Which key should I check for, in order to confirm?

It depends by the ini file used for launching the cameras, see for example :

https://github.com/robotology/robots-configuration/tree/master/iCubGenova01/camera

> We used cameras at 640x480 in iCubGenova01 even without Bayer coding.

Yeah, I did the commit, the trick was reducing the framerate to 25 fps instead 30, for bandwith issued, see https://github.com/robotology/robots-configuration/commit/2423f690519b7792574b464546046a632e612b4d

**Comment by xEnVrE** [comment]
It seems that during our tests iCubV3 we were using `dragonfly2_config_{left, right}.ini`, i.e. without beyer.

**Comment by julijenv** [comment]
Hi @ddetommaso ,
after changing the flat cable - see issue : https://github.com/robotology/icub-tech-support/issues/926
can you tell me if the issue is still occuring? or did it solve it?
let me know

**Comment by julijenv** [comment]
@ddetommaso ,
puoi chiudere l'issue se tutto a posto, grzie?

**Comment by ddetommaso** [comment]
@julijenv issue risolta!
