### ISSUE TITLE
right shoulder cables about to break

### ISSUE THREAD

**Issue by amaroyo** [robotology/icub-tech-support#880]
Hi @julijenv, 

Right shoulder, I think they are the cables 1 and 2. It's strange that they are wearing down as there's no direct friction with anything. Check the images attached - also one of those cables is getting twisted, similarly to the one you changed some time ago. 

Cheers, 
Alex.

![IMG_20191031_091220](https://user-images.githubusercontent.com/11769446/68020261-4558f180-fc9e-11e9-9045-54dc5dac1dd0.jpg)
![IMG_20191031_091327](https://user-images.githubusercontent.com/11769446/68020262-4558f180-fc9e-11e9-9325-479d23681359.jpg)
![IMG_20191031_091454](https://user-images.githubusercontent.com/11769446/68020263-4558f180-fc9e-11e9-9a11-adf39c70acd5.jpg)

**Comment by amaroyo** [comment]
Adding to the issues from before, right thumb distal and proximal broken.

**Comment by julijenv** [comment]
I think then, it is another issue to open?!?!
@amaroyo  :P

**Comment by amaroyo** [comment]
@julijenv, our robot is falling apart... they tried to fix the shoulder today and this plastic part broke...

I think it will be convinient to come over half a day to fix all of them, and take a look to the CAD issue. 

![IMG_20191105_153017](https://user-images.githubusercontent.com/11769446/68220391-fb4a7580-ffe7-11e9-8f4f-a5e30a1c0d1a.jpg)

**Comment by julijenv** [comment]
Ok I will let you know tomorrow. when you would need to pass by and give me a lift.
by the way this piece is not really importatn
