### ISSUE TITLE
icub genova04 left wrist is broken

### ISSUE THREAD

**Issue by kouroshD** [robotology/icub-tech-support#882]
The left wrist of the iCub Genova 04 is broken during teleoperation experiment.

**Comment by julijenv** [comment]
repaired with

| IITCODE | Alias | Rev. | Qta | Description |
| --- | --- | --- | --- | --- |
|6419 | RC_IIT_019_G_028 |  0  | 1   |  WRIST V2 TENDON #10 - 45mm|
