### ISSUE TITLE
Broken right shoulder tendon 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#883]
During a walking experiment, the right shoulder tendon broke.

**Comment by DanielePucci** [comment]
Gentle ping @julijenv On Monday we have a demo and we are rushing for the tests

Thanks as always

**Comment by julijenv** [comment]
It has been restored thx to @Mick3Lozzo  and @emilianobarbieri,
it has been taaken from warehouse

| IITCODE  |  Rev.  | Qta | DEscription |
| --- | --- | --- | --- |
| 4765 |  2 | 1 | SHOULDER ROTATION CABLE 8 |

**Comment by GiulioRomualdi** [comment]
Thanks @julijenv
