### ISSUE TITLE
Robot checkup in preparation of the RAI demo

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#884]
## Brief description of the request/failure
In preparation of the RAI demo we identified the following problems:
- [ ] Some skin parts do not seem to be working. In particular:
    - [x] some portions of the torso are not sensitive
    - [x] the right arm boards do not seem to be running
    - [ ] the back part of the left forearm does not seem to be working
- [x] There is a mechanical backlash on the left leg.
- [x] When moving the cables of the right elbow, the wrist jumps.

This is in preparation for the RAI demo, hence I  would address the easy fixes. If the fix would require to unmount several parts of the robot and/or keep it busy for a long time, I would postpone it after the demo.

## Accompanying material

cc. @fjandrad

**Comment by davidetome** [comment]
2 boards (mc4plus and mtb3) have been replaced; see tickets below:

https://github.com/icub-tech-iit/tickets/issues/153
https://github.com/icub-tech-iit/tickets/issues/154

cc @julijenv  @maggia80  @Fabrizio69

**Comment by S-Dafarra** [comment]
The right hand appeared to have a lot of problems. The problem was that MAIS board was not communicating. @julijenv noticed that several boards where shortcircuited and had to remove almost all the skin boards. Also, he noticed that the pinky spring was broken. All these problems were temporarily fixed to run the demo.

@julijenv do you want me to open another issue to definitely fix the problems above?

**Comment by julijenv** [comment]
it has been checked and nothing can be
