### ISSUE TITLE
right thumb distal and proximal broken

### ISSUE THREAD

**Issue by amaroyo** [robotology/icub-tech-support#887]
@julijenv, 

I know you fixed them last week, and we have used them only for pointing... so I don't know why they're broken again. 

You need to take off the full arm, right? How much time would you need, and when could you do it? 

Thanks!
Alex.

**Comment by julijenv** [comment]
It has been repaired
it has been used the following items.


|IITCODE|Alias|Qta|Tipology|Description|
| --- | --- | --- | --- | ---|
|1815 | CG077063 | 2m  | Mechanical Cables | Stainless steel microcable, cable construction 7x7mm, nom. dia 0,63mm, not coated, AISI 316|
|2391|U7194561|2m|Mechanical cables| Stainless steel microcable, cable construction 7x19mm, nom. dia 0.45mm, outer dia 0.61mm, Polyamide coated, AISI 316|
