### ISSUE TITLE
Right ring finger misplaced

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#888]
## Brief description of the failure

When the `ring and little finger` joint of the right hand is commanded to its lower bound, the ring finger assumes a wrong position as depicted in the picture. If the desired joint is moved slightly away from the lower bound, the ring finger recovers its position.

![IMG_20191118_141143836](https://user-images.githubusercontent.com/6014499/69146784-d5859c00-0ad0-11ea-9de0-94b99279eda4.jpg)

**Comment by eleramp** [comment]
Hi @julijenv, any news about this? Sorry for bothering you, we would need this to be fixed asap, in order to be able to do the demos on December 9th.

**Comment by julijenv** [comment]
@davidetome , puoi mica andare a verificare che magari ci sia soltanto da ricalibrare?!? Grazie in anticipo

**Comment by davidetome** [comment]
@julijenv  just checked;  the cable was wrappred in the bad way.
I wrapped it back in the right direction using the screwdriver.

please, @eleramp can you check the encoder reading of the joint in the motorgui when you come back?

**Comment by eleramp** [comment]
Thank you @davidetome, it works well! Encoder reading are okay.

**Comment by eleramp** [comment]
I'm sorry I was wrong. After few days of usage the finger is again as in the picture.

**Comment by julijenv** [comment]
It should be ok, now, I mean at least the motor will not spin back and close the rig finger. It would be nice to understand if the CAN board MC4 have a FW compatible with controltype 12, Could you @valegagge confirm that to me, because as iCubGenova01 is the only robot with no xls files associated ( it has been deleted at some point by mistake and never retrieved).
let us know.

**Comment by eleramp** [comment]
Hi, I try to use the right hand today, for the first time after Julien's fix. Unfortunately, the ring and little finger joint does not move, neither by controlling its position from the motorgui..

**Comment by fbottarel** [comment]
Any news on this? @julijenv repaired the fingers but the resting position of the joints show up as values that are different from zero in the motorgui. Shall we fix the configuration issue and missing files problem once and for all? @valegagge 

@lornat75

**Comment by pattacini** [comment]
With a visual inspection, we can confirm that fingers are working properly.

Thanks @emilianob80 and @fiorisi
