### ISSUE TITLE
iCubV3 short circuit on PC104 power supply input

### ISSUE THREAD

**Issue by ale-git** [robotology/icub-tech-support#889]
## Brief description of the request/failure

The power supply board goes in fault state as soon as the PC104 is switched on.

## Detailed context

When the PC104 board is unplugged there is no fault on CPU power supply. Moreover, the PC104 impedence between the terminals of the PC104 power supply connector is less than 1 ohm.  

@maggia80 @pattacini

**Comment by julijenv** [comment]
Double check, there is a shortcircuit in between the input pins of the pc104.
The board need to be replaced I presume, a further and deeper check need to be done on the connection inside the conneections side of the pc104 to see if it is not one of the peripheral that put the pc104 in short.
more coming

**Comment by maggia80** [comment]
@julijenv yes I would suggest unplugging all the connection between the COM-Express Carrier board ([CCG012](http://connecttech.com/product/com-express-type-6-rugged-ultra-lite-carrier-board/) and all the peripherals. 

![image](https://user-images.githubusercontent.com/6987330/69283796-62257c80-0bed-11ea-9dad-ee72d39b21c5.png)
