### ISSUE TITLE
iCubErzelli01: Issues on calibrating fingers

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#892]
During the starting process the fingers get stuck during calibration. @julijenv 

## Brief description of the request/failure
..

## Detailed context
..

**Comment by julijenv** [comment]
logfile?!?!??! @ddetommaso

**Comment by julijenv** [comment]
It has been changed the cable of the thumb abduction

IITCODE Qta DEsciriton
1815 x 1m:carlstahl 0.63mm
