### ISSUE TITLE
Yarprobotinterface not working

### ISSUE THREAD

**Issue by TheCamusean** [robotology/icub-tech-support#893]
## yarprobotinterface not working after a reinstallation of the OS in the robot

Hello, I have installed Yarp v3.2.1 and Icub v1.13.0 on our robot in Darmstadt.

After the installation, yarprobotinterface is not working.

I attach some of the error messages in the log

![er1](https://user-images.githubusercontent.com/19637265/69485021-8924be00-0e3a-11ea-925f-e7840b9e7351.png)
![er2](https://user-images.githubusercontent.com/19637265/69485022-8aee8180-0e3a-11ea-8d98-561668157c70.png)
![er4](https://user-images.githubusercontent.com/19637265/69485023-8c1fae80-0e3a-11ea-8e57-c4369a0c8625.png)

I hope you can help me :)

**Comment by julijenv** [comment]
Dear @TheCamusean , could you please send a full logfile please, thx in advance

**Comment by julijenv** [comment]
ping @TheCamusean

**Comment by julijenv** [comment]
Desar @TheCamusean ,
You need to update the FW of the EMS board inside the robot from what I can see, I would have loved to see the entire log but looks like you may alreasdy figure out what's going on.
You need to use FirmwarUpdater.
You probably need to contact me to help you to do so.
let me know - my skype-I is icub.support

**Comment by TheCamusean** [comment]
Hi @julijenv , 

The following weeks I will be really busy, but maybe we can contact some time in the future and finish this work.

Thanks alot for the support
