### ISSUE TITLE
Neck joint cable is broken

### ISSUE THREAD

**Issue by MiladShafiee** [robotology/icub-tech-support#894]
## Brief description of the request/failure
The cable of the neck joints is broken.

## Detailed context
During push recovery test, we pushed the robot and the rope of the carrier rolled around the neck and the neck joint cable has been broken.

**Comment by julijenv** [comment]
it has been succesfully repaired.
It has been taken from warehouse

| Item / IITCODE |Alias| Ver.| Quantity |  Description |
|:---:|:---:|:---|:---|:---|
|5965 | RC_IIT_019_G_018 |   | 1 | Head Cable A|
