### ISSUE TITLE
Skin hand taxel mapping

### ISSUE THREAD

**Issue by lucagl** [robotology/icub-tech-support#896]
Hi all,
With @dabbous, @arrenglover, and @ChiaraBartolozzi I am trying to build a visualizer for the event-driven library with a nice map of the skin events. In particular, we would like to have it working on events coming from the hand skin of the iCub. 
I found in the icub-main library methods and files to print and read the skin map. Combining .ini and .txt (calibration) files, I'm able to find how actual taxel addresses are mapped for some skin patches (eg. triangle 10 pad). To do so I used some a priori knowledge on the actual location of each taxel (see figure below) which helped me to device how the numbering is built. The files themselves are indeed extremely hermetic to me (those in icub-main/app/skinGui/conf). 
With the hand patch I'm halfway in the job. I figured out how to map the fingers but still the palm is puzzling me. Do you have a map of the type of the figure below relating taxel addresses and position for the hand? This would help a lot.

Thank you

Luca

![map](https://user-images.githubusercontent.com/15234767/70065982-37272980-15ec-11ea-9ac0-e7efe413e537.jpeg)

**Comment by julijenv** [comment]
@maggia80 to whom can I ask for feedback about that?!?! thx in advance

**Comment by simeonedussoni** [comment]
@julijenv tomorrow I will provide the documentation about this.

**Comment by simeonedussoni** [comment]
![FingertipV2_map](https://user-images.githubusercontent.com/31098248/70224973-71a8d780-174e-11ea-8a24-08f57df02574.jpg)
here the mapping of the taxels in the fingertips, left and right respectively.
The correspondence between taxels and data is as follows
- data are streamed in MTB(3/4) as two packets of 8 bytes
- first packet contains header 40 + 7 words of data from taxels 0-6
- second packet contains header C0 + 5 words o data from taxels 7-11  + 2 control bytes
- this structure is replicated for each AD7147 chip in the I2C bus ( addresses from 0 to 3) and for each I2C bus from SDA1 to SDA3 

the taxel positions for the palm are represented in the following figure
![taxelpositionpalm](https://user-images.githubusercontent.com/31098248/70225825-12e45d80-1750-11ea-90f8-07954644a150.PNG)
please note that you need to add the correct offset for finding the taxels in the data stream.

**Comment by lucagl** [comment]
@simeonedussoni  any chance for the documentation coming soon? 
thank you
Luca

**Comment by lucagl** [comment]
thank you very much!

**Comment by julijenv** [comment]
thx to @simeonedussoni
