### ISSUE TITLE
Align right shoulder's yaw with the left counterpart

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-tech-support#899]
## Brief description of the request/failure
While setting up iCub 3, we realized that the right shoulder yaw is mounted with a physical displacement of roughly 20 deg with respect to the left yaw.

As of now, the software accounts for the offset, but it'd be good to fix this up.

**Comment by julijenv** [comment]
I think it would be done later, when the visit with the Committee will be ended, I dont think you want to do that before, right? @pattacini

**Comment by pattacini** [comment]
Yep, there's no hurry 👍

**Comment by pattacini** [comment]
After the maintenance, we need to remember to change the joints' bounds in the configuration file.

@julijenv

**Comment by julijenv** [comment]
@marcellosavoldi

**Comment by marcellosavoldi** [comment]
I'm checking the CAD to understand where is the problem.
For now, is all right and the right arm met to the CAD
I need to investigate better on the robot.

![image](https://user-images.githubusercontent.com/53296021/72826663-8ba86600-3c79-11ea-978d-b61ed967b07b.png)

**Comment by marcellosavoldi** [comment]
Tomorrow I'll remove the left arm...
I have to check the right position of the plug for hard-stop.
Is possible that the wrong position of the arm is on the left arm and no on the right.

![image](https://user-images.githubusercontent.com/53296021/72827512-3ec58f00-3c7b-11ea-957c-e3fff4c93f75.png)

**Comment by marcellosavoldi** [comment]
@pattacini  and @julijenv ,
I removed the left arm and I noted that there is a problem with the supports fixed on the FTSensor on the arm:

![image](https://user-images.githubusercontent.com/53296021/72903789-282c4000-3d2e-11ea-88ca-6e46fc25bad1.png)

The part and the drawing are different:

![image](https://user-images.githubusercontent.com/53296021/72903834-3b3f1000-3d2e-11ea-91f4-0a3aca3de43c.png)

I'm sorry, but I don't remeber the history of the part.
I think that we need to open a workshop job to create the right part:
Q.ty 2 code ICUB3_001_P_234 (7082.A2)

**Comment by Fabrizio69** [comment]
@pattacini ho richiesto una commessa d'officina per la produzione dei due pezzi richiesti da @marcellosavoldi (vedi *[Proto issue #220](https://github.com/icub-tech-iit/proto/issues/220)*.
Vi segnalerò quando arriveranno i pezzi a magazzino

**Comment by pattacini** [comment]
While waiting for the parts to be produced, we will mount the arms in the current (buggy) configuration.

**Comment by Fabrizio69** [comment]
@pattacini @julijenv @marcellosavoldi il materiale richiesto è disponibile presso il Proto Team Warehouse (vedi *[Proto issue #243](https://github.com/icub-tech-iit/proto/issues/243)*)

**Comment by pattacini** [comment]
Thanks @Fabrizio69 👍 
@julijenv will be dealing with all the necessary steps, as agreed f2f.

**Comment by julijenv** [comment]
thx @Mick3Lozzo from task-force to have handled the repair.
we still need @ale-git to handle the recalibration and mainly let us know if the repair went fine.

**Comment by pattacini** [comment]
@ale-git did it in https://github.com/robotology/robots-configuration/pull/166 👍
