### ISSUE TITLE
Legs and torso bords dectect a hole in rx ropframe sequence number 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#902]
## Brief description of the request/failure
While testing the walking in torque control via current the right leg and part of the torso went in hardware fault. 

Checking the logger i noticed that the problem is also caused by a `hole in rx ropframe sequence number`. 

Rebooting the robot does not solve the problem 

## Detailed context

```
4673	687.806548	ERROR	 from BOARD 10.0.1.5 (torso-eb5-j0_2), src LOCAL, adr 0, time 739s 530m 546u: (code 0x00000030, par16 0x0001 par64 0x000000000000fc79) -> SYS: the board has detected a hole in rx ropframe sequence number. In par64 there is the expected number. The received is obtained by adding par64 with par16 treated as a int16_t + .
```

## Accompanying material
Log: [log_icub-head_yarprobotinterface_6978.txt](https://github.com/robotology/icub-tech-support/files/3977858/log_icub-head_yarprobotinterface_6978.txt)

@S-Dafarra @nunoguedelha

**Comment by julijenv** [comment]
@GiulioRomualdi ,
The problem was due to some ethernet lost packets. The colprit was the link in btween board 26 e 25 (left arm MC4-PLUS), ricrimping the ground solved the issue
