### ISSUE TITLE
Left hip pitch cable and neck cable broken  

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#903]
During a yoga demo, the robot fell down and the Left hip pitch cable and neck cable broke

**Comment by julijenv** [comment]
It has been repositionned and retensed the cable 14 - HIP FLEXION -
It has been changed the cable "A" from the neck

partts needed to repaired
IITCODE Qta DEsciption
5965 x 1 : NECK CABLE A
