### ISSUE TITLE
iCubGenova04: Neck cable out of place

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/icub-tech-support#905]
## Brief description of the request/failure

The neck cable of iCubGenova04 is out of the pulley drives after a failure in running the yoga demo

![photo_2020-01-08_14-05-07](https://user-images.githubusercontent.com/6505998/71980361-1ae85f00-3220-11ea-8f45-2a8bf653b241.jpg)

@julijenv can you please come and fix it this afternoon. I have some experiments planned. Thank you!

**Comment by julijenv** [comment]
done @Yeshasvitvs

**Comment by Yeshasvitvs** [comment]
Thanks @julijenv
