### ISSUE TITLE
 Discrepancy between Physical robot and Simulator 

### ISSUE THREAD

**Issue by YANGGANG1971** [robotology/icub-tech-support#906]
When I try to move the program to a physical robot, I find that eyeball moves the opposite direction, resulting in failure of gaze control. Is it common? Do I need to configure any settings while moving the program to a physical robot? 
(Simulator performs as well as we desired.)

**Comment by pattacini** [comment]
@YANGGANG1971 could you please provide us with further information about your robot, beginning with its nickname `iCub<City><Id>`?

**Comment by pattacini** [comment]
What are exactly the steps you followed for your experiment? Do you have pointers to the code you ran, can you list down the software components you launched and you interacted with?

**Comment by YANGGANG1971** [comment]
> @YANGGANG1971 could you please provide us with further information about your robot, beginning with its nickname `iCub<City><Id>`?

icubosaka

**Comment by YANGGANG1971** [comment]
> What are exactly the steps you followed for your experiment? Do you have pointers to the code you ran, can you list down the software components you launched and you interacted with?

On the physical robot, the majority seems good. Only the robot moves towards the opposite direction as we desired. 
I uploaded all the codes, relative settings, and experimental procedures blow. 
https://www.dropbox.com/sh/gmwnzybxh0vi7tk/AAAXcAh7Io6rYBJxSPSNW2t6a?dl=0
/usr/local/src/robot/Codes/test/Recording2.doc

**Comment by pattacini** [comment]
Thanks @YANGGANG1971 for the information.

Can you do the following test on the iCub_SIM first and then repeat it on the real iCub?

### On iCub_SIM
- Launch the simulator `iCub_SIM`.
- Launch `yarpmotorgui --robot icubSim`.
- Leave ticked on only the head part.
- Play with the sliders of the joints 4, 5 and 6 and note down how the eye bulbs move accordingly. 

### On iCub
- Launch the robot.
- Launch `yarpmotorgui`.
- Leave ticked on only the head part.
- Play with the sliders of the joints 4, 5 and 6 and note down how the eye bulbs move.

Is there correspondence of the movements among the simulator and the real robot?

**Comment by YANGGANG1971** [comment]
Test outcome as follows,
on iCub_SIM
Joint 3rd: negative down, positive up; range: [-35 15] degrees
Joint 4th: negative left (iCub_SIM view), positive right (iCub_SIM view); range [-50 50] degrees 
Joint 5th: Positive convergence inside; [0-90] degrees

On iCub
Launch yarpmotorgui, errors occurred.
 
![Screenshot from 2020-01-10 10-24-34](https://user-images.githubusercontent.com/55526431/72119492-ee575300-3397-11ea-877f-3368f5718d8d.png)

Joint 3rd: positive up; range: [0 ?] degrees, only positive value
Joint 4th: positive right (iCub_SIM view); range [0 ?] degrees only positive value
Joint 5th: Positive convergence inside; [0-90] degrees

![Screenshot from 2020-01-10 10-29-40](https://user-images.githubusercontent.com/55526431/72119525-12b32f80-3398-11ea-9a82-205fdf3fff9c.png)

**Comment by pattacini** [comment]
Thanks @YANGGANG1971 for reporting the test results.

It seems that there's a more critical problem on the real iCub as the ranges are not correctly retrieved. Give us some time to figure out what might be causing this flaw.

**Comment by pattacini** [comment]
Just to get around the `yarpmotorgui` and watch the face of those joint limits, could you do the following?

1. Launch the real iCub.
1. Run: `simpleClient --robot icub --part head`
1. Type: `get llim n`, where `n` accounts for the joint number, i.e. 0, 1, 2, 3, 4, 5.

What results did you get?

**Comment by YANGGANG1971** [comment]
The test results are as follows,
$ get llim 0
>> Bottle get lim 0
>>llim: limits: (-30.02 22.02)
$ get llim 1
>> Bottle get lim 1
>> llim: limits: (-20 20)
$ get llim 2
>> Bottle get lim 2
>> llim: limits: (-44.97 44.97)
$ get llim 3
>> Bottle get lim 3
>> llim: limits: (-30.03 30.01)
$ get llim 4
>> Bottle get lim 4
>> llim: limits: (-30.00 30.00)
$ get llim 5
>> Bottle get lim 5
>> llim: limits: (0 50)

**Comment by pattacini** [comment]
This sounds actually very strange since `yarpmotorgui` and `simpleClient` do rely on the same YARP interfaces and, from your last report, it appears that range limits are correctly set and retrieved on the real robot.

Can you provide the following further info?
1. The output of the command `yarp version` both on the PC104 (the robot hub located in the head) and on the computer where you launched the `simpleClient` and `yarpmotorgui` services.
1. The output of the commands `which simpleClient` and `which yarpmotorgui` on the computer where you launched these services.

**Comment by YANGGANG1971** [comment]
On the user computer, 
> $ yarp version 
> >> YARP version 3.1.0+29-20180903.4+git131bb8c 
> $ which simpleClient 
> >> /usr/local/src/robot/install/bin/simpleClient 
> $ which yarpmotorgui 
> >>  /usr/local/src/robot/install/bin/yarpmotorgui 

Sorry, I have no idea how to operate pc104. The pc104 was put in a big box and it seems that users are hard to operate it.

**Comment by pattacini** [comment]
You should be able to do:
```sh
$ ping pc104
$ ssh pc104
```

**Comment by pattacini** [comment]
We have observed a similar behavior on the robot when an embedded control board stopped working. Power cycling solved the problem.

I suspect this issue is quite related to this. This would also explain why `simpleClient` was successful to read the joint bounds: it's very likely that after a reboot you got the iCub on shape again.

**Comment by pattacini** [comment]
Closing, feel free to open it again if needed.
