### ISSUE TITLE
Right hand fingers not moving

### ISSUE THREAD

**Issue by dariopasquali** [robotology/icub-tech-support#910]
Ciao @julijenv ,
We have a problem with thumb, ring and pinky fingers of **right hand** of **iCub03**.

- [ ] The thumb correctly performs the initial calibration but, in the end, it moves to the centre of the palm and stops moving.
- [x] Ring and pinky fingers do not move at all. - HAS BEEN DONE ON 11/02/2020

We cannot move them either with the motorgui and the arm keeps emitting a noise like it is trying to move the fingers but they do not move.

is there something we can do? Otherwise, we would need your help.

Thank you,
Dario

**Comment by julijenv** [comment]
hard to say like that @dariopasquali , the cable of either thumb oppose or thumb proximal might be broken. For the last 2 joints I guess the value  is out of boundary, but it can be seen if you send me the log file of the calibration.
Please remind you it is the upmost imprtance that you join the log file to any of your porblem in order to speed the process - or else I need to request it ahahhah.
let me know

**Comment by dariopasquali** [comment]
Hi @julijenv you are right!
I attach:
* a zip with the yarplog of yarprobotinterface (both the log session and the txt file, I don't know which one you prefer) [yarprobotinterface_log.zip](https://github.com/robotology/icub-tech-support/files/4169718/yarprobotinterface_log.zip)
* a picture of the right thumb

Francesco told me that you will be here next week for the iCub04 training. Maybe, if you have time, you could help us fix this.

![IMG_20200207_092511](https://user-images.githubusercontent.com/11158169/74013378-9dce1800-498c-11ea-8bb0-fe7216c0d02c.jpg)

Thank you,
Dario

**Comment by julijenv** [comment]
Hi @dariopasquali , yes I will be there next Tuesday for the PhD course. Afterwards I will check youur robot S/N:020 (the old red).
I have also to make a jump in the other side of the building.
On the picture I cant really see any big problem with the mechanical cables, could you please check if the FC pcb boards is well aligned above the MAIS board (on top of the knuckles to make myself clear)
![image](https://user-images.githubusercontent.com/7140395/74016194-4fbc1300-4992-11ea-985d-ceaa9bb9b1f5.png)

**Comment by julijenv** [comment]
the thumb motor proximal has been found with a shaft broken from the gearbox output.
They are waiting to get the replacement place
