### ISSUE TITLE
A little piece of plastic fell from Green iCub

### ISSUE THREAD

**Issue by HosameldinMohamed** [robotology/icub-tech-support#915]
## Brief description of the request/failure
We were handling the Green iCub (iCubGenova04) during an experiment on Friday 31/01/2020 where a small plastic piece fell from the robot (see the photo). I am not sure if it got broken or it was glued.

## Detailed context
The piece fell from inside the cover of the robot. I am not sure if it fell from the front part of the back part.

I put the piece on my desk.

## Accompanying material

![image](https://user-images.githubusercontent.com/45564317/73668481-32dbc300-46a6-11ea-98f2-243814b45edd.png)

**Comment by julijenv** [comment]
@HosameldinMohamed , this  piece is part of the chest holder, it has been broekn and reglued and repaired 1000 times of times, every time we put a new one it got broken right after , so I will reglue it again. Dont worry

**Comment by HosameldinMohamed** [comment]
> @HosameldinMohamed , this piece is part of the chest holder, it has been broekn and reglued and repaired 1000 times of times, every time we put a new one it got broken right after , so I will reglue it again. Dont worry

Thank you @julijenv :+1:

**Comment by Elio75** [comment]
**ok the new piece has been replaced ...**
@julijenv @Mick3Lozzo  Gesino se stai modificando il pezzo in questione dai una occhiata ai fori delle viti d'attacco , c'è poco materiale e penso che basta poco in chiusura per rompersi... (guarda imagine)
![37](https://user-images.githubusercontent.com/53298662/74348485-14b34880-4db3-11ea-988d-e829f7e508a8.jpg)

potresti magari attaccare il pezzo qua 
![36](https://user-images.githubusercontent.com/53298662/74348913-baff4e00-4db3-11ea-9517-13f5f0f7255e.JPG)

**Comment by julijenv** [comment]
Please @Mick3Lozzo , as you are making the new piece, try to use the feedback given by @Elio75 , thx
