### ISSUE TITLE
iTeenGenova01: neck broken

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-tech-support#917]
## Brief description of the request/failure
As the attached photo shows, a cable of neck is out of its pulley

![20200206_093606](https://user-images.githubusercontent.com/4233231/73920053-fc2fc380-48c4-11ea-867b-fe00ed12c478.jpg)

**Comment by julijenv** [comment]
@valegagge , @vtikha , done. Let me know if it restart corrrectly i f indeed it is the case , pleas eclose the issue thx

**Comment by julijenv** [comment]
@ale-git , could you check that the neck is working fine now that I repaired it.
let me know by closing it if it is ok,
thx in advance
