### ISSUE TITLE
Unable to move thumb proximal joint

### ISSUE THREAD

**Issue by fbottarel** [robotology/icub-tech-support#918]
## Brief description of the request/failure
The proximal joint of the right thumb does not move either with yarpmotorgui nor by hand. 

## Detailed context
Setting the joint to idle does not change anything. Currently, the joint is frozen close to the palm.

**Comment by fbottarel** [comment]
@xEnVrE

**Comment by julijenv** [comment]
it has been checked the thumb proximal is broken - I need at least 2-3hours to restore it,
I will seee next week to make it done.
So far, @xEnVrE @damianomal told me that they dont use the grasping recently, so I will do it later.

**Comment by julijenv** [comment]
it has been restored the thumb proximal cable.
|IITCODE|Qta|Description|
|---|---|---|
|1895|1m|carlstahl 0.63mm|
thx to @xEnVrE , the commit has been put in robots-configuration correctly
