### ISSUE TITLE
Left arm CAN problem

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#920]
## Brief description of the request/failure

When running the ``yarprobotinterface``, the logger is filled with messages like 
```
173062	485.527100	ERROR	 from BOARD 10.0.1.24 (left_arm-eb24-j4_7), src CAN1, adr 0, time 53s 466m 108u: (code 0x00000019, par16 0x0b01 par64 0x0000000000000000) -> SYS: EOtheCANservice could not tx frames on CAN bus. In par16 there is: on msb the size of txfifo, on lsb a code. + .
```

In addition, the left wrist pronosupination moves much slower than usual.

## Detailed context
It can be noticed by simply running the ``yarprobotinterface``. In addition, from the ``yarpmotorgui`` the left wrist pronosupination barely moves.

## Accompanying material

cc @GiulioRomualdi @MiladShafiee @julijenv

**Comment by julijenv** [comment]
Hi @S-Dafarra ,
Could you please send an entire log-file and not only the first ERROR message displayed you found.
unfortunately, the ERROR message that you quoted is related to skin patches-boards and not to controlling board itself.
please add the absolute entire log=file when next time the pronosuppination don't work,\thx in advance

**Comment by S-Dafarra** [comment]
Hi @julijenv, you are absolutely right. Indeed, the problem was that the logger was filled with basically only that message and quickly saturate, hence we were not able to see any new error. 

How can we mute that error?

**Comment by julijenv** [comment]
Hi @S-Dafarra , just remove the skin from the left arm inside  icub_all-wbd.xml

**Comment by S-Dafarra** [comment]
I would keep it open for the time being.
