### ISSUE TITLE
Torso yaw cable broken

### ISSUE THREAD

**Issue by dariopasquali** [robotology/icub-tech-support#922]
CIao @julijenv ,

We just broke the yaw cable of the torso (attached pictures).
It happened during a normal startup, no weird movements.

The problem is that me, Giulia and Elena have to make experiments in this and the next week.
So few questions:
* We never replaced that cable, and we don't have a spare one. is it simple enough to repair it by myself if I came to take the cable? Can you teach me?
* Otherwise, could you come here asap (like tomorrow) and fix it?

Thank you,
Dario

![IMG_20200212_134637](https://user-images.githubusercontent.com/11158169/74336486-a06eaa00-4d9e-11ea-9bf7-4f2bc82bc560.jpg)
![IMG_20200212_124312](https://user-images.githubusercontent.com/11158169/74336491-a2386d80-4d9e-11ea-94a4-82b886c751de.jpg)
![IMG_20200212_124332](https://user-images.githubusercontent.com/11158169/74336494-a3699a80-4d9e-11ea-9625-e4bb9f995163.jpg)

**Comment by julijenv** [comment]
Ciao @dariopasquali,
Here is the link to get the documentation on how to repair iCub
https://icub-tech-iit.github.io/documentation/mkdocs/tendons_icub/site/waist_legs/
You need cable 13 to proceed with this guide.
Or else I pass by tomorrow morning before going to IIT sanqui

**Comment by dariopasquali** [comment]
Ciao @julijenv ,
thank you!
If you can come here tomorrow morning would be perfect! This way I can also learn directly from you.
if you are not in sanqui we can go there and take the cable.

Let me know.
Thank you again.
Dario

**Comment by pattacini** [comment]
@dariopasquali @julijenv I'm assuming this is `iCubGenova03`.
Amend the title as well as the label if this info is not correct.

**Comment by pattacini** [comment]
@dariopasquali I've just invited to join Robotology org as a member 😉

**Comment by julijenv** [comment]
it has been taken from the warehouse

|IITCODE |Qta |DEscription|
|:--:|:--:|:--:|
|4770.1 |1 |WAIST TOP CABLE 13|
