### ISSUE TITLE
Right-hand thumb skin sensors are not working iCubChemnitz

### ISSUE THREAD

**Issue by johnnass** [robotology/icub-tech-support#923]
## Brief description of the request/failure

Right-hand thumb skin sensors are not working

## Detailed context
We have received the robot (right arm and head) last week. During the testing, we found that the thump fingertip is not sensitive at all. In addition, we found that the little finger is much less sensitive than the other remaining fingers. 

We tried to adjust the threshold "th" in the configuration file right_hand_V2.ini but that makes no change. 

## Accompanying material

![Screenshot from 2020-02-19 15-32-03](https://user-images.githubusercontent.com/8449029/74846556-eee8ef00-5330-11ea-96f2-08f5c7104893.png)
![Screenshot from 2020-02-19 15-26-08](https://user-images.githubusercontent.com/8449029/74846559-f01a1c00-5330-11ea-952a-d5f6f29aeab6.png)

**Comment by julijenv** [comment]
Dear @johnnass ,
I think the problem on the thumb is quite simple, during the transportation, I guess that the little chip here above the knuckle beneath the dorso cover just get unplugged.
But first you need to remove the dorso cover this way
![image](https://user-images.githubusercontent.com/7140395/74848211-bf89b080-5337-11ea-9476-e99edd38cfcc.png)
And replace this little chip
![chip_unplugged](https://user-images.githubusercontent.com/7140395/74848298-d29c8080-5337-11ea-9e0a-14eb00a6996e.png)
For the non-perfect gain on every finger unfortunately I didn't really noticed it when testing it, I gonna try to fetch you some information about the possibility or not to increase the gain and let you know.
