### ISSUE TITLE
Restore original fingertips and top cover of left hand of iCubGenova01

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#924]
## Brief description of the request
After a f2f discussion with @pattacini and considering that the VVV20 school is approaching, I think we should restore the original fingertips and the top cover of the left hand of `iCubGenova01`.

As regards the fingertips, even if some of them might be working (we did not test all of them), they were mounted temporarily and the wire connecting them are exposed and can be easily damaged during an experiment.

Restoring the original cover is very easy and I can also take care of it if the proper screwdriver is available.

![](https://user-images.githubusercontent.com/6014499/68677553-91d4e480-055c-11ea-90e9-3503dca00218.jpg)

cc @pattacini @lornat75 @julijenv @simeonedussoni

**Comment by pattacini** [comment]
@simeonedussoni @julijenv can we plan some time next week to restore the old functionalities?
We shall be quick as Blacky will be leaving to attend VVV20 quite soon.

**Comment by julijenv** [comment]
it is quite simple and fast @pa, @xEnVrE  1 hour max

**Comment by xEnVrE** [comment]
Closing as both the cover and the fingertips have been restored.

Thanks @julijenv.

**Comment by julijenv** [comment]
the fingertips were replaced and tested with @xEnVrE , they look they work alright.
