### ISSUE TITLE
Green icub left shoulder cable broken

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#929]
## Brief description of the failure
While performing retargering experiments, at the startup of the experiment the robot (on the pole) did an unexpected fast motion hitting with the arm and torso.
Luckily, despite scaring crack noise, at the moment it looks like only the shoulder brake, plus we found a finger piece on the ground (shown in the picture below), but not sure if it comes from this failure since all the fingers cover seems to be fine

## Accompanying material
![photo5960623676191781680](https://user-images.githubusercontent.com/35487806/75359041-15200900-58b4-11ea-92ce-8662d7d3ca12.jpg)
![photo5960623676191781679](https://user-images.githubusercontent.com/35487806/75359117-37198b80-58b4-11ea-8d0f-341c10dc8c4d.jpg)

CC @julijenv @Yeshasvitvs

**Comment by lrapetti** [comment]
I tried to run the `yarprobotinterface` without the left arm and it started correctly, so no other joint is damaged.

**Comment by julijenv** [comment]
it has been used the following pieces to restore the robot
|IITCODE|Ver.|Qta |DEscription|
|--|--|--|--|
|4759|1|1|Shoulder rotation cable 2|
|4764|2|1|Shoulder rotation cable 7|
|4682|A1|1|AEA cover wrist|
