### ISSUE TITLE
Green iCub fingers broken

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#930]
## Brief description of the request
Some of the finger of ICub green appears to be broken or not properly working and should be checked.
In particular the following have been reported:
- [x] l_little_finger broken
- [ ] r_hand_finger and r_little_finger going in hardware fault
- [ ] a temporary fix is present on the RIGHT hand as shown in the picture below
 
## Accompanying material
![photo5962875476005466695](https://user-images.githubusercontent.com/35487806/75437438-7b5d6800-5956-11ea-9478-1b5f497c3140.jpg)

**Comment by violadelbono** [comment]
Hi @lrapetti,

The distal joint of ring and little fingers of the left hand has been restored.

The cable was taken from warehouse:
|IITCODE|Ver.|Qta |Description|
|--|--|--|--|
|2391||2x40cm|Stainless steel microcable, cable construction 7x19mm, nom. dia 0.45mm, outer dia 0.61mm, Polyamide coated, AISI 316||

The figertips cables were also damaged, so we re-welded and put some glue.
We didn't remove the tape on the other hand for now.
