### ISSUE TITLE
R1: Error on BOARD EB10 when launching yarprobotinterface

### ISSUE THREAD

**Issue by miccol** [robotology/icub-tech-support#931]
## Brief description of the request/failure
The yarprobotinterface cannot be launched.

## Detailed context
When running the yarprobotinterface on the R1 robot we get the error in the figure below.
We tried to powerloop several times but the problem is still there

## Accompanying material

![image](https://user-images.githubusercontent.com/8132627/75449937-347b6c80-596e-11ea-88a5-c449ce3d9b8d.png)

**Comment by miccol** [comment]
@safoex

**Comment by julijenv** [comment]
Hi @miccol , what did you do with the neck?!?!?!?

**Comment by julijenv** [comment]
The MC4-PLUS board was found not correctl funxtionning, after deeper investigation it looks like the board was dead in some part.
I substitued the board and everything went back to normal.

it has been taken from the warehous ethe following piece to restore the R1 robot
|IITCODE|Ver.|Qta|description|
|--|--|--|--|
|5443|D|1|MC4-PLUs|

**Comment by vtikha** [comment]
Thank you @julijenv

**Comment by miccol** [comment]
Thank you for the quick fix @julijenv !
