### ISSUE TITLE
iCubGenova02 bad general loose conditions 

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-tech-support#932]
## Brief description of the request/failure
We started working on the robot and preliminary qualitative checks clearly show that the robot is in a bad general mechanical conditions - see videos below. Unfortunately, we cannot upload videos with sounds, that would have helped understand also the general situation 

## Accompanying material

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/5045846/75524666-a4d9ca80-5a0e-11ea-8e24-20eca9bc07cd.gif)
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/5045846/75524674-aacfab80-5a0e-11ea-89ff-e5920fc72b8c.gif)
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/5045846/75524679-ac00d880-5a0e-11ea-94c6-5d0cba3b3a6f.gif)
![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/5045846/75524808-eb2f2980-5a0e-11ea-89a9-9b554a99df58.gif)
![ezgif-7-e41c0cf4b4a9](https://user-images.githubusercontent.com/5045846/75526576-562e2f80-5a12-11ea-97dd-a931c0f69d13.gif)

Also, the robot fine calibration seems bad - torso in (0,0,0) looks like 

![IMAGE 2020-02-28 10:08:26](https://user-images.githubusercontent.com/5045846/75526626-6b0ac300-5a12-11ea-89d9-8d9db2fd478b.jpg)

CC
@julijenv @S-Dafarra @lrapetti @marco-monforte  @ChiaraBartolozzi

**Comment by traversaro** [comment]
> Unfortunately, we cannot upload videos with sounds, 

Small note: you can attach arbitrary file size by compressing them in a `.zip` .

**Comment by julijenv** [comment]
Hi @traversaro , @DanielePucci  and @lrapetti ,
I just finish to reense everything that I could do on the fly, before @lrapetti start using it.
the left arm needed clearly to get a tiny tensing.
I will need to get the robot for more time to be able to adjust the overall situation

**Comment by violadelbono** [comment]
Hello guys,

The cables of the torso, legs and arms were tensed.
The fine calibration of the torso was corrected (there was an offset of about 1.8 deg in joint 1)

**Comment by marco-monforte** [comment]
Thanks @violadelbono !

What is missing is only the head then, which is more complicated to tense.
In the next weeks, the robot is needed (at least) by Giulia D'Angelo for some experiments, so we might go back to this once the robot won't be used.

@DanielePucci @traversaro @lrapetti feel free to close the issue :+1:

**Comment by lrapetti** [comment]
Great, thank you @violadelbono and @marco-monforte!

**Comment by DanielePucci** [comment]
CC @Uboldi80 @gsisinna @GiacomoVassallo13 we are having a [similar head issue](https://user-images.githubusercontent.com/5045846/75526576-562e2f80-5a12-11ea-97dd-a931c0f69d13.gif) on iCub 3, it would be nice to discuss about this before opening a specific issue for iCub 3 head
