### ISSUE TITLE
Broken eye tilt belt

### ISSUE THREAD

**Issue by loreucci** [robotology/icub-tech-support#935]
## Brief description of the request/failure
The belt for the eye tilt broke (iCubPisa01) and we have no more spares. We tried searching for a replacement from [http://wiki.icub.org/wiki/Springs,_belts_and_cables](http://wiki.icub.org/wiki/Springs,_belts_and_cables) but it seems that the code for that specific belt is no longer available from the manufacturer website. Do you have a new code or a different supplier from which we could get the spare part?

**Comment by julijenv** [comment]
Hi @loreucci ,
thx to @salvi-mattia, we found out the old correct code for this specific belt.
**53.6MXL025**
![image](https://user-images.githubusercontent.com/7140395/76517285-53ddc380-645d-11ea-94fb-1ee8c05e54f6.png)
![image](https://user-images.githubusercontent.com/7140395/76518592-ad46f200-645f-11ea-912c-8e39f51007a3.png)

we double check and I sent a mail to sitspa our provider and ask if it is still available. It is a belt that has to be done on demand unfortunately, so I dont know exactely what will be the price for it.
let you know

**Comment by julijenv** [comment]
Hi @loreucci ,
 Here what I received for the requested belt from the supplier sitspa italy
[Offer-166625.pdf](https://github.com/robotology/icub-tech-support/files/4621363/Offer-166625.pdf)
the only bad part of it , is that you need to order at least 30 pieces of it.
let me know
