### ISSUE TITLE
iCub power connection question

### ISSUE THREAD

**Issue by iPsych** [robotology/icub-tech-support#936]
Dear all,

I set up two PSU and trying to connect them.
Is there any visualized guideline or instruction for connecting 48V and 12V cables?

Also I am afraid I don't have any information about DB15 cable. What does it for?

Below I attach the photos. of the cables : )

![IMG_3736](https://user-images.githubusercontent.com/28276515/79547272-a2baf080-80ce-11ea-8d17-5d4366243f05.JPG)
![IMG_4776](https://user-images.githubusercontent.com/28276515/79547285-a5b5e100-80ce-11ea-86f3-42bc4917b69a.JPG)

**Comment by julijenv** [comment]
Dear, @iPsych ,
I see that you perfectly found the documentation for the Harness of the cable but it seems that you didnt find the one for the connection for the power supply, here it is.
[6486_ExtPowerCable_3.0.1.pdf](https://github.com/robotology/icub-tech-support/files/4504065/6486_ExtPowerCable_3.0.1.pdf)
To be faster \:
both yellow ring labelled *12V* are connected to the positive pin of the 12V power Supply and the black one to GND (negative pin of the 12V power supply)
![image](https://user-images.githubusercontent.com/7140395/79763610-992ac600-8324-11ea-9c2d-2ec70012e9d7.png)
Th 2 red ring labelled *48V* are connected to the positive pin of the 48V power Supply and the 2 black ones to GND (negative pin of the48V power supply)
![image](https://user-images.githubusercontent.com/7140395/79763361-45b87800-8324-11ea-8939-273abf31c5fb.png)
Moreover you have a black wire (with the Heart symbol) which connect both GND of the 2 power supplies.
THe DB15 needs to be connected in the bak of the power supply 48V
![image](https://user-images.githubusercontent.com/7140395/79763986-10f8f080-8325-11ea-84ac-67120dc0a647.png)

Hope it is clear, let us know

**Comment by iPsych** [comment]
@julijenv Thanks so much!
It's more than clear explanation!
By the way, the red marked connector in last picture, is it standard one? If so, would you let me know the connector name?
Some strange events happened to the PSU in icub-Seoul01, and we don't have the connector...

**Comment by julijenv** [comment]
Hi @iPsych , which connector are you talking about? the power cord in between the mural socket and the power supply??? or one of the provided by IIT to make connection in between power supply to power supply or power supplies to iCub???
let me know.
if it is about the power cord you can find easily some spare parts on RS components or Farnell, I've done that when I was for a month in Japan for iCubOsaka01.

**Comment by iPsych** [comment]
![IMG_1105](https://user-images.githubusercontent.com/28276515/79839506-8f21c980-83ef-11ea-9abb-b98deebd6758.JPG)
The DB15 cable, connected to 12V parts.

**Comment by julijenv** [comment]
Hi @iPsych , I see that you have the DB15, so I guess you are missing the 2 wires connected the DB15 and the power supply 12V? Am I right?

**Comment by iPsych** [comment]
![KakaoTalk_Photo_2020-04-21-16-55-04](https://user-images.gihubusercontent.com/28276515/79840475-eaa08700-83f0-11ea-93e7-69ecad5e033e.jpeg)
Hi, @julijenv, I meant the yellow marked connector. : )

**Comment by julijenv** [comment]
Hi @iPsych , coul you take a picture of the back of the 2 power supplies please? thx in advance

**Comment by iPsych** [comment]
![KakaoTalk_Photo_2020-04-21-17-17-31](https://user-images.githubusercontent.com/28276515/79842588-ffcae500-83f3-11ea-835c-1a4c2a6bf15b.jpeg)
@julijenv Here it is : )

**Comment by julijenv** [comment]
Hi @iPsych , could you please try to fetch me on skype please my skypei ID is icub.support

**Comment by julijenv** [comment]
Hi @iPsych ,
could you please attache the final resault of the wring of the back side of the power supplies, thx in advance

**Comment by iPsych** [comment]
@julijenv Sure : )
The upper one is 12V and the lower one is 40V.
![IMG_5958](https://user-images.githubusercontent.com/28276515/80111688-26874800-85bb-11ea-8a90-6e7996a16344.JPG)
![IMG_8414](https://user-images.githubusercontent.com/28276515/80111695-29823880-85bb-11ea-9638-2bdbfcb3039a.JPG)
![IMG_3000](https://user-images.githubusercontent.com/28276515/80111696-2b4bfc00-85bb-11ea-9f3b-aea3ce91c083.JPG)
![IMG_5758](https://user-images.githubusercontent.com/28276515/80111707-2dae5600-85bb-11ea-881f-7f6398f223ed.JPG)

**Comment by julijenv** [comment]
Everything looks connected as it should.
