### ISSUE TITLE
Right foot is not fixed to the joint and has some clearance

### ISSUE THREAD

**Issue by MiladShafiee** [robotology/icub-tech-support#943]
## Brief description of the request/failure
During the walking of the `iCubGenova04` there is some impact with the ground that it seems some part of that is because of the clearance of the right foot.

## Detailed context
It seems the right foot of the iCub green is not completely fixed and has some clearance.

**Comment by julijenv** [comment]
we (@violadelbono and I)( retightened some screws. It is now ready
