### ISSUE TITLE
iCubGenova02 hip problems

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#945]
## Brief description of the request/failure
We are experiencing some problem affecting the right/left hip motors of the iCubGenova02 robot.
In particular we are experiencing:
- suspicious motion on both right/left in hip abduction/adduction directions when the robot is in position control.
- on the right hip flexion/extension we hear and feel something obstructing the motion of the motor (by putting the motor in idle). This problem in particular seems to be quite important.

The issue has been discussed and verified with @julijenv and @violadelbono.

**Comment by lrapetti** [comment]
CC @marco-monforte @GiuliaDAngelo

We are planning to fix it on Thursday and require quite some work, let us know if you (or any other `iCubGenova02` user you are aware of) might need the robot that day.

**Comment by marco-monforte** [comment]
At the moment, no one needs it on Thursday. We will update you if something changes, but I don't think it will happen 👍

**Comment by violadelbono** [comment]
Good morning ☕ 

Today @julijenv and I are still in Erzelli so won't be able to fix the robot.
We will re-book the maintenance.

**Comment by julijenv** [comment]
@marco-monforte , @GiuliaDAngelo , @lrapetti , I was not able to cancel the reservation for today.
Feel free to use it today, sorry for this.

**Comment by julijenv** [comment]
sorry guys, we will need to work one more time in Erzelli tomorrow and I fear I wont make it to the repair. So I prefer post pone for in 2 weeks as next week Im not there in IIT

**Comment by violadelbono** [comment]
Guys,
I just booked the robot for this afternoon for the fixing.

**Comment by violadelbono** [comment]
Ciao everyone,

The reason behind the obstruction and the noise of the right hip was a damaged ball bearing, and probably some of the spheres detached and blocked the pulleys movement.

We replaced the following ball bearing:

|IITCODE|Ver.|Qta |DEscription|
|--|--|--|--|
|3045||1|Rad. ball bearing 1Row. 7X14X4 - SKF CODE 618/7     ||

![image](https://user-images.githubusercontent.com/61685519/85385307-6f6b6680-b542-11ea-8052-9a7ac7734467.png)

After launching again the robot the right hip is correctly working and it stays in position.
Now it's ready to go.
