### ISSUE TITLE
both hands + left forearm skintaxels not working with old MTB

### ISSUE THREAD

**Issue by 2103simon** [robotology/icub-tech-support#949]
## Brief description of the request/failure
Taxel read out not possible. No response from the skin taxels at the fingers, thumbs and palm of both hands. Read-out with the new MTB (event-driven) works on the right hand for thumb and palm, but NOT for the fingers) .

## Detailed context
I noticed that the blue LED at the forearm not blinking, but constant shining (see attached pictures). 

## Accompanying material
![20200626_093424_HDR](https://user-images.githubusercontent.com/60852381/85848923-56fd8500-b7aa-11ea-908d-9f71317b177b.jpg)
![20200626_093320_HDR](https://user-images.githubusercontent.com/60852381/85848940-5b29a280-b7aa-11ea-84da-998cce4794ec.jpg)

**Comment by julijenv** [comment]
Hi @2103simon , R U sure that you did not confuse your right with the right or the robot??
from my knowledge the event-driven skin is on the LEFT arm not the RIGHT....

**Comment by 2103simon** [comment]
Your right, the event-driven skin is on the left, but the sample based one is not working on non of the sides...

**Comment by violadelbono** [comment]
Hi Simon,

- Right arm: the hand had some detached cables and there was also some glue blob that we removed. We also re-crimped some skin connections. Now fully working

- Left arm: it is now working without the forearm skin, we will investigate the problem on Monday. Probably some loose connections

**Comment by 2103simon** [comment]
Oh super! You did great work! Thanks a lot :)
The forearm is not of interest for me, it was just mentioned because I realized it too.
Thanks again!

**Comment by violadelbono** [comment]
Hello @2103simon, FYI:

The skin chain (upper arm + forearm + hand) of the left arm does not work. The single components work alone, meaning that there is not enough power to make the whole skin of the arm function. This problem could be due to the fact that the skin is old and damaged.

As a solution, we deactivated the upper patch of the forearm, so now the hand, lower forearm and upper-arm skin is fully working.

**Comment by 2103simon** [comment]
Hi @violadelbono ,
These are good news! Not that the hole chain is not working, but that the hand works when upper arm skin is unplugged is fine for me! 
I will be at IIT on Wednesday again to check it personally. If it is ok for you, I would give a feedback when I've get an impression on my own :)

**Comment by violadelbono** [comment]
Perfect! If everything will be ok feel free to close this issue
