### ISSUE TITLE
Right leg don't work，Calibrator reports errors

### ISSUE THREAD

**Issue by andy200712** [robotology/icub-tech-support#951]
iCub No.041
## Brief description of the request/failure

icub's right leg is out of control after run yarprobotinterface . When starting yarprobotinterface, yarp logger reported two errors:
1 Right leg Calibrator: checkGoneToZeroThreshold: joint 2 Timeout while going to zero
2 Right leg Calibrator: set1 :some axis got timeout while reaching zero position... disabling this set of axes

And then , when the yoga demo runs, the right leg don't move.

## Detailed context
When starting yarprobotinterface, yarp logger reported two errors:
1 Right leg Calibrator: checkGoneToZeroThreshold: joint 2 Timeout while going to zero
2 Right leg Calibrator: set1 :some axis got timeout while reaching zero position... disabling this set of axes

## Accompanying material

[yarprunlog_29_06_2020_15_30_05.log](https://github.com/robotology/icub-tech-support/files/4845833/yarprunlog_29_06_2020_15_30_05.log)
[log_icub-head_yarprobotinterface_1314.log](https://github.com/robotology/icub-tech-support/files/4845834/log_icub-head_yarprobotinterface_1314.log)
[log_icubsrv_demoYoga_5378.log](https://github.com/robotology/icub-tech-support/files/4845835/log_icubsrv_demoYoga_5378.log)

**Comment by julijenv** [comment]
At the oment nothing really clear is visible, moving by hand the leg, succeed to make it work perfectly finea s before.
Let's wait another failure to rise a real failure
