### ISSUE TITLE
iCubGenova02 torso not tensed

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#952]
## Brief description of the request/failure
As observed today with @julijenv, the torso cable seems not to be much tense. As result the following behaviour is observed when the robot is position controlled

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35487806/86038556-69ddb700-ba41-11ea-91d2-7486c9f09a53.gif)

**Comment by julijenv** [comment]
done by @violadelbono
