### ISSUE TITLE
iCubGenova03 - right hand little fingers not moving

### ISSUE THREAD

**Issue by dariopasquali** [robotology/icub-tech-support#953]
Hi @julijenv,
After your intervention of issue #939 we noticed a new issue with iCubGenova03 right-hand little fingers.

The pinky&ring fingers of right hand do not move.
The motor just spins empty without moving them.

I checked from `yarpmotorgui` and the encoder works fine.
So, I suppose it is a broken cable.

**Comment by julijenv** [comment]
Hi @dariopasquali ,
from what I recall you had the chance to undergo a little training for repairing distal joint.
That could be the right moment for you to try if you remember something about it.
btw we have already a website about restoring disal joint that you can refresh your memories with.
here is the link:
https://icub-tech-iit.github.io/documentation/icub_tendons/lower_arm_V2/#ring-and-pinkie

**Comment by violadelbono** [comment]
Cables of little and ring fingers were broken and have been repaired.
The proximal thumb was also broken and has been replaced.
