### ISSUE TITLE
Green icub left shoulder cable broken

### ISSUE THREAD

**Issue by MiladShafiee** [robotology/icub-tech-support#955]
## Brief description of the request/failure
While performing the push recovery test I broke the left shoulder cable.

**Comment by violadelbono** [comment]
Hi @MiladShafiee 

Cable 6 of left shoulder was replaced. You can now use the robot.

Taken from the warehouse:
| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| 4763.1 |  1  | SHOULDER ELEVATION CABLE 6| Alias:RC_IIT_019_G_006|
