### ISSUE TITLE
iCubGenova02: right shoulder cable broken

### ISSUE THREAD

**Issue by lunagava** [robotology/icub-tech-support#957]
## Description of the request/failure

Ciao,
I'm sorry but I just broke the purple iCub right shoulder cable moving the joint close to one of its limits during some experiments.

Should be the "shoulder rotation cable N1".

## Accompanying material

![IMG_4131](https://user-images.githubusercontent.com/45895918/87156852-a15c2700-c2bd-11ea-8b30-393780652967.jpg)

**Comment by violadelbono** [comment]
Hi @lunagava 

There were actually two broken tendons:  # 2 and # 7. 
They were taken from the warehouse and replaced:

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| 4759 | 1 | 	SHOULDER ROTATION CABLE 2 |  |
| 4764 | 1  | SHOULDER ROTATION CABLE 7 |  |

We also noticed some friction in the block of pulleys in the shoulder and added grease.
The robot is now functional and ready to be used.

**Comment by lunagava** [comment]
Hi @violadelbono. 
Thank you for your early intervation. I am glad that iCub is ready to be used.
