### ISSUE TITLE
Replacement of a plastic lever in the blinking system

### ISSUE THREAD

**Issue by carlomazzola** [robotology/icub-tech-support#959]
## Brief description of the request/failure
iCubGenova03: break of the plastic lever connected to the servomotor mechanism of blinkers

## Detailed context
In the front cover of iCub's head the plastic lever that connects blinkers to their motor is broken. We need a spare part of it for the replacement. It broke while blinking because the cover had been attached so that it touched some points of the blinking system. 

## Accompanying material

![blinker mechanism](https://user-images.githubusercontent.com/57671432/87402330-aec62980-c5bb-11ea-8276-933b5897fbb8.jpg)
![piece of the plastic lever](https://user-images.githubusercontent.com/57671432/87402334-b08fed00-c5bb-11ea-9ce2-a03facd57259.jpg)

**Comment by julijenv** [comment]
Hi @carlomazzola ,
I have the piece you reuested, I will mount it next time i'll come to you guys.
Just please remind me about it.
I will let you know some days before when we shulld be passing by.

**Comment by carlomazzola** [comment]
Hi @julijenv ,
Perfect! Thank you very much!
I'll remind you about that
Bye!

**Comment by violadelbono** [comment]
Hello @carlomazzola,

The piece was substituted.
Let us know if it will need some adjustments.

**Comment by julijenv** [comment]
still waitng to get a feedback from you guys.
@carlomazzola

**Comment by carlomazzola** [comment]
Hello, sorry if I have been late.
Actually, I couldn't try the eyelids system because we think the cover of
the face needs to be a bit adjusted: it is old and it seems that the
plastic has been altered a bit over time. If I would try the system now, it
is highly probable that it will break again.
As soon as we try it, I will let you know.
Sorry again and thank you!
Carlo

Il giorno lun 31 ago 2020 alle ore 16:34 julien jenvrin <
notifications@github.com> ha scritto:

**Comment by julijenv** [comment]
Hi @carlomazzola ,
working or not?
let us nkow
if yes please close the issue.
thx in advance

**Comment by carlomazzola** [comment]
Hi Julien,
I will check as soon as I will come back to Erzelli, and I will let you
know,
sorry,
Carlo

Il giorno lun 12 ott 2020 alle ore 09:51 julien jenvrin <
notifications@github.com> ha scritto:

**Comment by carlomazzola** [comment]
Hi @julijenv , 
I checked and everything is ok, thank you!
Carlo
