### ISSUE TITLE
Right arm wrist pitch and yaw joints does not run 

### ISSUE THREAD

**Issue by MiladShafiee** [robotology/icub-tech-support#961]
## Brief description of the request/failure
The right arm wrist pitch and yaw joint does not run and also the idle mode does not work(when I try to put in idle mode with motor gui)

## Detailed context
There is a hardware fault in right arm wrist pitch and yaw joints.

## Accompanying material

[log_icub-head_yarprobotinterface_1560-right-arm-wrist-pitch-yaw.txt](https://github.com/robotology/icub-tech-support/files/4920723/log_icub-head_yarprobotinterface_1560-right-arm-wrist-pitch-yaw.txt)

**Comment by S-Dafarra** [comment]
The error seems related to #960. In addition, the neck joints go often in hardware fault with the same message of #960

**Comment by julijenv** [comment]
It has been checked the movement after having found one screw missing, fixing the palm and checked the 2 AEA encoders, it seems ok to me, let me know
