### ISSUE TITLE
R1-mk2 - right arm error when running yarprobotinterface 

### ISSUE THREAD

**Issue by Arya07** [robotology/icub-tech-support#963]
## Brief description of the request/failure
When launching the yarprobotinterface on R1-mk2 we get errors for two boards of the right arm.

## Detailed context
The log of the error is reported below. Even if with this error, after a longer initialization than usual, the yarprobotinterface succeeds to start. However the same error recurs in the log. The fault button was not pressed.

## Accompanying material

![Screenshot from 2020-07-15 18-16-17](https://user-images.githubusercontent.com/3706242/87571448-5df12680-c6ca-11ea-84f5-1dc34d286723.png)

**Comment by julijenv** [comment]
Hi @Arya07 , 
it seems that the fault cable is disconnected.
Next time please attach the entire log file as attachments.

**Comment by julijenv** [comment]
Hi @Arya07 ,
it has been found as expected a FAULT wire broken, a bit hidden a tedious to foud but we made it to restore the robot.

**Comment by Arya07** [comment]
Grazie mille!!
