### ISSUE TITLE
Left shoulder cable broken

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#966]
## Brief description of the request/failure
While doing some tests for https://github.com/dic-iit/lab-events-demos/issues/146, one or two cables of the left shoulder broke

## Accompanying material

cc @violadelbono @julijenv @kouroshD @Yeshasvitvs

**Comment by violadelbono** [comment]
Hello @S-Dafarra,

The broken cable was # 8 and it has been replaced.
The following was taken from the warehouse:

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| 13737 | 1  | SHOULDER ROTATION CABLE 8, U7191215/SE000094 - 121mm - cyl. nipple AM420716/NI000007 - ball nipple KU000012 |  |

**Comment by DanielePucci** [comment]
The cable N.8 broke again. See https://github.com/dic-iit/lab-events-demos/issues/146#issuecomment-662563328

**Comment by julijenv** [comment]
Hello @S-Dafarra, @DanielePucci ,

The broken cable was # 8 and it has been replaced one more time.
The following was taken from the warehouse:

| Item / IITCODE | ver|Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|:---|
| 4765 |2| 1  | SHOULDER ROTATION CABLE 8 |  |
