### ISSUE TITLE
iCubErzelli01: Hip capacitor

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#968]
## Brief description of the request/failure
The capacitor needs to be fixed to the plastic cover.

## Accompanying material
![_20200730_164129](https://user-images.githubusercontent.com/3440640/88936892-b526f780-d283-11ea-8b38-5206a9008d0a.JPG)

**Comment by julijenv** [comment]
it has been given to the 2 pieces and next time I pass by to ERzelli I will attach everything.
I dont remember if i already attach or not the pieces.
@ddetommaso , you can double check please , thx?

**Comment by ddetommaso** [comment]
Hi @julijenv 

I confirm you that we have the pieces but they are still not mounted.

**Comment by violadelbono** [comment]
The new capacitor supports have been mounted on 13/10.
I close the issue.
