### ISSUE TITLE
iCubErzelli01: yarprobotinterface doesn't start cause Bosh IMU fails

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#970]
After updating PC104 software and boards firmware, yarprobotinterface stopped working.
The yarprobotinterface starts correctly when Inertial Sensors section is commented.

## Detailed context

**PC104 OS**
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

**SW Distro:** 
2020.02.feat-01
## Accompanying material
[log_pc104_yarprobotinterface_4582.txt](https://github.com/robotology/icub-tech-support/files/5033472/log_pc104_yarprobotinterface_4582.txt)

**Comment by julijenv** [comment]
Hi @ddetommaso , this isssue is still opened?
Unfortunately from the log file you sent me, i cant figure out what's going wrong. Let me know

**Comment by ddetommaso** [comment]
Hi @julijenv 

please attached you can find a recent logfile using default icub_all.xml configuration.
[log_icub-head_yarprobotinterface_1823.txt](https://github.com/robotology/icub-tech-support/files/5223955/log_icub-head_yarprobotinterface_1823.txt)

**Comment by julijenv** [comment]
Hi @ddetommaso ,

> 638 2.547453 <ERROR> 2 of 4: wrong eobrd_foc BOARD 10.0.1.6:CAN1:2 because it has:  WRONG APPLICATION VERSION  
> 639 2.547461 <ERROR> 4 of 4: wrong eobrd_foc BOARD 10.0.1.6:CAN1:4 because it has:  WRONG APPLICATION VERSION 

I guess you forgot to update the 2_FOC boards.
did you try again to update?

**Comment by violadelbono** [comment]
- 2FOC firmware was updated
- Skin boards firmware still needs an update

@ddetommaso let us know if you have any issues after updating

**Comment by ddetommaso** [comment]
Hi @violadelbono and @julijenv 

everything seems fine now! Thanks

**Comment by julijenv** [comment]
hi @ddetommaso ,
even the first start error due to imu bosch???
if yes please close the issue, thx in advance
