### ISSUE TITLE
iCubGenova02 - right wrist broken

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#973]
The yaw cable of the robot right wrist seems to be broken/loose, as it can be observed in the following picture
![photo5875358834380354420](https://user-images.githubusercontent.com/35487806/89796045-71f14200-db29-11ea-96c7-a00b4c0804db.jpg)
also the following piece was found
![photo5875358834380354421](https://user-images.githubusercontent.com/35487806/89796103-833a4e80-db29-11ea-8955-4bd7a27ea530.jpg)

cc @Yeshasvitvs

**Comment by violadelbono** [comment]
Hi @lrapetti 

The following broken cable of the wrist was replaced:

| IITCODE  |  QUANTITY | ALIAS  | DESCRIPTION  |
|---|---|---|---|
| 6419  |1   | RC_IIT_019_G_028  | WRIST V2 TENDON # 10 - 45mm  |

**Comment by lrapetti** [comment]
> Hi @lrapetti
> 
> The following broken cable of the wrist was replaced:

Great, thanks!
I think we can close the issue then.

**Comment by lrapetti** [comment]
It seems the cable was not the only problem, the wrist is not starting even after changing the cable. There might be a problem similar to what observed on the green (https://github.com/robotology/icub-tech-support/issues/972).

**Comment by marco-monforte** [comment]
Hi everyone! I confirm the motor shaft broken on the right side (like in the issue pointed by Lorenzo above) and I add the following issues on the left side:

- Calibration issue 

![20200825_164055](https://user-images.githubusercontent.com/32684998/91190931-d3eea180-e6fc-11ea-80cc-a92d65af6731.jpg)

- Thumb proximal cable broke

![20200825_164045](https://user-images.githubusercontent.com/32684998/91190939-d5b86500-e6fc-11ea-9760-c27c840c41c0.jpg)

- A pending capacitor from the back

![20200825_164131](https://user-images.githubusercontent.com/32684998/91190955-da7d1900-e6fc-11ea-916f-9d32c8c18ab0.jpg)

**Comment by violadelbono** [comment]
Yesterday the following cables of the left hand were fixed (and re-calibrated):

- Thumb proximal
- Ring and little fingers distal
- Middle distal

We also put a support for the capacitor.

List of items and quantity

| Item / IITCODE | Quantity |  Description |
|:---:|:---:|:---|
| 2035 . A2 | 1  | CAPACITOR HOLDING PLATE | 
| 1815 | 1m  | Stainless steel microcable, cable construction 7x7mm, nom. dia 0,63mm, not coated, AISI 316 | 
| 2391 | 1.5m | Stainless steel micro-cable, cable construction 7x19mm, nom. diameter 0.45mm, outer diameter 0.61mm, Polyamide coated, AISI 316 - CARL STAHL GMBH |

**Comment by Nicogene** [comment]
I don't know id it is related to known issues of `iCubGenova02`, but today `gravityCompensator` crashed as soon as was connected to `wholeBodyDynamics`, both using the imu in the rfe and the classic imu in the head.

I ran it with gdb and I got:

![immagine](https://user-images.githubusercontent.com/19152494/92740766-4ce92c80-f37e-11ea-8182-a0fc26378079.png)

cc @traversaro @pattacini

**Comment by julijenv** [comment]
The left arm wrist motor was broekn and has been repaired.
afteer having remounted everything I didnt notice anything.


IITCODE | Qta | S/N | Description 
-- | -- | -- | -- 
4471 | 1 | 1537 | 1331T012SR-IE2-400+14/1-159:1+2082,   Faulhaber - Brush motor, gear box, encoder with 500 mm cable length
