### ISSUE TITLE
icubosaka: YARP network does not seem to be available, is the yarp server available?

### ISSUE THREAD

**Issue by YANGGANG1971** [robotology/icub-tech-support#975]
After turning on icubsrv, icub01, icubVR2 and pc104,
run ./startYarpNetwork,sh on icubsrv.

When I type yarprun --server /icubo1 on icub01, there was something wrong as follows.
![WeChat Image_20200813184001](https://user-images.githubusercontent.com/55526431/90119375-73727280-dd94-11ea-84ef-ea3ee63b6279.jpg)

**Comment by pattacini** [comment]
Hi @YANGGANG1971 

From the terminal where you launched `yarprun`, what will you get if you type the following command?
```sh
$ yarp where
```

Likely, you will be notified that the YARP server is not found. Thus, give a look at the machine whose IP is displayed in the output of the above command and see there if something wrong is happening.

In case you've changed the machine where YARP server is supposed to be running, then you'd need to update the remaining machines by doing on each:
```sh
$ yarp conf --clean
$ yarp detect --write
```
Alternatively, the following couple of commands is also doable:
```sh
$ yarp conf --clean
$ yarp conf <IP> <port>
```
where _IP_ accounts for the IP of the YARP server host and _port_ should be 10000.

Hope this helps out.

**Comment by YANGGANG1971** [comment]
It works, thanks.

**Comment by YANGGANG1971** [comment]
It works, thanks.

**Comment by YANGGANG1971** [comment]
It works, thanks.

**Comment by YANGGANG1971** [comment]
It works, thanks.

**Comment by YANGGANG1971** [comment]
It works, thanks.

**Comment by YANGGANG1971** [comment]
It works, thanks.

**Comment by YANGGANG1971** [comment]
It works, thanks.

**Comment by YANGGANG1971** [comment]
It works, thanks.

**Comment by YANGGANG1971** [comment]
It works, thanks.

**Comment by YANGGANG1971** [comment]
It works, thanks.
