### ISSUE TITLE
error occuring during redBallDemo

### ISSUE THREAD

**Issue by julijenv** [robotology/icub-tech-support#976]
## Brief description of the request/failure
during the last 2 run on demoRedBall (it is a recurring issue seen into the previous robot as well), both arms fell for HW problem.
The problem is surely due to some delay inside the wholebodyDynamic and the FT sensor- Please try to find out the reason with the hel of the log file form yarprobotinterface e wholebodyDybanmic from those 2 runs 

## Detailed context

cc @pattacini , cc @marcoaccame , cc @Nicogene 
## Accompanying material

[log_icub-head_yarprobotinterface_crash_braccia_dopo 5 minuti.txt](https://github.com/robotology/icub-tech-support/files/5131048/log_icub-head_yarprobotinterface_crash_braccia_dopo.5.minuti.txt)
[log_icubsrv_wholeBodyDynamics_crash_braccia dopo 5 minuti.txt](https://github.com/robotology/icub-tech-support/files/5131050/log_icubsrv_wholeBodyDynamics_crash_braccia.dopo.5.minuti.txt)

[log_icub-head_yarprobotinterface_2_Virtual_analosensor.txt](https://github.com/robotology/icub-tech-support/files/5131046/log_icub-head_yarprobotinterface_2_Virtual_analosensor.txt)
[log_icubsrv_wholeBodyDynamics_2_die_Virtual_Analof FT.txt](https://github.com/robotology/icub-tech-support/files/5131049/log_icubsrv_wholeBodyDynamics_2_die_Virtual_Analof.FT.txt)

**Comment by pattacini** [comment]
@julijenv the problems you mentioned did have the following root and were corrected with the corresponding actions, so let's use this issue as a sort of FAQ/report for the future 😏

On one robot we discovered that the codebase was compiled in `Debug`; therefore the communication between the IMU and WBD was slowed down significantly causing timeout expirations. When WBD goes in timeout, it puts the torque-controlled limbs in protection (HW-fault) for safety reasons.

On the last robot you configured, instead, we found out that the RFE controller was hanging up during HW readouts. This triggered the WBD timeout as the RFE delivers IMU data. To fix this, @marcoaccame has recently devised a patch to the RFE FW.

Hope this report will help out.
