### ISSUE TITLE
The tactile sensors on both thumbs are malfunctioning

### ISSUE THREAD

**Issue by tKsome** [robotology/icub-tech-support#977]
## Detailed context
There was a problem with the tactile sensor of the thumb in the first few weeks. When the skin of the palm is touched, the tactile sensor of the thumb will always respond.

However, just now, I touched the palm of icub's left hand, and the tactile sensor of the thumb kept responding. Then I pressed the recalibration button and the tactile sensor of the thumb was reset.

After that, the tactile sensors of both thumbs were not working.

What is causing this? Is the wiring of the thumb's tactile sensor damaged?

**Comment by julijenv** [comment]
Hi @tKsome ,
could you try to record a video of the problem occurring because I can not figure out your problem so much.
Do you mean that when you are touching the palm, you got some SPIKES on the visualization of the skin at the level of the thumb OR the thumb got ENTIRELY enlighted?
if it is just some spikes (for sure you have some grounding issues) you can get rid off them by clicking on the button ON-OFF of the binarization filter onto the QtSkinManagerGui window.
let me know.

**Comment by tKsome** [comment]
[VID20200901201744.zip](https://github.com/robotology/icub-tech-support/files/5156115/VID20200901201744.zip)

**Comment by tKsome** [comment]
_Do you mean that when you are touching the palm, you got some SPIKES on the visualization of the skin at the level of the thumb OR the thumb got ENTIRELY enlighted?_

Yes, BUT just sometime.

_if it is just some spikes (for sure you have some grounding issues) you can get rid off them by clicking on the button ON-OFF of the binarization filter onto the QtSkinManagerGui window._


I think this has nothing to do with the binary filter, it should be a problem with the touch sensor of the thumb. But I don't know where the problem occurred. What makes me more puzzled is that the same problem occurred on the other hand at the same time.

**Comment by julijenv** [comment]
Hi @tKsome ,
could you please also record the problem in between the palm and thumb, because from your video it doesn't really match your interpretation of the situation?
thx in advance

**Comment by violadelbono** [comment]
Hi @tKsome 

Looking at your video we also suggest to take a look at the thumb chip inside the back of the hand and check if it is correctly in position. 

First remove the back cover by unscrewing the M2x6 screw:
![image](https://user-images.githubusercontent.com/61685519/91857833-c12e1c80-ec68-11ea-8de0-37eb1817fbbd.png)

![image](https://user-images.githubusercontent.com/61685519/91859151-609fdf00-ec6a-11ea-9c54-0cf6d7f48e87.png)

Let us know if this will solve the problem.

**Comment by tKsome** [comment]
> Hi @tKsome ,
> could you please also record the problem in between the palm and thumb, because from your video it doesn't really match your interpretation of the situation?
> thx in advance

emmmm.... 
The reaction of the tactile sensor of the thumb after touching the palm only happens sometimes, and I cannot guarantee that it will not happen.

**Comment by tKsome** [comment]
I opened the back cover and found the first chip protruding
![5b9ccfd2855325d91a80593ed1c5fb0](https://user-images.githubusercontent.com/28921533/91922101-ad81c500-ecff-11ea-90c1-decfc144eec8.jpg)
![5391d01a58a6d2be7b68896fa745f3a](https://user-images.githubusercontent.com/28921533/91922103-afe41f00-ecff-11ea-8f4a-1c3a9064eaf6.jpg)

**Comment by violadelbono** [comment]
Hello @tKsome 

Is the problem still occurring after having pressed the chip in its position? It should now make a proper contact.

**Comment by tKsome** [comment]
> Hello @tKsome
> 
> Is the problem still occurring after having pressed the chip in its position? It should now make a proper contact.

yes , it's work.

However, the back cover on the back of the hand will cause the chip to fall off. Can you send us the cad of the back cover? We redesign a more suitable back cover.

**Comment by violadelbono** [comment]
Hello @tKsome 

I suggest you to clone our public github CAD repository :https://github.com/icub-tech-iit/cad-mechanics-public

Then go into this path: cad-mechanics-public\projects\icub\icub1_icub2 and look for the part named RC_IIT_017_P_030

**Comment by tKsome** [comment]
> Hello @tKsome
> 
> I suggest you to clone our public github CAD repository :https://github.com/icub-tech-iit/cad-mechanics-public
> 
> Then go into this path: cad-mechanics-public\projects\icub\icub1_icub2 and look for the part named RC_IIT_017_P_030

OK, thanks.
