### ISSUE TITLE
Broken parts - iCubGenova01

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#978]
## Brief description of the request/failure

I found some pieces of the robot on the desk, as depicted in the following

![IMG_20200902_131231190](https://user-images.githubusercontent.com/6014499/91975163-44aa4500-ed1f-11ea-8d1d-09fa61370a28.jpg)

More in details:
- the finger nail is that of the right thumb finger(and is transparent instead of being white as all the others)
- the rubber ring is that of the left little finger
- the black piece belongs to the right leg (see figure below)

![IMG_20200902_131451234](https://user-images.githubusercontent.com/6014499/91975351-8e932b00-ed1f-11ea-8318-471bf4923249.jpg)

**Comment by violadelbono** [comment]
@xEnVrE  I removed the rubber ring from the left thumb because I needed to tense the cable 😄 
I will replace it soon

**Comment by xEnVrE** [comment]
> @xEnVrE I removed the rubber ring from the left thumb because I needed to tense the cable smile :smile:

@violadelbono sorry I didn't know it! I opened the issue just to avoid losing track of all these parts :smile:

**Comment by violadelbono** [comment]
The robot is now fixed:

- I glued the broken piece of the cover
- replaced the nail 

| IIT CODE  | ALIAS  | QUANTITY  | DESCRIPTION  | 
|---|---|---|---|
|  6187 . A3  | RC_IIT_012_P_058  | 1  |  FINGERNAIL (left and right) |  

- Tensed proximal thumb joint and thumb oppose of both hands

-  replaced all the rubber rings missing

**Comment by xEnVrE** [comment]
Thank you @violadelbono
