### ISSUE TITLE
iCubShenzhen01 - The thumb joint cable is loose

### ISSUE THREAD

**Issue by tKsome** [robotology/icub-tech-support#979]
## Brief description of the request/failure
There was a collision between the thumb and the index finger, which caused the cable of the thumb joint9 to loosen when retracted.  The motor calibration of the right thumb cannot be completed after restarting.

## Accompanying material

[icub_thumb_cable.zip](https://github.com/robotology/icub-tech-support/files/5207808/icub_thumb_cable.zip)

**Comment by tKsome** [comment]
hello???

The icub cable may be broken, but I am not sure if it is broken

**Comment by pattacini** [comment]
Hi @tKsome 

Our mech support will be not available this week.
Sorry for the inconvenience.

**Comment by tKsome** [comment]
> Hi @tKsome
> 
> Our mech support will be not available this week.
> Apologies for the inconvenience.

emmmm, 
Is the technical support department here this week？？？

**Comment by maggia80** [comment]
Hi @tKsome, looking at the video it seems that the cable of the proximal joint of the thumb is broken. 
Instructions on how to fix it are at the following link: https://icub-tech-iit.github.io/documentation/icub_tendons/remove/

**Comment by julijenv** [comment]
Hi @tKsome,
as already suspected by @maggia80 , the thumb proximal cable is quite loss - meaning 95% of the cases : cable broekn - 5% cases : just loose.
Could you please try to remove the cover of the forearm? and check the middle motor at the level of the elbow (see red circle - 
![image](https://user-images.githubusercontent.com/7140395/94437560-36283f80-019e-11eb-8f7a-aea7fd45160f.png))
if the cable is broken you will see it from this place or just by pulling out the wire you may find out that the cable gets out.
Please follow the instructions from:
https://icub-tech-iit.github.io/documentation/icub_tendons/lower_arm_V2/#3-proximal-joints
Let us know

**Comment by tKsome** [comment]
> Hi @tKsome,
> as already suspected by @maggia80 , the thumb proximal cable is quite loss - meaning 95% of the cases : cable broekn - 5% cases : just loose.
> Could you please try to remove the cover of the forearm? and check the middle motor at the level of the elbow (see red circle -
> ![image](https://user-images.githubusercontent.com/7140395/94437560-36283f80-019e-11eb-8f7a-aea7fd45160f.png))
> if the cable is broken you will see it from this place or just by pulling out the wire you may find out that the cable gets out.
> Please follow the instructions from:
> https://icub-tech-iit.github.io/documentation/icub_tendons/lower_arm_V2/#3-proximal-joints
> Let us know

but how can i open the tactile sensor in lower arm, it is tooooo complicated

**Comment by julijenv** [comment]
Hi @tKsome ,
sorry I dont understand what you mean by :

> but how can i open the tactile sensor in lower arm, it is tooooo complicated

could you take a picture of what you are talking about?

BTW, I will be back in IIT on Monday, please contact me on skype:
my Id is icub.support
thx in advacne

**Comment by tKsome** [comment]
Can we have a video meeting next Friday 9th Oct and fix the robot together? SZ is 7hours ahead. I think it is the best approach.

**Comment by violadelbono** [comment]
Hi @tKsome,

We can schedule a Skype call for Oct Friday 9th at  9.30am CET which for you will be 3.30pm if I am correct.

Let me know!

**Comment by tKsome** [comment]
> Hi @tKsome,
> 
> We can schedule a Skype call for Oct Friday 9th at 9.30am CET which for you will be 3.30pm if I am correct.
> 
> Let me know!

this time is OK. Looking forward to your support.

**Comment by julijenv** [comment]
as it is a double issue let's close this one
