### ISSUE TITLE
iCubErzelli01: Leftarm wrist not calibrating

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#982]
## Brief description of the request/failure
The wrist of the left arm is not calibrating anymore.

## Accompanying material
[log_pc104_icubblue_yarprobotinterface_2143.txt](https://github.com/robotology/icub-tech-support/files/5224006/log_pc104_icubblue_yarprobotinterface_2143.txt)
![_20200915_114340](https://user-images.githubusercontent.com/3440640/93195065-17ab5880-f749-11ea-8b66-a9d941dd7c1d.JPG)

**Comment by julijenv** [comment]
Hi @ddetommaso ,
could you plese try to makea a video of the failing?
from the log file, the joint 7 seems out of boundries. Try to close the fingers and relaunch the robot and let me know

**Comment by ddetommaso** [comment]
Hi @julijenv 

I've tried with different positions of the left arm but nothing changed.
Basically the wrist start moving during the calibration but it doesn't complete the movement.

If may help we already had a similar issue with this robot
https://github.com/robotology/icub-tech-support/issues/937

**Comment by violadelbono** [comment]
Hi @ddetommaso 

We tensed the wrist tendons and re-calibrated the joint 7 (fingers abduction). As a result, the wrist now properly calibrate.
Issue can be closed.
