### ISSUE TITLE
iCubGenova04 Battery pack not working

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#984]
One of the battery pack of robot `iCubGenova04` is not working. After it shut down (probably out of battery) we are no longer able to recharge it. 

What happens is that when we put it in charge, on the charger we observe that the CHARGE light (orange) is blinking as expected, however after short time the ALARM light (red) goes on. If we check the battery status pressing the button, the red light is always blinking.

CC @MrAndrea @Yeshasvitvs

**Comment by lrapetti** [comment]
The charger we were using is the following one
![photo5983129021354980260](https://user-images.githubusercontent.com/35487806/93242385-0a14c380-f787-11ea-90db-655ba0c94122.jpg)
![photo5983129021354980261](https://user-images.githubusercontent.com/35487806/93242463-1dc02a00-f787-11ea-9e78-52cde9aba07a.jpg)

**Comment by MrAndrea** [comment]
I suppose that the battery pack is in undervoltage protection status due to the BMS, and the only way to come back to life is to connect opportunely and with extremely care the plus and minus poles to a power supply (42V, current limit eg 1A or 2A) .
I can check it next week.

**Comment by S-Dafarra** [comment]
> I suppose that the battery pack is in undervoltage protection status due to the BMS, and the only way to come back to life is to connect opportunely and with extremely care the plus and minus poles to a power supply (42V, current limit eg 1A or 2A) .
> I can check it next week.
 
We tried to recharge it with the bigger blue power supplier. It seemed to work, but then the robot fell and we broke it definitely 😅

**Comment by MrAndrea** [comment]
> We tried to recharge it with the bigger blue power supplier. It seemed to work, but then the robot fell and we broke it definitely 😅

I think we can close this issue, but if there are some pics of the broken battery pack please add them, it might be helpful to track the battery story and organise a possible repair.

**Comment by S-Dafarra** [comment]
> > We tried to recharge it with the bigger blue power supplier. It seemed to work, but then the robot fell and we broke it definitely sweat_smile
> 
> I think we can close this issue, but if there are some pics of the broken battery pack please add them, it might be helpful to track the battery story and organise a possible repair.

I don't think we have it anymore in our open space. @DanielePucci brought it upstairs as soon as we unmounted it from the robot.
