### ISSUE TITLE
iCubGenova04 left elbow cable broken

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#985]
## Brief description of the request/failure

The cables from the left elbow appear to be out of the track, but they do not appear to be broken

![photo5985380821168666250](https://user-images.githubusercontent.com/35487806/93340055-9fb65e80-f82c-11ea-87de-a4bf7ba9f669.jpg)

## Detailed context
It happened while doing robot-robot collaboration experiments.

**Comment by lrapetti** [comment]
Apparently @julijenv and @violadelbono are out of office this week, we should try to fix it because of upcoming experiments.

CC @DanielePucci @maggia80

**Comment by lrapetti** [comment]
Update on the status, we tried to put the cable back on the track but the cable brake so it needs to be replaced.

cc @Giulero

**Comment by maggia80** [comment]
https://icub-tech-iit.github.io/documentation/icub_tendons/shoulder_elbow/#3-left-elbow-cabling 

@Miche19  could you please provide them cable 9 and 10 (IITCODE 4766 e 4767)

**Comment by Miche19** [comment]
@lrapetti the material is ready to be collected

cc: @maggia80

**Comment by lrapetti** [comment]
Both the cables have been replaced and the elbow is now fixed.
Thanks @emilianob80 @prashanthr05 @Giulero
