### ISSUE TITLE
Right wrist measurements are moving even if the arm is still

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#986]
## Brief description of the request/failure
The right wrist measurements jump even if the robot is perfectly still. I noticed this by looking at the iCub GUI
![gifWristMoving](https://user-images.githubusercontent.com/18591940/93617820-c2847680-f9d6-11ea-96c5-53acf8bd8948.gif)

The robot was instead perfectly still.

## Detailed context
Here the log
[log_icub-head_yarprobotinterface_3097_right_arm_weird.txt](https://github.com/robotology/icub-tech-support/files/5246583/log_icub-head_yarprobotinterface_3097_right_arm_weird.txt)

cc @lrapetti @Yeshasvitvs @kouroshD @DanielePucci

**Comment by julijenv** [comment]
After having removed the right arm adn restore some of the problems on the last 2 fingers. I double check the connectgions ofthe AEA and recrimp 1 wire, hopefully this has restored the overall correct behaviour, I tried when I remounted everything and this should have gone.
please close the issue if yiu conrfimr that the problem dont show up.
@S-Dafarra

**Comment by S-Dafarra** [comment]
> After having removed the right arm adn restore some of the problems on the last 2 fingers. I double check the connectgions ofthe AEA and recrimp 1 wire, hopefully this has restored the overall correct behaviour, I tried when I remounted everything and this should have gone.
> please close the issue if yiu conrfimr that the problem dont show up.
> @S-Dafarra

The arms have been removed again because of the iRonCub experiments, so I cannot check right now. In addition, if the problem appears again it may be a different problem. Hence, I prefer to close this and open a new one in case of problems. Thanks for dealing with this.
