### ISSUE TITLE
Left arm wrist recalibration needed and distal index left hand broken

### ISSUE THREAD

**Issue by lunagava** [robotology/icub-tech-support#988]
## Brief description of the request/failure
1) Left wrist is tilted after calibration. I ask to restore the initial configuration.
2) Distal index of left hand seems not working. 

## Accompanying material

![IMG_5413](https://user-images.githubusercontent.com/45895918/93745469-e375e300-fbf3-11ea-9529-127cadbc6de8.jpg)

**Comment by julijenv** [comment]
it has been recalibrated,
