### ISSUE TITLE
Robotics X - Icub's thumb proximal cables are broken

### ISSUE THREAD

**Issue by tKsome** [robotology/icub-tech-support#993]
## Brief description of the request/failure
Just like this issue https://github.com/robotology/icub-tech-support/issues/979, we have check the thumb proximal cables, it had broken, probably. Therefore, we decided to reopen a new issue and solve this problem.

the thumb cables of both hands are probably broken. in https://icub-tech-iit.github.io/documentation/icub_tendons/remove/ have the arm disassembly tutorial. BUT it is so complicated that we don't want take it apart with ourselves. We need guidance.

## Accompanying material
![webwxgetmsgimg](https://user-images.githubusercontent.com/28921533/94661456-a7e8c080-0339-11eb-9a14-01fde22ba5dc.jpg)

**Comment by julijenv** [comment]
Hi @tKsome ,

could you please wait for me, from Monday I' will be totally dedicated to you guys
cheers,

**Comment by tKsome** [comment]
Thank you for your help. Cable has been reinstalled, but there is a new problem. The reinstalled forearm will shake. joint3 in yarpmotorgui.

[1602337511122.zip](https://github.com/robotology/icub-tech-support/files/5359104/1602337511122.zip)

**Comment by julijenv** [comment]
Hi @tKsome ,
I was not present on your skype meeting on Friday but from the video there 2 possibilities either the cables of the elbow are loose or, from what happened often, the 2 lateral pieces holding the forearm stand are loose.
Could you check if the cables tensioners are tightened and if those 4 following screws are tightened as well?
![image](https://user-images.githubusercontent.com/7140395/95718277-81e2ea80-0c6e-11eb-9050-4c99bbae587c.png)
![image](https://user-images.githubusercontent.com/7140395/95718367-a343d680-0c6e-11eb-9855-ad77b98440d2.png)
let us know

**Comment by violadelbono** [comment]
I also suggest to check that the three screws holding the elbow are tight (I remember you had some issue while removing the forearm and pushing hard on those threads)

![image](https://user-images.githubusercontent.com/61685519/95724934-46005300-0c77-11eb-870b-cb073b277c67.png)

**Comment by julijenv** [comment]
@tKsome , Did you succeed to fix the shakering of the elbow by checking the tensionning of the s crews above mentionned?
thx to let us know

**Comment by tKsome** [comment]
awwww, we haven't test it yet. but we will test it later according to your suggestions
