### ISSUE TITLE
[iCubGenova04] Ethernet cable broken

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#998]
## Brief description of the request/failure
The gripper of the Ethernet cable used to connect the robot is broken 
![IMG_20201006_122606287_HDR](https://user-images.githubusercontent.com/16744101/95190800-1f9e6b80-07d0-11eb-8019-2b4791c61cb9.jpg)

cc @S-Dafarra and @prashanthr05

**Comment by julijenv** [comment]
TO BE RECRIMPED

**Comment by julijenv** [comment]
has been recrimped.

**Comment by GiulioRomualdi** [comment]
Thank you!
